"""Emit a Go package for the pane protocol: types, validators, a typed
client, and provider handler interfaces for the namespaces a provider owns.

The output imports the hand-written runtime
``github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane`` (package ``pane``).
Naming and gofmt reuse the mux SDK Go emitter so both Go SDKs read alike.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

from codegen.emit_go import _go_name, _gofmt
from codegen.pane.ir import (
    Any_,
    Array,
    Bool,
    Event,
    Int,
    Map,
    Node,
    Null,
    Nullable,
    Num,
    Object,
    Op,
    Prop,
    PaneIR,
    PaneIRError,
    Ref,
    Str,
    Union,
)

RUNTIME_IMPORT = "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
HEADER_MARK = "// Code generated by cmux pane-protocol codegen. DO NOT EDIT."

_GO_KEYWORDS = {
    "break", "case", "chan", "const", "continue", "default", "defer", "else",
    "fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
    "map", "package", "range", "return", "select", "struct", "switch", "type", "var",
}


def _q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


@dataclass
class _Ctx:
    ir: PaneIR
    # Go name -> (origin, node) for every named type, including synthesized ones.
    named: dict[str, tuple[str, Node]] = field(default_factory=dict)
    # IR type name -> Go name.
    go_of: dict[str, str] = field(default_factory=dict)
    # Compiled string patterns used by validators, in order.
    patterns: list[str] = field(default_factory=list)
    counter: int = 0

    def tmp(self, stem: str) -> str:
        self.counter += 1
        return f"{stem}{self.counter}"

    def add(self, go_name: str, origin: str, node: Node) -> str:
        if go_name in self.named and self.named[go_name][0] != origin:
            raise PaneIRError(
                f"Go type name {go_name!r} is used by both {self.named[go_name][0]} and {origin}"
            )
        self.named[go_name] = (origin, node)
        return go_name


def _ns_ident(ns: str) -> str:
    return _go_name(ns.replace(".", "_"))


def _local_ident(local: tuple[str, ...]) -> str:
    return "".join(_go_name(part) for part in local)


def _full_ident(name: str) -> str:
    return _go_name(name.replace(".", "_").replace("/", "_"))


# Named types -----------------------------------------------------------------


def _collect(ctx: _Ctx) -> None:
    for name in sorted(ctx.ir.types):
        ctx.go_of[name] = _go_name(name)
    for name in sorted(ctx.ir.types):
        ctx.add(ctx.go_of[name], f"types.{name}", ctx.ir.types[name])
        _collect_inline(ctx, ctx.go_of[name], ctx.ir.types[name])


def _collect_inline(ctx: _Ctx, owner: str, node: Node) -> None:
    """Name inline object schemas Owner+Field so they get Go structs."""

    if isinstance(node, (Object, Union)):
        props = node.props if isinstance(node, Object) else [p for _, v in node.variants for p in v.props]
        for prop in props:
            inner = _strip_nullable(prop.node)
            while isinstance(inner, (Array, Map)):
                inner = _strip_nullable(inner.items if isinstance(inner, Array) else inner.values)
            if isinstance(inner, (Object, Union)):
                child = owner + _go_name(prop.name)
                if child in ctx.named and ctx.named[child][1] is inner:
                    continue
                ctx.add(child, f"{owner}.{prop.name}", inner)
                _collect_inline(ctx, child, inner)
    elif isinstance(node, Array):
        _collect_inline_value(ctx, owner + "Item", node.items)
    elif isinstance(node, Map):
        _collect_inline_value(ctx, owner + "Value", node.values)
    elif isinstance(node, Nullable):
        _collect_inline(ctx, owner, node.inner)


def _collect_inline_value(ctx: _Ctx, name: str, node: Node) -> None:
    inner = _strip_nullable(node)
    if isinstance(inner, (Object, Union)):
        ctx.add(name, name, inner)
    _collect_inline(ctx, name, inner)


def _strip_nullable(node: Node) -> Node:
    return node.inner if isinstance(node, Nullable) else node


def _message_type(ctx: _Ctx, node: Node, synth_name: str, origin: str) -> str:
    """Go type name for an op's params/result or an event's data."""

    if isinstance(node, Ref):
        return ctx.go_of[node.name]
    ctx.add(synth_name, origin, node)
    _collect_inline(ctx, synth_name, node)
    return synth_name


def _inline_struct_name(ctx: _Ctx, node: Object | Union) -> str:
    for go_name, (_, candidate) in ctx.named.items():
        if candidate is node:
            return go_name
    raise PaneIRError("internal: inline object was not collected")


def _go_type(ctx: _Ctx, node: Node) -> str:
    if isinstance(node, Ref):
        return ctx.go_of[node.name]
    if isinstance(node, Str):
        return "string"
    if isinstance(node, Bool):
        return "bool"
    if isinstance(node, Num):
        return "float64"
    if isinstance(node, Int):
        return node.go_type
    if isinstance(node, (Any_, Null)):
        return "json.RawMessage"
    if isinstance(node, Array):
        return "[]" + _go_type(ctx, node.items)
    if isinstance(node, Map):
        return "map[string]" + _go_type(ctx, node.values)
    if isinstance(node, (Object, Union)):
        return _inline_struct_name(ctx, node)
    if isinstance(node, Nullable):
        inner = node.inner
        base = _go_type(ctx, inner)
        return base if _nilable(ctx, inner) else "*" + base
    raise PaneIRError(f"internal: no Go type for {node!r}")


def _resolve(ctx: _Ctx, node: Node) -> Node:
    seen = set()
    while isinstance(node, Ref):
        if node.name in seen:
            break
        seen.add(node.name)
        node = ctx.ir.types[node.name]
    return node


def _nilable(ctx: _Ctx, node: Node) -> bool:
    """Go types whose zero value is nil already (no pointer needed)."""

    return isinstance(_resolve(ctx, node), (Array, Map, Any_, Null))


def _field_type(ctx: _Ctx, prop) -> tuple[str, bool]:
    """Return (Go type, omitempty) for an object property."""

    node = prop.node
    nullable = isinstance(node, Nullable)
    inner = node.inner if nullable else node
    base = _go_type(ctx, inner)
    if _nilable(ctx, inner):
        return base, not prop.required
    if nullable or not prop.required:
        return "*" + base, not prop.required
    return base, False


def _field_ident(name: str, taken: set[str]) -> str:
    ident = _go_name(name)
    while ident in taken:
        ident += "_"
    taken.add(ident)
    return ident


def _render_types(ctx: _Ctx) -> str:
    out: list[str] = []
    for go_name in sorted(ctx.named):
        origin, node = ctx.named[go_name]
        out.append(f"// {go_name} is {origin} in the pane-protocol IR.")
        if isinstance(node, Object):
            out.append(f"type {go_name} struct {{")
            taken: set[str] = set()
            fixups = []
            for prop in node.props:
                ident = _field_ident(prop.name, taken)
                go_t, omit = _field_type(ctx, prop)
                tag = prop.name + (",omitempty" if omit else "")
                out.append(f"\t{ident} {go_t} `json:{_q(tag)}`")
                resolved = _resolve(ctx, prop.node)
                if prop.required and isinstance(resolved, (Array, Map)) and not isinstance(prop.node, Nullable):
                    empty = "{}"
                    fixups.append((ident, go_t + empty))
            out.append("}")
            out.append("")
            if fixups:
                out.append(
                    f"// MarshalJSON sends required arrays and maps as [] or {{}}, never null."
                )
                out.append(f"func (v {go_name}) MarshalJSON() ([]byte, error) {{")
                out.append(f"\ttype plain {go_name}")
                out.append("\tp := plain(v)")
                for ident, empty in fixups:
                    out.append(f"\tif p.{ident} == nil {{\n\t\tp.{ident} = {empty}\n\t}}")
                out.append("\treturn json.Marshal(p)")
                out.append("}")
                out.append("")
        elif isinstance(node, Union):
            merged: dict[str, object] = {}
            for tag_value, variant in node.variants:
                for prop in variant.props:
                    if prop.name == node.tag:
                        continue
                    if prop.name in merged and merged[prop.name] != prop.node:
                        raise PaneIRError(
                            f"{origin}: property {prop.name!r} has different schemas in different oneOf variants"
                        )
                    merged[prop.name] = prop.node
            out.append(f"// It is a tagged union on {_q(node.tag)}; which other fields apply depends on the tag:")
            for tag_value, variant in node.variants:
                names = ", ".join(p.name for p in variant.props if p.name != node.tag) or "none"
                out.append(f"//   - {tag_value}: {names}")
            out.append(f"type {go_name} struct {{")
            taken: set[str] = set()
            ident = _field_ident(node.tag, taken)
            out.append(f"\t{ident} string `json:{_q(node.tag)}`")
            for name, prop_node in merged.items():
                go_t, omit = _field_type(ctx, Prop(name, prop_node, False))
                out.append(f"\t{_field_ident(name, taken)} {go_t} `json:{_q(name + ',omitempty')}`")
            out.append("}")
            out.append("")
            out.append("const (")
            for tag_value, _ in node.variants:
                out.append(f"\t{go_name}{_go_name(node.tag)}{_go_name(tag_value)} = {_q(tag_value)}")
            out.append(")")
            out.append("")
        elif isinstance(node, Str) and node.enum:
            out.append(f"type {go_name} string")
            out.append("")
            out.append("const (")
            for value in node.enum:
                out.append(f"\t{go_name}{_go_name(value)} {go_name} = {_q(value)}")
            out.append(")")
            out.append("")
        else:
            if isinstance(node, Nullable):
                raise PaneIRError(f"{origin}: a nullable top-level type is not supported")
            out.append(f"type {go_name} = {_go_type(ctx, node)}")
            out.append("")
    body = "\n".join(out)
    imports = 'import "encoding/json"\n\n' if "json." in body else ""
    return f"{HEADER_MARK}\n\npackage {{pkg}}\n\n{imports}{body}"


# Validators -----------------------------------------------------------------


def _validator_name(go_name: str) -> str:
    return "Validate" + go_name


def _check(ctx: _Ctx, node: Node, var: str, path: str, indent: str) -> list[str]:
    """Go statements that return an error when var violates node."""

    ret = f"{indent}\treturn err\n{indent}}}"
    if isinstance(node, Any_):
        return []
    if isinstance(node, Null):
        return [f"{indent}if err := pane.CheckNull({var}, {path}); err != nil {{", ret]
    if isinstance(node, Ref):
        return [f"{indent}if err := validate{ctx.go_of[node.name]}({var}, {path}); err != nil {{", ret]
    if isinstance(node, Str):
        enum = "".join(", " + _q(v) for v in node.enum)
        lines = [f"{indent}if err := pane.CheckString({var}, {path}{enum}); err != nil {{", ret]
        if node.min_length is not None or node.max_length is not None:
            lo = "nil" if node.min_length is None else f"pane.Int({node.min_length})"
            hi = "nil" if node.max_length is None else f"pane.Int({node.max_length})"
            lines += [f"{indent}if err := pane.CheckStringLength({var}, {path}, {lo}, {hi}); err != nil {{", ret]
        if node.pattern is not None:
            if node.pattern not in ctx.patterns:
                ctx.patterns.append(node.pattern)
            re_var = f"pattern{ctx.patterns.index(node.pattern) + 1}"
            lines += [f"{indent}if err := pane.CheckPattern({var}, {path}, {re_var}); err != nil {{", ret]
        return lines
    if isinstance(node, Bool):
        return [f"{indent}if err := pane.CheckBool({var}, {path}); err != nil {{", ret]
    if isinstance(node, Num):
        def f(value):
            return "nil" if value is None else f"pane.F64({float(value)!r})"

        if all(b is None for b in (node.minimum, node.maximum, node.exclusive_minimum, node.exclusive_maximum)):
            return [f"{indent}if err := pane.CheckNumber({var}, {path}); err != nil {{", ret]
        bounds = ", ".join(f(b) for b in (node.minimum, node.maximum, node.exclusive_minimum, node.exclusive_maximum))
        return [f"{indent}if err := pane.CheckNumberRange({var}, {path}, {bounds}); err != nil {{", ret]
    if isinstance(node, Union):
        obj, tag = ctx.tmp("o"), ctx.tmp("t")
        lines = [
            f"{indent}{obj}, err := pane.AsObject({var}, {path})",
            f"{indent}if err != nil {{",
            ret,
            f"{indent}if err := pane.RequireFields({obj}, {path}, {_q(node.tag)}); err != nil {{",
            ret,
            f"{indent}switch {tag} := {obj}[{_q(node.tag)}]; {tag} {{",
        ]
        for tag_value, variant in node.variants:
            lines.append(f"{indent}case {_q(tag_value)}:")
            lines += _check(ctx, variant, var, path, indent + "\t")
        values = ", ".join(_q(v) for v, _ in node.variants)
        lines += [
            f"{indent}default:",
            f"{indent}\treturn pane.CheckString({tag}, pane.Field({path}, {_q(node.tag)}), {values})",
            f"{indent}}}",
        ]
        return [f"{indent}{{", *[("\t" + l) if l else l for l in lines], f"{indent}}}"]
    if isinstance(node, Int):
        if node.go_type.startswith("uint"):
            hi = "nil" if node.maximum is None else f"pane.U64({node.maximum})"
            return [f"{indent}if err := pane.CheckUint({var}, {path}, {hi}); err != nil {{", ret]
        lo = "nil" if node.minimum is None else f"pane.I64({node.minimum})"
        hi = "nil" if node.maximum is None else f"pane.I64({node.maximum})"
        return [f"{indent}if err := pane.CheckInt({var}, {path}, {lo}, {hi}); err != nil {{", ret]
    if isinstance(node, Nullable):
        body = _check(ctx, node.inner, var, path, indent + "\t")
        if not body:
            return []
        return [f"{indent}if {var} != nil {{", *body, f"{indent}}}"]
    if isinstance(node, Array):
        arr, i, item = ctx.tmp("a"), ctx.tmp("i"), ctx.tmp("x")
        body = _check(ctx, node.items, item, f"pane.Index({path}, {i})", indent + "\t")
        lines = [
            f"{indent}{arr}, err := pane.AsArray({var}, {path})",
            f"{indent}if err != nil {{",
            ret,
        ]
        if node.min_items is not None or node.max_items is not None:
            lo = "nil" if node.min_items is None else f"pane.Int({node.min_items})"
            hi = "nil" if node.max_items is None else f"pane.Int({node.max_items})"
            lines += [f"{indent}if err := pane.CheckItems(len({arr}), {path}, {lo}, {hi}); err != nil {{", ret]
        if body:
            lines += [f"{indent}for {i}, {item} := range {arr} {{", *body, f"{indent}}}"]
        else:
            lines.append(f"{indent}_ = {arr}")
        return [f"{indent}{{", *[("\t" + l) if l else l for l in lines], f"{indent}}}"]
    if isinstance(node, Map):
        obj, key, val = ctx.tmp("o"), ctx.tmp("k"), ctx.tmp("x")
        body = _check(ctx, node.values, val, f"pane.Field({path}, {key})", indent + "\t")
        lines = [f"{indent}{obj}, err := pane.AsObject({var}, {path})", f"{indent}if err != nil {{", ret]
        if body:
            lines += [f"{indent}for {key}, {val} := range {obj} {{", *body, f"{indent}}}"]
        else:
            lines.append(f"{indent}_ = {obj}")
        return [f"{indent}{{", *[("\t" + l) if l else l for l in lines], f"{indent}}}"]
    if isinstance(node, Object):
        obj = ctx.tmp("o")
        lines = [f"{indent}{obj}, err := pane.AsObject({var}, {path})", f"{indent}if err != nil {{", ret]
        required = [p.name for p in node.props if p.required]
        if required:
            names = ", ".join(_q(n) for n in required)
            lines += [f"{indent}if err := pane.RequireFields({obj}, {path}, {names}); err != nil {{", ret]
        if node.closed:
            names = ", ".join(_q(p.name) for p in node.props)
            lines += [f"{indent}if err := pane.OnlyFields({obj}, {path}, {names}); err != nil {{", ret]
        for prop in node.props:
            val = ctx.tmp("x")
            body = _check(ctx, prop.node, val, f"pane.Field({path}, {_q(prop.name)})", indent + "\t")
            if body:
                lines += [f"{indent}if {val}, ok := {obj}[{_q(prop.name)}]; ok {{", *body, f"{indent}}}"]
        return [f"{indent}{{", *[("\t" + l) if l else l for l in lines], f"{indent}}}"]
    raise PaneIRError(f"internal: no validator for {node!r}")


def _render_validators(ctx: _Ctx) -> str:
    out: list[str] = []
    for go_name in sorted(ctx.named):
        origin, node = ctx.named[go_name]
        out.append(f"// {_validator_name(go_name)} checks a decoded JSON value (pane.DecodeValue)")
        out.append(f"// against {origin}.")
        out.append(f"func {_validator_name(go_name)}(v any) error {{ return validate{go_name}(v, \"\") }}")
        out.append("")
        out.append(f"func validate{go_name}(v any, path string) error {{")
        out.extend(_check(ctx, node, "v", "path", "\t"))
        out.append("\treturn nil")
        out.append("}")
        out.append("")
    out.append("// Validators maps each IR type name to its validator (for conformance vectors")
    out.append("// and dynamic checks).")
    out.append("var Validators = map[string]func(any) error{")
    for name in sorted(ctx.ir.types):
        out.append(f"\t{_q(name)}: {_validator_name(ctx.go_of[name])},")
    out.append("}")
    out.append("")
    head = [HEADER_MARK, "", "package {pkg}", ""]
    if ctx.patterns:
        head += ["import (", '\t"regexp"', "", f"\tpane {_q(RUNTIME_IMPORT)}", ")", ""]
        head.append("var (")
        for i, pattern in enumerate(ctx.patterns, 1):
            head.append(f"\tpattern{i} = regexp.MustCompile({_q(pattern)})")
        head += [")", ""]
    else:
        head += [f"import pane {_q(RUNTIME_IMPORT)}", ""]
    return "\n".join(head + out)


# Ops, client, provider ----------------------------------------------------------


@dataclass(frozen=True)
class _OpGo:
    op: Op
    const: str
    method: str
    params: str
    result: str


@dataclass(frozen=True)
class _EventGo:
    event: Event
    const: str
    method: str
    data: str


def _plan(ctx: _Ctx) -> tuple[list[_OpGo], list[_EventGo]]:
    ops: list[_OpGo] = []
    seen: dict[tuple[str, str], str] = {}
    for op in sorted(ctx.ir.ops, key=lambda o: o.name):
        if op.kind == "stream":
            # Byte streams are not implemented in the Go SDK yet; stream ops
            # get no client method or handler (see README).
            continue
        method = _local_ident(op.local)
        key = (op.namespace, method)
        if key in seen:
            raise PaneIRError(f"{op.name} and {seen[key]} both map to Go method {method}")
        seen[key] = op.name
        base = _ns_ident(op.namespace) + method
        ops.append(
            _OpGo(
                op,
                "Op" + base,
                method,
                _message_type(ctx, op.params, base + "Params", f"{op.name} params"),
                _message_type(ctx, op.result, base + "Result", f"{op.name} result"),
            )
        )
    events: list[_EventGo] = []
    for ev in sorted(ctx.ir.events, key=lambda e: e.name):
        method = _local_ident(ev.local)
        key = (ev.namespace, "Subscribe" + method)
        if key in seen:
            raise PaneIRError(f"{ev.name} and {seen[key]} both map to Go method Subscribe{method}")
        seen[key] = ev.name
        base = _ns_ident(ev.namespace) + method
        events.append(
            _EventGo(ev, "Event" + base, method, _message_type(ctx, ev.data, base + "Data", f"{ev.name} data"))
        )
    return ops, events


def _render_ops(ctx: _Ctx, ops: list[_OpGo], events: list[_EventGo], provider_ns: tuple[str, ...]) -> str:
    out = [HEADER_MARK, "", "package {pkg}", "", f"import pane {_q(RUNTIME_IMPORT)}", ""]
    out.append("// IR the package was generated from.")
    out.append("const (")
    out.append(f"\tIRVersion = {_q(ctx.ir.version)}")
    out.append(f"\tIRSHA256  = {_q(ctx.ir.sha256)}")
    out.append(")")
    out.append("")
    out.append("// Op names.")
    out.append("const (")
    for o in ops:
        out.append(f"\t{o.const} = {_q(o.op.name)}")
    out.append(")")
    out.append("")
    if events:
        out.append("// Event stream names.")
        out.append("const (")
        for e in events:
            out.append(f"\t{e.const} = {_q(e.event.name)}")
        out.append(")")
        out.append("")
    codes = sorted({code for o in ops for code in o.op.errors})
    if codes:
        out.append("// Op error codes declared in the IR.")
        out.append("const (")
        for code in codes:
            out.append(f"\tErr{_full_ident(code)} = {_q(code)}")
        out.append(")")
        out.append("")
    if ctx.ir.interfaces:
        out.append("// Shared interface contracts.")
        out.append("const (")
        for iface in ctx.ir.interfaces:
            out.append(f"\tInterface{_full_ident(iface.name)} = {_q(iface.name)}")
        out.append(")")
        out.append("")
    def strs(values) -> str:
        return "nil" if not values else "[]string{" + ", ".join(_q(v) for v in values) + "}"

    by_op = {o.op.name: o for o in ops}
    out.append("// Catalog is the IR this package was generated from, as the runtime enforces")
    out.append("// it: per op the scope, path params, risk metadata and validators.")
    out.append("var Catalog = &pane.Catalog{")
    out.append("\tIRVersion: IRVersion,")
    out.append("\tIRSHA256:  IRSHA256,")
    out.append("\tOps: []pane.OpInfo{")
    for op in sorted(ctx.ir.ops, key=lambda o: o.name):
        planned = by_op.get(op.name)
        validators = (
            f"ValidateParams: {_validator_name(planned.params)}, ValidateResult: {_validator_name(planned.result)},"
            if planned
            else "// stream op: no validators until byte streams exist"
        )
        out.append("\t\t{")
        out.append(f"\t\t\tName: {_q(op.name)}, Kind: {_q(op.kind)}, Scope: {_q(op.scope)},")
        out.append(f"\t\t\tErrors: {strs(op.errors)}, Aliases: {strs(op.aliases)}, Paths: {strs(op.paths)},")
        out.append(
            f"\t\t\tMCPExpose: {_q(op.mcp_expose)}, MCPGroup: {_q(op.mcp_group or '')}, MCPTool: {_q(op.mcp_tool)},"
        )
        out.append(
            f"\t\t\tCLIPath: {_q(op.cli_path or '')}, CLIVisible: {'true' if op.cli_visible else 'false'}, "
            f"CLIPositional: {strs(op.cli_positional)},"
        )
        out.append(
            f"\t\t\tSecretOutput: {'true' if op.secret_output else 'false'}, Risk: {_q(op.risk)}, "
            f"Gesture: {'true' if op.gesture else 'false'}, ScopeClass: {_q(op.scope_class)}, "
            f"ServerOnly: {'true' if op.server_only else 'false'},"
        )
        out.append(f"\t\t\t{validators}")
        out.append("\t\t},")
    out.append("\t},")
    out.append("\tEvents: []pane.EventInfo{")
    for e in events:
        out.append(f"\t\t{{Name: {_q(e.event.name)}, Scope: {_q(e.event.scope)}, Validate: {_validator_name(e.data)}}},")
    out.append("\t},")
    out.append("}")
    out.append("")
    if provider_ns:
        out.append("// ProviderNamespaces are the namespaces this package serves.")
        out.append("var ProviderNamespaces = []string{" + ", ".join(_q(n) for n in provider_ns) + "}")
        out.append("")
    return "\n".join(out)


def _doc_op(o: _OpGo) -> str:
    errs = ", ".join(o.op.errors) if o.op.errors else "none"
    return f"{o.op.name} ({o.op.kind}, scope {o.op.scope}; errors: {errs})"


def _render_client(ctx: _Ctx, ops: list[_OpGo], events: list[_EventGo]) -> str:
    out = [HEADER_MARK, "", "package {pkg}", ""]
    out.append("import (")
    out.append('\t"context"')
    if events:
        out.append('\t"encoding/json"')
    out.append("")
    out.append(f"\tpane {_q(RUNTIME_IMPORT)}")
    out.append(")")
    out.append("")
    out.append("// Client is a typed pane-protocol client on one connection. It validates")
    out.append("// params before sending and results and events after receiving.")
    out.append("type Client struct{ Conn *pane.Conn }")
    out.append("")
    out.append("// NewClient wraps a serving *pane.Conn.")
    out.append("func NewClient(c *pane.Conn) *Client { return &Client{Conn: c} }")
    out.append("")
    for ns in ctx.ir.namespaces:
        ns_ops = [o for o in ops if o.op.namespace == ns.name]
        ns_events = [e for e in events if e.event.namespace == ns.name]
        if not ns_ops and not ns_events:
            continue
        ident = _ns_ident(ns.name)
        out.append(f"// {ident}Client calls ops in namespace {ns.name}.")
        out.append(f"type {ident}Client struct{{ conn *pane.Conn }}")
        out.append("")
        out.append(f"// {ident} returns the {ns.name} namespace client.")
        out.append(f"func (c *Client) {ident}() {ident}Client {{ return {ident}Client{{conn: c.Conn}} }}")
        out.append("")
        for o in ns_ops:
            out.append(f"// {o.method} calls {_doc_op(o)}.")
            out.append(
                f"func (c {ident}Client) {o.method}(ctx context.Context, params {o.params}) ({o.result}, error) {{"
            )
            out.append(f"\tvar zero {o.result}")
            out.append(f"\traw, err := pane.EncodeAndValidate(params, {_validator_name(o.params)}, pane.CodeInvalidParams)")
            out.append("\tif err != nil {\n\t\treturn zero, err\n\t}")
            out.append(f"\tvalue, err := c.conn.Call(ctx, {o.const}, raw)")
            out.append("\tif err != nil {\n\t\treturn zero, err\n\t}")
            out.append(f"\treturn pane.DecodeAndValidate[{o.result}](value, {_validator_name(o.result)}, pane.CodeInvalidResult)")
            out.append("}")
            out.append("")
        for e in ns_events:
            out.append(f"// Subscribe{e.method} subscribes to {e.event.name} (scope {e.event.scope}).")
            out.append(
                f"func (c {ident}Client) Subscribe{e.method}(ctx context.Context, filter json.RawMessage) (*pane.TypedSubscription[{e.data}], error) {{"
            )
            out.append(f"\tsub, err := c.conn.Subscribe(ctx, {e.const}, filter)")
            out.append("\tif err != nil {\n\t\treturn nil, err\n\t}")
            out.append(f"\treturn pane.NewTypedSubscription[{e.data}](sub, {_validator_name(e.data)}), nil")
            out.append("}")
            out.append("")
    return "\n".join(out)


def _render_provider(ctx: _Ctx, ops: list[_OpGo], events: list[_EventGo], provider_ns: tuple[str, ...]) -> str:
    owners = {ctx.ir.namespace(n).app for n in provider_ns}
    if len(owners) != 1:
        raise PaneIRError(f"provider namespaces {list(provider_ns)} have different owners {sorted(owners)}")
    app = owners.pop()
    out: list[str] = []
    out.append(f"// App is the app id that owns {', '.join(provider_ns)}.")
    out.append(f"const App = {_q(app)}")
    out.append("")
    out.append("// NewProvider creates a provider for App that owns ProviderNamespaces. Register")
    out.append("// a handler for each namespace, then call Run.")
    out.append("func NewProvider() (*pane.Provider, error) {")
    out.append("\treturn pane.NewProvider(App, Catalog, ProviderNamespaces...)")
    out.append("}")
    out.append("")
    for ns in provider_ns:
        ident = _ns_ident(ns)
        ns_ops = [o for o in ops if o.op.namespace == ns]
        ns_events = [e for e in events if e.event.namespace == ns]
        out.append(f"// {ident}Handler serves the ops and event streams of namespace {ns}.")
        out.append("// Params arrive validated; results and events are validated before they")
        out.append("// are sent. Return *pane.Error with a declared code for expected failures;")
        out.append("// any other error is logged and sent as cmux.protocol.internal.")
        out.append(f"type {ident}Handler interface {{")
        for o in ns_ops:
            out.append(f"\t// {o.method} serves {_doc_op(o)}.")
            out.append(f"\t{o.method}(ctx context.Context, call *pane.Call, params {o.params}) ({o.result}, error)")
        for e in ns_events:
            out.append(f"\t// Subscribe{e.method} runs when a peer subscribes to {e.event.name} (scope")
            out.append(f"\t// {e.event.scope}), before the ok. Emit on sink for this subscriber only;")
            out.append("\t// return an error to refuse. Do not block: start a goroutine that stops")
            out.append("\t// when ctx is done. Publish reaches every subscriber.")
            out.append(f"\tSubscribe{e.method}(ctx context.Context, call *pane.Call, sink *pane.TypedSink[{e.data}]) error")
        out.append("}")
        out.append("")
        out.append(f"// Register{ident} registers h for every op and event of {ns}.")
        out.append(f"func Register{ident}(p *pane.Provider, h {ident}Handler) error {{")
        for o in ns_ops:
            # The runtime has already authorized, confined and validated the
            # params against Catalog, and validates the result after.
            out.append(f"\tif err := p.Register({o.const}, func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {{")
            out.append(f"\t\tvar params {o.params}")
            out.append("\t\tif err := json.Unmarshal(raw, &params); err != nil {")
            out.append("\t\t\treturn nil, err")
            out.append("\t\t}")
            out.append(f"\t\tresult, err := h.{o.method}(ctx, call, params)")
            out.append("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}")
            out.append("\t\treturn json.Marshal(result)")
            out.append("\t}); err != nil {\n\t\treturn err\n\t}")
        for e in ns_events:
            out.append(f"\tif err := p.RegisterEvent({e.const}, pane.EventHandler{{")
            out.append("\t\tOnSubscribe: func(ctx context.Context, call *pane.Call, sink *pane.Sink) error {")
            out.append(f"\t\t\treturn h.Subscribe{e.method}(ctx, call, pane.NewTypedSink[{e.data}](sink))")
            out.append("\t\t},")
            out.append("\t}); err != nil {\n\t\treturn err\n\t}")
        out.append("\treturn nil")
        out.append("}")
        out.append("")
        for e in ns_events:
            out.append(f"// Publish{_ns_ident(ns)}{e.method} publishes {e.event.name} to its subscribers.")
            out.append(f"func Publish{_ns_ident(ns)}{e.method}(p *pane.Provider, data {e.data}) error {{")
            out.append("\traw, err := json.Marshal(data)")
            out.append("\tif err != nil {\n\t\treturn err\n\t}")
            out.append(f"\treturn p.Publish({e.const}, raw) // validated against Catalog")
            out.append("}")
            out.append("")
    body = "\n".join(out)
    std = [name for name, use in (("context", "context."), ("encoding/json", "json."), ("fmt", "fmt.")) if use in body]
    head = [HEADER_MARK, "", "package {pkg}", "", "import ("]
    head += [f"\t{_q(name)}" for name in std]
    if std:
        head.append("")
    head += [f"\tpane {_q(RUNTIME_IMPORT)}", ")", ""]
    return "\n".join(head) + "\n" + body


def render(ir: PaneIR, *, package: str, provider_namespaces: tuple[str, ...] = ()) -> dict[str, str]:
    """Return {filename: Go source} for one generated package."""

    if not package.isidentifier() or package in _GO_KEYWORDS or package != package.lower():
        raise PaneIRError(f"invalid Go package name {package!r}")
    declared = {ns.name for ns in ir.namespaces}
    unknown = sorted(set(provider_namespaces) - declared)
    if unknown:
        raise PaneIRError(f"provider namespaces {unknown} are not declared in the IR")
    provider_ns = tuple(sorted(set(provider_namespaces)))
    ctx = _Ctx(ir)
    _collect(ctx)
    ops, events = _plan(ctx)
    files = {
        "ops.go": _render_ops(ctx, ops, events, provider_ns),
        "client.go": _render_client(ctx, ops, events),
        "types.go": _render_types(ctx),
        "validate.go": _render_validators(ctx),
    }
    if provider_ns:
        files["provider.go"] = _render_provider(ctx, ops, events, provider_ns)
    header = f"{HEADER_MARK}\n// Generated from pane-protocol IR {ir.version} (SHA-256 {ir.sha256})."
    return {
        name: _gofmt(
            source.replace(HEADER_MARK, header, 1).replace("package {pkg}", f"package {package}", 1)
        )
        for name, source in sorted(files.items())
    }
