//! `coderouter` strings of the CLI catalog (English and Japanese).

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct CodeRouterMessages {
    pub usage: &'static str,
    pub unknown_claude_verb: &'static str,
    pub add_kind_required: &'static str,
    pub add_kind_unsupported: &'static str,
    pub secret_in_argv: &'static str,
    pub bedrock_model: &'static str,
    pub bedrock_only: &'static str,
    pub bedrock_region: &'static str,
    pub bedrock_keys: &'static str,
    pub no_secret: &'static str,
    pub hidden_prompt: &'static str,
    pub oauth_label: &'static str,
    pub api_key_label: &'static str,
    pub not_oauth_token: &'static str,
    pub not_api_key: &'static str,
    pub account_required: &'static str,
    pub account_not_found: &'static str,
    pub account_ambiguous: &'static str,
    pub account_email_selector: &'static str,
    pub no_accounts: &'static str,
    pub status_signed_in: &'static str,
    pub status_signed_out: &'static str,
    pub unexpected_argument: &'static str,
    pub no_bundle: &'static str,
    pub missing_binary: &'static str,
    pub exec_failed: &'static str,
}

pub(super) const ENGLISH: CodeRouterMessages = CodeRouterMessages {
    usage: "usage: cmux coderouter <status|machines|claude> [--team ID] [--json]\n\nThe cmux app manages the team's CodeRouter model plane. Any other verb, and\nevery `cmux cr ...`, runs the CodeRouter CLI bundled in the app unchanged.\n\n  cmux coderouter status [--team ID]\n      Sign-in state, team, and the team's Claude upstream accounts.\n  cmux coderouter machines [--team ID]\n      30-day CodeRouter usage per Cloud machine.\n  cmux coderouter claude list [--team ID]\n      The team's Claude upstream accounts; secrets are never printed.\n  cmux coderouter claude add oauth-token|api-key [--label L] [--stdin] [--team ID]\n      Add a Claude Code OAuth token (CLAUDE_CODE_OAUTH_TOKEN) or an Anthropic\n      API key (ANTHROPIC_API_KEY), from that variable, --stdin, or a hidden\n      prompt. Never pass a secret as an argument.\n  cmux coderouter claude add bedrock [--label L] [--region R] [--model CLAUDE=BEDROCK]...\n      Add Amazon Bedrock credentials from AWS_ACCESS_KEY_ID,\n      AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN.\n  cmux coderouter claude remove|disable|enable ACCOUNT [--team ID]\n      ACCOUNT is the acct_… handle (best), the id, the masked identifier, or a\n      label that one account has. An email is refused.\n  cmux coderouter claude clear [--team ID]\n      Remove every Claude upstream account of the team.\n",
    unknown_claude_verb: "unknown coderouter claude verb \"{verb}\"; use list, add, remove, disable, enable, or clear",
    add_kind_required: "coderouter claude add needs a credential kind: oauth-token, api-key, or bedrock",
    add_kind_unsupported: "coderouter claude add: unsupported credential kind \"{kind}\"; use oauth-token, api-key, or bedrock",
    secret_in_argv: "never pass a secret as an argument: set its environment variable, pipe it with --stdin, or type it at the hidden prompt",
    bedrock_model: "--model needs CLAUDE_MODEL=BEDROCK_MODEL, not \"{value}\"",
    bedrock_only: "--region and --model apply only to bedrock",
    bedrock_region: "coderouter claude add bedrock needs --region or AWS_REGION / AWS_DEFAULT_REGION",
    bedrock_keys: "coderouter claude add bedrock reads AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from the environment; export both, then retry",
    no_secret: "no {label}: set {env}, pipe it with --stdin, or type it at the prompt",
    hidden_prompt: "{label} (input hidden): ",
    oauth_label: "Claude Code OAuth token",
    api_key_label: "Anthropic API key",
    not_oauth_token: "that is not a Claude Code OAuth token (expected sk-ant-oat01-...); for an Anthropic API key use `cmux coderouter claude add api-key`",
    not_api_key: "that is not an Anthropic API key (expected sk-ant-...); for a Claude Code OAuth token use `cmux coderouter claude add oauth-token`",
    account_required: "{command} needs an account id, label, or identifier; run `cmux coderouter claude list`",
    account_not_found: "no Claude upstream account matches \"{account}\"; run `cmux coderouter claude list` and use its acct_… handle",
    account_ambiguous: "\"{account}\" matches {count} Claude upstream accounts; select one by its acct_… handle:",
    account_email_selector: "select the account by its acct_… handle (cmux coderouter claude list)",
    no_accounts: "no Claude upstream accounts",
    status_signed_in: "signed in",
    status_signed_out: "not signed in",
    unexpected_argument: "{command}: unexpected argument \"{value}\"",
    no_bundle: "this cmux is not inside a cmux app, so it has no bundled CodeRouter CLI; use the cmux in the app (Contents/Resources/bin/cmux)",
    missing_binary: "the bundled CodeRouter CLI is missing at {path}",
    exec_failed: "cannot run {path}: {error}",
};

pub(super) const JAPANESE: CodeRouterMessages = CodeRouterMessages {
    usage: "使い方: cmux coderouter <status|machines|claude> [--team ID] [--json]\n\ncmux アプリがチームの CodeRouter モデルプレーンを管理します。その他の動詞と\n`cmux cr ...` はすべて、アプリ同梱の CodeRouter CLI をそのまま実行します。\n\n  cmux coderouter status [--team ID]\n      サインイン状態、チーム、チームの Claude アップストリームアカウント。\n  cmux coderouter machines [--team ID]\n      Cloud マシンごとの 30 日間の CodeRouter 使用量。\n  cmux coderouter claude list [--team ID]\n      チームの Claude アップストリームアカウント。シークレットは表示しません。\n  cmux coderouter claude add oauth-token|api-key [--label L] [--stdin] [--team ID]\n      Claude Code OAuth トークン (CLAUDE_CODE_OAUTH_TOKEN) または Anthropic API\n      キー (ANTHROPIC_API_KEY) を、その変数、--stdin、または非表示の入力から追加。\n      シークレットを引数で渡さないでください。\n  cmux coderouter claude add bedrock [--label L] [--region R] [--model CLAUDE=BEDROCK]...\n      AWS_ACCESS_KEY_ID、AWS_SECRET_ACCESS_KEY、AWS_SESSION_TOKEN から\n      Amazon Bedrock の認証情報を追加。\n  cmux coderouter claude remove|disable|enable アカウント [--team ID]\n      アカウントは acct_… ハンドル (推奨)、ID、マスクされた識別子、または\n      1 つのアカウントだけが持つラベル。メールアドレスは使用できません。\n  cmux coderouter claude clear [--team ID]\n      チームの Claude アップストリームアカウントをすべて削除。\n",
    unknown_claude_verb: "coderouter claude の動詞「{verb}」は不明です。list、add、remove、disable、enable、clear のいずれかを使ってください",
    add_kind_required: "coderouter claude add には認証情報の種類 (oauth-token、api-key、bedrock) が必要です",
    add_kind_unsupported: "coderouter claude add: 認証情報の種類「{kind}」には対応していません。oauth-token、api-key、bedrock のいずれかを使ってください",
    secret_in_argv: "シークレットを引数で渡さないでください。環境変数に設定するか、--stdin で渡すか、非表示の入力で入力してください",
    bedrock_model: "--model には CLAUDE モデル=BEDROCK モデル が必要です (「{value}」は不正)",
    bedrock_only: "--region と --model は bedrock でのみ使えます",
    bedrock_region: "coderouter claude add bedrock には --region または AWS_REGION / AWS_DEFAULT_REGION が必要です",
    bedrock_keys: "coderouter claude add bedrock は環境変数 AWS_ACCESS_KEY_ID と AWS_SECRET_ACCESS_KEY を読み取ります。両方を設定してから再試行してください",
    no_secret: "{label}がありません: {env} を設定するか、--stdin で渡すか、入力欄で入力してください",
    hidden_prompt: "{label} (入力は表示されません): ",
    oauth_label: "Claude Code OAuth トークン",
    api_key_label: "Anthropic API キー",
    not_oauth_token: "Claude Code OAuth トークンではありません (sk-ant-oat01-... が必要)。Anthropic API キーには `cmux coderouter claude add api-key` を使ってください",
    not_api_key: "Anthropic API キーではありません (sk-ant-... が必要)。Claude Code OAuth トークンには `cmux coderouter claude add oauth-token` を使ってください",
    account_required: "{command} にはアカウントの ID、ラベル、または識別子が必要です。`cmux coderouter claude list` で確認してください",
    account_not_found: "「{account}」に一致する Claude アップストリームアカウントはありません。`cmux coderouter claude list` で acct_… ハンドルを確認してください",
    account_ambiguous: "「{account}」は {count} 個の Claude アップストリームアカウントに一致します。acct_… ハンドルで選択してください:",
    account_email_selector: "アカウントは acct_… ハンドルで選択してください (cmux coderouter claude list)",
    no_accounts: "Claude アップストリームアカウントはありません",
    status_signed_in: "サインイン済み",
    status_signed_out: "サインインしていません",
    unexpected_argument: "{command}: 予期しない引数「{value}」",
    no_bundle: "この cmux は cmux アプリ内にないため、同梱の CodeRouter CLI がありません。アプリ内の cmux (Contents/Resources/bin/cmux) を使ってください",
    missing_binary: "同梱の CodeRouter CLI が {path} にありません",
    exec_failed: "{path} を実行できません: {error}",
};
