//! `local_server` strings of the CLI catalog (English and Japanese).

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct LocalServerMessages {
    pub shorthand_help: &'static str,
    pub shorthand_invalid: &'static str,
    pub startup_lifecycle_usage: &'static str,
    pub root_remote_usage: &'static str,
    pub root_server_usage: &'static str,
    pub root_server_scope: &'static str,
    pub root_acp_scope: &'static str,
    pub cmux_root_help: &'static str,
    pub scope_not_in_cmux: &'static str,
    pub mutation_key_note: &'static str,
    pub session_stop_help: &'static str,
    pub help: &'static str,
    pub start_help: &'static str,
    pub ensure_help: &'static str,
    pub status_help: &'static str,
    pub stats_help: &'static str,
    pub stats_unsupported: &'static str,
    pub stop_help: &'static str,
    pub reload_config_help: &'static str,
    pub running: &'static str,
    pub started: &'static str,
    pub stopped: &'static str,
    pub not_running: &'static str,
    pub owner_spawn_failed: &'static str,
    pub owner_not_ready: &'static str,
    pub reloaded: &'static str,
    pub connect_failed: &'static str,
    pub starting: &'static str,
    pub identity_failed: &'static str,
    pub communication_failed: &'static str,
    pub invalid_response: &'static str,
    pub reload_rejected: &'static str,
    pub reload_owner_stopped: &'static str,
    pub stop_rejected: &'static str,
    pub wrong_owner: &'static str,
    pub different_session: &'static str,
    pub invalid_identity: &'static str,
    pub unsupported_protocol: &'static str,
    pub force_unsupported: &'static str,
    pub end_terminals_unsupported: &'static str,
    pub stopped_terminals_ended: &'static str,
    pub session_conflict: &'static str,
    pub machine_not_supported: &'static str,
    pub invalid_session: &'static str,
    pub session_name_required: &'static str,
    pub invalid_action_syntax: &'static str,
    pub start_options_after_action: &'static str,
    pub start_rejects_output_mode: &'static str,
    pub unknown_scope: &'static str,
    pub unknown_server_action: &'static str,
    pub suggestion: &'static str,
    pub daemon_removed: &'static str,
    pub unexpected_after_stop: &'static str,
    pub stop_timeout: &'static str,
}

impl LocalServerMessages {
    pub(crate) fn owner_spawn_failed(&self) -> String {
        self.owner_spawn_failed.to_string()
    }

    pub(crate) fn unknown_scope(&self, scope: &str, suggestion: Option<&str>) -> String {
        self.with_suggestion(self.unknown_scope.replace("{scope}", scope), suggestion)
    }

    pub(crate) fn unknown_server_action(&self, action: &str, suggestion: Option<&str>) -> String {
        self.with_suggestion(self.unknown_server_action.replace("{action}", action), suggestion)
    }

    pub(super) fn with_suggestion(&self, message: String, suggestion: Option<&str>) -> String {
        match suggestion {
            Some(candidate) => {
                format!("{message} {}", self.suggestion.replace("{candidate}", candidate))
            }
            None => message,
        }
    }
}

pub(super) const ENGLISH: LocalServerMessages = LocalServerMessages {
    shorthand_help: "USAGE\n  cmux help shorthands\n\nShorthands use the same public resource operations and output modes.\n-t/--target accepts a cmux selector, not tmux session:window.pane syntax.\nNo target means current in the selected session. Lists stay within that session.\nsplitw defaults to down; -h is right and -v is down. Use --help for help.\nselectp accepts one of -L/-R/-U/-D. neww accepts -n NAME.\nrenamew accepts one new name. capturep always prints (-p is optional).\nsend-keys accepts key names (Enter, C-c, M-x); -l joins literal UTF-8 text.\nIt does not mix arbitrary text and key names. Use terminal write for text.\nResource paths may omit current: pane split, term read, ws rename --name NAME.\nExplicit selector paths win; name: forces names that match command words.\nNo new-session alias: use cmux --session NAME or server ensure --session NAME.\n",
    shorthand_invalid: "invalid or unsupported shorthand argument {value}; use cmux help shorthands",
    startup_lifecycle_usage: "  cmux server <ACTION>     Start, inspect, stop, or reload one local session\n  cmux remote connect <ROUTE>  Attach through an authenticated remote route\n  cmux remote ssh <HOST>       Bootstrap and attach over direct SSH\n  cmux remote forward <ROUTE>  Forward a workspace TCP service locally\n  cmux remote rpc <ROUTE>     Run workspace coding-agent RPC requests\n  cmux remote enroll <ACTION> Enroll, approve, list, or revoke devices\n  cmux remote known-daemons   List client-pinned daemon identities and routes\n  cmux remote stop            Stop a replaceable SSH sidecar explicitly",
    root_remote_usage: "  cmux remote <connect|ssh|forward|rpc|enroll|known-daemons|stop> [OPTIONS]",
    root_server_usage: "  cmux server <start|ensure|status|stats|stop|reload-config> [OPTIONS]",
    root_server_scope: "  server        Manage one named local durable session owner",
    root_acp_scope: "  acp           Agent sessions (acpmux); `cmux acp --help`",
    cmux_root_help: "cmux - terminal multiplexer and cmux app control\n\nUSAGE\n  cmux                          Open the TUI (attach to or start the session)\n  cmux attach [START OPTIONS]\n  cmux [GLOBAL OPTIONS] <scope> <action>\n\nGLOBAL OPTIONS\n  --socket <path>           Connect to an exact local session socket\n  --session <name>          Route through a named local session\n  --all-sessions            Run a list on every local session (records gain `session`)\n  <session>:<id>            An id on another local session (`build:ws_…`) routes there\n  --app-socket <path>       Connect to an exact app control socket\n  --idempotency-key <key>   Retry a failed change with the key it printed\n  --json                    Print one JSON result\n  --jsonl                   Print one JSON value per result or event\n  --quiet                   Suppress successful output\n  -h, --help                Show command help\n\nSCOPES\n  workspace     Create and organize workspaces\n  screen        Create and organize screens\n  pane          Split, focus, and organize panes\n  tab           Create and organize terminal or browser tabs\n  terminal      Read, write, and attach to terminals\n  browser       Navigate browsers and drive app browser pages\n  notification  List and create notifications\n  agent         List and report agent state; install agent hooks\n  room          Organize workspaces into rooms\n  closed        List and reopen closed tabs, screens, workspaces\n  git           Read a repository's status and changes; capture checkpoints\n  acp           Agent sessions (acpmux); `cmux acp --help`\n  mcp           Serve cmux tools to MCP clients (off by default); `cmux mcp --help`\n  coderouter    CodeRouter team accounts; `cr` and other verbs run the bundled CodeRouter CLI\n  window        List the app's windows\n  settings      Read and change cmux.json settings\n  events        Stream app events as JSON lines\n  history       List and search the app's history\n  bookmark      List and search browser bookmarks\n  app           ping, identify, capabilities, and app actions\n  action        List, describe, and run app actions\n  server        Start, inspect, and stop the local session owner\n\nApp actions marked for the CLI also run by their CLI name (`cmux action list`\nshows them). An action waits until its work is done; --no-wait returns when\nthe app accepts it.\n\nRun `cmux <scope> --help` for scope-specific paths, `cmux help start` for\nstart options and `cmux help shorthands` for tmux-style shorthands.\n",
    scope_not_in_cmux: "\"{scope}\" is not part of cmux; run `cmux --help` for its scopes",
    mutation_key_note: "idempotency key: {key}\nThe change may still apply. To retry it safely, run the same command with --idempotency-key {key}.",
    session_stop_help: "  cmux session <name>|current stop",
    help: "USAGE\n  cmux server start [START OPTIONS]\n  cmux server ensure [--session <name>] [--socket <path>] [--terminal-reap-grace-seconds <n>]\n  cmux server status [--session <name>] [--socket <path>]\n  cmux server stats [--session <name>] [--socket <path>]\n  cmux server stop [--session <name>] [--socket <path>] [--force] [--end-terminals]\n  cmux server reload-config [--session <name>] [--socket <path>]\n\n`server` always targets the local durable mux owner for one named session.\nUse `cmux remote --help` for authenticated remote-daemon lifecycle.\n",
    start_help: "USAGE\n  cmux server start [START OPTIONS]\n\nStart the local durable mux owner for one named session in the foreground.\n",
    ensure_help: "USAGE\n  cmux server ensure [--session <name>] [--socket <path>] [--terminal-reap-grace-seconds <n>]\n\nStart a detached local session owner when none is running, wait until it\naccepts clients, and report it. Ensuring a running session succeeds.\n--terminal-reap-grace-seconds starts the owner with that reap grace; a\nrunning owner keeps its own.\n",
    status_help: "USAGE\n  cmux server status [--session <name>] [--socket <path>]\n",
    stats_help: "USAGE\n  cmux server stats [--session <name>] [--socket <path>]\n\nReport where the daemon spends its time: registry lock waits and holders,\njournal writer batch sizes and commit latency, and connection admission.\nUse --json for the exact `server-stats` object.\n",
    stats_unsupported: "this server does not support server-stats; upgrade cmux-tui",
    stop_help: "USAGE\n  cmux server stop [--session <name>] [--socket <path>] [--force] [--end-terminals]\n\nStopping an absent server succeeds. Durable session topology is preserved.\n--end-terminals ends every terminal and removes its tabs first (test teardown).\n",
    reload_config_help: "USAGE\n  cmux server reload-config [--session <name>] [--socket <path>]\n",
    running: "local server is running",
    started: "local server started",
    stopped: "local server stopped; durable session topology was preserved",
    not_running: "local server is not running; nothing needed to be stopped",
    owner_spawn_failed: "cannot start the detached session owner; check the session state and retry",
    owner_not_ready: "the detached session owner did not become ready; inspect the client log under the session state directory and retry",
    reloaded: "local server configuration reloaded",
    connect_failed: "cannot connect to the local server; check that the named session is running and retry",
    starting: "the local server is still starting; retry the lifecycle command",
    identity_failed: "cannot verify the local server identity; retry with the cmux build that started the session",
    communication_failed: "communication with the local server failed; verify that it is running and retry",
    invalid_response: "the local server returned an invalid lifecycle response; retry with the cmux build that started the session",
    reload_rejected: "the local server rejected the configuration reload; inspect its diagnostics and retry",
    reload_owner_stopped: "the local server stopped before it applied the configuration reload; start the session and retry",
    stop_rejected: "the local server rejected the stop request; retry with --force only when active clients can disconnect",
    wrong_owner: "the selected socket is not owned by a cmux local server",
    different_session: "the selected socket belongs to a different session",
    invalid_identity: "the local server returned an incomplete lifecycle identity",
    unsupported_protocol: "the selected session uses an incompatible cmux-tui protocol; restart it with this cmux build",
    force_unsupported: "this local server cannot accept a safely fenced forced stop; use the cmux build that started it",
    end_terminals_unsupported: "this local server cannot end its terminals on stop; use a cmux build that advertises terminal-reap-v1",
    stopped_terminals_ended: "local server stopped; every terminal was ended",
    session_conflict: "the session name conflicts with --session",
    machine_not_supported: "--machine cannot target a local server; use the machine resource commands",
    invalid_session: "the session name is invalid; use one path component without separators or control characters",
    session_name_required: "session stop requires an exact session name or current",
    invalid_action_syntax: "unknown or incomplete server action; use --help",
    start_options_after_action: "server start options must appear after `server start`",
    start_rejects_output_mode: "server start does not support output modes",
    unknown_scope: "unknown resource scope \"{scope}\".",
    unknown_server_action: "unknown server action \"{action}\".",
    suggestion: "Did you mean `{candidate}`?",
    daemon_removed: "`cmux daemon` was renamed to `cmux server start`; run `cmux server start --help`",
    unexpected_after_stop: "local server sent unexpected data after accepting shutdown",
    stop_timeout: "timed out waiting for the local server to stop",
};

pub(super) const JAPANESE: LocalServerMessages = LocalServerMessages {
    shorthand_help: "使用方法\n  cmux help shorthands\n\n短縮形は同じ公開リソース操作と出力形式を使います。\n-t/--target は cmux セレクターです。tmux の session:window.pane 形式ではありません。\n対象の省略は選択したセッションの current です。一覧もそのセッション内です。\nsplitw の既定は下、-h は右、-v は下です。ヘルプは --help を使います。\nselectp は -L/-R/-U/-D の一つ、neww は -n NAME を受け付けます。\nrenamew は新しい名前一つ、capturep は常に出力します（-p は省略可）。\nsend-keys は Enter、C-c、M-x などのキー名、-l は UTF-8 文字列を連結します。\n文字列とキー名の混在には対応しません。文字列には terminal write を使います。\nリソースの current は省略可能です: pane split、term read、ws rename --name NAME。\n明示的なセレクターパスを優先します。コマンドと同名なら name: を使います。\nnew-session はありません。cmux --session NAME または server ensure --session NAME を使います。\n",
    shorthand_invalid: "短縮形の引数 {value} は無効または未対応です。cmux help shorthands を参照してください",
    startup_lifecycle_usage: "  cmux server <操作>       一つのローカルセッションを起動、確認、停止、再読み込み\n  cmux remote connect <ルート>  認証済みリモートルート経由で接続\n  cmux remote ssh <ホスト>       直接 SSH で導入して接続\n  cmux remote forward <ルート>  ワークスペースの TCP サービスをローカル転送\n  cmux remote rpc <ルート>       ワークスペースのコーディングエージェント RPC を実行\n  cmux remote enroll <操作>      デバイスを登録、承認、一覧、失効\n  cmux remote known-daemons      クライアントに固定したデーモン ID とルートを一覧表示\n  cmux remote stop               置換可能な SSH サイドカーを明示的に停止",
    root_remote_usage: "  cmux remote <connect|ssh|forward|rpc|enroll|known-daemons|stop> [オプション]",
    root_server_usage: "  cmux server <start|ensure|status|stats|stop|reload-config> [オプション]",
    root_server_scope: "  server        一つの名前付きローカル永続セッション所有者を管理",
    root_acp_scope: "  acp           エージェントセッション (acpmux)。`cmux acp --help`",
    cmux_root_help: "cmux - ターミナルマルチプレクサと cmux アプリの操作\n\n使い方\n  cmux                          TUI を開く (セッションに接続、なければ開始)\n  cmux attach [開始オプション]\n  cmux [グローバルオプション] <スコープ> <アクション>\n\nグローバルオプション\n  --socket <パス>           指定したローカルセッションソケットに接続\n  --session <名前>          名前付きローカルセッションを経由\n  --all-sessions            一覧をすべてのローカルセッションで実行 (各レコードに `session` を追加)\n  <セッション>:<ID>         別のローカルセッションの ID (`build:ws_…`) はそのセッションへ送る\n  --app-socket <パス>       指定したアプリ制御ソケットに接続\n  --idempotency-key <キー>  失敗した変更を、表示されたキーで再試行\n  --json                    JSON の結果を一つ出力\n  --jsonl                   結果またはイベントごとに JSON 値を一つ出力\n  --quiet                   成功時の出力を省略\n  -h, --help                コマンドのヘルプを表示\n\nスコープ\n  workspace     ワークスペースの作成と整理\n  screen        スクリーンの作成と整理\n  pane          ペインの分割、フォーカス、整理\n  tab           ターミナルタブやブラウザタブの作成と整理\n  terminal      ターミナルの読み取り、書き込み、接続\n  browser       ブラウザの移動とアプリのブラウザページの操作\n  notification  通知の一覧と作成\n  agent         エージェント状態の一覧と報告、エージェントフックの導入\n  room          ワークスペースをルームに整理\n  closed        閉じたタブ、スクリーン、ワークスペースの一覧と再オープン\n  git           リポジトリの状態と変更を読み、チェックポイントを保存\n  acp           エージェントセッション (acpmux)。`cmux acp --help`\n  mcp           MCP クライアントに cmux のツールを提供 (既定でオフ)。`cmux mcp --help`\n  coderouter    CodeRouter のチームアカウント。`cr` とその他の動詞は同梱の CodeRouter CLI を実行\n  window        アプリのウィンドウ一覧\n  settings      cmux.json の設定の読み取りと変更\n  events        アプリのイベントを JSON 行で表示\n  history       アプリの履歴の一覧と検索\n  bookmark      ブラウザのブックマークの一覧と検索\n  app           ping、identify、capabilities とアプリのアクション\n  action        アプリのアクションの一覧、説明、実行\n  server        ローカルセッション所有者の開始、確認、停止\n\nCLI 向けのアプリのアクションは CLI 名でも実行できます (`cmux action list` で表示)。\nアクションは処理の完了を待ちます。--no-wait を付けると、アプリが受け付けた時点で戻ります。\n\nスコープごとの使い方は `cmux <スコープ> --help`、開始オプションは `cmux help start`、\ntmux 風の短縮形は `cmux help shorthands` で表示します。\n",
    scope_not_in_cmux: "\"{scope}\" は cmux のスコープではありません。`cmux --help` でスコープを確認してください",
    mutation_key_note: "冪等キー: {key}\n変更はまだ適用される可能性があります。安全に再試行するには、同じコマンドに --idempotency-key {key} を付けて実行してください。",
    session_stop_help: "  cmux session <名前>|current stop",
    help: "使用方法\n  cmux server start [起動オプション]\n  cmux server ensure [--session <名前>] [--socket <パス>] [--terminal-reap-grace-seconds <秒>]\n  cmux server status [--session <名前>] [--socket <パス>]\n  cmux server stats [--session <名前>] [--socket <パス>]\n  cmux server stop [--session <名前>] [--socket <パス>] [--force] [--end-terminals]\n  cmux server reload-config [--session <名前>] [--socket <パス>]\n\n`server` は常に一つの名前付きセッションのローカル永続 mux 所有者を対象にします。\n認証済みリモートデーモンの操作は `cmux remote --help` を参照してください。\n",
    start_help: "使用方法\n  cmux server start [起動オプション]\n\n一つの名前付きセッションのローカル永続 mux 所有者をフォアグラウンドで起動します。\n",
    ensure_help: "使用方法\n  cmux server ensure [--session <名前>] [--socket <パス>] [--terminal-reap-grace-seconds <秒>]\n\nローカルセッション所有者が実行されていない場合はデタッチ状態で起動し、\nクライアントを受け付けるまで待って結果を報告します。実行中の場合も成功します。\n--terminal-reap-grace-seconds は起動する所有者にその猶予を渡します。\n実行中の所有者は自身の設定を保ちます。\n",
    status_help: "使用方法\n  cmux server status [--session <名前>] [--socket <パス>]\n",
    stats_help: "使用方法\n  cmux server stats [--session <名前>] [--socket <パス>]\n\nデーモンの時間の使われ方を報告します: レジストリロックの待機と保持元、\nジャーナルライターのバッチサイズとコミット遅延、接続の受け入れ状況。\n正確な `server-stats` オブジェクトは --json で取得できます。\n",
    stats_unsupported: "このサーバーは server-stats に対応していません。cmux-tui を更新してください",
    stop_help: "使用方法\n  cmux server stop [--session <名前>] [--socket <パス>] [--force] [--end-terminals]\n\nサーバーが存在しない場合も成功します。永続セッションの構成は保持されます。\n--end-terminals は先にすべてのターミナルを終了し、そのタブを削除します (テストの後始末用)。\n",
    reload_config_help: "使用方法\n  cmux server reload-config [--session <名前>] [--socket <パス>]\n",
    running: "ローカルサーバーは実行中です",
    started: "ローカルサーバーを起動しました",
    stopped: "ローカルサーバーを停止しました。永続セッションの構成は保持されています",
    not_running: "ローカルサーバーは実行されていません。停止は不要でした",
    owner_spawn_failed: "デタッチされたセッション所有者を起動できません。セッション状態を確認して再試行してください",
    owner_not_ready: "デタッチされたセッション所有者が準備完了になりませんでした。セッション状態ディレクトリのクライアントログを確認して再試行してください",
    reloaded: "ローカルサーバーの設定を再読み込みしました",
    connect_failed: "ローカルサーバーに接続できません。名前付きセッションが実行中であることを確認して再試行してください",
    starting: "ローカルサーバーは起動中です。ライフサイクルコマンドを再試行してください",
    identity_failed: "ローカルサーバーの識別情報を確認できません。セッションを起動した cmux ビルドで再試行してください",
    communication_failed: "ローカルサーバーとの通信に失敗しました。実行中であることを確認して再試行してください",
    invalid_response: "ローカルサーバーが無効なライフサイクル応答を返しました。セッションを起動した cmux ビルドで再試行してください",
    reload_rejected: "ローカルサーバーが設定の再読み込みを拒否しました。診断情報を確認して再試行してください",
    reload_owner_stopped: "ローカルサーバーが設定の再読み込みを適用する前に停止しました。セッションを起動して再試行してください",
    stop_rejected: "ローカルサーバーが停止要求を拒否しました。アクティブなクライアントを切断できる場合のみ --force で再試行してください",
    wrong_owner: "選択したソケットは cmux ローカルサーバーに所有されていません",
    different_session: "選択したソケットは別のセッションに属しています",
    invalid_identity: "ローカルサーバーが完全なライフサイクル識別情報を返しませんでした",
    unsupported_protocol: "選択したセッションは互換性のない cmux-tui プロトコルを使用しています。この cmux ビルドで再起動してください",
    force_unsupported: "このローカルサーバーは安全にフェンスされた強制停止に対応していません。起動に使用した cmux ビルドで停止してください",
    end_terminals_unsupported: "このローカルサーバーは停止時にターミナルを終了できません。terminal-reap-v1 に対応した cmux ビルドを使用してください",
    stopped_terminals_ended: "ローカルサーバーを停止し、すべてのターミナルを終了しました",
    session_conflict: "セッション名が --session と競合しています",
    machine_not_supported: "--machine でローカルサーバーを対象にすることはできません。machine リソースコマンドを使用してください",
    invalid_session: "セッション名が無効です。区切り文字や制御文字を含まない 1 つのパス要素を指定してください",
    session_name_required: "session stop には正確なセッション名または current が必要です",
    invalid_action_syntax: "サーバー操作が不明または不完全です。--help を使用してください",
    start_options_after_action: "server start のオプションは `server start` の後に指定してください",
    start_rejects_output_mode: "server start では出力モードを使用できません",
    unknown_scope: "不明なリソーススコープ \"{scope}\"。",
    unknown_server_action: "不明なサーバー操作 \"{action}\"。",
    suggestion: "`{candidate}` のことですか？",
    daemon_removed: "`cmux daemon` は `cmux server start` に名前が変更されました。`cmux server start --help` を実行してください",
    unexpected_after_stop: "停止を受理した後にローカルサーバーが予期しないデータを送信しました",
    stop_timeout: "ローカルサーバーの停止待機がタイムアウトしました",
};
