//! `menu` strings of the CLI catalog (English and Japanese).

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct MenuMessages {
    pub move_tab_workspace_unsupported: &'static str,
    pub move_tab_workspace: &'static str,
    pub move_tab_new_workspace: &'static str,
    pub copy_message: &'static str,
    pub copy_workspace_id: &'static str,
    pub copy_tab_id: &'static str,
    pub copy_pane_id: &'static str,
    pub copy_url: &'static str,
    pub show_in_chrome: &'static str,
    pub connected_clients: &'static str,
    pub this_client: &'static str,
    pub excluded: &'static str,
    pub no_grid: &'static str,
    pub use_client_size: &'static str,
    pub use_only_client_size: &'static str,
    pub include_client_size: &'static str,
    pub restore_all_client_sizing: &'static str,
    pub disconnect_client: &'static str,
    pub terminal_size: &'static str,
    pub terminal_size_changed: &'static str,
    pub size_mode_fit_everyone: &'static str,
    pub size_mode_follow_latest: &'static str,
    pub size_mode_largest: &'static str,
    pub size_mode_priority: &'static str,
    pub size_mode_fixed: &'static str,
    pub size_counts: &'static str,
    pub size_disconnect: &'static str,
    pub size_sets_size: &'static str,
    pub size_not_counted: &'static str,
    pub size_owner_fits_everyone: &'static str,
    pub size_owner_largest: &'static str,
    pub size_owner_fixed: &'static str,
    pub size_owner_held: &'static str,
    pub size_owner_shared: &'static str,
    /// `{name}` and `{device}`, e.g. `Lawrence's Mac`.
    pub size_possessive_device: &'static str,
    pub size_one_col_hidden: &'static str,
    /// `{count}` columns of the grid this client cannot show.
    pub size_cols_hidden: &'static str,
    pub device_mac: &'static str,
    pub device_iphone: &'static str,
    pub device_ipad: &'static str,
    pub device_tui: &'static str,
    pub device_browser: &'static str,
    pub device_unknown: &'static str,
    pub copied: &'static str,
    pub copied_url: &'static str,
    pub rename: &'static str,
    pub maximize_pane: &'static str,
    pub restore_pane_layout: &'static str,
    pub show_sidebar: &'static str,
    pub hide_sidebar: &'static str,
    pub compact_sidebar: &'static str,
    pub full_sidebar: &'static str,
    pub focus_sidebar: &'static str,
    pub sidebar_layout: &'static str,
    pub sidebar_profiles: &'static str,
    pub show_sidebar_view: &'static str,
    pub hide_sidebar_view: &'static str,
}

pub(super) const ENGLISH: MenuMessages = MenuMessages {
    move_tab_workspace_unsupported: "This session owner needs a newer cmux build to move tabs between workspaces",
    move_tab_workspace: "Move tab to workspace",
    move_tab_new_workspace: "New workspace",
    copy_message: "Copy message",
    copy_workspace_id: "Copy workspace id",
    copy_tab_id: "Copy tab id",
    copy_pane_id: "Copy pane id",
    copy_url: "Copy URL",
    show_in_chrome: "Show in Chrome",
    connected_clients: "Connected clients",
    this_client: "this client",
    excluded: "excluded",
    no_grid: "no grid",
    use_client_size: "Use client size",
    use_only_client_size: "Use only this client size",
    include_client_size: "Include client size",
    restore_all_client_sizing: "Restore all client sizing",
    disconnect_client: "Disconnect client",
    terminal_size: "Terminal size",
    terminal_size_changed: "The terminal size changed; open the menu again",
    size_mode_fit_everyone: "Fit everyone",
    size_mode_follow_latest: "Follow latest",
    size_mode_largest: "Largest window",
    size_mode_priority: "Priority",
    size_mode_fixed: "Fixed",
    size_counts: "Counts toward size",
    size_disconnect: "Disconnect",
    size_sets_size: "sets size",
    size_not_counted: "not counted",
    size_owner_fits_everyone: "Fits everyone",
    size_owner_largest: "Largest window",
    size_owner_fixed: "Fixed",
    size_owner_held: "Held size",
    size_owner_shared: "Shared size",
    size_possessive_device: "{name}'s {device}",
    size_one_col_hidden: "1 col hidden",
    size_cols_hidden: "{count} cols hidden",
    device_mac: "Mac",
    device_iphone: "iPhone",
    device_ipad: "iPad",
    device_tui: "Terminal client",
    device_browser: "Browser",
    device_unknown: "Device",
    copied: "Copied",
    copied_url: "Copied URL",
    rename: "Rename",
    maximize_pane: "Maximize pane",
    restore_pane_layout: "Restore pane layout",
    show_sidebar: "Show sidebar",
    hide_sidebar: "Hide sidebar",
    compact_sidebar: "Use compact sidebar",
    full_sidebar: "Use full sidebar",
    focus_sidebar: "Focus sidebar",
    sidebar_layout: "Sidebar",
    sidebar_profiles: "Layouts",
    show_sidebar_view: "Show {view}",
    hide_sidebar_view: "Hide {view}",
};

pub(super) const JAPANESE: MenuMessages = MenuMessages {
    move_tab_workspace_unsupported: "ワークスペース間でタブを移動するにはセッション所有者を新しい cmux ビルドに更新してください",
    move_tab_workspace: "タブをワークスペースへ移動",
    move_tab_new_workspace: "新しいワークスペース",
    copy_message: "メッセージをコピー",
    copy_workspace_id: "ワークスペース ID をコピー",
    copy_tab_id: "タブ ID をコピー",
    copy_pane_id: "ペイン ID をコピー",
    copy_url: "URL をコピー",
    show_in_chrome: "Chrome で表示",
    connected_clients: "接続中のクライアント",
    this_client: "このクライアント",
    excluded: "除外",
    no_grid: "グリッドなし",
    use_client_size: "クライアントサイズを使用",
    use_only_client_size: "このクライアントサイズのみを使用",
    include_client_size: "クライアントサイズを含める",
    restore_all_client_sizing: "すべてのクライアントサイズ設定を復元",
    disconnect_client: "クライアントを切断",
    terminal_size: "ターミナルサイズ",
    terminal_size_changed: "ターミナルサイズが変更されました。メニューを開き直してください",
    size_mode_fit_everyone: "全員に合わせる",
    size_mode_follow_latest: "最新の入力に合わせる",
    size_mode_largest: "最大のウインドウ",
    size_mode_priority: "優先順位",
    size_mode_fixed: "固定",
    size_counts: "サイズに反映",
    size_disconnect: "切断",
    size_sets_size: "サイズを設定",
    size_not_counted: "カウント対象外",
    size_owner_fits_everyone: "全員に合わせる",
    size_owner_largest: "最大のウィンドウ",
    size_owner_fixed: "固定",
    size_owner_held: "保持されたサイズ",
    size_owner_shared: "共有サイズ",
    size_possessive_device: "{name}の{device}",
    size_one_col_hidden: "1列非表示",
    size_cols_hidden: "{count}列非表示",
    device_mac: "Mac",
    device_iphone: "iPhone",
    device_ipad: "iPad",
    device_tui: "ターミナルクライアント",
    device_browser: "ブラウザ",
    device_unknown: "デバイス",
    copied: "コピーしました",
    copied_url: "URL をコピーしました",
    rename: "名前を変更",
    maximize_pane: "ペインを最大化",
    restore_pane_layout: "ペイン配置を復元",
    show_sidebar: "サイドバーを表示",
    hide_sidebar: "サイドバーを隠す",
    compact_sidebar: "サイドバーをコンパクト表示",
    full_sidebar: "サイドバーを通常表示",
    focus_sidebar: "サイドバーにフォーカス",
    sidebar_layout: "サイドバー",
    sidebar_profiles: "レイアウト",
    show_sidebar_view: "{view}を表示",
    hide_sidebar_view: "{view}を非表示",
};
