//! `sidebar` strings of the CLI catalog (English and Japanese).

use super::format_usd;
use cmux_tui_machine_protocol::provider_action_id;

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct SidebarMessages {
    pub machines: &'static str,
    pub workspaces: &'static str,
    pub panes: &'static str,
    pub tabs: &'static str,
    pub agents: &'static str,
    pub projection_path_separator: &'static str,
    pub new_machine: &'static str,
    pub connect_machine: &'static str,
    pub no_machines: &'static str,
    pub no_workspaces: &'static str,
    pub no_panes: &'static str,
    pub no_tabs: &'static str,
    pub no_agents: &'static str,
    pub recoverable_machine: &'static str,
    pub rename_machine: &'static str,
    pub delete_machine: &'static str,
    pub restore_machine: &'static str,
    pub purge_machine: &'static str,
    pub confirm_delete_machine: &'static str,
    pub confirm_purge_machine: &'static str,
    pub new_workspace: &'static str,
    pub new_isolated_workspace: &'static str,
    pub new_shared_workspace: &'static str,
    pub recoverable_workspace: &'static str,
    pub rename_workspace: &'static str,
    pub delete_workspace: &'static str,
    pub restore_workspace: &'static str,
    pub purge_workspace: &'static str,
    pub confirm_purge_workspace: &'static str,
    pub no_active_session: &'static str,
    pub managed_workspace_unsupported: &'static str,
    pub managed_workspace_machine_inactive: &'static str,
    pub managed_workspace_unavailable: &'static str,
    pub managed_workspace_operation_not_allowed: &'static str,
    pub running: &'static str,
    pub connecting: &'static str,
    pub waking: &'static str,
    pub sleeping_wake_hint: &'static str,
    pub sleeping: &'static str,
    pub stopped: &'static str,
    pub unavailable: &'static str,
    pub working: &'static str,
    pub blocked: &'static str,
    pub idle: &'static str,
    pub done: &'static str,
    pub unknown: &'static str,
    pub connect_prompt: &'static str,
    pub connect_host_prompt: &'static str,
    pub connecting_to: &'static str,
    pub starting_on: &'static str,
    pub failed_to_connect: &'static str,
    pub retry_connection: &'static str,
    pub close_dialog: &'static str,
    pub ssh_hosts: &'static str,
    pub type_to_filter: &'static str,
    pub other_host: &'static str,
    pub personal_scope: &'static str,
    pub plugin_exited: &'static str,
    pub team_scope: &'static str,
    pub scope: &'static str,
    pub provider_actions: &'static str,
    pub action_required: &'static str,
    pub action_too_long: &'static str,
    pub action_invalid_email: &'static str,
    pub action_invalid_integer: &'static str,
    pub action_below_minimum: &'static str,
    pub action_above_maximum: &'static str,
    pub action_missing_selected_machine: &'static str,
    pub action_missing_selected_workspace: &'static str,
    pub action_multiple_fields_unsupported: &'static str,
    pub action_list_workspace_ports: &'static str,
    pub action_make_workspace_port_public: &'static str,
    pub action_make_workspace_port_private: &'static str,
    pub action_open_private_workspace_port: &'static str,
    pub action_workspace_port: &'static str,
    pub confirm_destructive_action: &'static str,
    pub confirm_layout_undo: &'static str,
    pub confirmation_mismatch: &'static str,
    pub layout_nothing_to_undo: &'static str,
    pub layout_undo_stale: &'static str,
    pub initial_machine_connection_failed: &'static str,
    pub provider_notice_identity_unavailable: &'static str,
    pub provider_connection_already_running: &'static str,
    pub machine_provider_disconnected: &'static str,
    pub machine_action_failed: &'static str,
    pub layout_refresh_failed: &'static str,
    pub layout_stale: &'static str,
    pub file_no_focused_pane: &'static str,
    pub file_surface_unavailable: &'static str,
    pub file_input_not_queued: &'static str,
    pub file_path_has_control_characters: &'static str,
    pub file_command_failed: &'static str,
    pub file_sent_to_focused_pane: &'static str,
    pub refresh_remote_tree_retrying: &'static str,
    pub refresh_remote_tree_stopped: &'static str,
    pub clients_list_failed: &'static str,
    pub layout_undo_failed: &'static str,
    pub pairing_response_failed: &'static str,
    pub workspace_state_failed: &'static str,
    pub provider_action_open_url: &'static str,
    pub machine_provider_update_failed: &'static str,
    pub machine_provider_lifecycle_update_failed: &'static str,
    pub machine_provider_workspace_update_failed: &'static str,
    pub machine_reconnect_failed: &'static str,
    pub machine_provider_external_connect_unsupported: &'static str,
    pub machine_provider_external_connect_ambiguous: &'static str,
    pub machine_not_ready_to_connect: &'static str,
    pub machine_managed_authority_unsupported: &'static str,
    pub machine_managed_authority_invalid: &'static str,
    pub machine_catalog_create_unsupported: &'static str,
    pub machine_creation_source_unavailable: &'static str,
    pub machine_name_required: &'static str,
    pub client_machine_unavailable: &'static str,
    pub prototype_machine_added: &'static str,
    pub machine_catalog_provider_actions_unsupported: &'static str,
    pub machine_catalog_updates_failed: &'static str,
    pub machine_catalog_restart_failed: &'static str,
    pub machine_replacement_pending: &'static str,
    pub machine_replacement_worker_stopped: &'static str,
    pub machine_replacement_stale: &'static str,
    pub machine_replacement_not_pending: &'static str,
    pub machine_replacement_target_missing: &'static str,
    pub managed_ssh_requires_unix: &'static str,
    /// Compact machine spend readout template: `{usd}` is the formatted
    /// dollar amount and `{days}` the trailing window length.
    pub machine_usage_readout: &'static str,
}

impl SidebarMessages {
    /// Render the machine spend readout, e.g. `$1.23 / 30d`.
    pub(crate) fn machine_usage_readout(
        &self,
        api_equivalent_usd: f64,
        period_days: u32,
    ) -> String {
        self.machine_usage_readout
            .replace("{usd}", &format_usd(api_equivalent_usd))
            .replace("{days}", &period_days.to_string())
    }

    pub(crate) fn connecting_to_message(&self, target: &str) -> String {
        self.connecting_to.replace("{target}", target)
    }

    pub(crate) fn starting_on_message(&self, target: &str) -> String {
        self.starting_on.replace("{target}", target)
    }

    pub(crate) fn failed_to_connect_message(&self, target: &str) -> String {
        self.failed_to_connect.replace("{target}", target)
    }

    pub(crate) fn provider_action_label(&self, action_id: &str) -> Option<&'static str> {
        match action_id {
            provider_action_id::LIST_WORKSPACE_PORTS => Some(self.action_list_workspace_ports),
            provider_action_id::MAKE_WORKSPACE_PORT_PUBLIC => {
                Some(self.action_make_workspace_port_public)
            }
            provider_action_id::MAKE_WORKSPACE_PORT_PRIVATE => {
                Some(self.action_make_workspace_port_private)
            }
            provider_action_id::OPEN_PRIVATE_WORKSPACE_PORT => {
                Some(self.action_open_private_workspace_port)
            }
            _ => None,
        }
    }

    pub(crate) fn provider_action_field_label(
        &self,
        action_id: &str,
        field_id: &str,
    ) -> Option<&'static str> {
        matches!(
            (action_id, field_id),
            (
                provider_action_id::MAKE_WORKSPACE_PORT_PUBLIC
                    | provider_action_id::MAKE_WORKSPACE_PORT_PRIVATE
                    | provider_action_id::OPEN_PRIVATE_WORKSPACE_PORT,
                "port"
            )
        )
        .then_some(self.action_workspace_port)
    }
}

pub(super) const ENGLISH: SidebarMessages = SidebarMessages {
    machines: "machines",
    workspaces: "workspaces",
    panes: "panes",
    tabs: "tabs",
    agents: "agents",
    projection_path_separator: " › ",
    new_machine: "new vm",
    connect_machine: "ssh host",
    no_machines: "no machines",
    no_workspaces: "no workspaces",
    no_panes: "no panes",
    no_tabs: "no tabs",
    no_agents: "no agents",
    recoverable_machine: "recoverable",
    rename_machine: "Rename machine",
    delete_machine: "Delete machine",
    restore_machine: "Restore machine",
    purge_machine: "Delete permanently",
    confirm_delete_machine: "Type CONFIRM to delete this machine after a final snapshot",
    confirm_purge_machine: "Type CONFIRM to permanently delete this machine and its snapshots",
    new_workspace: "new workspace",
    new_isolated_workspace: "new isolated",
    new_shared_workspace: "new shared",
    recoverable_workspace: "recoverable",
    rename_workspace: "Rename workspace",
    delete_workspace: "Delete workspace",
    restore_workspace: "Restore workspace",
    purge_workspace: "Delete permanently",
    confirm_purge_workspace: "Type CONFIRM to permanently delete this workspace",
    no_active_session: "select or create a machine first",
    managed_workspace_unsupported: "this machine provider cannot create managed workspaces",
    managed_workspace_machine_inactive: "No machine is active; select or reconnect this workspace's machine, then retry",
    managed_workspace_unavailable: "Managed workspace details are unavailable; wait for the provider to refresh, then retry",
    managed_workspace_operation_not_allowed: "The provider does not allow this operation for this workspace; use an action shown in its menu",
    running: "running",
    connecting: "connecting",
    waking: "waking",
    sleeping_wake_hint: "sleeping — press any key to wake",
    sleeping: "sleeping",
    stopped: "stopped",
    unavailable: "unavailable",
    working: "working",
    blocked: "blocked",
    idle: "idle",
    done: "done",
    unknown: "unknown",
    connect_prompt: "Host address or pairing code",
    connect_host_prompt: "SSH host or user@host",
    connecting_to: "Connecting to {target}…",
    starting_on: "Starting a session on {target}…",
    failed_to_connect: "Could not connect to {target}",
    retry_connection: "Retry",
    close_dialog: "Close",
    ssh_hosts: "SSH hosts",
    type_to_filter: "type to filter",
    other_host: "Add SSH host…",
    personal_scope: "personal",
    plugin_exited: "sidebar plugin exited",
    team_scope: "team",
    scope: "scope",
    provider_actions: "actions",
    action_required: "This value is required",
    action_too_long: "This value is too long",
    action_invalid_email: "Enter a valid email address",
    action_invalid_integer: "Enter a whole number",
    action_below_minimum: "This number is below the allowed minimum",
    action_above_maximum: "This number is above the allowed maximum",
    action_missing_selected_machine: "Select a machine before running this action",
    action_missing_selected_workspace: "Select a workspace before running this action",
    action_multiple_fields_unsupported: "This action needs a form that this client cannot show",
    action_list_workspace_ports: "List workspace ports",
    action_make_workspace_port_public: "Make workspace port public",
    action_make_workspace_port_private: "Make workspace port private",
    action_open_private_workspace_port: "Open private workspace port",
    action_workspace_port: "Port",
    confirm_destructive_action: "Type CONFIRM to continue",
    confirm_layout_undo: "Type CONFIRM to close pane(s) {items}",
    confirmation_mismatch: "Type CONFIRM exactly to run this action",
    layout_nothing_to_undo: "Nothing to undo",
    layout_undo_stale: "The layout changed; undo was not applied",
    initial_machine_connection_failed: "Could not connect",
    provider_notice_identity_unavailable: "Could not prepare the connection. Try again; if the problem persists, restart cmux.",
    provider_connection_already_running: "Another connection is already running. Close it and try again.",
    machine_provider_disconnected: "Machine provider disconnected; reconnecting",
    machine_action_failed: "Machine action failed",
    layout_refresh_failed: "Session changed, but its layout refresh failed: {error}",
    layout_stale: "Session changed, but its layout is still stale: {error}",
    file_no_focused_pane: "No focused pane",
    file_surface_unavailable: "Focused surface is unavailable",
    file_input_not_queued: "Input was not queued",
    file_path_has_control_characters: "Folder name has control characters; not typed into the shell",
    file_command_failed: "File command failed: {error}",
    file_sent_to_focused_pane: "Sent to focused pane",
    refresh_remote_tree_retrying: "Refresh remote tree failed; retrying: {error}",
    refresh_remote_tree_stopped: "Refresh remote tree failed after {attempts} attempts; automatic retries stopped, reconnect to retry: {error}",
    clients_list_failed: "Could not list clients: {error}",
    layout_undo_failed: "Could not undo layout: {error}",
    pairing_response_failed: "Could not respond to pairing request: {error}",
    workspace_state_failed: "Could not update workspace state: {error}",
    provider_action_open_url: "Open",
    machine_provider_update_failed: "Machine provider update failed",
    machine_provider_lifecycle_update_failed: "Machine provider lifecycle update failed",
    machine_provider_workspace_update_failed: "Machine provider workspace update failed",
    machine_reconnect_failed: "Could not reconnect machine",
    machine_provider_external_connect_unsupported: "This machine provider cannot connect external machines",
    machine_provider_external_connect_ambiguous: "The previous connection attempt may have succeeded; reconnect the provider and retry with the same pairing code",
    machine_not_ready_to_connect: "Selected machine is not ready to connect",
    machine_managed_authority_unsupported: "This provider cannot authorize managed workspace mirrors; upgrade the machine provider",
    machine_managed_authority_invalid: "The machine provider returned an invalid managed workspace authority binding",
    machine_catalog_create_unsupported: "This machine catalog cannot create machines",
    machine_creation_source_unavailable: "This machine creation source is unavailable",
    machine_name_required: "Enter a machine name",
    client_machine_unavailable: "This client-owned machine is unavailable",
    prototype_machine_added: "Added prototype machine",
    machine_catalog_provider_actions_unsupported: "This machine catalog has no provider actions",
    machine_catalog_updates_failed: "Machine catalog updates could not start",
    machine_catalog_restart_failed: "Machine switched without live catalog updates",
    machine_replacement_pending: "Another machine replacement is already pending",
    machine_replacement_worker_stopped: "Machine replacement worker stopped before commit",
    machine_replacement_stale: "Machine replacement decision is stale",
    machine_replacement_not_pending: "Machine replacement is no longer pending",
    machine_replacement_target_missing: "Machine replacement target is missing",
    managed_ssh_requires_unix: "Managed SSH machine connections require Unix",
    machine_usage_readout: "{usd} / {days}d",
};

pub(super) const JAPANESE: SidebarMessages = SidebarMessages {
    machines: "マシン",
    workspaces: "ワークスペース",
    panes: "ペイン",
    tabs: "タブ",
    agents: "エージェント",
    projection_path_separator: " › ",
    new_machine: "新規VM",
    connect_machine: "SSHホスト",
    no_machines: "マシンがありません",
    no_workspaces: "ワークスペースがありません",
    no_panes: "ペインがありません",
    no_tabs: "タブがありません",
    no_agents: "エージェントがありません",
    recoverable_machine: "復元可能",
    rename_machine: "マシン名を変更",
    delete_machine: "マシンを削除",
    restore_machine: "マシンを復元",
    purge_machine: "完全に削除",
    confirm_delete_machine: "最終スナップショット後に削除するには CONFIRM と入力してください",
    confirm_purge_machine: "マシンとスナップショットを完全に削除するには CONFIRM と入力してください",
    new_workspace: "新規ワークスペース",
    new_isolated_workspace: "新規隔離",
    new_shared_workspace: "新規共有",
    recoverable_workspace: "復元可能",
    rename_workspace: "ワークスペース名を変更",
    delete_workspace: "ワークスペースを削除",
    restore_workspace: "ワークスペースを復元",
    purge_workspace: "完全に削除",
    confirm_purge_workspace: "完全に削除するには CONFIRM と入力してください",
    no_active_session: "先にマシンを選択または作成してください",
    managed_workspace_unsupported: "このマシンプロバイダーは管理ワークスペースを作成できません",
    managed_workspace_machine_inactive: "アクティブなマシンがありません。このワークスペースのマシンを選択または再接続してから再試行してください",
    managed_workspace_unavailable: "管理ワークスペースの情報を取得できません。プロバイダーの更新後に再試行してください",
    managed_workspace_operation_not_allowed: "プロバイダーはこのワークスペースでこの操作を許可していません。メニューに表示される操作を使用してください",
    running: "実行中",
    connecting: "接続中",
    waking: "再開中",
    sleeping_wake_hint: "スリープ中 — 任意のキーで再開",
    sleeping: "スリープ中",
    stopped: "停止",
    unavailable: "利用不可",
    working: "作業中",
    blocked: "ブロック中",
    idle: "待機中",
    done: "完了",
    unknown: "不明",
    connect_prompt: "ホストアドレスまたはペアリングコード",
    connect_host_prompt: "SSH ホストまたは user@host",
    connecting_to: "{target} に接続中…",
    starting_on: "{target} でセッションを開始中…",
    failed_to_connect: "{target} に接続できませんでした",
    retry_connection: "再試行",
    close_dialog: "閉じる",
    ssh_hosts: "SSH ホスト",
    type_to_filter: "入力して絞り込み",
    other_host: "SSH ホストを追加…",
    personal_scope: "個人",
    plugin_exited: "サイドバープラグインが終了しました",
    team_scope: "チーム",
    scope: "スコープ",
    provider_actions: "操作",
    action_required: "この値は必須です",
    action_too_long: "この値は長すぎます",
    action_invalid_email: "有効なメールアドレスを入力してください",
    action_invalid_integer: "整数を入力してください",
    action_below_minimum: "この数値は許可された最小値未満です",
    action_above_maximum: "この数値は許可された最大値を超えています",
    action_missing_selected_machine: "この操作を実行する前にマシンを選択してください",
    action_missing_selected_workspace: "この操作を実行する前にワークスペースを選択してください",
    action_multiple_fields_unsupported: "この操作に必要なフォームをこのクライアントでは表示できません",
    action_list_workspace_ports: "ワークスペースのポートを表示",
    action_make_workspace_port_public: "ワークスペースのポートを公開",
    action_make_workspace_port_private: "ワークスペースのポートを非公開",
    action_open_private_workspace_port: "非公開のワークスペースポートを開く",
    action_workspace_port: "ポート",
    confirm_destructive_action: "続行するには CONFIRM と入力",
    confirm_layout_undo: "ペイン {items} を閉じるには CONFIRM と入力",
    confirmation_mismatch: "この操作を実行するには CONFIRM と正確に入力してください",
    layout_nothing_to_undo: "元に戻せるレイアウト操作はありません",
    layout_undo_stale: "レイアウトが変更されたため、元に戻す操作は適用されませんでした",
    initial_machine_connection_failed: "マシンに接続できませんでした",
    provider_notice_identity_unavailable: "接続を準備できませんでした。もう一度お試しください。問題が解決しない場合は、cmux を再起動してください。",
    provider_connection_already_running: "別の接続がすでに実行中です。終了してから、もう一度お試しください。",
    machine_provider_disconnected: "マシンプロバイダーから切断されました。再接続しています",
    machine_action_failed: "マシン操作に失敗しました",
    layout_refresh_failed: "セッションが変更されましたが、レイアウトの更新に失敗しました: {error}",
    layout_stale: "セッションが変更されましたが、レイアウトはまだ古いままです: {error}",
    file_no_focused_pane: "フォーカスされたペインがありません",
    file_surface_unavailable: "フォーカスされたサーフェスを利用できません",
    file_input_not_queued: "入力をキューに追加できませんでした",
    file_path_has_control_characters: "フォルダ名に制御文字が含まれているため、シェルに入力しません",
    file_command_failed: "ファイル操作に失敗しました: {error}",
    file_sent_to_focused_pane: "フォーカスされたペインに送信しました",
    refresh_remote_tree_retrying: "リモートツリーの更新に失敗しました。再試行しています: {error}",
    refresh_remote_tree_stopped: "{attempts} 回試行しましたがリモートツリーの更新に失敗しました。自動再試行を停止しました。再接続して再試行してください: {error}",
    clients_list_failed: "クライアント一覧を取得できませんでした: {error}",
    layout_undo_failed: "レイアウトを元に戻せませんでした: {error}",
    pairing_response_failed: "ペアリング要求に応答できませんでした: {error}",
    workspace_state_failed: "ワークスペースの状態を更新できませんでした: {error}",
    provider_action_open_url: "リンクを開く",
    machine_provider_update_failed: "マシンプロバイダーの更新に失敗しました",
    machine_provider_lifecycle_update_failed: "マシンプロバイダーのライフサイクル更新に失敗しました",
    machine_provider_workspace_update_failed: "マシンプロバイダーのワークスペース更新に失敗しました",
    machine_reconnect_failed: "マシンに再接続できませんでした",
    machine_provider_external_connect_unsupported: "このマシンプロバイダーは外部マシンに接続できません",
    machine_provider_external_connect_ambiguous: "前回の接続処理が完了している可能性があります。プロバイダーを再接続し、同じペアリングコードで再試行してください",
    machine_not_ready_to_connect: "選択したマシンは接続準備ができていません",
    machine_managed_authority_unsupported: "このプロバイダーは管理ワークスペースのミラーを認可できません。マシンプロバイダーをアップグレードしてください",
    machine_managed_authority_invalid: "マシンプロバイダーから無効な管理ワークスペース権限バインディングが返されました",
    machine_catalog_create_unsupported: "このマシンカタログではマシンを作成できません",
    machine_creation_source_unavailable: "このマシン作成元は利用できません",
    machine_name_required: "マシン名を入力してください",
    client_machine_unavailable: "このクライアント管理マシンは利用できません",
    prototype_machine_added: "プロトタイプマシンを追加しました",
    machine_catalog_provider_actions_unsupported: "このマシンカタログにはプロバイダーアクションがありません",
    machine_catalog_updates_failed: "マシンカタログの更新を開始できませんでした",
    machine_catalog_restart_failed: "マシンは切り替わりましたが、カタログのライブ更新を再開できませんでした",
    machine_replacement_pending: "別のマシン切り替えを処理中です",
    machine_replacement_worker_stopped: "確定前にマシン切り替え処理が停止しました",
    machine_replacement_stale: "マシン切り替えの状態が古くなっています",
    machine_replacement_not_pending: "保留中のマシン切り替えがありません",
    machine_replacement_target_missing: "マシン切り替え先が見つかりません",
    managed_ssh_requires_unix: "管理 SSH マシン接続には Unix が必要です",
    machine_usage_readout: "{usd} / {days}日",
};
