//! `terminal` strings of the CLI catalog (English and Japanese).

#[derive(Debug, PartialEq, Eq)]
pub(crate) struct TerminalMessages {
    pub clear_history_help: &'static str,
    pub clear_history_failed: &'static str,
    pub clear_history_outcome_unknown: &'static str,
    pub clear_history_unsupported: &'static str,
    pub clear_history_fallback_unrepresentable: &'static str,
    pub clear_history_preservation_impossible: &'static str,
    pub clear_history_stream_timeout: &'static str,
    pub clear_history_fallback_write_timeout: &'static str,
    pub clear_history_host_unsupported: &'static str,
    pub clear_history_host_exited: &'static str,
    pub clear_history_host_failed: &'static str,
    pub clear_history_host_malformed_response: &'static str,
    pub clear_history_host_no_response: &'static str,
    pub clear_history_remote_no_response: &'static str,
    pub clear_history_remote_disconnected: &'static str,
    pub clear_history_remote_rejected: &'static str,
    pub clear_history_unexpected: &'static str,
    pub keyboard_text_too_large: &'static str,
    pub paste_text_too_large: &'static str,
    pub deferred_input_destination_changed: &'static str,
    pub pointer_input_discarded_during_layout_change: &'static str,
    pub deferred_input_queue_full: &'static str,
    pub pty_input_too_large: &'static str,
    pub pty_input_queue_full: &'static str,
    pub pty_input_unavailable: &'static str,
    pub pty_input_exited: &'static str,
    pub attach_outcome_unknown: &'static str,
    pub operation_failed: &'static str,
}

pub(super) const ENGLISH: TerminalMessages = TerminalMessages {
    clear_history_help: "Clear PTY history while preserving its active prompt.",
    clear_history_failed: "Could not clear terminal history",
    clear_history_outcome_unknown: "Terminal history clear outcome is unknown. Reconnect the session before retrying.",
    clear_history_unsupported: "clear-history is not supported by this server; restart the cmux-tui server",
    clear_history_fallback_unrepresentable: "the current terminal keyboard mode cannot encode the fallback key",
    clear_history_preservation_impossible: "the active terminal input extends into retained history",
    clear_history_stream_timeout: "terminal output did not reach a safe clear-history boundary",
    clear_history_fallback_write_timeout: "terminal input did not accept the fallback key before timeout",
    clear_history_host_unsupported: "the terminal host does not support clear-history; reconnect the session",
    clear_history_host_exited: "the terminal host exited; reconnect the session",
    clear_history_host_failed: "the terminal host could not clear its history",
    clear_history_host_malformed_response: "the terminal host returned an invalid response; reconnect the session",
    clear_history_host_no_response: "the terminal host did not acknowledge clear-history; reconnect the session",
    clear_history_remote_no_response: "the remote session did not respond",
    clear_history_remote_disconnected: "the remote session disconnected; reconnect it",
    clear_history_remote_rejected: "the remote server rejected clear-history",
    clear_history_unexpected: "an unexpected terminal error occurred",
    keyboard_text_too_large: "Keyboard text exceeds the 4 MiB PTY buffer limit",
    paste_text_too_large: "Paste exceeds the 4 MiB PTY buffer limit",
    deferred_input_destination_changed: "Deferred input was discarded because its destination changed",
    pointer_input_discarded_during_layout_change: "Pointer input was discarded while the layout changed",
    deferred_input_queue_full: "Input queue byte limit reached while a session change is pending",
    pty_input_too_large: "Input exceeds the 4 MiB PTY buffer limit",
    pty_input_queue_full: "PTY input queue is full; input was not sent",
    pty_input_unavailable: "PTY input is unavailable after a transport failure",
    pty_input_exited: "Terminal exited; input was not sent",
    attach_outcome_unknown: "Surface attach outcome is unknown. Detach and reconnect before sending more input",
    operation_failed: "Terminal input failed",
};

pub(super) const JAPANESE: TerminalMessages = TerminalMessages {
    clear_history_help: "アクティブなプロンプトを保持したまま PTY 履歴を消去します。",
    clear_history_failed: "ターミナル履歴を消去できませんでした",
    clear_history_outcome_unknown: "ターミナル履歴の消去結果を確認できません。再試行する前にセッションを再接続してください。",
    clear_history_unsupported: "このサーバーでは clear-history を使用できません。cmux-tui サーバーを再起動してください",
    clear_history_fallback_unrepresentable: "現在のターミナルキーボードモードでは代替キーを送信できません",
    clear_history_preservation_impossible: "アクティブなターミナル入力が保持中の履歴にまたがっています",
    clear_history_stream_timeout: "ターミナル出力が履歴を安全に消去できる境界に達しませんでした",
    clear_history_fallback_write_timeout: "タイムアウトまでにターミナル入力が代替キーを受け付けませんでした",
    clear_history_host_unsupported: "ターミナルホストが clear-history に対応していません。セッションを再接続してください",
    clear_history_host_exited: "ターミナルホストが終了しました。セッションを再接続してください",
    clear_history_host_failed: "ターミナルホストで履歴の消去に失敗しました",
    clear_history_host_malformed_response: "ターミナルホストから無効な応答が返されました。セッションを再接続してください",
    clear_history_host_no_response: "ターミナルホストから clear-history の応答がありませんでした。セッションを再接続してください",
    clear_history_remote_no_response: "リモートセッションから応答がありませんでした",
    clear_history_remote_disconnected: "リモートセッションとの接続が切れました。再接続してください",
    clear_history_remote_rejected: "リモートサーバーが clear-history を拒否しました",
    clear_history_unexpected: "予期しないターミナルエラーが発生しました",
    keyboard_text_too_large: "キーボード入力が 4 MiB の PTY バッファ上限を超えています",
    paste_text_too_large: "貼り付けテキストが 4 MiB の PTY バッファ上限を超えています",
    deferred_input_destination_changed: "遅延入力は送信先が変更されたため破棄されました",
    pointer_input_discarded_during_layout_change: "レイアウトの変更中にポインター入力が破棄されました",
    deferred_input_queue_full: "セッション変更の保留中に入力キューのバイト上限に達しました",
    pty_input_too_large: "入力が 4 MiB の PTY バッファ上限を超えています",
    pty_input_queue_full: "PTY 入力キューがいっぱいのため、入力は送信されませんでした",
    pty_input_unavailable: "転送エラー後のため PTY 入力を使用できません",
    pty_input_exited: "ターミナルが終了したため、入力は送信されませんでした",
    attach_outcome_unknown: "サーフェスの接続結果を確認できません。入力を再開する前に切断して再接続してください",
    operation_failed: "ターミナル入力に失敗しました",
};
