// Every string key the markdown page uses. Values live in `Localizable.xcstrings` next to this file;
// scripts/pages/gen-strings.mjs writes `generated/strings.json`.
export const L = {
  title: "page.title",
  loading: "page.loading",
  failed: "page.failed",
  disconnected: "page.disconnected",
  retry: "page.retry",
  modeLabel: "mode.label",
  rich: "mode.rich",
  source: "mode.source",
  saved: "status.saved",
  edited: "status.edited",
  saving: "status.saving",
  statusFailed: "status.failed",
  readOnly: "status.readOnly",
  readOnlyHelp: "readOnly.outside",
  saveFailed: "save.failed",
  conflictChanged: "conflict.changed",
  conflictDeleted: "conflict.deleted",
  reload: "conflict.reload",
  keep: "conflict.keep",
  frontmatter: "block.frontmatter",
  html: "block.html",
  definition: "block.definition",
  rawSource: "block.source",
  plainText: "code.plainText",
  diagramFailed: "diagram.failed",
} as const;
