// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.0.0-test (SHA-256 a38a1bdd52b7e40974a7f48c69b12e6629072998d2798cd772cc30aaa45fe611).

package richpane

import (
	"context"
	"encoding/json"

	pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
)

// Client is a typed pane-protocol client on one connection. It validates
// params before sending and results and events after receiving.
type Client struct{ Conn *pane.Conn }

// NewClient wraps a serving *pane.Conn.
func NewClient(c *pane.Conn) *Client { return &Client{Conn: c} }

// ComExampleRichClient calls ops in namespace com.example.rich.
type ComExampleRichClient struct{ conn *pane.Conn }

// ComExampleRich returns the com.example.rich namespace client.
func (c *Client) ComExampleRich() ComExampleRichClient { return ComExampleRichClient{conn: c.Conn} }

// DocClose calls com.example.rich.doc.close (mutation, scope rich:write; errors: none).
func (c ComExampleRichClient) DocClose(ctx context.Context, params ComExampleRichDocCloseParams) (ComExampleRichDocCloseResult, error) {
	var zero ComExampleRichDocCloseResult
	raw, err := pane.EncodeAndValidate(params, ValidateComExampleRichDocCloseParams, pane.CodeInvalidParams)
	if err != nil {
		return zero, err
	}
	value, err := c.conn.Call(ctx, OpComExampleRichDocClose, raw)
	if err != nil {
		return zero, err
	}
	return pane.DecodeAndValidate[ComExampleRichDocCloseResult](value, ValidateComExampleRichDocCloseResult, pane.CodeInvalidResult)
}

// DocOpen calls com.example.rich.doc.open (mutation, scope rich:write; errors: com.example.rich.not_found, com.example.rich.locked).
func (c ComExampleRichClient) DocOpen(ctx context.Context, params ComExampleRichDocOpenParams) (Doc, error) {
	var zero Doc
	raw, err := pane.EncodeAndValidate(params, ValidateComExampleRichDocOpenParams, pane.CodeInvalidParams)
	if err != nil {
		return zero, err
	}
	value, err := c.conn.Call(ctx, OpComExampleRichDocOpen, raw)
	if err != nil {
		return zero, err
	}
	return pane.DecodeAndValidate[Doc](value, ValidateDoc, pane.CodeInvalidResult)
}

// SubscribeDocChanged subscribes to com.example.rich.doc.changed (scope rich:read).
func (c ComExampleRichClient) SubscribeDocChanged(ctx context.Context, filter json.RawMessage) (*pane.TypedSubscription[Doc], error) {
	sub, err := c.conn.Subscribe(ctx, EventComExampleRichDocChanged, filter)
	if err != nil {
		return nil, err
	}
	return pane.NewTypedSubscription[Doc](sub, ValidateDoc), nil
}
