// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.0.0-test (SHA-256 a38a1bdd52b7e40974a7f48c69b12e6629072998d2798cd772cc30aaa45fe611).

package richpane

import pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"

// IR the package was generated from.
const (
	IRVersion = "0.0.0-test"
	IRSHA256  = "a38a1bdd52b7e40974a7f48c69b12e6629072998d2798cd772cc30aaa45fe611"
)

// Op names.
const (
	OpComExampleRichDocClose = "com.example.rich.doc.close"
	OpComExampleRichDocOpen  = "com.example.rich.doc.open"
)

// Event stream names.
const (
	EventComExampleRichDocChanged = "com.example.rich.doc.changed"
)

// Op error codes declared in the IR.
const (
	ErrComExampleRichLocked   = "com.example.rich.locked"
	ErrComExampleRichNotFound = "com.example.rich.not_found"
)

// Catalog is the IR this package was generated from, as the runtime enforces
// it: per op the scope, path params, risk metadata and validators.
var Catalog = &pane.Catalog{
	IRVersion: IRVersion,
	IRSHA256:  IRSHA256,
	Ops: []pane.OpInfo{
		{
			Name: "com.example.rich.doc.close", Kind: "mutation", Scope: "rich:write",
			Errors: nil, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "com_example_rich_doc_close",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "mutate-own", Gesture: false, ScopeClass: "sensitive", ServerOnly: false,
			ValidateParams: ValidateComExampleRichDocCloseParams, ValidateResult: ValidateComExampleRichDocCloseResult,
		},
		{
			Name: "com.example.rich.doc.open", Kind: "mutation", Scope: "rich:write",
			Errors: []string{"com.example.rich.not_found", "com.example.rich.locked"}, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "com_example_rich_doc_open",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "mutate-own", Gesture: false, ScopeClass: "sensitive", ServerOnly: false,
			ValidateParams: ValidateComExampleRichDocOpenParams, ValidateResult: ValidateDoc,
		},
	},
	Events: []pane.EventInfo{
		{Name: "com.example.rich.doc.changed", Scope: "rich:read", Validate: ValidateDoc},
	},
}

// ProviderNamespaces are the namespaces this package serves.
var ProviderNamespaces = []string{"com.example.rich"}
