// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.0.0-test (SHA-256 a38a1bdd52b7e40974a7f48c69b12e6629072998d2798cd772cc30aaa45fe611).

package richpane

import (
	"context"
	"encoding/json"

	pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
)

// App is the app id that owns com.example.rich.
const App = "com.example.rich"

// NewProvider creates a provider for App that owns ProviderNamespaces. Register
// a handler for each namespace, then call Run.
func NewProvider() (*pane.Provider, error) {
	return pane.NewProvider(App, Catalog, ProviderNamespaces...)
}

// ComExampleRichHandler serves the ops and event streams of namespace com.example.rich.
// Params arrive validated; results and events are validated before they
// are sent. Return *pane.Error with a declared code for expected failures;
// any other error is logged and sent as cmux.protocol.internal.
type ComExampleRichHandler interface {
	// DocClose serves com.example.rich.doc.close (mutation, scope rich:write; errors: none).
	DocClose(ctx context.Context, call *pane.Call, params ComExampleRichDocCloseParams) (ComExampleRichDocCloseResult, error)
	// DocOpen serves com.example.rich.doc.open (mutation, scope rich:write; errors: com.example.rich.not_found, com.example.rich.locked).
	DocOpen(ctx context.Context, call *pane.Call, params ComExampleRichDocOpenParams) (Doc, error)
	// SubscribeDocChanged runs when a peer subscribes to com.example.rich.doc.changed (scope
	// rich:read), before the ok. Emit on sink for this subscriber only;
	// return an error to refuse. Do not block: start a goroutine that stops
	// when ctx is done. Publish reaches every subscriber.
	SubscribeDocChanged(ctx context.Context, call *pane.Call, sink *pane.TypedSink[Doc]) error
}

// RegisterComExampleRich registers h for every op and event of com.example.rich.
func RegisterComExampleRich(p *pane.Provider, h ComExampleRichHandler) error {
	if err := p.Register(OpComExampleRichDocClose, func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {
		var params ComExampleRichDocCloseParams
		if err := json.Unmarshal(raw, &params); err != nil {
			return nil, err
		}
		result, err := h.DocClose(ctx, call, params)
		if err != nil {
			return nil, err
		}
		return json.Marshal(result)
	}); err != nil {
		return err
	}
	if err := p.Register(OpComExampleRichDocOpen, func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {
		var params ComExampleRichDocOpenParams
		if err := json.Unmarshal(raw, &params); err != nil {
			return nil, err
		}
		result, err := h.DocOpen(ctx, call, params)
		if err != nil {
			return nil, err
		}
		return json.Marshal(result)
	}); err != nil {
		return err
	}
	if err := p.RegisterEvent(EventComExampleRichDocChanged, pane.EventHandler{
		OnSubscribe: func(ctx context.Context, call *pane.Call, sink *pane.Sink) error {
			return h.SubscribeDocChanged(ctx, call, pane.NewTypedSink[Doc](sink))
		},
	}); err != nil {
		return err
	}
	return nil
}

// PublishComExampleRichDocChanged publishes com.example.rich.doc.changed to its subscribers.
func PublishComExampleRichDocChanged(p *pane.Provider, data Doc) error {
	raw, err := json.Marshal(data)
	if err != nil {
		return err
	}
	return p.Publish(EventComExampleRichDocChanged, raw) // validated against Catalog
}
