// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.0.0-test (SHA-256 a38a1bdd52b7e40974a7f48c69b12e6629072998d2798cd772cc30aaa45fe611).

package richpane

import pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"

// ValidateComExampleRichDocCloseParams checks a decoded JSON value (pane.DecodeValue)
// against com.example.rich.doc.close params.
func ValidateComExampleRichDocCloseParams(v any) error {
	return validateComExampleRichDocCloseParams(v, "")
}

func validateComExampleRichDocCloseParams(v any, path string) error {
	{
		o1, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o1, path, "id"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o1, path, "id"); err != nil {
			return err
		}
		if x2, ok := o1["id"]; ok {
			if err := pane.CheckUint(x2, pane.Field(path, "id"), nil); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateComExampleRichDocCloseResult checks a decoded JSON value (pane.DecodeValue)
// against com.example.rich.doc.close result.
func ValidateComExampleRichDocCloseResult(v any) error {
	return validateComExampleRichDocCloseResult(v, "")
}

func validateComExampleRichDocCloseResult(v any, path string) error {
	if err := pane.CheckNull(v, path); err != nil {
		return err
	}
	return nil
}

// ValidateComExampleRichDocOpenParams checks a decoded JSON value (pane.DecodeValue)
// against com.example.rich.doc.open params.
func ValidateComExampleRichDocOpenParams(v any) error {
	return validateComExampleRichDocOpenParams(v, "")
}

func validateComExampleRichDocOpenParams(v any, path string) error {
	{
		o3, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o3, path, "path", "mode"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o3, path, "path", "mode", "cursor", "tags", "limits"); err != nil {
			return err
		}
		if x4, ok := o3["path"]; ok {
			if err := pane.CheckString(x4, pane.Field(path, "path")); err != nil {
				return err
			}
		}
		if x5, ok := o3["mode"]; ok {
			if err := validateMode(x5, pane.Field(path, "mode")); err != nil {
				return err
			}
		}
		if x6, ok := o3["cursor"]; ok {
			if x6 != nil {
				if err := validateCursor(x6, pane.Field(path, "cursor")); err != nil {
					return err
				}
			}
		}
		if x7, ok := o3["tags"]; ok {
			{
				a8, err := pane.AsArray(x7, pane.Field(path, "tags"))
				if err != nil {
					return err
				}
				for i9, x10 := range a8 {
					if err := pane.CheckString(x10, pane.Index(pane.Field(path, "tags"), i9)); err != nil {
						return err
					}
				}
			}
		}
		if x11, ok := o3["limits"]; ok {
			{
				o12, err := pane.AsObject(x11, pane.Field(path, "limits"))
				if err != nil {
					return err
				}
				if err := pane.RequireFields(o12, pane.Field(path, "limits"), "lines"); err != nil {
					return err
				}
				if err := pane.OnlyFields(o12, pane.Field(path, "limits"), "lines"); err != nil {
					return err
				}
				if x13, ok := o12["lines"]; ok {
					if err := pane.CheckUint(x13, pane.Field(pane.Field(path, "limits"), "lines"), pane.U64(100000)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateComExampleRichDocOpenParamsLimits checks a decoded JSON value (pane.DecodeValue)
// against ComExampleRichDocOpenParams.limits.
func ValidateComExampleRichDocOpenParamsLimits(v any) error {
	return validateComExampleRichDocOpenParamsLimits(v, "")
}

func validateComExampleRichDocOpenParamsLimits(v any, path string) error {
	{
		o14, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o14, path, "lines"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o14, path, "lines"); err != nil {
			return err
		}
		if x15, ok := o14["lines"]; ok {
			if err := pane.CheckUint(x15, pane.Field(path, "lines"), pane.U64(100000)); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateCursor checks a decoded JSON value (pane.DecodeValue)
// against types.Cursor.
func ValidateCursor(v any) error { return validateCursor(v, "") }

func validateCursor(v any, path string) error {
	{
		o16, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o16, path, "line", "col"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o16, path, "line", "col"); err != nil {
			return err
		}
		if x17, ok := o16["line"]; ok {
			if err := pane.CheckInt(x17, pane.Field(path, "line"), pane.I64(1), nil); err != nil {
				return err
			}
		}
		if x18, ok := o16["col"]; ok {
			if err := pane.CheckInt(x18, pane.Field(path, "col"), pane.I64(-2147483648), pane.I64(2147483647)); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateDoc checks a decoded JSON value (pane.DecodeValue)
// against types.Doc.
func ValidateDoc(v any) error { return validateDoc(v, "") }

func validateDoc(v any, path string) error {
	{
		o19, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o19, path, "id", "kind", "meta", "lines"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o19, path, "id", "kind", "score", "meta", "lines", "extra"); err != nil {
			return err
		}
		if x20, ok := o19["id"]; ok {
			if err := pane.CheckUint(x20, pane.Field(path, "id"), nil); err != nil {
				return err
			}
		}
		if x21, ok := o19["kind"]; ok {
			if err := pane.CheckString(x21, pane.Field(path, "kind"), "doc"); err != nil {
				return err
			}
		}
		if x22, ok := o19["score"]; ok {
			if err := pane.CheckNumber(x22, pane.Field(path, "score")); err != nil {
				return err
			}
		}
		if x23, ok := o19["meta"]; ok {
			{
				o24, err := pane.AsObject(x23, pane.Field(path, "meta"))
				if err != nil {
					return err
				}
				for k25, x26 := range o24 {
					if err := pane.CheckString(x26, pane.Field(pane.Field(path, "meta"), k25)); err != nil {
						return err
					}
				}
			}
		}
		if x27, ok := o19["lines"]; ok {
			{
				a28, err := pane.AsArray(x27, pane.Field(path, "lines"))
				if err != nil {
					return err
				}
				for i29, x30 := range a28 {
					if err := pane.CheckString(x30, pane.Index(pane.Field(path, "lines"), i29)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateMode checks a decoded JSON value (pane.DecodeValue)
// against types.Mode.
func ValidateMode(v any) error { return validateMode(v, "") }

func validateMode(v any, path string) error {
	if err := pane.CheckString(v, path, "read", "write"); err != nil {
		return err
	}
	return nil
}

// Validators maps each IR type name to its validator (for conformance vectors
// and dynamic checks).
var Validators = map[string]func(any) error{
	"Cursor": ValidateCursor,
	"Doc":    ValidateDoc,
	"Mode":   ValidateMode,
}
