from __future__ import annotations

import copy
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

from codegen.pane import generate as pane_generate
from codegen.pane.emit_go import render
from codegen.pane.ir import (
    SUPPORTED_KEYWORDS,
    PaneIRError,
    file_sha256,
    parse_pane_ir,
    parse_pane_ir_with_fragment,
)
from codegen.pane import ir as pane_ir


GO_PANE = Path(__file__).resolve().parents[3] / "go-pane"
SEED = GO_PANE.parent.parent / "crates" / "cmux-pane-protocol" / "spec" / "pane-protocol.json"  # Rust emit-ir output
VECTORS = Path(os.environ.get("PANE_PROTOCOL_VECTORS", str(SEED.parent / "pane-protocol-vectors.json")))
RICH = GO_PANE / "testdata" / "pane-protocol.rich.json"

# Committed generated packages and the arguments that produce them.
COMMITTED = (
    (SEED, GO_PANE / "examples" / "hello" / "hellopane", "hellopane", ("com.example.hello",)),
    (RICH, GO_PANE / "internal" / "richpane", "richpane", ("com.example.rich",)),
)


def seed() -> dict:
    return json.loads(SEED.read_text(encoding="utf-8"))


def parse(document: dict):
    return parse_pane_ir(json.dumps(document))


@unittest.skipUnless(shutil.which("gofmt"), "gofmt is required for Go generation")
class PaneGoEmitterTests(unittest.TestCase):
    def test_committed_packages_match_the_ir(self) -> None:
        for ir_path, out, package, provider_ns in COMMITTED:
            problems = pane_generate.run(
                ir_path=ir_path, out=out, package=package, provider_ns=provider_ns, mode="check"
            )
            self.assertEqual(problems, [], f"regenerate {out} with codegen/pane/generate.py --write")

    def test_output_is_deterministic(self) -> None:
        ir = parse(seed())
        first = render(ir, package="x", provider_namespaces=("com.example.hello",))
        second = render(parse(seed()), package="x", provider_namespaces=("com.example.hello",))
        self.assertEqual(first, second)
        self.assertEqual(sorted(first), ["client.go", "ops.go", "provider.go", "types.go", "validate.go"])

    def test_client_only_package_has_no_provider(self) -> None:
        files = render(parse(seed()), package="x")
        self.assertNotIn("provider.go", files)
        self.assertIn("func (c ComExampleHelloClient) GreetSay(", files["client.go"])

    def test_provider_has_one_handler_interface_per_owned_namespace(self) -> None:
        provider = render(parse(seed()), package="x", provider_namespaces=("com.example.hello",))["provider.go"]
        self.assertIn("type ComExampleHelloHandler interface", provider)
        self.assertNotIn("CmuxHandler", provider)
        self.assertIn('const App = "com.example.hello"', provider)

    def test_check_mode_reports_drift(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "pkg"
            args = dict(ir_path=SEED, out=out, package="pkg", provider_ns=("com.example.hello",))
            self.assertTrue(pane_generate.run(mode="check", **args))
            pane_generate.run(mode="write", **args)
            self.assertEqual(pane_generate.run(mode="check", **args), [])
            (out / "types.go").write_text("// edited\n", encoding="utf-8")
            (out / "extra.go").write_text(
                "// Code generated by cmux pane-protocol codegen. DO NOT EDIT.\npackage pkg\n",
                encoding="utf-8",
            )
            (out / "handwritten_test.go").write_text("package pkg\n", encoding="utf-8")
            problems = pane_generate.run(mode="check", **args)
            self.assertTrue(any("stale" in p and "types.go" in p for p in problems), problems)
            self.assertTrue(any("extra.go" in p for p in problems), problems)
            self.assertFalse(any("handwritten" in p for p in problems), problems)
            pane_generate.run(mode="write", **args)
            self.assertFalse((out / "extra.go").exists())
            self.assertTrue((out / "handwritten_test.go").exists())


class PaneIRTests(unittest.TestCase):
    def assertRefused(self, document: dict, fragment: str) -> None:
        with self.assertRaises(PaneIRError) as caught:
            parse(document)
        self.assertIn(fragment, str(caught.exception))

    def test_unsupported_keywords_are_refused(self) -> None:
        cases = {
            "lookahead pattern": ({"type": "string", "pattern": "^(?=a)"}, "RE2 cannot run"),
            "patternProperties": ({"type": "object", "patternProperties": {}}, "unsupported schema keyword"),
            "oneOf": ({"oneOf": [{"type": "string"}, {"type": "integer"}]}, "oneOf"),
            "union": ({"type": ["string", "integer"]}, "union types"),
            "ref sibling": ({"$ref": "#/types/HelloResult", "minimum": 1}, "unsupported schema keyword"),
            "allOf of two": ({"allOf": [{"type": "string"}, {"maxLength": 3}]}, "allOf is supported only with one"),
            "float format": ({"type": "integer", "format": "float"}, "integer format"),
            "external ref": ({"$ref": "other.json#/X"}, "unsupported $ref"),
        }
        for name, (schema, fragment) in cases.items():
            with self.subTest(name):
                document = seed()
                document["types"]["HelloParams"]["properties"]["name"] = schema
                self.assertRefused(document, fragment)

    def test_ops_must_stay_in_their_namespace(self) -> None:
        hello = next(i for i, op in enumerate(seed()["ops"]) if op["name"] == "com.example.hello.greet.say")
        document = seed()
        document["ops"][hello]["name"] = "com.example.other.greet.say"
        self.assertRefused(document, "outside every declared namespace")
        document = seed()
        document["ops"][0]["errors"] = ["com.example.hello.oops"]
        self.assertRefused(document, "outside namespace 'cmux'")
        document = seed()
        document["ops"][hello]["name"] = "com.example.hello.say"
        self.assertRefused(document, "<namespace>.<family>.<verb>")
        document = seed()
        document["ops"][0]["owner"] = "app:com.example.hello"
        self.assertRefused(document, "is owned by")

    def test_third_party_namespace_is_its_app_id(self) -> None:
        document = seed()
        document["namespaces"][1]["owner"] = "app:com.example.other"
        self.assertRefused(document, "is not its owner's app id")

    def test_unknown_refs_and_duplicates(self) -> None:
        document = seed()
        document["ops"][0]["result"] = {"$ref": "#/types/Missing"}
        self.assertRefused(document, "unknown type 'Missing'")
        with self.assertRaises(PaneIRError):
            parse_pane_ir('{"version":"1","version":"2","namespaces":[],"ops":[],"types":{}}')

    def test_provider_namespaces_must_share_one_owner(self) -> None:
        with self.assertRaises(PaneIRError):
            render(parse(seed()), package="x", provider_namespaces=("cmux", "com.example.hello"))
        with self.assertRaises(PaneIRError):
            render(parse(seed()), package="x", provider_namespaces=("com.nope",))

    def test_risk_gesture_and_scope_class(self) -> None:
        ir = parse(seed())
        hello = next(op for op in ir.ops if op.name == "cmux.router.hello")
        self.assertEqual((hello.risk, hello.gesture, hello.scope_class, hello.server_only), ("mutate-shared", False, "sensitive", False))
        document = seed()
        document["ops"][0]["risk"] = "money"
        self.assertRefused(document, "risk must be one of")
        document = seed()
        del document["ops"][0]["gesture"]
        self.assertRefused(document, "gesture must be a boolean")
        document = seed()
        document["ops"][0]["scope_class"] = "restricted"  # stale against the table
        self.assertRefused(document, "the table gives 'standard'")
        document = seed()
        document["ops"][0]["scope"] = "git:use"
        self.assertRefused(document, "matches no rule")
        document = seed()
        document["ops"][0]["scope"] = "process:spawn:git"
        document["ops"][0]["scope_class"] = "restricted"
        self.assertRefused(document, "server_only False but the table gives True")
        document["ops"][0]["server_only"] = True
        op = parse(document).ops[0]
        self.assertEqual((op.scope_class, op.server_only), ("restricted", True))

    def test_hash_is_of_the_file_bytes(self) -> None:
        text = SEED.read_text(encoding="utf-8")
        self.assertEqual(parse_pane_ir(text).sha256, file_sha256(text))

    def test_rust_ir_unions_and_enums(self) -> None:
        ir = parse(seed())
        self.assertIsInstance(ir.types["PageProvider"], pane_ir.Union)
        self.assertEqual(ir.types["PageProvider"].tag, "kind")
        self.assertEqual(ir.types["EndpointKind"], pane_ir.Str(("ws", "unix")))

    def test_alias_rules(self) -> None:
        document = seed()
        hello = next(op for op in document["ops"] if op["name"] == "com.example.hello.greet.say")
        hello["aliases"] = ["greet.say"]
        self.assertRefused(document, "third-party op may not declare aliases")
        document = seed()
        document["ops"][0]["aliases"] = ["cmux.git.diff"]
        self.assertRefused(document, "names an existing op")
        document = seed()
        document["ops"][0]["aliases"] = ["cmux.git.status.changed"]
        self.assertRefused(document, "names an existing op, event")
        document = seed()
        document["ops"][0]["aliases"] = ["git.status"]
        self.assertEqual(parse(document).ops[0].aliases, ("git.status",))

    def test_mcp_cli_and_paths_rules(self) -> None:
        document = seed()
        status = document["ops"][0]
        diff = copy.deepcopy(status)
        diff.pop("cli")
        status["name"], diff["name"] = "cmux.git-x.status", "cmux.git.x-status"
        document["ops"].append(diff)
        self.assertRefused(document, "same MCP tool name")
        document = seed()
        document["ops"][1]["cli"] = {"path": "git status", "visible": True}
        self.assertRefused(document, "same cli path")
        document = seed()
        document["ops"][1]["cli"] = {"path": "git diff", "visible": True, "positional": ["nope"]}
        self.assertRefused(document, "positional 'nope'")
        document = seed()
        document["ops"][0]["paths"] = ["missing"]
        self.assertRefused(document, "not a top-level param")
        document = seed()
        document["ops"][0]["name"] = "cmux.git." + "x" * 40
        self.assertRefused(document, "longer than 48")
        ir = parse(seed())
        self.assertEqual(ir.ops[0].paths, ("cwd",))
        self.assertEqual(ir.ops[0].mcp, {"expose": "default", "group": "git"})
        self.assertFalse(any(op.secret_output for op in ir.ops))

    def test_schemars_nullable_shape(self) -> None:
        document = copy.deepcopy(seed())
        document["types"]["HelloResult"]["properties"]["message"] = {
            "anyOf": [{"$ref": "#/$defs/HelloParams"}, {"type": "null"}],
            "description": "schemars Option<T>",
        }
        ir = parse(document)
        self.assertEqual(type(ir.types["HelloResult"].props[0].node).__name__, "Nullable")


@unittest.skipUnless(VECTORS.exists(), "no shared vectors")
class PaneVectorTests(unittest.TestCase):
    """The generator-side sections of the Rust lane's vectors.json."""

    def setUp(self) -> None:
        self.vectors = json.loads(VECTORS.read_text(encoding="utf-8"))

    def test_supported_keywords_match_rust(self) -> None:
        section = self.vectors["ir_keywords"]
        self.assertEqual(SUPPORTED_KEYWORDS, set(section["supported"]))
        self.assertEqual(pane_ir._ANNOTATIONS, set(section["annotations"]))

    def test_fragments(self) -> None:
        base = SEED.read_text(encoding="utf-8")
        for vector in self.vectors["fragments"]:
            with self.subTest(vector["name"]):
                text = json.dumps(vector["fragment"])
                if vector["valid"]:
                    ir = parse_pane_ir_with_fragment(base, text)
                    self.assertEqual(ir.sha256, file_sha256(text))
                    owned = tuple(ns["name"] for ns in vector["fragment"].get("namespaces", ()))
                    render(ir, package="x", provider_namespaces=owned)
                    expect = dict(vector.get("expect") or {})
                    if expect:
                        name = expect.pop("op")
                        op = next(o for o in ir.ops if o.name == name)
                        for field, value in expect.items():
                            got = getattr(op, field)
                            self.assertEqual(list(got) if isinstance(got, tuple) else got, value, field)
                else:
                    with self.assertRaises(PaneIRError):
                        parse_pane_ir_with_fragment(base, text)


if __name__ == "__main__":
    unittest.main()
