#!/usr/bin/env python3
"""Generates the agent brand catalog from design/agent-icons/ for Swift and TypeScript.

Source of truth: design/agent-icons/manifest.json plus one monochrome SVG per brand in
design/agent-icons/svg/. Outputs:

- Packages/Shared/CmuxAgentBrands/Sources/CmuxAgentBrands/AgentBrandCatalog+Generated.swift
  (CmuxNext macOS app and the iOS app)
- webviews/src/agent-session/shared/agentBrands.generated.ts (React pages and the agent pane)
- agent-chat/src/agentBrands.generated.ts (the agent-chat sidecar; the same module)

Each SVG must be minimal: only <svg viewBox fill="currentColor"> and <path> children with d,
fill-rule, opacity, or fill="none" stroke="currentColor" stroke-width. Path data is normalized
to absolute M, L, C and Z, so both platforms draw it with a trivial parser and no SVG engine.
Run with --check to fail when an output is out of date or an SVG breaks the rules.
"""
import argparse
import importlib.util
import json
import math
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "design" / "agent-icons"
SWIFT_OUT = REPO / "Packages/Shared/CmuxAgentBrands/Sources/CmuxAgentBrands/AgentBrandCatalog+Generated.swift"
TS_OUT = REPO / "webviews/src/agent-session/shared/agentBrands.generated.ts"
AGENT_CHAT_OUT = REPO / "agent-chat/src/agentBrands.generated.ts"
HEADER = "Generated by scripts/agent-icons/generate.py from design/agent-icons. Do not edit."
SVG_NS = "{http://www.w3.org/2000/svg}"
HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")
ID = re.compile(r"^[a-z0-9][a-z0-9_-]*$")


def load_path_tools():
    """Reuses the icon pack's SVG path parser (arcs, quadratics and shorthands become cubics)."""
    spec = importlib.util.spec_from_file_location("build_pack", REPO / "scripts/icons/build_pack.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.parse_path, module.fmt


parse_path, fmt = load_path_tools()


class SourceError(Exception):
    pass


def decimals_for(view_box):
    """About a thousandth of the view box: 3 decimals on a 24-unit grid, none on a 4000-unit one."""
    return max(0, min(3, 3 - math.floor(math.log10(max(view_box[2], view_box[3]) / 24))))


def num(v, decimals):
    s = f"{round(v, decimals):.{decimals}f}"
    s = s.rstrip("0").rstrip(".") if "." in s else s
    return "0" if s in ("-0", "") else s


def normalize(d, decimals):
    """Absolute M, L, C and Z only, for the Swift renderer."""
    out = []
    for seg in parse_path(d):
        op = seg[0]
        out.append(op + " ".join(f"{num(x, decimals)} {num(y, decimals)}" for x, y in seg[1:]) if op != "Z" else "Z")
    return "".join(out)


def read_svg(brand_id):
    path = SOURCE / "svg" / f"{brand_id}.svg"
    if not path.exists():
        raise SourceError(f"{path.relative_to(REPO)} is missing")
    text = path.read_text()
    root = ET.fromstring(text)
    where = path.relative_to(REPO)
    if root.tag != SVG_NS + "svg":
        raise SourceError(f"{where}: root is not <svg>")
    extra = set(root.attrib) - {"viewBox", "fill"}
    if extra or root.get("fill") != "currentColor" or not root.get("viewBox"):
        raise SourceError(f"{where}: root must be <svg viewBox fill=\"currentColor\"> only (has {sorted(root.attrib)})")
    view_box = [float(v) for v in root.get("viewBox").replace(",", " ").split()]
    if len(view_box) != 4 or view_box[2] <= 0 or view_box[3] <= 0:
        raise SourceError(f"{where}: bad viewBox")
    paths = []
    for child in root:
        if child.tag != SVG_NS + "path":
            raise SourceError(f"{where}: only <path> children are allowed, found {child.tag.replace(SVG_NS, '')}")
        attrs = dict(child.attrib)
        if len(child):
            raise SourceError(f"{where}: <path> must have no children")
        raw = attrs.pop("d")
        # The web draws the minimized source path; Swift draws the normalized one.
        item = {"svgD": raw, "d": normalize(raw, decimals_for(view_box))}
        if attrs.pop("fill-rule", None) == "evenodd":
            item["evenOdd"] = True
        if "opacity" in attrs:
            item["monoOpacity"] = float(attrs.pop("opacity"))
        if "stroke-width" in attrs:
            if attrs.pop("fill", None) != "none" or attrs.pop("stroke", None) != "currentColor":
                raise SourceError(f"{where}: a stroked path needs fill=\"none\" stroke=\"currentColor\"")
            item["strokeWidth"] = float(attrs.pop("stroke-width"))
        if attrs:
            raise SourceError(f"{where}: unsupported path attributes {sorted(attrs)}")
        paths.append(item)
    if not paths:
        raise SourceError(f"{where}: no paths")
    return text, view_box, paths


def tone(value, where):
    pair = [value, value] if isinstance(value, str) else value
    if not (isinstance(pair, list) and len(pair) == 2 and all(isinstance(v, str) and HEX.match(v) for v in pair)):
        raise SourceError(f"{where}: a tone is \"#RRGGBB\" or [dark, light]")
    return [v.upper() for v in pair]


def load():
    manifest = json.loads((SOURCE / "manifest.json").read_text())
    default_budget = manifest["sizeBudgetBytes"]
    brands, sizes = [], {}
    seen = set()
    for entry in manifest["brands"]:
        bid = entry["id"]
        if not ID.match(bid) or bid in seen:
            raise SourceError(f"brand id {bid!r} is invalid or repeated")
        seen.add(bid)
        for key in ("name", "owner", "kind", "source"):
            if not entry.get(key):
                raise SourceError(f"brand {bid}: missing {key}")
        if entry["kind"] not in ("mark", "wordmark"):
            raise SourceError(f"brand {bid}: kind is mark or wordmark")
        for key in ("url", "file", "license"):
            if not entry["source"].get(key):
                raise SourceError(f"brand {bid}: source.{key} is required")
        text, view_box, paths = read_svg(bid)
        budget = entry.get("sizeBudgetBytes", default_budget)
        size = len(text.encode())
        sizes[bid] = size
        if size > budget:
            raise SourceError(f"svg/{bid}.svg is {size} B, over its {budget} B budget")
        color = entry["color"]
        spec = {"id": bid, "name": entry["name"], "kind": entry["kind"], "viewBox": view_box,
                "tone": tone(color["tone"], f"brand {bid}"), "paths": paths}
        for index, override in color.get("paths", {}).items():
            i = int(index)
            if i >= len(paths):
                raise SourceError(f"brand {bid}: color.paths[{index}] has no path")
            paths[i]["tone"] = tone(override["tone"], f"brand {bid} path {index}")
        if "tile" in color:
            tile = color["tile"]
            spec["tile"] = {"viewBox": [float(v) for v in tile["viewBox"].split()], "radius": float(tile["radius"]),
                            "tone": tone(tile["tone"], f"brand {bid} tile")}
        if "overlays" in color:
            spec["overlays"] = [{"x1": o["x1"], "y1": o["y1"], "x2": o["x2"], "y2": o["y2"],
                                 "stops": [[float(s[0]), tone(s[1], bid)[0], float(s[2])] for s in o["stops"]]}
                                for o in color["overlays"]]
        brands.append(spec)
    unused = {p.stem for p in (SOURCE / "svg").glob("*.svg")} - seen
    if unused:
        raise SourceError(f"svg files without a manifest brand: {sorted(unused)}")

    lookup = {}

    def add(key, brand, where):
        key = key.strip().lower()
        if not key:
            raise SourceError(f"{where}: empty id")
        if brand is not None and brand not in seen:
            raise SourceError(f"{where}: unknown brand {brand!r}")
        if key in lookup and lookup[key] != brand:
            raise SourceError(f"{where}: {key!r} maps to both {lookup[key]!r} and {brand!r}")
        lookup[key] = brand

    agents = []
    for agent in manifest["agents"]:
        add(agent["id"], agent["brand"], f"agent {agent['id']}")
        for alias in agent["aliases"]:
            add(alias, agent["brand"], f"agent {agent['id']} alias")
        agents.append({"id": agent["id"], "name": agent["name"], "brand": agent["brand"]})
    for provider in manifest["providers"]:
        add(provider["id"], provider["brand"], f"provider {provider['id']}")
    for bid in seen:
        if bid not in lookup:
            add(bid, bid, f"brand {bid}")
    cases = [[c[0], c[1]] for c in manifest["resolutionCases"]]
    return brands, agents, dict(sorted(lookup.items())), cases, sizes


# MARK: Swift


def swift_str(s):
    return json.dumps(s, ensure_ascii=False)


def swift_tone(t):
    return f"AgentBrandTone(dark: 0x{t[0][1:]}, light: 0x{t[1][1:]})"


def swift_num(v):
    return fmt(v) if fmt(v) != "-0" else "0"


def swift_rect(v):
    return f"AgentBrandRect(x: {swift_num(v[0])}, y: {swift_num(v[1])}, width: {swift_num(v[2])}, height: {swift_num(v[3])})"


def swift_member(bid):
    return bid if bid.isidentifier() else "`" + bid + "`"


def swift(brands, agents, lookup, cases):
    lines = [f"// {HEADER}", "// swiftlint:disable all", "", "extension AgentBrandID {"]
    lines.append("    /// Every brand with a mark, in manifest order.")
    lines.append("    public static let allCases: [AgentBrandID] = [" + ", ".join("." + swift_member(b["id"]) for b in brands) + "]")
    for b in brands:
        lines.append(f"    public static let {swift_member(b['id'])} = AgentBrandID(rawValue: {swift_str(b['id'])})")
    lines += ["}", "", "extension AgentBrandCatalog {", "    static let specs: [AgentBrandID: AgentBrandSpec] = ["]
    for b in brands:
        lines.append(f"        .{swift_member(b['id'])}: AgentBrandSpec(")
        lines.append(f"            name: {swift_str(b['name'])},")
        lines.append(f"            isWordmark: {'true' if b['kind'] == 'wordmark' else 'false'},")
        lines.append(f"            viewBox: {swift_rect(b['viewBox'])},")
        lines.append(f"            tone: {swift_tone(b['tone'])},")
        lines.append("            paths: [")
        for p in b["paths"]:
            args = [f"d: {swift_str(p['d'])}"]
            if p.get("evenOdd"):
                args.append("evenOdd: true")
            if "tone" in p:
                args.append(f"tone: {swift_tone(p['tone'])}")
            if "monoOpacity" in p:
                args.append(f"monoOpacity: {swift_num(p['monoOpacity'])}")
            if "strokeWidth" in p:
                args.append(f"strokeWidth: {swift_num(p['strokeWidth'])}")
            lines.append(f"                AgentBrandPathSpec({', '.join(args)}),")
        lines.append("            ],")
        tile = b.get("tile")
        lines.append("            tile: " + (f"AgentBrandTile(viewBox: {swift_rect(tile['viewBox'])}, radius: {swift_num(tile['radius'])}, tone: {swift_tone(tile['tone'])})" if tile else "nil") + ",")
        overlays = b.get("overlays", [])
        if overlays:
            lines.append("            overlays: [")
            for o in overlays:
                stops = ", ".join(f"AgentBrandGradientStop(offset: {swift_num(s[0])}, color: 0x{s[1][1:]}, opacity: {swift_num(s[2])})" for s in o["stops"])
                lines.append(f"                AgentBrandGradient(x1: {swift_num(o['x1'])}, y1: {swift_num(o['y1'])}, x2: {swift_num(o['x2'])}, y2: {swift_num(o['y2'])}, stops: [{stops}]),")
            lines.append("            ]")
        else:
            lines.append("            overlays: []")
        lines.append("        ),")
    lines += ["    ]", "", "    /// Agent, alias, provider and brand ids, lowercased, to a brand; nil means known but without a mark.",
              "    static let lookup: [String: AgentBrandID?] = ["]
    for key, brand in lookup.items():
        lines.append(f"        {swift_str(key)}: " + (f".{swift_member(brand)}" if brand else "nil") + ",")
    lines += ["    ]", "", "    /// The agents and harnesses cmux supports, with their display names.",
              "    public static let agents: [AgentDescriptor] = ["]
    for a in agents:
        lines.append(f"        AgentDescriptor(id: {swift_str(a['id'])}, name: {swift_str(a['name'])}, brand: " + (f".{swift_member(a['brand'])}" if a["brand"] else "nil") + "),")
    lines += ["    ]", "", "    /// Inputs and the brand they must resolve to; shared with the TypeScript resolver's tests.",
              "    public static let resolutionCases: [(input: String, brand: AgentBrandID?)] = ["]
    for inp, brand in cases:
        lines.append(f"        ({swift_str(inp)}, " + (f".{swift_member(brand)}" if brand else "nil") + "),")
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


# MARK: TypeScript


def ts(brands, agents, lookup, cases):
    def tone_ts(t):
        return json.dumps(t[0]) if t[0] == t[1] else f"[{json.dumps(t[0])}, {json.dumps(t[1])}]"

    out = [f"// {HEADER}", "/* eslint-disable */", "",
           "/// A color, or one per theme: [on dark, on light].",
           "export type BrandTone = string | readonly [dark: string, light: string];", "",
           "export type BrandPath = {",
           "  /** SVG path data. */", "  d: string;", "  evenOdd?: boolean;",
           "  /** This path's own brand tone; otherwise the mark's. */", "  tone?: BrandTone;",
           "  /** Opacity in mono; 0 hides the path (detail the brand style paints in its own tone). */",
           "  monoOpacity?: number;", "  /** Stroke instead of fill, at this width in view-box units. */",
           "  strokeWidth?: number;", "};", "",
           "export type BrandGradient = {", "  x1: number;", "  y1: number;", "  x2: number;", "  y2: number;",
           "  stops: readonly (readonly [offset: number, color: string, opacity: number])[];", "};", "",
           "export type AgentBrandSpec = {", "  name: string;", "  wordmark?: boolean;",
           "  /** [minX, minY, width, height] */", "  viewBox: readonly [number, number, number, number];",
           "  tone: BrandTone;", "  paths: readonly BrandPath[];",
           "  /** Brand style only: a rounded tile behind the mark, in its own view box. */",
           "  tile?: { viewBox: readonly [number, number, number, number]; radius: number; tone: BrandTone };",
           "  /** Brand style only: gradients laid over the whole mark. */",
           "  overlays?: readonly BrandGradient[];", "};", "",
           "export const AGENT_BRANDS = {"]
    for b in brands:
        out.append(f"  {json.dumps(b['id'])}: {{")
        out.append(f"    name: {json.dumps(b['name'])},")
        if b["kind"] == "wordmark":
            out.append("    wordmark: true,")
        out.append(f"    viewBox: [{', '.join(fmt(v) for v in b['viewBox'])}],")
        out.append(f"    tone: {tone_ts(b['tone'])},")
        out.append("    paths: [")
        for p in b["paths"]:
            fields = [f"d: {json.dumps(p['svgD'])}"]
            if p.get("evenOdd"):
                fields.append("evenOdd: true")
            if "tone" in p:
                fields.append(f"tone: {tone_ts(p['tone'])}")
            if "monoOpacity" in p:
                fields.append(f"monoOpacity: {fmt(p['monoOpacity'])}")
            if "strokeWidth" in p:
                fields.append(f"strokeWidth: {fmt(p['strokeWidth'])}")
            out.append(f"      {{ {', '.join(fields)} }},")
        out.append("    ],")
        if b.get("tile"):
            t = b["tile"]
            out.append(f"    tile: {{ viewBox: [{', '.join(fmt(v) for v in t['viewBox'])}], radius: {fmt(t['radius'])}, tone: {tone_ts(t['tone'])} }},")
        if b.get("overlays"):
            out.append("    overlays: [")
            for o in b["overlays"]:
                stops = ", ".join(f"[{fmt(s[0])}, {json.dumps(s[1])}, {fmt(s[2])}]" for s in o["stops"])
                out.append(f"      {{ x1: {fmt(o['x1'])}, y1: {fmt(o['y1'])}, x2: {fmt(o['x2'])}, y2: {fmt(o['y2'])}, stops: [{stops}] }},")
            out.append("    ],")
        out.append("  },")
    out += ["} as const satisfies Record<string, AgentBrandSpec>;", "",
            "export type AgentBrandId = keyof typeof AGENT_BRANDS;", "",
            "/// Agent, alias, provider and brand ids, lowercased, to a brand; null means known but without a mark.",
            "export const AGENT_BRAND_LOOKUP: Readonly<Record<string, AgentBrandId | null>> = {"]
    for key, brand in lookup.items():
        out.append(f"  {json.dumps(key)}: {json.dumps(brand)},")
    out += ["};", "", "/// The agents and harnesses cmux supports, with their display names.",
            "export const SUPPORTED_AGENTS: readonly { id: string; name: string; brand: AgentBrandId | null }[] = ["]
    for a in agents:
        out.append(f"  {{ id: {json.dumps(a['id'])}, name: {json.dumps(a['name'])}, brand: {json.dumps(a['brand'])} }},")
    out += ["];", "", "/// Inputs and the brand they must resolve to; shared with the Swift resolver's tests.",
            "export const AGENT_BRAND_RESOLUTION_CASES: readonly (readonly [input: string, brand: AgentBrandId | null])[] = ["]
    for inp, brand in cases:
        out.append(f"  [{json.dumps(inp)}, {json.dumps(brand)}],")
    out += ["];", "", TS_RESOLVER]
    return "\n".join(out)


TS_RESOLVER = """/// The ids an agent string may be known by, most specific first. Must match
/// AgentBrandCatalog.candidates in Packages/Shared/CmuxAgentBrands (both run
/// AGENT_BRAND_RESOLUTION_CASES).
function candidates(raw: string): string[] {
  const id = raw.trim().toLowerCase();
  if (!id) return [];
  const out = [id];
  const add = (value: string | undefined) => {
    if (value && !out.includes(value)) out.push(value);
  };
  add(id.split(":").filter(Boolean).at(-1));
  add(id.split("/").filter(Boolean).at(-1));
  const word = out.at(-1)!.split(/\\s+/).find(Boolean);
  add(word);
  add(word?.split(/[-_.]/).find(Boolean));
  return out;
}

/// The brand for an agent, harness, alias, binary path or provider id ("claude-sr",
/// "acp:claude", "/usr/local/bin/codex", "xai"), or undefined when it has no mark. The
/// first candidate the catalog knows decides, including ids known to have no mark.
export function agentBrand(agent: string | undefined): AgentBrandId | undefined {
  if (!agent) return undefined;
  for (const candidate of candidates(agent))
    if (Object.hasOwn(AGENT_BRAND_LOOKUP, candidate)) return AGENT_BRAND_LOOKUP[candidate] ?? undefined;
  return undefined;
}

/// The mark to draw for an agent id, or undefined for the generic glyph.
export function agentBrandSpec(agent: string | undefined): AgentBrandSpec | undefined {
  const brand = agentBrand(agent);
  return brand ? AGENT_BRANDS[brand] : undefined;
}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when an output is out of date")
    parser.add_argument("--sizes", action="store_true", help="print each mark's SVG size")
    args = parser.parse_args()
    try:
        brands, agents, lookup, cases, sizes = load()
    except (SourceError, KeyError, ValueError, ET.ParseError) as error:
        print(f"agent-icons: {error}", file=sys.stderr)
        return 1
    module = ts(brands, agents, lookup, cases)
    outputs = {SWIFT_OUT: swift(brands, agents, lookup, cases), TS_OUT: module, AGENT_CHAT_OUT: module}
    stale = []
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(REPO)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if args.sizes:
        for bid, size in sorted(sizes.items(), key=lambda kv: -kv[1]):
            print(f"{bid:12} {size:6d} B")
        print(f"{'total':12} {sum(sizes.values()):6d} B")
    if stale:
        print("agent icons out of date; run scripts/agent-icons/generate.py:\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    if not args.check:
        print(f"{len(brands)} brands, {len(lookup)} ids -> " + ", ".join(str(p.relative_to(REPO)) for p in outputs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
