//! The catalog of declared ops, events, interfaces and namespaces, and the
//! IR it emits (`spec/pane-protocol.json`):
//! `{version, namespaces, ops[], events[], interfaces[], types{...}}`.
//! Op params, results and event data are `{"$ref": "#/types/<Name>"}` into
//! `types`, which holds JSON Schema 2020-12 subschemas generated by
//! schemars. Generators in every language read only this file.

use std::collections::BTreeMap;

use schemars::JsonSchema;
use schemars::generate::{SchemaGenerator, SchemaSettings};
use serde::Serialize;
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};

use crate::op::{Event, McpExpose, Op, OpKind};

/// The IR format version.
pub const IR_VERSION: &str = "0.1.0";

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NamespaceDecl {
    pub name: String,
    /// `first-party`, or `app:<app id>`.
    pub owner: String,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct OpDecl {
    pub name: String,
    pub kind: OpKind,
    pub scope: String,
    /// `first-party`, or `app:<app id>`: the owner of the op's namespace.
    pub owner: String,
    /// Old wire names that still reach this op.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub aliases: Vec<String>,
    pub params: Value,
    pub result: Value,
    pub errors: Vec<String>,
    /// What the op does (decision 27).
    pub risk: crate::op::Risk,
    /// Whether a call needs a user gesture token.
    pub gesture: bool,
    /// Derived from scope-classes.json: standard, sensitive or restricted.
    pub scope_class: String,
    /// Derived: the scope's rule is server-only.
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub server_only: bool,
    /// Params that name filesystem paths; every provider confines them to
    /// the token's roots (decisions 20, 22). Empty when none.
    pub paths: Vec<String>,
    /// Agent exposure; `{"expose":"never"}` unless declared.
    pub mcp: McpDecl,
    /// The CLI verb, if the op has one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cli: Option<CliDecl>,
    /// Derived: some property reachable from `result` has
    /// `x-cmux-secret: true`. Such ops are never offered to agents.
    pub secret_output: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct McpDecl {
    pub expose: McpExpose,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CliDecl {
    pub path: String,
    pub visible: bool,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub positional: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct EventDecl {
    pub name: String,
    pub scope: String,
    pub data: Value,
}

/// An interface, in the shape of `cmux-tui/crates/cmux-app-host/interfaces/<name>/<major>.json`.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct InterfaceDecl {
    /// `<name>/<major>`, such as `cmux.diff.source/1`.
    pub name: String,
    pub version: u32,
    pub docs: String,
    pub props: Map<String, Value>,
    /// Method name to signature text.
    pub methods: BTreeMap<String, String>,
    pub events: Vec<String>,
    pub status: String,
}

/// Collects declarations; [`CatalogBuilder::build`] freezes them into a
/// [`Catalog`].
pub struct CatalogBuilder {
    generator: SchemaGenerator,
    namespaces: Vec<NamespaceDecl>,
    ops: Vec<OpDecl>,
    events: Vec<EventDecl>,
    interfaces: Vec<InterfaceDecl>,
}

/// Everything declared, with the generated schemas. Plain data, so a
/// router can share it across threads.
#[derive(Debug, Clone)]
pub struct Catalog {
    namespaces: Vec<NamespaceDecl>,
    ops: Vec<OpDecl>,
    events: Vec<EventDecl>,
    interfaces: Vec<InterfaceDecl>,
    types: Map<String, Value>,
}

impl Default for CatalogBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl Catalog {
    pub fn builder() -> CatalogBuilder {
        CatalogBuilder::new()
    }
}

impl CatalogBuilder {
    pub fn new() -> Self {
        let mut settings = SchemaSettings::draft2020_12();
        settings.definitions_path = "/types".into();
        Self {
            generator: settings.into_generator(),
            namespaces: Vec::new(),
            ops: Vec::new(),
            events: Vec::new(),
            interfaces: Vec::new(),
        }
    }

    pub fn build(self) -> Catalog {
        let types = self.generator.definitions().clone();
        let mut ops = self.ops;
        for op in &mut ops {
            op.secret_output = secret_output(&op.result, &types);
            // An unclassified scope leaves "" here; emit-ir's merge check
            // then refuses the IR.
            if let Ok((class, server_only)) = crate::scope_class::classify(&op.scope) {
                op.scope_class = class;
                op.server_only = server_only;
            }
        }
        Catalog {
            types,
            namespaces: self.namespaces,
            ops,
            events: self.events,
            interfaces: self.interfaces,
        }
    }

    /// Declare a namespace. `owner` is `None` for first party (`cmux`), or
    /// the app id that reserves it.
    pub fn namespace(mut self, name: &str, owner: Option<&str>) -> Self {
        let owner = owner.map_or_else(|| "first-party".to_owned(), |app| format!("app:{app}"));
        self.namespaces.push(NamespaceDecl { name: name.to_owned(), owner });
        self
    }

    pub fn op<O: Op>(mut self) -> Self {
        let params = self.schema_value::<O::Params>();
        let result = self.schema_value::<O::Result>();
        let owner = self.owner_of(O::NAME);
        self.ops.push(OpDecl {
            name: O::NAME.to_owned(),
            kind: O::KIND,
            scope: O::SCOPE.to_owned(),
            owner,
            aliases: O::ALIASES.iter().map(|alias| (*alias).to_owned()).collect(),
            params,
            result,
            errors: O::ERRORS.iter().map(|code| (*code).to_owned()).collect(),
            risk: O::RISK,
            gesture: O::GESTURE,
            scope_class: String::new(),
            server_only: false,
            paths: O::PATH_PARAMS.iter().map(|name| (*name).to_owned()).collect(),
            mcp: McpDecl {
                expose: O::MCP.expose,
                group: O::MCP.group.first().map(|group| (*group).to_owned()),
            },
            cli: O::CLI.first().map(|cli| CliDecl {
                path: cli.path.to_owned(),
                visible: cli.visible,
                positional: cli.positional.iter().map(|name| (*name).to_owned()).collect(),
            }),
            secret_output: false,
        });
        self
    }

    pub fn event<E: Event>(mut self) -> Self {
        let data = self.schema_value::<E::Data>();
        self.events.push(EventDecl { name: E::NAME.to_owned(), scope: E::SCOPE.to_owned(), data });
        self
    }

    pub fn interface(mut self, interface: InterfaceDecl) -> Self {
        self.interfaces.push(interface);
        self
    }

    /// The owner of the longest declared namespace containing `name`.
    fn owner_of(&self, name: &str) -> String {
        self.namespaces
            .iter()
            .filter(|ns| crate::router::within(name, &ns.name))
            .max_by_key(|ns| ns.name.len())
            .map_or_else(|| "first-party".to_owned(), |ns| ns.owner.clone())
    }

    fn schema_value<T: JsonSchema>(&mut self) -> Value {
        serde_json::to_value(self.generator.subschema_for::<T>()).unwrap_or(Value::Null)
    }
}

impl Catalog {
    pub fn ops(&self) -> &[OpDecl] {
        &self.ops
    }

    pub fn op_decl(&self, name: &str) -> Option<&OpDecl> {
        self.ops.iter().find(|op| op.name == name)
    }

    pub fn event_decl(&self, name: &str) -> Option<&EventDecl> {
        self.events.iter().find(|event| event.name == name)
    }

    pub fn namespaces(&self) -> &[NamespaceDecl] {
        &self.namespaces
    }

    pub fn interfaces(&self) -> &[InterfaceDecl] {
        &self.interfaces
    }

    /// The IR document, with every object's keys sorted.
    pub fn ir(&self) -> Value {
        let types = &self.types;
        canonical(&json!({
            "version": IR_VERSION,
            "namespaces": self.namespaces,
            "ops": self.ops,
            "events": self.events,
            "interfaces": self.interfaces,
            "types": types,
        }))
    }

    /// The committed file's exact text: pretty JSON and a trailing newline.
    pub fn ir_text(&self) -> String {
        let mut text = serde_json::to_string_pretty(&self.ir()).unwrap_or_default();
        text.push('\n');
        text
    }

    /// Lowercase hex SHA-256 of [`Catalog::ir_text`], sent in provider hello.
    pub fn digest(&self) -> String {
        digest_text(&self.ir_text())
    }
}

/// A serde `deserialize_with` for an `Option` field that must be present
/// (it may be null). Pair it with [`require_all`] so the IR agrees.
pub fn nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <Option<T> as serde::Deserialize>::deserialize(deserializer)
}

/// A schemars transform: every property is required, including `Option`
/// ones, which stay nullable. For results whose nullable fields are always
/// present on the wire (`GitStatus.branch`).
pub fn require_all(schema: &mut schemars::Schema) {
    let Some(object) = schema.as_object_mut() else { return };
    let names: Vec<Value> = object
        .get("properties")
        .and_then(Value::as_object)
        .map(|properties| properties.keys().map(|name| Value::String(name.clone())).collect())
        .unwrap_or_default();
    object.insert("required".into(), Value::Array(names));
}

/// Lowercase hex SHA-256 of `text`.
pub fn digest_text(text: &str) -> String {
    Sha256::digest(text.as_bytes()).iter().map(|byte| format!("{byte:02x}")).collect()
}

/// `value` with every object's keys in sorted order, so the output does not
/// depend on whether serde_json preserves insertion order in this build.
pub fn canonical(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let sorted: BTreeMap<&String, Value> =
                map.iter().map(|(key, value)| (key, canonical(value))).collect();
            let mut out = Map::new();
            for (key, value) in sorted {
                out.insert(key.clone(), value);
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(canonical).collect()),
        other => other.clone(),
    }
}

pub use crate::ir_merge::{
    ANNOTATION_KEYWORDS, FragmentValidator, MergeError, SUPPORTED_KEYWORDS, ShapeValidator, merge,
    schema_keywords_supported,
};
pub use crate::ir_merge::{mcp_tool_name, secret_output, strip_derived, valid_cli_path};

/// A JSON Schema validator for one schema of an IR document (an op's
/// `params` or `result`, or `{"$ref": "#/types/<Name>"}`), resolving refs
/// against the IR's `types`. Every receiver validates untrusted peers'
/// payloads with the IR, not only with its own types.
pub fn validator(ir: &Value, schema: &Value) -> anyhow::Result<jsonschema::Validator> {
    let mut root = Map::new();
    root.insert("$schema".into(), json!("https://json-schema.org/draft/2020-12/schema"));
    root.insert("types".into(), ir.get("types").cloned().unwrap_or_else(|| json!({})));
    root.insert("allOf".into(), json!([schema]));
    jsonschema::validator_for(&Value::Object(root)).map_err(|error| anyhow::anyhow!("{error}"))
}
