// Typed session over any Transport (spec: "Wire", "Transports"). One Session per connection.
// Both peers are symmetric: either may call, subscribe or open a stream, and either may
// serve registered handlers. Ids are per connection and per direction, so results may
// arrive in any order.

import { disposeSymbol } from "./dispose";
import {
  decodeBinaryFrame,
  decodeEnvelope,
  encodeBinaryFrame,
  encodeEnvelope,
  type CallMessage,
  type Envelope,
  type ErrMessage,
  type OpenMessage,
  type SubMessage,
} from "./envelope";
import { ProtocolError, ProtocolErrorCode, type ValidationIssue } from "./errors";
import { ByteStream, type ByteStreamHost, type ByteStreamOptions } from "./stream";
import type { Transport, TransportCloseInfo, TransportMessage } from "./transport";

/**
 * Validators the session applies to every incoming value. Each returns `null` when the IR
 * has no entry for the name (unknown op or event), otherwise the list of issues ([] = valid).
 * Generated by the codegen as `schema` in generated/validators.ts.
 */
export interface SessionSchema {
  validateParams(op: string, value: unknown): ValidationIssue[] | null;
  validateResult(op: string, value: unknown): ValidationIssue[] | null;
  validateEvent(event: string, value: unknown): ValidationIssue[] | null;
}

export interface SessionOptions {
  /** "client" (the dialing side) opens odd stream ids, "server" even ids. */
  role: "client" | "server";
  /**
   * When set, incoming params, results and events are checked against it, and names the
   * schema does not know are refused (peers are untrusted). Leave unset only in tests.
   */
  schema?: SessionSchema;
  /** Malformed or unexpected messages the session dropped. */
  onProtocolError?: (error: Error) => void;
  maxFramePayload?: number;
}

export interface CallOptions {
  signal?: AbortSignal;
  /** Capability handle sent as `cap`. */
  cap?: RemoteHandle | string;
}

export interface SubscribeOptions<T = unknown> {
  filter?: Record<string, unknown>;
  cap?: RemoteHandle | string;
  /** Aborting before the `ok` cancels the subscribe; aborting after unsubscribes. */
  signal?: AbortSignal;
  onEvent: (data: T, seq: number) => void;
  /**
   * Events were lost before this one. `dropped` means the provider said so (`gap:true`, its queue
   * overflowed; decision 15); otherwise seq skipped. Either way, resync from a fresh read.
   */
  onGap?: (gap: { expected: number; received: number; dropped: boolean }) => void;
  /** An event failed validation and was dropped. */
  onInvalid?: (error: ProtocolError, seq: number) => void;
  /** The session closed under the subscription. */
  onEnd?: (error: ProtocolError) => void;
}

export interface HandlerContext {
  id: number;
  op: string;
  cap: string | undefined;
  /** Aborted when the peer cancels or the session closes. */
  signal: AbortSignal;
  session: Session;
}

export type CallHandler = (params: unknown, ctx: HandlerContext) => unknown;

export interface EventSourceContext {
  stream: string;
  filter: Record<string, unknown> | undefined;
  cap: string | undefined;
  /** Sends one event with the next seq (starting at 1). */
  emit(data: unknown): void;
  /** Aborted on unsub or session close. */
  signal: AbortSignal;
}

export type EventSource = (ctx: EventSourceContext) => void;

export interface StreamHandlerContext {
  op: string;
  cap: string | undefined;
  params: unknown;
  session: Session;
}

export type StreamHandler = (stream: ByteStream, ctx: StreamHandlerContext) => void;

interface PendingCall {
  op: string;
  resolve: (value: unknown) => void;
  reject: (error: ProtocolError) => void;
  cleanup: () => void;
}

interface ActiveSubscription {
  stream: string;
  lastSeq: number | null;
  options: SubscribeOptions<unknown>;
}

interface ServedSubscription {
  controller: AbortController;
}

function capId(cap: RemoteHandle | string | undefined): string | undefined {
  if (cap === undefined) return undefined;
  return typeof cap === "string" ? cap : cap.id;
}

function cancelledError(): ProtocolError {
  return new ProtocolError(ProtocolErrorCode.cancelled, "cancelled");
}

/** A handle the peer gave us. Release it when done; `using` releases it at scope exit. */
export class RemoteHandle {
  readonly id: string;
  private readonly session: Session;
  private releasedFlag = false;

  constructor(session: Session, id: string) {
    this.session = session;
    this.id = id;
  }

  get released(): boolean {
    return this.releasedFlag;
  }

  release(): void {
    if (this.releasedFlag) return;
    this.releasedFlag = true;
    this.session.releaseRemoteHandle(this);
  }

  [disposeSymbol](): void {
    this.release();
  }
}

export class Subscription {
  /** Subscription id the peer assigned (`ok` value `{"sub":n}`). */
  readonly id: number;
  readonly stream: string;
  private readonly session: Session;
  private active = true;

  constructor(session: Session, id: number, stream: string) {
    this.session = session;
    this.id = id;
    this.stream = stream;
  }

  get lastSeq(): number | null {
    return this.session.subscriptionLastSeq(this.id);
  }

  unsubscribe(): void {
    if (!this.active) return;
    this.active = false;
    this.session.unsubscribe(this.id);
  }

  [disposeSymbol](): void {
    this.unsubscribe();
  }
}

export class Session {
  private readonly transport: Transport;
  private readonly options: SessionOptions;
  private nextCallId = 1;
  private nextServedSubId = 1;
  private nextStreamId: number;
  private readonly pending = new Map<number, PendingCall>();
  private readonly subscriptions = new Map<number, ActiveSubscription>();
  private readonly handlers = new Map<string, CallHandler>();
  private readonly sources = new Map<string, EventSource>();
  private readonly streamHandlers = new Map<string, StreamHandler>();
  private readonly running = new Map<number, AbortController>();
  private readonly served = new Map<number, ServedSubscription>();
  private readonly streams = new Map<number, ByteStream>();
  private readonly remoteHandles = new Map<string, RemoteHandle>();
  private readonly exportedHandles = new Map<string, () => void>();
  private readonly closeListeners = new Set<(error: ProtocolError) => void>();
  private closeError: ProtocolError | null = null;
  private readonly detach: Array<() => void>;
  private readonly streamHost: ByteStreamHost;

  constructor(transport: Transport, options: SessionOptions) {
    this.transport = transport;
    this.options = options;
    this.nextStreamId = options.role === "client" ? 1 : 2;
    this.streamHost = {
      sendFrame: (stream, payload) => this.sendRaw(encodeBinaryFrame({ stream, credit: 0, payload })),
      sendCredit: (stream, bytes) => this.send({ t: "credit", stream, bytes }),
      sendEnd: (stream, abort) => this.send(abort ? { t: "end", stream, ...abort } : { t: "end", stream }),
      forget: (stream) => this.streams.delete(stream),
    };
    this.detach = [transport.onMessage((msg) => this.receive(msg)), transport.onClose((info) => this.shutdown(info))];
    if (transport.closed) this.shutdown({ reason: "transport closed before session start" });
  }

  get closed(): boolean {
    return this.closeError !== null;
  }

  // Outgoing calls.

  call(op: string, params: unknown, options: CallOptions = {}): Promise<unknown> {
    if (this.closeError) return Promise.reject(this.closeError);
    const { signal } = options;
    if (signal?.aborted) return Promise.reject(cancelledError());
    const id = this.nextCallId++;
    return new Promise<unknown>((resolve, reject) => {
      const onAbort = () => {
        if (!this.pending.delete(id)) return;
        this.trySend({ t: "cancel", id });
        reject(cancelledError());
      };
      signal?.addEventListener("abort", onAbort, { once: true });
      this.pending.set(id, {
        op,
        resolve,
        reject,
        cleanup: () => signal?.removeEventListener("abort", onAbort),
      });
      const msg: CallMessage = { t: "call", id, op, params: params ?? {} };
      const cap = capId(options.cap);
      if (cap !== undefined) msg.cap = cap;
      this.sendOrFail(id, msg);
    });
  }

  // Subscriptions to the peer.

  subscribe<T = unknown>(stream: string, options: SubscribeOptions<T>): Promise<Subscription> {
    if (this.closeError) return Promise.reject(this.closeError);
    const { signal } = options;
    if (signal?.aborted) return Promise.reject(cancelledError());
    const id = this.nextCallId++;
    return new Promise<Subscription>((resolve, reject) => {
      const onAbort = () => {
        if (!this.pending.delete(id)) return;
        this.trySend({ t: "cancel", id });
        reject(cancelledError());
      };
      signal?.addEventListener("abort", onAbort, { once: true });
      this.pending.set(id, {
        op: stream,
        resolve: (value) => {
          signal?.removeEventListener("abort", onAbort);
          const subId = (value as { sub?: unknown } | null)?.sub;
          if (typeof subId !== "number" || !Number.isSafeInteger(subId) || subId < 1) {
            reject(new ProtocolError(ProtocolErrorCode.invalidResult, "subscribe result must be {sub:<id>}"));
            return;
          }
          this.subscriptions.set(subId, { stream, lastSeq: null, options: options as SubscribeOptions<unknown> });
          const subscription = new Subscription(this, subId, stream);
          signal?.addEventListener("abort", () => subscription.unsubscribe(), { once: true });
          resolve(subscription);
        },
        reject,
        cleanup: () => signal?.removeEventListener("abort", onAbort),
      });
      const msg: SubMessage = { t: "sub", id, stream };
      if (options.filter) msg.filter = options.filter;
      const cap = capId(options.cap);
      if (cap !== undefined) msg.cap = cap;
      this.sendOrFail(id, msg);
    });
  }

  /** @internal Used by Subscription. */
  unsubscribe(subId: number): void {
    if (!this.subscriptions.delete(subId)) return;
    this.trySend({ t: "unsub", sub: subId });
  }

  /** @internal Used by Subscription. */
  subscriptionLastSeq(subId: number): number | null {
    return this.subscriptions.get(subId)?.lastSeq ?? null;
  }

  // Handles.

  /** Wraps a handle id the peer returned. The same id yields the same object until released. */
  handle(id: string): RemoteHandle {
    let handle = this.remoteHandles.get(id);
    if (!handle) {
      handle = new RemoteHandle(this, id);
      this.remoteHandles.set(id, handle);
    }
    return handle;
  }

  /** @internal Used by RemoteHandle. */
  releaseRemoteHandle(handle: RemoteHandle): void {
    if (this.remoteHandles.get(handle.id) === handle) this.remoteHandles.delete(handle.id);
    this.trySend({ t: "release", handle: handle.id });
  }

  /** Declares a handle we hand to the peer; `onRelease` runs when the peer releases it or the session closes. */
  exportHandle(id: string, onRelease: () => void): void {
    this.exportedHandles.set(id, onRelease);
  }

  // Local handlers (the peer calls us).

  register(op: string, handler: CallHandler): () => void {
    this.handlers.set(op, handler);
    return () => {
      if (this.handlers.get(op) === handler) this.handlers.delete(op);
    };
  }

  provide(stream: string, source: EventSource): () => void {
    this.sources.set(stream, source);
    return () => {
      if (this.sources.get(stream) === source) this.sources.delete(stream);
    };
  }

  onStream(op: string, handler: StreamHandler): () => void {
    this.streamHandlers.set(op, handler);
    return () => {
      if (this.streamHandlers.get(op) === handler) this.streamHandlers.delete(op);
    };
  }

  // Byte streams.

  /** Opens a byte stream for `op`; resolves when the peer accepts it. */
  openStream(op: string, params: unknown, options: ByteStreamOptions & CallOptions = {}): Promise<ByteStream> {
    if (this.closeError) return Promise.reject(this.closeError);
    const id = this.nextCallId++;
    const streamId = this.nextStreamId;
    this.nextStreamId += 2;
    const stream = new ByteStream(this.streamHost, streamId, op, {
      window: options.window,
      maxFramePayload: options.maxFramePayload ?? this.options.maxFramePayload,
    });
    this.streams.set(streamId, stream);
    return new Promise<ByteStream>((resolve, reject) => {
      const { signal } = options;
      const onAbort = () => {
        if (!this.pending.delete(id)) return;
        this.trySend({ t: "cancel", id });
        stream.abort(ProtocolErrorCode.cancelled, "cancelled");
        reject(cancelledError());
      };
      signal?.addEventListener("abort", onAbort, { once: true });
      this.pending.set(id, {
        op,
        resolve: () => {
          signal?.removeEventListener("abort", onAbort);
          resolve(stream);
        },
        reject: (error) => {
          stream.fail(error);
          reject(error);
        },
        cleanup: () => signal?.removeEventListener("abort", onAbort),
      });
      const msg: OpenMessage = { t: "open", id, stream: streamId, op };
      if (params !== undefined) msg.params = params;
      const cap = capId(options.cap);
      if (cap !== undefined) msg.cap = cap;
      if (this.sendOrFail(id, msg)) stream.start();
    });
  }

  // Lifecycle.

  onClose(cb: (error: ProtocolError) => void): () => void {
    const error = this.closeError;
    if (error) {
      queueMicrotask(() => cb(error));
      return () => {};
    }
    this.closeListeners.add(cb);
    return () => this.closeListeners.delete(cb);
  }

  close(): void {
    // Queued releases, unsubs and replies still go out before the transport closes.
    this.flush();
    this.transport.close();
    this.shutdown({ reason: "session closed" });
  }

  // Incoming.

  private receive(msg: TransportMessage): void {
    if (this.closeError) return;
    if (typeof msg !== "string") {
      this.receiveBinary(msg);
      return;
    }
    let envelope: Envelope;
    try {
      envelope = decodeEnvelope(msg);
    } catch (error) {
      this.protocolError(error as Error);
      this.refuseMalformed(msg, error as Error);
      return;
    }
    switch (envelope.t) {
      case "ok":
        this.settle(envelope.id, (call) => {
          if (call.op && this.options.schema && !this.subscribeOrStream(call)) {
            const issues = this.options.schema.validateResult(call.op, envelope.value);
            const error = this.checkIssues(issues, ProtocolErrorCode.invalidResult, `result of ${call.op}`);
            if (error) {
              call.reject(error);
              return;
            }
          }
          call.resolve(envelope.value);
        });
        return;
      case "err":
        this.settle(envelope.id, (call) => call.reject(errorFromMessage(envelope)));
        return;
      case "ev":
        this.receiveEvent(envelope.sub, envelope.seq, envelope.data, envelope.gap === true);
        return;
      case "call":
        this.receiveCall(envelope);
        return;
      case "cancel":
        this.running.get(envelope.id)?.abort();
        return;
      case "sub":
        this.receiveSub(envelope);
        return;
      case "unsub": {
        const served = this.served.get(envelope.sub);
        if (served) {
          this.served.delete(envelope.sub);
          served.controller.abort();
        }
        return;
      }
      case "release": {
        const onRelease = this.exportedHandles.get(envelope.handle);
        if (onRelease) {
          this.exportedHandles.delete(envelope.handle);
          onRelease();
        }
        return;
      }
      case "open":
        this.receiveOpen(envelope);
        return;
      case "credit":
        this.streams.get(envelope.stream)?.receiveCredit(envelope.bytes);
        return;
      case "end":
        this.streams.get(envelope.stream)?.receiveEnd(envelope);
        return;
    }
  }

  /** Subscribe and open results are session-shaped, not IR results. */
  private readonly sessionShaped = new WeakSet<PendingCall>();

  private subscribeOrStream(call: PendingCall): boolean {
    return this.sessionShaped.has(call);
  }

  private settle(id: number, apply: (call: PendingCall) => void): void {
    const call = this.pending.get(id);
    if (!call) {
      // A result for a call we cancelled is expected; one for an id we never issued is not.
      if (id >= this.nextCallId) this.protocolError(new Error(`result for unknown call id ${id}`));
      return;
    }
    this.pending.delete(id);
    call.cleanup();
    apply(call);
  }

  private receiveEvent(subId: number, seq: number, data: unknown, gap: boolean): void {
    const sub = this.subscriptions.get(subId);
    if (!sub) return; // Late event after unsub.
    const previous = sub.lastSeq;
    sub.lastSeq = seq;
    const expected = previous === null ? seq : previous + 1;
    if (gap || seq !== expected) sub.options.onGap?.({ expected, received: seq, dropped: gap });
    if (this.options.schema) {
      const issues = this.options.schema.validateEvent(sub.stream, data);
      const error = this.checkIssues(issues, ProtocolErrorCode.invalidEvent, `event ${sub.stream}`);
      if (error) {
        if (sub.options.onInvalid) sub.options.onInvalid(error, seq);
        else this.protocolError(error);
        return;
      }
    }
    sub.options.onEvent(data, seq);
  }

  private receiveCall(msg: CallMessage): void {
    const handler = this.handlers.get(msg.op);
    if (!handler) {
      this.replyError(msg.id, new ProtocolError(ProtocolErrorCode.unknownOp, `no handler for ${msg.op}`));
      return;
    }
    if (this.options.schema) {
      const issues = this.options.schema.validateParams(msg.op, msg.params);
      const error = this.checkIssues(issues, ProtocolErrorCode.invalidParams, `params of ${msg.op}`);
      if (error) {
        this.replyError(msg.id, error);
        return;
      }
    }
    if (this.running.has(msg.id)) {
      this.protocolError(new Error(`duplicate call id ${msg.id}`));
      return;
    }
    const controller = new AbortController();
    this.running.set(msg.id, controller);
    const ctx: HandlerContext = { id: msg.id, op: msg.op, cap: msg.cap, signal: controller.signal, session: this };
    Promise.resolve()
      .then(() => handler(msg.params, ctx))
      .then(
        (value) => {
          if (this.running.get(msg.id) !== controller) return;
          this.running.delete(msg.id);
          if (controller.signal.aborted) this.replyError(msg.id, cancelledError());
          else this.trySend({ t: "ok", id: msg.id, value: value === undefined ? null : value });
        },
        (error: unknown) => {
          if (this.running.get(msg.id) !== controller) return;
          this.running.delete(msg.id);
          this.replyError(msg.id, controller.signal.aborted ? cancelledError() : toProtocolError(error));
        },
      );
  }

  private receiveSub(msg: SubMessage): void {
    const source = this.sources.get(msg.stream);
    if (!source) {
      this.replyError(msg.id, new ProtocolError(ProtocolErrorCode.unknownStream, `no event source for ${msg.stream}`));
      return;
    }
    const subId = this.nextServedSubId++;
    const controller = new AbortController();
    this.served.set(subId, { controller });
    this.trySend({ t: "ok", id: msg.id, value: { sub: subId } });
    let seq = 0;
    try {
      source({
        stream: msg.stream,
        filter: msg.filter,
        cap: msg.cap,
        signal: controller.signal,
        emit: (data) => {
          if (controller.signal.aborted || this.closeError) return;
          seq += 1;
          this.trySend({ t: "ev", sub: subId, seq, data: data === undefined ? null : data });
        },
      });
    } catch (error) {
      this.protocolError(error as Error);
    }
  }

  private receiveOpen(msg: OpenMessage): void {
    const handler = this.streamHandlers.get(msg.op);
    const peerParity = this.options.role === "client" ? 0 : 1;
    if (msg.stream % 2 !== peerParity || this.streams.has(msg.stream)) {
      this.replyError(msg.id, new ProtocolError(ProtocolErrorCode.streamAborted, `stream id ${msg.stream} not usable`));
      return;
    }
    if (!handler) {
      this.replyError(msg.id, new ProtocolError(ProtocolErrorCode.unknownOp, `no stream handler for ${msg.op}`));
      return;
    }
    if (this.options.schema) {
      const issues = this.options.schema.validateParams(msg.op, msg.params ?? {});
      const error = this.checkIssues(issues, ProtocolErrorCode.invalidParams, `params of ${msg.op}`);
      if (error) {
        this.replyError(msg.id, error);
        return;
      }
    }
    const stream = new ByteStream(this.streamHost, msg.stream, msg.op, {
      maxFramePayload: this.options.maxFramePayload,
    });
    this.streams.set(msg.stream, stream);
    this.trySend({ t: "ok", id: msg.id, value: null });
    try {
      handler(stream, { op: msg.op, cap: msg.cap, params: msg.params, session: this });
    } catch (error) {
      stream.abort(ProtocolErrorCode.internal, String((error as Error)?.message ?? error));
    }
  }

  private receiveBinary(bytes: Uint8Array): void {
    let frame;
    try {
      frame = decodeBinaryFrame(bytes);
    } catch (error) {
      this.protocolError(error as Error);
      return;
    }
    const stream = this.streams.get(frame.stream);
    if (!stream) {
      this.protocolError(new Error(`binary frame for unknown stream ${frame.stream}`));
      return;
    }
    stream.receiveData(frame.payload, frame.credit);
  }

  // Helpers.

  /**
   * A malformed request still gets an answer when its id can be read, so the peer's call does
   * not hang: `err` with `cmux.protocol.bad_message` (decision 13, R4). Other malformed messages
   * are only reported.
   */
  private refuseMalformed(text: string, error: Error): void {
    let raw: unknown;
    try {
      raw = JSON.parse(text);
    } catch {
      return;
    }
    const { t, id } = (raw ?? {}) as { t?: unknown; id?: unknown };
    if ((t !== "call" && t !== "sub" && t !== "open") || typeof id !== "number") return;
    if (!Number.isSafeInteger(id) || id < 1) return;
    this.replyError(id, new ProtocolError(ProtocolErrorCode.badMessage, error.message));
  }

  private checkIssues(issues: ValidationIssue[] | null, code: string, what: string): ProtocolError | null {
    if (issues === null) return new ProtocolError(code, `${what}: not in the protocol schema`);
    if (issues.length === 0) return null;
    return ProtocolError.fromIssues(code, what, issues);
  }

  private replyError(id: number, error: ProtocolError): void {
    const msg: ErrMessage = { t: "err", id, code: error.code, message: error.message, retryable: error.retryable };
    if (error.details) msg.details = error.details;
    this.trySend(msg);
  }

  private send(msg: Envelope): void {
    this.sendRaw(encodeEnvelope(msg));
  }

  /**
   * Queues one message. Everything queued in the same tick goes out in one flush, in queue
   * order, as a single `sendBatch` when the transport has one, otherwise one `send` each.
   * Size and encoding errors throw here, synchronously, so the caller's call still rejects.
   */
  private sendRaw(msg: TransportMessage): void {
    if (this.closeError) throw this.closeError;
    this.outbox.push(msg);
    if (this.outbox.length === 1) queueMicrotask(this.flushTask);
  }

  private readonly outbox: TransportMessage[] = [];
  private readonly flushTask = () => this.flush();

  private flush(): void {
    if (this.outbox.length === 0 || this.closeError) return;
    const batch = this.outbox.splice(0);
    try {
      if (batch.length > 1 && this.transport.sendBatch) this.transport.sendBatch(batch);
      else for (const msg of batch) this.transport.send(msg);
    } catch (error) {
      // A transport that fails mid-batch has lost ordering; nothing after it can be trusted.
      this.protocolError(error as Error);
      this.shutdown({ reason: `send failed: ${(error as Error)?.message ?? String(error)}` });
      this.transport.close();
    }
  }

  private trySend(msg: Envelope): void {
    if (this.closeError) return;
    try {
      this.send(msg);
    } catch (error) {
      this.protocolError(error as Error);
    }
  }

  /** Sends a request message; on failure rejects the pending entry. Returns whether it was sent. */
  private sendOrFail(id: number, msg: Envelope): boolean {
    const call = this.pending.get(id);
    if (call && (msg.t === "sub" || msg.t === "open")) this.sessionShaped.add(call);
    try {
      this.send(msg);
      return true;
    } catch (error) {
      if (call && this.pending.delete(id)) {
        call.cleanup();
        call.reject(
          error instanceof ProtocolError ? error : new ProtocolError(ProtocolErrorCode.closed, String(error)),
        );
      }
      return false;
    }
  }

  private protocolError(error: Error): void {
    this.options.onProtocolError?.(error);
  }

  private shutdown(info: TransportCloseInfo): void {
    if (this.closeError) return;
    const error = new ProtocolError(ProtocolErrorCode.closed, info.reason || "session closed", {
      retryable: true,
      details: info.code === undefined ? undefined : { code: info.code },
    });
    this.closeError = error;
    this.outbox.length = 0;
    for (const off of this.detach) off();
    const pending = [...this.pending.values()];
    this.pending.clear();
    for (const call of pending) {
      call.cleanup();
      call.reject(error);
    }
    const subs = [...this.subscriptions.values()];
    this.subscriptions.clear();
    for (const sub of subs) sub.options.onEnd?.(error);
    for (const controller of this.running.values()) controller.abort();
    this.running.clear();
    for (const served of this.served.values()) served.controller.abort();
    this.served.clear();
    for (const stream of this.streams.values()) stream.fail(error);
    this.streams.clear();
    for (const handle of this.remoteHandles.values()) handle.release();
    this.remoteHandles.clear();
    const exported = [...this.exportedHandles.values()];
    this.exportedHandles.clear();
    for (const onRelease of exported) onRelease();
    const listeners = [...this.closeListeners];
    this.closeListeners.clear();
    for (const cb of listeners) cb(error);
  }
}

function errorFromMessage(msg: ErrMessage): ProtocolError {
  return new ProtocolError(msg.code, msg.message, { retryable: msg.retryable, details: msg.details });
}

function toProtocolError(error: unknown): ProtocolError {
  if (error instanceof ProtocolError) return error;
  const message = error instanceof Error ? error.message : String(error);
  return new ProtocolError(ProtocolErrorCode.internal, message);
}
