// GENERATED by backend/packages/protocol/scripts/export-client.ts from backend/catalog/cloud-operations.json.
// Do not edit. Types and op metadata only (GPL-3.0-or-later, like the rest of the repository outside the BSL list).

export interface MutationResult<T> {
  readonly value: T
  readonly revision: string
  readonly transaction: string
  readonly replayed: boolean
}

/** HMAC id of a normalized email or phone; never the raw address. */
export type AddressId = string

export type AgentId = string

export type Automation = {
  readonly id: AutomationId
  readonly owner: TeamId
  readonly name: string
  readonly description: string
  readonly enabled: boolean
  readonly version: number
  readonly triggers: ReadonlyArray<Trigger>
  readonly body: Body
  readonly target: TargetPolicy
  readonly concurrency: Concurrency
  readonly budget: Budget
  readonly created_by: UserId
  readonly created_at: number
  readonly updated_at: number
  readonly next_run_at: number | null
}

/** An automation definition, owned by its team's SchedulerDO. */
export type AutomationId = string

export type AutomationSettings = {
  readonly agent_run_default_seconds: number | null
}

export type Body = {
  readonly type: "agent_prompt"
  readonly instructions: string
  readonly model?: string
  readonly effort?: "low" | "medium" | "high" | "xhigh"
  readonly workspace: {
    readonly mode: "fresh_worktree" | "repo"
    readonly repo?: string
    readonly ref?: string
  }
  readonly conversation: "fresh" | "continue"
} | {
  readonly type: "steps"
  readonly steps: ReadonlyArray<Step>
} | {
  readonly type: "code"
  readonly ref: CodeRef
  readonly egress?: ReadonlyArray<EgressHost>
}

export type Budget = {
  readonly wall_clock_seconds?: number
  readonly vm_minutes?: number
  readonly model_spend_usd?: number | "Infinity" | "-Infinity" | "NaN"
  readonly tool_calls?: number
}

export type ChiefId = string

/** 1 to 128 printable ASCII characters (idempotency key, client_msg_id). */
export type ClientToken = string

export type CodeRef = {
  readonly commit: CommitSha
  readonly path: string
  readonly export?: string
}

export type CommitSha = string

export type Concurrency = {
  readonly max: number
  readonly on_limit: "queue" | "skip"
}

export type ConfirmLevel = "strict" | "destructive-only" | "off"

export type Connection = {
  readonly id: ConnectionId
  readonly owner: TeamId
  readonly created_by: UserId
  readonly provider: IntegrationProvider
  readonly account: {
    readonly key: string
    readonly name: string
    readonly url?: string
  } | null
  readonly scopes_requested: ReadonlyArray<string>
  readonly scopes_granted: ReadonlyArray<string>
  readonly status: ConnectionStatus
  readonly status_detail?: string
  readonly sharing: "private" | "team"
  readonly resources?: {
    readonly repos: ReadonlyArray<string> | null
  }
  readonly created_at: number
  readonly updated_at: number
}

/** One integration connection (a provider account linked to a team). */
export type ConnectionId = string

export type ConnectionStatus = "pending" | "active" | "needs_reauth" | "error" | "revoked" | "expired"

/** conv_<26> (group or chief) or conv_dm_<26> (one-to-one, derived from the pair). */
export type ConversationId = string

export type ConversationKind = "chief" | "dm" | "group"

export type CronSpec = {
  readonly expr: string
  readonly tz: string
}

/** A device (hardware) that groups installs. */
export type DeviceId = string

export type DeviceStatus = {
  readonly install: InstallId
  readonly user: string
  readonly policy_version: number
  readonly app_version: string
  readonly mdm_keys: ReadonlyArray<string>
  readonly conflicts: ReadonlyArray<string>
  readonly reported_at: number
}

export type EgressHost = string

export type EmailAddress = string

/** A lowercase DNS name such as acme.com. */
export type EmailDomain = string

export type EnrollmentToken = {
  readonly id: EnrollmentTokenId
  readonly label: string
  readonly allowed_domains: ReadonlyArray<string> | null
  readonly expires_at: number | null
  readonly created_by: string
  readonly created_at: number
  readonly revoked_at: number | null
  readonly uses: number
}

/** base64url(SHA-256(token)) without padding. */
export type EnrollmentTokenHash = string

export type EnrollmentTokenId = string

export type FeedAction = {
  readonly id: string
  readonly label: string
  readonly style?: "default" | "primary" | "destructive"
  readonly answer?: unknown
}

/** A file attached to a feed item or an answer. */
export type FeedAttachment = {
  readonly id: string
  readonly name: string
  readonly mime: string
  readonly size: number
  readonly sha256: string
  readonly ref: string
}

export type FeedCancelReason = "poster" | "declined" | "answered_elsewhere" | "superseded" | "poster_gone"

/** What the item is about; clients open it and use it for the visibility rule. */
export type FeedContext = {
  readonly host?: string
  readonly workspace?: string
  readonly tab?: string
  readonly terminal?: string
  readonly browser_tab?: string
  readonly acp_session?: string
  readonly task?: string
  readonly url?: string
}

export type FeedFilter = {
  readonly poster_kind?: FeedPosterKind
  readonly thread?: string
  readonly workspace?: string
  readonly kind?: FeedKind
}

/** One notice or request in a user's feed. */
export type FeedItem = {
  readonly id: FeedItemId
  readonly home: string
  readonly type: "notice" | "request"
  readonly kind: FeedKind
  readonly title: string
  readonly body: string
  readonly prompt?: unknown
  readonly answer_schema?: unknown
  readonly priority: FeedPriority
  readonly dedupe_key: string | null
  readonly thread: string | null
  readonly context: FeedContext
  readonly attachments: ReadonlyArray<FeedAttachment>
  readonly actions: ReadonlyArray<FeedAction>
  readonly open: FeedOpen | null
  readonly poster: FeedPoster
  readonly state: FeedState
  readonly answer: {
    readonly value: unknown
    readonly by: string
    readonly device: string | null
    readonly at: number
  } | null
  readonly cancel: {
    readonly reason: FeedCancelReason
    readonly by: string
    readonly at: number
    readonly note: string | null
  } | null
  readonly needs_mac: boolean
  readonly expires_at: number
  readonly read_at: number | null
  readonly seen_at: number | null
  readonly archived_at: number | null
  readonly snoozed_until: number | null
  readonly push_due_at: number | null
  readonly pushed_at: number | null
  readonly count: number
  readonly order: number
  readonly revision: number
  readonly created_at: number
  readonly updated_at: number
  readonly closed_at: number | null
}

/** A feed item; stable when its home moves from a local owner to the cloud. */
export type FeedItemId = string

/** notice, a built-in request kind, or a custom kind x-<publisher>.<name>. */
export type FeedKind = string

export type FeedOpen = {
  readonly action: "tab.focus" | "workspace.focus" | "browser.open" | "browser.duplicateRight" | "url.open" | "task.open" | "acp.session.open" | "app.open"
  readonly args: Readonly<Record<string, never>>
}

export type FeedPoster = {
  readonly kind: FeedPosterKind
  readonly scope: string
  readonly label: string
  readonly install?: string
  readonly agent?: string
  readonly harness?: string
}

export type FeedPosterKind = "agent" | "harness" | "app" | "server" | "vm" | "automation" | "integration" | "system" | "user"

/** Per-user push rules, synced by the feed owner. */
export type FeedPrefs = {
  readonly push_enabled: boolean
  readonly push_delay: {
    readonly urgent: number | null
    readonly high: number | null
    readonly normal: number | null
    readonly low: number | null
  }
  readonly push_skip_when_mac_active: boolean
}

export type FeedPriority = "low" | "normal" | "high" | "urgent"

export type FeedState = "open" | "answered" | "cancelled" | "expired"

export type Grant = {
  readonly id: GrantId
  readonly grantee: string
  readonly op_classes: ReadonlyArray<OpClass>
  readonly approval: "none" | "per_call" | "per_session"
  readonly expires_at: number | null
  readonly revoked_at: number | null
  readonly created_from: "install" | "ui" | "automation" | "standing_rule"
}

/** A server-side grant; tokens carry only its id. */
export type GrantId = string

export type HomeChief = {
  readonly id: ChiefId
  readonly owner_user: string
  readonly display_name: string
  readonly is_default: boolean
  readonly brain: "cloud"
  readonly main_conversation: ConversationId | null
  readonly harness: string | null
  readonly rev: number | "Infinity" | "-Infinity" | "NaN"
  readonly created_at: Timestamp
  readonly updated_at: Timestamp
  readonly archived_at: Timestamp | null
}

/** rev after the op; seq and message_id for a new message; change is the committed Change. */
export type HomeConversationCommit = {
  readonly rev: number
  readonly seq?: number
  readonly message_id?: MessageId
  readonly change: unknown
}

export type HomeConversationSettings = {
  readonly wake_policy: "auto" | "mentions" | "all"
  readonly agent_budget: {
    readonly turns: number
    readonly gap_ms: number
  }
  readonly history_visible: "all" | "since_join"
}

export type HomeConversationSummary = {
  readonly id: ConversationId
  readonly owner: string
  readonly title: string
  readonly participants: ReadonlyArray<HomeParticipant>
  readonly last_seq: number
  readonly rev: number
  readonly created_at: Timestamp
  readonly updated_at: Timestamp
  readonly last_message?: HomeMessage
  readonly read_cursors: Readonly<Record<string, number>>
  readonly kind?: ConversationKind
  readonly team?: string
  readonly created_by?: string
  readonly state?: "active" | "archived"
  readonly settings?: HomeConversationSettings
  readonly invites?: ReadonlyArray<HomeInvite>
  readonly retention_days?: number
}

export type HomeDeliveryState = "queued" | "sent" | "delivered" | "bounced" | "complained" | "failed" | "suppressed" | "refused_env"

export type HomeInboxEntry = {
  readonly conversation: ConversationId
  readonly rev: number
  readonly kind: ConversationKind
  readonly title: string
  readonly last_seq: number
  readonly last_at: Timestamp
  readonly preview: string
  readonly dm_peer?: ParticipantId
  readonly removed: boolean
  readonly unread: number
  readonly mentions: number
  readonly counts_rev: number
  readonly pinned: boolean
  readonly pin_position?: number
  readonly muted: boolean
  readonly muted_until?: number | "Infinity" | "-Infinity" | "NaN"
  readonly archived: boolean
  readonly archived_seq: number
  readonly marked_unread: boolean
}

export type HomeInvite = {
  readonly id: InviteId
  readonly address: AddressId
  readonly channel: "email" | "sms"
  readonly display_name: string
  readonly invited_by: ParticipantId
  readonly created_at: Timestamp
  readonly expires_at: Timestamp
  readonly status: "pending" | "pending_approval" | "accepted" | "revoked" | "expired"
  readonly accepted_by?: string
  readonly accepted_at?: Timestamp
  readonly requested_by?: string
  readonly requested_name?: string
  readonly requested_at?: Timestamp
  readonly delivery: {
    readonly state: HomeDeliveryState
    readonly provider_id?: string
    readonly at: Timestamp
  }
  readonly copy_variant: string
  readonly locale: string
}

export type HomeMessage = {
  readonly id: MessageId
  readonly conversation: ConversationId
  readonly seq: number
  readonly client_msg_id: ClientToken
  readonly author: ParticipantId
  readonly parts: ReadonlyArray<HomePart>
  readonly reply_to?: HomePartRef
  readonly created_at: Timestamp
  readonly edited_at?: Timestamp
  readonly retracted_at?: Timestamp
  readonly reactions: ReadonlyArray<HomeReaction>
}

export type HomePart = {
  readonly type: "text"
  readonly text: string
  readonly runs?: ReadonlyArray<HomeTextRun>
} | {
  readonly type: "work"
  readonly session: string
  readonly host?: string
  readonly status: "running" | "done" | "failed" | "waiting"
  readonly preview?: string
}

export type HomeParticipant = {
  readonly id: ParticipantId
  readonly kind: "human" | "agent" | "address"
  readonly display_name: string
  readonly agent_class?: "mux" | "agent"
  readonly acp_session?: string
  readonly owner_user?: string
  readonly role?: "owner" | "member"
  readonly joined_seq?: number
  readonly added_by?: string
  readonly left_at?: Timestamp
}

export type HomeParticipantInput = {
  readonly id: ParticipantId
  readonly kind: "human" | "agent"
  readonly display_name: string
  readonly agent_class?: "mux" | "agent"
  readonly owner_user?: string
}

export type HomePartRef = {
  readonly message_id: MessageId
  readonly part_index: number
}

export type HomeReaction = {
  readonly author: ParticipantId
  readonly part_index: number
  readonly kind: HomeReactionKind
  readonly at: Timestamp
}

export type HomeReactionKind = {
  readonly tapback: "love" | "like" | "dislike" | "laugh" | "emphasize" | "question"
} | {
  readonly emoji: string
}

/** A styled range of a text part, in UTF-16 code units. */
export type HomeTextRun = {
  readonly start: number
  readonly length: number
  readonly mention?: ParticipantId
  readonly link?: string
}

export type Host = {
  readonly id: HostId
  readonly name: string
  readonly platform: Platform
  readonly owner_user: UserId
  readonly enrolled_by: InstallId
  readonly enrolled_at: number
  readonly kind?: HostKind
  readonly wg_public_key?: WgPublicKey
  readonly tags?: ReadonlyArray<string>
}

/** A machine's session host, enrolled by its link. */
export type HostId = string

export type HostKind = "device" | "server"

export type Install = {
  readonly id: InstallId
  readonly device: DeviceId
  readonly kind: InstallKind
  readonly name: string
  readonly device_name: string
  readonly platform: Platform
  readonly public_jwk: PublicJwk
  readonly thumbprint: string
  readonly grant: GrantId
  readonly created_at: number
  readonly revoked_at: number | null
  readonly bound_team?: TeamId
  readonly sso_team?: TeamId
}

/** One app, CLI or daemon install with its own keypair. */
export type InstallId = string

export type InstallKind = "mac" | "ios" | "cli" | "daemon" | "web" | "vm"

export type IntegrationProvider = "github" | "linear" | "slack" | "google_calendar" | "gmail"

export type InviteId = string

export type ManagedDevice = {
  readonly install: InstallId
  readonly user: string
  readonly via: "token" | "accept"
  readonly token: EnrollmentTokenId | null
  readonly at: number
}

export type MessageId = string

export type Meter = "automation.steps" | "automation.cpu_ms" | "automation.invocations" | "automation.dynamic_workers" | "egress.requests" | "model.spend_usd"

export type OpClass = "read" | "mutate-own" | "mutate-shared" | "execute" | "send-external" | "money" | "destructive"

/** A normalized pairing code: 8 Crockford base32 symbols, no hyphen. */
export type PairingCode = string

export type PairingInfo = {
  readonly name: string
  readonly platform: Platform
  readonly os_version: string
  readonly arch: "x86_64" | "aarch64"
  readonly cmux_version: string
}

export type PairingPreview = {
  readonly code: PairingCode
  readonly info: PairingInfo
  readonly public_jwk: PublicJwk
  readonly thumbprint: string
  readonly country: string | null
  readonly expires_at: number
}

/** user_<id>, agent_<name> or addr_<26> (an invited address). */
export type ParticipantId = string

export type Platform = "macos" | "ios" | "linux" | "windows" | "web"

export type PolicyChange = {
  readonly key: PolicyKey
  readonly value: {
    readonly value: unknown
    readonly mode: PolicyMode
  } | null
}

/** A team policy key (spec/enterprise.md 4.2). */
export type PolicyKey = "github.repoScope" | "github.requireOrgAdmin" | "github.repoAllowList" | "integrations.allowedProviders" | "mcp.server" | "mcp.remoteTransport" | "apps.install" | "apps.allowedTiers" | "apps.allowList" | "apps.forcedInstalls" | "computerUse.allowed" | "browserAutomation.rawCdp" | "cloud.sandboxes" | "telemetry.level" | "updates.channel" | "updates.minimumVersion" | "retention.cuaEventsDays" | "retention.cuaFramesDays" | "retention.transcriptDays" | "retention.auditDays" | "sso.enforce" | "sso.enforceForOwners" | "sso.allowGuests" | "sso.sessionMaxAgeHours" | "sso.idleTimeoutHours" | "agents.allowedClasses" | "device.settings"

export type PolicyMode = "enforced" | "default"

/** ES256 (P-256) public key of an install. */
export type PublicJwk = {
  readonly kty: "EC"
  readonly crv: "P-256"
  readonly x: string
  readonly y: string
}

/** One device's APNs registration. */
export type PushTarget = {
  readonly token: PushToken
  readonly topic: string
  readonly environment: "development" | "production"
  readonly install: string
  readonly device_name: string
  readonly registered_at: number
}

/** An APNs device token (hex). */
export type PushToken = string

export type RepoPattern = string

export type Run = {
  readonly id: RunId
  readonly automation: AutomationId
  readonly automation_version: number
  readonly owner: TeamId
  readonly trigger: {
    readonly id: TriggerId | null
    readonly type: string
    readonly scheduled_at?: number
    readonly delivery_id?: string
    readonly parent_run?: RunId
    readonly root_run?: RunId
    readonly depth?: number
  }
  readonly state: RunState
  readonly step: number
  readonly created_at: number
  readonly started_at: number | null
  readonly finished_at: number | null
  readonly error: RunError | null
  readonly outcome: {
    readonly goal_met: boolean
    readonly summary?: string
  } | null
}

export type RunError = {
  readonly code: string
  readonly message: string
}

/** One automation run; also its Workflow instance id. */
export type RunId = string

export type RunState = "queued" | "running" | "sleeping" | "waiting" | "succeeded" | "failed" | "cancelled" | "skipped" | "dead"

/** `human`: a full shell as the person's Linux user. `agent`: the person's `<name>-agents` Linux user, limited by the certificate's force-command to `cmux team …` commands (decision D28). */
export type SshCertClass = "human" | "agent"

export type SshPresenceProof = {
  readonly install: InstallId
  readonly nonce: string
  readonly signature: string
  readonly app_attest?: string
}

export type SsoConnection = {
  readonly id: SsoConnectionId
  readonly kind: "oidc"
  readonly state: "draft" | "active" | "disabled"
  readonly domains: ReadonlyArray<EmailDomain>
  readonly oidc: {
    readonly issuer: string
    readonly client_id: string
    readonly scopes: ReadonlyArray<string>
    readonly authorization_endpoint: string | null
    readonly token_endpoint: string | null
    readonly jwks_uri: string | null
  }
  readonly secret_set: boolean
  readonly secret_generation?: number
  readonly jit: {
    readonly enabled: boolean
    readonly default_role: "member" | "admin"
  }
  readonly created_at: number
  readonly updated_at: number
}

export type SsoConnectionId = string

export type Step = {
  readonly type: "sleep"
  readonly seconds: number
} | {
  readonly type: "note"
  readonly text: string
} | {
  readonly type: "op"
  readonly op: "automation.list" | "automation.get" | "automation.runs.list" | "automation.run" | "usage.summary"
  readonly params: unknown
}

export type TargetPolicy = {
  readonly kind: "cloud_vm"
} | {
  readonly kind: "host"
  readonly host: HostId
  readonly fallback: "cloud_vm" | "wait" | "fail"
}

export type TeamDomain = {
  readonly domain: EmailDomain
  readonly state: "pending" | "verified" | "lost" | "lapsed"
  readonly record_name: string
  readonly record_value: string
  readonly requested_at: number
  readonly expires_at: number
  readonly verified_at: number | null
  readonly last_checked_at?: number
  readonly check_failures?: number
}

/** A team; a personal account is a team of one. */
export type TeamId = string

export type TeamIntegrationPolicy = {
  readonly allowed_providers: ReadonlyArray<IntegrationProvider> | null
  readonly github: {
    readonly scope: "linking_user_repos" | "installation"
    readonly require_org_admin: boolean
    readonly repo_allowlist: ReadonlyArray<RepoPattern> | null
  }
  readonly source: "default" | "admin" | "sso" | "mdm" | "team_policy"
  readonly locked: boolean
  readonly updated_at: number | null
  readonly updated_by: string | null
}

export type TeamJournalStream = "tasks" | "mail" | "memory" | "files"

export type TeamMember = {
  readonly user: UserId
  readonly role: "owner" | "admin" | "member"
  readonly display_name: string
}

export type TeamPolicy = {
  readonly version: number
  readonly values: TeamPolicyValues
  readonly updated_at: number | null
  readonly updated_by: string | null
}

/** Set keys of a team policy; an absent key means the product default and the user's choice. */
export type TeamPolicyValues = {
  readonly "github.repoScope"?: {
    readonly value: "linking_user_repos" | "installation"
    readonly mode: PolicyMode
  }
  readonly "github.requireOrgAdmin"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "github.repoAllowList"?: {
    readonly value: "none" | ReadonlyArray<RepoPattern>
    readonly mode: PolicyMode
  }
  readonly "integrations.allowedProviders"?: {
    readonly value: "all" | ReadonlyArray<IntegrationProvider>
    readonly mode: PolicyMode
  }
  readonly "mcp.server"?: {
    readonly value: "user_choice" | "disabled"
    readonly mode: PolicyMode
  }
  readonly "mcp.remoteTransport"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "apps.install"?: {
    readonly value: "any" | "allow_list" | "disabled"
    readonly mode: PolicyMode
  }
  readonly "apps.allowedTiers"?: {
    readonly value: ReadonlyArray<"first-party" | "verified" | "community" | "unverified">
    readonly mode: PolicyMode
  }
  readonly "apps.allowList"?: {
    readonly value: ReadonlyArray<string>
    readonly mode: PolicyMode
  }
  readonly "apps.forcedInstalls"?: {
    readonly value: ReadonlyArray<string>
    readonly mode: PolicyMode
  }
  readonly "computerUse.allowed"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "browserAutomation.rawCdp"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "cloud.sandboxes"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "telemetry.level"?: {
    readonly value: "full" | "crash_only" | "off"
    readonly mode: PolicyMode
  }
  readonly "updates.channel"?: {
    readonly value: "stable" | "nightly"
    readonly mode: PolicyMode
  }
  readonly "updates.minimumVersion"?: {
    readonly value: string
    readonly mode: PolicyMode
  }
  readonly "retention.cuaEventsDays"?: {
    readonly value: number
    readonly mode: PolicyMode
  }
  readonly "retention.cuaFramesDays"?: {
    readonly value: number
    readonly mode: PolicyMode
  }
  readonly "retention.transcriptDays"?: {
    readonly value: number
    readonly mode: PolicyMode
  }
  readonly "retention.auditDays"?: {
    readonly value: number
    readonly mode: PolicyMode
  }
  readonly "sso.enforce"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "sso.enforceForOwners"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "sso.allowGuests"?: {
    readonly value: boolean
    readonly mode: PolicyMode
  }
  readonly "sso.sessionMaxAgeHours"?: {
    readonly value: number
    readonly mode: PolicyMode
  }
  readonly "sso.idleTimeoutHours"?: {
    readonly value: number
    readonly mode: PolicyMode
  }
  readonly "agents.allowedClasses"?: {
    readonly value: ReadonlyArray<"mux" | "agent" | "run">
    readonly mode: PolicyMode
  }
  readonly "device.settings"?: {
    readonly value: Readonly<Record<string, never>>
    readonly mode: PolicyMode
  }
}

export type TeamPolicyVersion = {
  readonly version: number
  readonly values: TeamPolicyValues
  readonly changed: ReadonlyArray<PolicyKey>
  readonly actor: string | null
  readonly at: number
  readonly reason: string | null
  readonly rollback_of: number | null
}

export type TeamVmError = {
  readonly code: string
  readonly message: string
  readonly at: number
}

export type TeamVmLeaseId = string

/** Last observed state of the team VM. `none`: never created. `failed`: the last provider call failed for good; the next ensure_awake retries. */
export type TeamVmStatus = "none" | "provisioning" | "starting" | "running" | "paused" | "failed"

export type TeamVmView = {
  readonly team: TeamId
  readonly status: TeamVmStatus
  readonly vm: string | null
  readonly epoch: number
  readonly leases: ReadonlyArray<{
    readonly lease: TeamVmLeaseId
    readonly holder: string
    readonly reason: string
    readonly expires_at: number
  }>
  readonly last_error: TeamVmError | null
  readonly updated_at: number
}

/** RFC 3339 UTC with milliseconds. */
export type Timestamp = string

export type Trigger = {
  readonly id: TriggerId
  readonly status: "active" | "not_yet_supported"
  readonly spec: TriggerInput
  readonly next_at: number | null
}

/** One trigger of an automation; assigned by the owner. */
export type TriggerId = string

export type TriggerInput = {
  readonly type: "cron"
  readonly expr: string
  readonly tz: string
} | {
  readonly type: "manual"
} | {
  readonly type: "webhook"
} | {
  readonly type: "event"
  readonly source: "integration" | "machine" | "store" | "task"
  readonly connection?: string
  readonly event: string
  readonly filter?: Readonly<Record<string, string>>
} | {
  readonly type: "message"
  readonly conversation: string
  readonly rule: string
} | {
  readonly type: "continue"
  readonly until: ReadonlyArray<"goal_met" | "budget" | "stop">
  readonly cooldown_seconds: number
  readonly max_runs?: number
} | {
  readonly type: "presence"
  readonly when: "user_active" | "user_returns_after"
  readonly idle_minutes?: number
  readonly earliest?: CronSpec
}

export type UsageMeterLine = {
  readonly meter: Meter
  readonly unit: string
  readonly quantity: number | "Infinity" | "-Infinity" | "NaN"
  readonly usd: number | "Infinity" | "-Infinity" | "NaN"
}

export type UsageStopReason = "cap.reached" | "cap.not_configured"

export type UsageSummary = {
  readonly owner: TeamId | null
  readonly month: string
  readonly meters: ReadonlyArray<UsageMeterLine>
  readonly total_usd: number | "Infinity" | "-Infinity" | "NaN"
  readonly cap_usd: number | "Infinity" | "-Infinity" | "NaN"
  readonly ceiling_usd: number | "Infinity" | "-Infinity" | "NaN"
  readonly team_cap_usd: number | "Infinity" | "-Infinity" | "NaN" | null
  readonly stopped: UsageStopReason | null
}

/** A cmux user (Stack user id kept as an external id). */
export type UserId = string

export type UserProfile = {
  readonly id: UserId
  readonly stack_user_id: string
  readonly email: string | null
  readonly email_verified?: boolean
  readonly display_name: string
  readonly personal_team: TeamId
}

/** A WireGuard public key, standard base64 of 32 bytes. */
export type WgPublicKey = string

/** Params and result of every cloud op, keyed by op name. */
export interface CloudOps {
  /** Create an automation (triggers, body, target policy) in the caller's team. */
  readonly "automation.create": {
    readonly params: {
      readonly name: string
      readonly description?: string
      readonly enabled?: boolean
      readonly triggers: ReadonlyArray<TriggerInput>
      readonly body: Body
      readonly target?: TargetPolicy
      readonly concurrency?: Concurrency
      readonly budget?: Budget
    }
    readonly result: Automation
  }
  /** Delete an automation. Its run history stays. */
  readonly "automation.delete": {
    readonly params: {
      readonly automation: AutomationId
    }
    readonly result: {
      readonly automation: string
    }
  }
  /** Pin a code automation to another commit of the team's code repository (the commit must contain <path>/dist/index.js). Later runs use it; started runs keep their commit. At most 50 code changes per team per UTC day. */
  readonly "automation.deploy": {
    readonly params: {
      readonly automation: AutomationId
      readonly commit: CommitSha
      readonly expected_version?: number
    }
    readonly result: Automation
  }
  /** Read one automation. */
  readonly "automation.get": {
    readonly params: {
      readonly automation: AutomationId
    }
    readonly result: Automation
  }
  /** List the automations of the caller's team. */
  readonly "automation.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly owner: TeamId | null
      readonly automations: ReadonlyArray<Automation>
      readonly revision: string
    }
  }
  /** Start a run of an automation now (manual trigger). */
  readonly "automation.run": {
    readonly params: {
      readonly automation: AutomationId
    }
    readonly result: Run
  }
  /** List recent runs, newest first (the owner keeps every active run and the last 200 finished ones; older history is in the projection). */
  readonly "automation.runs.list": {
    readonly params: {
      readonly automation?: AutomationId
      readonly limit?: number
    }
    readonly result: {
      readonly runs: ReadonlyArray<Run>
      readonly revision: string
    }
  }
  /** Read the team's automation settings (default limit of agent runs). */
  readonly "automation.settings.get": {
    readonly params: Readonly<Record<string, never>>
    readonly result: AutomationSettings
  }
  /** Change the team's automation settings (team admins). Each automation can still override with budget.wall_clock_seconds. */
  readonly "automation.settings.set": {
    readonly params: Readonly<Record<string, never>>
    readonly result: AutomationSettings
  }
  /** Change an automation; the version increments and later runs use the new version. */
  readonly "automation.update": {
    readonly params: {
      readonly automation: AutomationId
      readonly expected_version?: number
      readonly name?: string
      readonly description?: string
      readonly enabled?: boolean
      readonly triggers?: ReadonlyArray<TriggerInput>
      readonly body?: Body
      readonly target?: TargetPolicy
      readonly concurrency?: Concurrency
      readonly budget?: Budget
    }
    readonly result: Automation
  }
  /** Read a webhook trigger's endpoint path and signing secret (HMAC-SHA256 over '<x-cmux-timestamp>.<body>', header x-cmux-signature: v1=<hex>). Human sessions only: the secret starts runs. */
  readonly "automation.webhook.get": {
    readonly params: {
      readonly automation: AutomationId
      readonly trigger: TriggerId
    }
    readonly result: {
      readonly automation: AutomationId
      readonly trigger: TriggerId
      readonly path: string
      readonly secret: string
      readonly scheme: string
    }
  }
  /** List the calendars of a Google Calendar connection (ids for the other calendar ops). */
  readonly "calendar.calendars.list": {
    readonly params: {
      readonly connection: ConnectionId
    }
    readonly result: unknown
  }
  /** Create a Google Calendar event; attendees get Google's invitation email. */
  readonly "calendar.event.create": {
    readonly params: {
      readonly connection: ConnectionId
      readonly calendar_id?: string
      readonly summary: string
      readonly description?: string
      readonly location?: string
      readonly start: {
        readonly date_time?: string
        readonly date?: string
        readonly time_zone?: string
      }
      readonly end: {
        readonly date_time?: string
        readonly date?: string
        readonly time_zone?: string
      }
      readonly attendees?: ReadonlyArray<EmailAddress>
    }
    readonly result: unknown
  }
  /** Answer a Google Calendar invitation as the connected account; the organizer is notified. */
  readonly "calendar.event.respond": {
    readonly params: {
      readonly connection: ConnectionId
      readonly calendar_id?: string
      readonly event_id: string
      readonly response: "accepted" | "declined" | "tentative"
    }
    readonly result: unknown
  }
  /** List events of a Google calendar (single events, ordered by start). Read at call time; nothing is stored. */
  readonly "calendar.events.list": {
    readonly params: {
      readonly connection: ConnectionId
      readonly calendar_id?: string
      readonly time_min?: string
      readonly time_max?: string
      readonly query?: string
      readonly max_results?: number
      readonly page_token?: string
    }
    readonly result: unknown
  }
  /** Archive a chief (not the default): it stops waking; restorable for 30 days, then a tombstone keeps its id forever. */
  readonly "chief.archive": {
    readonly params: {
      readonly chief: ChiefId
      readonly expected_rev: number | "Infinity" | "-Infinity" | "NaN"
    }
    readonly result: HomeChief
  }
  /** Create a chief (the user's first chief is the default; use the idempotency key chief-default for it). Binds its wake queue and gives it the user's text confirmation level. */
  readonly "chief.create": {
    readonly params: {
      readonly display_name?: string
      readonly is_default?: boolean
    }
    readonly result: HomeChief
  }
  /** The user's chiefs (active first, the default marked), archived ones on request, and tombstones. */
  readonly "chief.list": {
    readonly params: {
      readonly include_archived?: boolean
    }
    readonly result: {
      readonly chiefs: ReadonlyArray<HomeChief>
      readonly tombstones: ReadonlyArray<{
        readonly id: ChiefId
        readonly owner_user: string
        readonly archived_at: Timestamp
      }>
    }
  }
  /** Rename a chief, make it the default (clears the old default in the same commit), set its harness, or restore it within 30 days of archiving (archived: false). */
  readonly "chief.update": {
    readonly params: {
      readonly chief: ChiefId
      readonly expected_rev: number | "Infinity" | "-Infinity" | "NaN"
      readonly display_name?: string
      readonly is_default?: true
      readonly harness?: string | null
      readonly archived?: false
    }
    readonly result: HomeChief
  }
  /** Create a group conversation. The Worker derives the id from the caller and the idempotency key, so a retry reaches the same conversation. At most 60 per hour per caller (home.rate_limited, with details.retry_after_ms). */
  readonly "conversation.create": {
    readonly params: {
      readonly kind?: "group"
      readonly title?: string
      readonly participants: ReadonlyArray<HomeParticipantInput>
      readonly settings?: HomeConversationSettings
    }
    readonly result: {
      readonly conversation: HomeConversationSummary
    }
  }
  /** Page older messages before before_seq (newest first within the page). */
  readonly "conversation.history": {
    readonly params: {
      readonly conversation: ConversationId
      readonly before_seq?: number
      readonly limit?: number
    }
    readonly result: {
      readonly messages: ReadonlyArray<HomeMessage>
      readonly next_before_seq: number | null
      readonly revision: string
    }
  }
  /** Promote a Mac conversation (home-messaging.md section 22). The first call names its source; the Worker derives the id from the signed-in user and the source. Later calls send {id, after_seq, messages}. At most 500 messages and 1 MiB per batch. */
  readonly "conversation.import": {
    readonly params: {
      readonly id?: ConversationId
      readonly source?: {
        readonly kind: "mac"
        readonly host: string
        readonly local_id: string
      }
      readonly kind?: "group" | "chief"
      readonly title?: string
      readonly participants?: ReadonlyArray<HomeParticipantInput>
      readonly after_seq?: number
      readonly messages: ReadonlyArray<unknown>
      readonly read_cursors?: unknown
    }
    readonly result: HomeConversationCommit
  }
  /** Finish an import: read cursors are clamped, normal ops open, each human gets one inbox entry. */
  readonly "conversation.import.commit": {
    readonly params: {
      readonly id: ConversationId
      readonly last_seq: number
    }
    readonly result: HomeConversationCommit
  }
  /** Change the chief wake policy, agent turn budget or history visibility (conversation owner). */
  readonly "conversation.settings.set": {
    readonly params: {
      readonly conversation: ConversationId
      readonly wake_policy?: "auto" | "mentions" | "all"
      readonly agent_budget?: {
        readonly turns: number
        readonly gap_ms: number
      }
      readonly history_visible?: "all" | "since_join"
    }
    readonly result: HomeConversationCommit
  }
  /** Read the conversation and its newest messages (history_visible since_join hides earlier ones). */
  readonly "conversation.snapshot": {
    readonly params: {
      readonly conversation: ConversationId
      readonly tail?: number
    }
    readonly result: {
      readonly conversation: HomeConversationSummary
      readonly messages: ReadonlyArray<HomeMessage>
      readonly revision: string
    }
  }
  /** Open the one-to-one conversation with a user or chief, or with an email or phone (which invites the address). Idempotent: an existing DM with the peer is returned. */
  readonly "dm.open": {
    readonly params: {
      readonly peer: ParticipantId | {
        readonly email: string
      } | {
        readonly phone: string
      }
    }
    readonly result: {
      readonly conversation: HomeConversationSummary
    }
  }
  /** Start verifying an email domain for the team (owners and admins): returns the DNS TXT record to publish. Public mail domains are refused. */
  readonly "domain.claim": {
    readonly params: {
      readonly domain: EmailDomain
    }
    readonly result: TeamDomain
  }
  /** The team's claimed and verified email domains (owners and admins). */
  readonly "domain.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly team: TeamId
      readonly domains: ReadonlyArray<TeamDomain>
      readonly revision: string
    }
  }
  /** Give up a claimed or verified domain (owners and admins). Another team may then verify it. */
  readonly "domain.release": {
    readonly params: {
      readonly domain: EmailDomain
    }
    readonly result: {
      readonly domain: EmailDomain
    }
  }
  /** Check the TXT record through two DNS-over-HTTPS resolvers and, when both see it, make the team the domain's owner (owners and admins). */
  readonly "domain.verify": {
    readonly params: {
      readonly domain: EmailDomain
    }
    readonly result: TeamDomain
  }
  /** Handoff: a daemon's local feed owner moves one of its items (same id) to the cloud owner after a reconnect. */
  readonly "feed.adopt": {
    readonly params: {
      readonly item: FeedItem
    }
    readonly result: {
      readonly item: FeedItem
    }
  }
  /** Handoff abort: a daemon's local feed owner withdraws `feed.adopt` with key `adopt:<item>`. Not adopted: a tombstone refuses a later adopt with that key and the reply is cancelled true. Adopted: cancelled false with the cloud item. */
  readonly "feed.adopt.cancel": {
    readonly params: {
      readonly key: string
    }
    readonly result: {
      readonly cancelled: boolean
      readonly item?: FeedItem
    }
  }
  /** Answer an open request (the user only, origin user). The first answer wins; a closed item is refused with feed.closed. */
  readonly "feed.answer": {
    readonly params: {
      readonly item: FeedItemId
      readonly answer: unknown
      readonly device?: string
    }
    readonly result: {
      readonly item: FeedItem
    }
  }
  /** Archive items (done) by ids or a filter. Open requests cannot be archived: answer or decline them (a filter skips them). */
  readonly "feed.archive": {
    readonly params: {
      readonly items?: ReadonlyArray<FeedItemId>
      readonly filter?: FeedFilter
    }
    readonly result: {
      readonly items: ReadonlyArray<{
        readonly id: FeedItemId
        readonly revision: number
      }>
    }
  }
  /** Cancel an open item: its poster withdraws it, an adapter reports it answered elsewhere, or the user declines it. */
  readonly "feed.cancel": {
    readonly params: {
      readonly item: FeedItemId
      readonly reason?: FeedCancelReason
      readonly note?: string
    }
    readonly result: {
      readonly item: FeedItem
    }
  }
  /** Badge counts: open requests, unread active items, open requests by priority. */
  readonly "feed.counts": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly open_requests: number
      readonly unread: number
      readonly by_priority: Readonly<Record<string, number>>
      readonly by_poster_kind: Readonly<Record<string, number>>
      readonly revision: string
    }
  }
  /** Read one feed item (its answer once it is answered). An agent reads only the items it posted. */
  readonly "feed.get": {
    readonly params: {
      readonly item: FeedItemId
    }
    readonly result: {
      readonly item: FeedItem
    }
  }
  /** The built-in request kinds with JSON Schemas of their prompt and answer; custom kinds x-<publisher>.<name> carry their own answer_schema. */
  readonly "feed.kinds": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly kinds: ReadonlyArray<{
        readonly kind: string
        readonly priority: FeedPriority
        readonly needs_mac: boolean
        readonly docs: string
        readonly prompt_schema: unknown
        readonly answer_schema: unknown
      }>
    }
  }
  /** List feed items in the owner's order (one order for every client), optionally grouped. An agent sees only the items it posted. */
  readonly "feed.list": {
    readonly params: {
      readonly state?: "open" | "closed" | "all"
      readonly type?: "notice" | "request"
      readonly kind?: FeedKind
      readonly unread?: boolean
      readonly archived?: boolean
      readonly thread?: string
      readonly needs_response?: boolean
      readonly poster_kind?: FeedPosterKind
      readonly workspace?: string
      readonly query?: string
      readonly order?: "urgent" | "recent"
      readonly group_by?: "thread" | "poster" | "workspace"
      readonly after?: FeedItemId
      readonly limit?: number
    }
    readonly result: {
      readonly items: ReadonlyArray<FeedItem>
      readonly groups?: ReadonlyArray<{
        readonly key: string
        readonly label: string
        readonly items: ReadonlyArray<FeedItemId>
      }>
      readonly next: FeedItemId | null
      readonly revision: string
    }
  }
  /** Post a notice or a request to the user's feed. A request waits for one answer from the user (use feed.watch or --wait). */
  readonly "feed.post": {
    readonly params: {
      readonly type: "notice" | "request"
      readonly kind: FeedKind
      readonly title: string
      readonly body?: string
      readonly prompt?: unknown
      readonly answer_schema?: unknown
      readonly priority?: FeedPriority
      readonly dedupe_key?: string
      readonly thread?: string
      readonly context?: FeedContext
      readonly attachments?: ReadonlyArray<FeedAttachment>
      readonly actions?: ReadonlyArray<FeedAction>
      readonly open?: FeedOpen
      readonly expires_in_ms?: number
      readonly poster?: {
        readonly kind?: FeedPosterKind
        readonly label?: string
        readonly agent?: string
        readonly harness?: string
      }
    }
    readonly result: {
      readonly item: FeedItem
      readonly deduped: boolean
    }
  }
  /** Change the user's synced push rules. */
  readonly "feed.prefs.set": {
    readonly params: {
      readonly push_enabled?: boolean
      readonly push_delay?: {
        readonly urgent?: number | null
        readonly high?: number | null
        readonly normal?: number | null
        readonly low?: number | null
      }
      readonly push_skip_when_mac_active?: boolean
    }
    readonly result: {
      readonly prefs: FeedPrefs
    }
  }
  /** Mark items read (the user opened or acknowledged them): by ids, by a filter, or `all` unread items. */
  readonly "feed.read": {
    readonly params: {
      readonly items?: ReadonlyArray<FeedItemId>
      readonly all?: boolean
      readonly filter?: FeedFilter
    }
    readonly result: {
      readonly items: ReadonlyArray<{
        readonly id: FeedItemId
        readonly revision: number
      }>
    }
  }
  /** Report items the user saw in view (a client's visibility rule); seen items do not push. */
  readonly "feed.seen": {
    readonly params: {
      readonly items: ReadonlyArray<FeedItemId>
    }
    readonly result: {
      readonly items: ReadonlyArray<{
        readonly id: FeedItemId
        readonly revision: number
      }>
    }
  }
  /** Hide items until a time (at most one year ahead); they come back unread. Open requests cannot be snoozed. */
  readonly "feed.snooze": {
    readonly params: {
      readonly items: ReadonlyArray<FeedItemId>
      readonly until: number
    }
    readonly result: {
      readonly items: ReadonlyArray<{
        readonly id: FeedItemId
        readonly revision: number
      }>
    }
  }
  /** Move archived items back to the active list. */
  readonly "feed.unarchive": {
    readonly params: {
      readonly items: ReadonlyArray<FeedItemId>
    }
    readonly result: {
      readonly items: ReadonlyArray<{
        readonly id: FeedItemId
        readonly revision: number
      }>
    }
  }
  /** Allow a validated path through the caller's private network. */
  readonly "firewall.create": {
    readonly params: {
      readonly source: {
        readonly vmId?: string
        readonly vpcId?: string
        readonly tunnelId?: string
        readonly cidr?: string
        readonly public?: boolean
        readonly port?: number
        readonly protocol?: "tcp" | "udp" | "icmp"
      }
      readonly destination: {
        readonly vmId?: string
        readonly vpcId?: string
        readonly tunnelId?: string
        readonly cidr?: string
        readonly public?: boolean
        readonly port?: number
        readonly protocol?: "tcp" | "udp" | "icmp"
      }
      readonly description?: string
    }
    readonly result: {
      readonly id: string
      readonly action: "allow"
      readonly source: {
        readonly vmId?: string
        readonly vpcId?: string
        readonly tunnelId?: string
        readonly cidr?: string
        readonly public?: boolean
        readonly port?: number
        readonly protocol?: "tcp" | "udp" | "icmp"
      }
      readonly destination: {
        readonly vmId?: string
        readonly vpcId?: string
        readonly tunnelId?: string
        readonly cidr?: string
        readonly public?: boolean
        readonly port?: number
        readonly protocol?: "tcp" | "udp" | "icmp"
      }
      readonly description?: string
    }
  }
  /** Delete one firewall rule owned by the caller. */
  readonly "firewall.delete": {
    readonly params: {
      readonly rule_id: string
    }
    readonly result: {
      readonly rule_id: string
    }
  }
  /** Read one firewall rule owned by the caller. */
  readonly "firewall.get": {
    readonly params: {
      readonly rule_id: string
    }
    readonly result: {
      readonly id: string
      readonly action: "allow"
      readonly source: {
        readonly vmId?: string
        readonly vpcId?: string
        readonly tunnelId?: string
        readonly cidr?: string
        readonly public?: boolean
        readonly port?: number
        readonly protocol?: "tcp" | "udp" | "icmp"
      }
      readonly destination: {
        readonly vmId?: string
        readonly vpcId?: string
        readonly tunnelId?: string
        readonly cidr?: string
        readonly public?: boolean
        readonly port?: number
        readonly protocol?: "tcp" | "udp" | "icmp"
      }
      readonly description?: string
    }
  }
  /** List firewall rules attached to the caller's private network. */
  readonly "firewall.list": {
    readonly params: {
      readonly vpc_id?: string
      readonly vm_id?: string
      readonly tunnel_id?: string
    }
    readonly result: {
      readonly rules: ReadonlyArray<{
        readonly id: string
        readonly action: "allow"
        readonly source: {
          readonly vmId?: string
          readonly vpcId?: string
          readonly tunnelId?: string
          readonly cidr?: string
          readonly public?: boolean
          readonly port?: number
          readonly protocol?: "tcp" | "udp" | "icmp"
        }
        readonly destination: {
          readonly vmId?: string
          readonly vpcId?: string
          readonly tunnelId?: string
          readonly cidr?: string
          readonly public?: boolean
          readonly port?: number
          readonly protocol?: "tcp" | "udp" | "icmp"
        }
        readonly description?: string
      }>
    }
  }
  /** Comment on a GitHub issue or pull request as the cmux GitHub App installation. */
  readonly "github.issue.comment": {
    readonly params: {
      readonly connection: ConnectionId
      readonly repo: string
      readonly issue: number
      readonly body: string
    }
    readonly result: unknown
  }
  /** Search Home messages in conversations you are a current human participant of (newest first, with a short Top section). */
  readonly "home.search": {
    readonly params: {
      readonly q: string
      readonly conversation?: ConversationId
      readonly author?: ParticipantId
      readonly kind?: ConversationKind
      readonly before?: Timestamp
      readonly cursor?: string
      readonly limit?: number
    }
    readonly result: {
      readonly hits: ReadonlyArray<{
        readonly conversation: ConversationId
        readonly title: string | null
        readonly seq: number
        readonly message_id: string
        readonly author: ParticipantId
        readonly created_at: Timestamp
        readonly snippet: string
        readonly ranges: ReadonlyArray<{
          readonly start: number
          readonly length: number
        }>
      }>
      readonly cursor?: string
    }
  }
  /** Choose who can find you by email or phone, who may start a conversation with you or add you to one (anyone, teams, nobody), and whether a message request also sends an email. */
  readonly "home.settings.set": {
    readonly params: {
      readonly discoverable_by_email?: boolean
      readonly discoverable_by_phone?: boolean
      readonly allow_requests_from?: "anyone" | "teams" | "nobody"
      readonly email_requests?: boolean
    }
    readonly result: {
      readonly discoverable_by_email: boolean
      readonly discoverable_by_phone: boolean
      readonly allow_requests_from: "anyone" | "teams" | "nobody"
      readonly email_requests: boolean
    }
  }
  /** Enroll the calling install's machine as a host in the team directory. */
  readonly "host.enroll": {
    readonly params: {
      readonly name: string
      readonly platform: Platform
    }
    readonly result: Host
  }
  /** Remove a host from the team directory (its owner or a team admin). */
  readonly "host.remove": {
    readonly params: {
      readonly host: HostId
    }
    readonly result: {
      readonly host: HostId
    }
  }
  /** Archive or unarchive a conversation; a new message unarchives it. */
  readonly "inbox.archive": {
    readonly params: {
      readonly conversation: ConversationId
      readonly archived: boolean
    }
    readonly result: HomeInboxEntry
  }
  /** Your existing one-to-one conversation with a peer, if any (dm.open checks it before deriving a new id). */
  readonly "inbox.dm_peer": {
    readonly params: {
      readonly peer: ParticipantId
    }
    readonly result: {
      readonly conversation: ConversationId | null
    }
  }
  /** List your Home conversations: pinned first by position, then newest activity first. */
  readonly "inbox.list": {
    readonly params: {
      readonly limit?: number
      readonly include_archived?: boolean
      readonly cursor?: string
    }
    readonly result: {
      readonly entries: ReadonlyArray<HomeInboxEntry>
      readonly next_cursor: string | null
      readonly revision: string
    }
  }
  /** Flag a conversation unread (the read cursor stays). */
  readonly "inbox.mark_unread": {
    readonly params: {
      readonly conversation: ConversationId
      readonly unread: boolean
    }
    readonly result: HomeInboxEntry
  }
  /** Mute a conversation (until a time in ms, or until unmuted). Approvals still notify. */
  readonly "inbox.mute": {
    readonly params: {
      readonly conversation: ConversationId
      readonly muted: boolean
      readonly until?: number | "Infinity" | "-Infinity" | "NaN"
    }
    readonly result: HomeInboxEntry
  }
  /** Pin or unpin a conversation in your Home list. */
  readonly "inbox.pin": {
    readonly params: {
      readonly conversation: ConversationId
      readonly pinned: boolean
      readonly position?: number
    }
    readonly result: HomeInboxEntry
  }
  /** List the caller's installs and grants. */
  readonly "install.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly user: UserProfile | null
      readonly installs: ReadonlyArray<Install>
      readonly grants: ReadonlyArray<Grant>
      readonly revision: string
    }
  }
  /** Register an install's public key under the signed-in user; returns the install with its default grant. */
  readonly "install.register": {
    readonly params: {
      readonly public_jwk: PublicJwk
      readonly kind: InstallKind
      readonly name: string
      readonly device_name: string
      readonly platform: Platform
      readonly device?: DeviceId
      readonly op_classes?: ReadonlyArray<OpClass>
      readonly bound_team?: TeamId
    }
    readonly result: Install
  }
  /** Rename an install. An install may rename only itself; the user's session may rename any of its installs. */
  readonly "install.rename": {
    readonly params: {
      readonly install: InstallId
      readonly name: string
    }
    readonly result: Install
  }
  /** Revoke an install: its tokens stop working within one token lifetime and new tokens are refused. */
  readonly "install.revoke": {
    readonly params: {
      readonly install: InstallId
    }
    readonly result: Install
  }
  /** Sign this install out: revokes the calling install (its token, grant, push targets and presence key) so a signed-out device keeps nothing usable. */
  readonly "install.sign_out": {
    readonly params: Readonly<Record<string, never>>
    readonly result: Install
  }
  /** Finish a connection from the provider's redirect (the signed-in user must be the one who started it). */
  readonly "integration.complete": {
    readonly params: {
      readonly state: string
      readonly code?: string
      readonly installation_id?: string
      readonly setup_action?: string
    }
    readonly result: Connection
  }
  /** Start connecting a provider account: returns a pending connection and the provider URL a human opens to approve it. */
  readonly "integration.connect": {
    readonly params: {
      readonly provider: IntegrationProvider
      readonly scopes?: ReadonlyArray<string>
      readonly sharing?: "private" | "team"
    }
    readonly result: {
      readonly connection: Connection
      readonly authorize_url: string
    }
  }
  /** List the team's connections the caller may use (no secrets) and which providers this deployment can connect. */
  readonly "integration.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly connections: ReadonlyArray<Connection>
      readonly providers: ReadonlyArray<{
        readonly provider: IntegrationProvider
        readonly configured: boolean
      }>
      readonly revision: string
    }
  }
  /** Read the team's integration policy (allowed providers, GitHub repository scope). */
  readonly "integration.policy.get": {
    readonly params: Readonly<Record<string, never>>
    readonly result: TeamIntegrationPolicy
  }
  /** Change the team's integration policy (team admins; refused while an SSO or MDM policy locks it). */
  readonly "integration.policy.set": {
    readonly params: {
      readonly allowed_providers?: ReadonlyArray<IntegrationProvider> | null
      readonly github?: {
        readonly scope?: "linking_user_repos" | "installation"
        readonly require_org_admin?: boolean
        readonly repo_allowlist?: ReadonlyArray<RepoPattern> | null
      }
    }
    readonly result: TeamIntegrationPolicy
  }
  /** Disconnect: deletes the stored provider credential at once and marks the connection revoked. */
  readonly "integration.revoke": {
    readonly params: {
      readonly connection: ConnectionId
    }
    readonly result: Connection
  }
  /** Accept an invite from its link (/i/<code>#<secret>). The Worker turns the secret into the proof the owner checks; a group invite may wait for the inviter's approval. */
  readonly "invite.accept": {
    readonly params: {
      readonly code: string
      readonly secret: string
    }
    readonly result: HomeConversationCommit
  }
  /** Approve (default) or decline a join that waits for approval (pending_approval). */
  readonly "invite.approve_join": {
    readonly params: {
      readonly conversation: ConversationId
      readonly invite_id: InviteId
      readonly approve?: boolean
    }
    readonly result: HomeConversationCommit
  }
  /** Invite an email or phone to the conversation. The Worker normalizes the address, checks limits and suppression, and the invite is sent by email or iMessage/SMS after the commit. */
  readonly "invite.create": {
    readonly params: {
      readonly conversation: ConversationId
      readonly address: {
        readonly email: string
      } | {
        readonly phone: string
      }
      readonly display_name: string
      readonly locale?: string
      readonly copy_variant?: string
    }
    readonly result: HomeConversationCommit
  }
  /** Revoke a pending invite (the inviter or the conversation owner). */
  readonly "invite.revoke": {
    readonly params: {
      readonly conversation: ConversationId
      readonly invite_id: InviteId
    }
    readonly result: HomeConversationCommit
  }
  /** Create a Linear issue in a Linear team as the cmux app. */
  readonly "linear.issue.create": {
    readonly params: {
      readonly connection: ConnectionId
      readonly team_id: string
      readonly title: string
      readonly description?: string
    }
    readonly result: unknown
  }
  /** List the Linear teams this connection can reach (ids for linear.issue.create). */
  readonly "linear.teams.list": {
    readonly params: {
      readonly connection: ConnectionId
    }
    readonly result: {
      readonly teams: ReadonlyArray<{
        readonly id: string
        readonly key: string
        readonly name: string
      }>
    }
  }
  /** Read one Gmail message (headers, plain text, attachment list) at call time; nothing is stored. */
  readonly "mail.get": {
    readonly params: {
      readonly connection: ConnectionId
      readonly message_id: string
    }
    readonly result: unknown
  }
  /** Change labels of Gmail messages or a thread (archive, mark read with remove_labels UNREAD). */
  readonly "mail.modify": {
    readonly params: {
      readonly connection: ConnectionId
      readonly thread_id?: string
      readonly message_ids?: ReadonlyArray<string>
      readonly add_labels?: ReadonlyArray<string>
      readonly remove_labels?: ReadonlyArray<string>
      readonly archive?: boolean
    }
    readonly result: unknown
  }
  /** Search the connected Gmail mailbox with Gmail query syntax; returns message and thread ids only. */
  readonly "mail.search": {
    readonly params: {
      readonly connection: ConnectionId
      readonly query: string
      readonly max_results?: number
      readonly page_token?: string
    }
    readonly result: unknown
  }
  /** Send a plain-text email from the connected Gmail account. */
  readonly "mail.send": {
    readonly params: {
      readonly connection: ConnectionId
      readonly to: ReadonlyArray<EmailAddress>
      readonly cc?: ReadonlyArray<EmailAddress>
      readonly bcc?: ReadonlyArray<EmailAddress>
      readonly subject: string
      readonly body: string
      readonly thread_id?: string
      readonly in_reply_to?: string
    }
    readonly result: unknown
  }
  /** Read one Gmail thread (every message, as mail.get) at call time; nothing is stored. */
  readonly "mail.thread.get": {
    readonly params: {
      readonly connection: ConnectionId
      readonly thread_id: string
    }
    readonly result: unknown
  }
  /** Row data for Gmail threads (subject, sender, date, snippet, unread) by id, for feed rows; held in client memory only. */
  readonly "mail.threads.peek": {
    readonly params: {
      readonly connection: ConnectionId
      readonly thread_ids: ReadonlyArray<string>
    }
    readonly result: unknown
  }
  /** Replace the parts of one of your messages (not after it was retracted). */
  readonly "message.edit": {
    readonly params: {
      readonly conversation: ConversationId
      readonly message_id: MessageId
      readonly parts: ReadonlyArray<HomePart>
    }
    readonly result: HomeConversationCommit
  }
  /** Retract one of your messages: its parts and reactions are cleared and it leaves search. */
  readonly "message.retract": {
    readonly params: {
      readonly conversation: ConversationId
      readonly message_id: MessageId
    }
    readonly result: HomeConversationCommit
  }
  /** Send a message. client_msg_id must equal the idempotency key; a retry with the same key returns the original message. */
  readonly "message.send": {
    readonly params: {
      readonly conversation: ConversationId
      readonly client_msg_id: ClientToken
      readonly parts: ReadonlyArray<HomePart>
      readonly reply_to?: HomePartRef
    }
    readonly result: HomeConversationCommit
  }
  /** The chief's brain host acknowledges its wakes in a conversation up to seq (moves its catch-up cursor). */
  readonly "mux.ack": {
    readonly params: {
      readonly agent: AgentId
      readonly conversation: ConversationId
      readonly seq: number
    }
    readonly result: {
      readonly cursor: number
      readonly cleared?: number
    }
  }
  /** Run a chief's brain locally (on a host) or in the cloud (the chief's owner). */
  readonly "mux.configure": {
    readonly params: {
      readonly agent: AgentId
      readonly brain: "local" | "cloud"
      readonly brain_host?: string | null
    }
    readonly result: unknown
  }
  /** List the caller-owned private Cloud networks. */
  readonly "network.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly networks: ReadonlyArray<{
        readonly id: string
        readonly cidr: string | null
        readonly cidrV6: string | null
        readonly scope: "user" | "team"
      }>
    }
  }
  /** Add a user who shares a team with you or is connected to you, when their allow_requests_from setting allows it, or a chief its reachability allows (max 64). Anyone else needs invite.create. At most 120 per hour per caller (home.rate_limited, with details.retry_after_ms). */
  readonly "participants.add": {
    readonly params: {
      readonly conversation: ConversationId
      readonly participant: HomeParticipantInput
    }
    readonly result: HomeConversationCommit
  }
  /** Leave (yourself), or remove a participant (conversation owner; a chief's owner for that chief). Removing the last human archives the conversation. */
  readonly "participants.remove": {
    readonly params: {
      readonly conversation: ConversationId
      readonly participant: ParticipantId
    }
    readonly result: HomeConversationCommit
  }
  /** Register the calling iPhone or iPad install's APNs token (replaces the install's earlier token). */
  readonly "push.target.register": {
    readonly params: {
      readonly token: PushToken
      readonly topic: string
      readonly environment: "development" | "production"
      readonly device_name?: string
    }
    readonly result: PushTarget
  }
  /** Remove an APNs token (sign-out on the device, or the user removes a device). */
  readonly "push.target.remove": {
    readonly params: {
      readonly token: PushToken
    }
    readonly result: {
      readonly token: PushToken
      readonly removed: boolean
    }
  }
  /** Add a tapback or emoji reaction to a message part (one per author, part and kind). */
  readonly "reaction.add": {
    readonly params: {
      readonly conversation: ConversationId
      readonly message_id: MessageId
      readonly part_index: number
      readonly reaction: HomeReactionKind
    }
    readonly result: HomeConversationCommit
  }
  /** Remove one of your reactions. */
  readonly "reaction.remove": {
    readonly params: {
      readonly conversation: ConversationId
      readonly message_id: MessageId
      readonly part_index: number
      readonly reaction: HomeReactionKind
    }
    readonly result: HomeConversationCommit
  }
  /** Move your read cursor forward (monotonic, at most last_seq). Recommended key: read:<seq>. */
  readonly "read_cursor.set": {
    readonly params: {
      readonly conversation: ConversationId
      readonly seq: number
    }
    readonly result: HomeConversationCommit
  }
  /** Approve a pairing code: register the server's install key under you and add the server to the team directory. */
  readonly "server.pair.approve": {
    readonly params: {
      readonly code: PairingCode
      readonly team: TeamId
      readonly name: string
    }
    readonly result: {
      readonly host: HostId
      readonly team: TeamId
      readonly user: UserId
      readonly install: InstallId
    }
  }
  /** Show what a pending pairing code would add: the server's name, platform, key thumbprint and location. */
  readonly "server.pair.preview": {
    readonly params: {
      readonly code: PairingCode
    }
    readonly result: PairingPreview
  }
  /** Remove a server from the team directory and revoke its install key (the owner; a team admin removes it from the directory). */
  readonly "server.revoke": {
    readonly params: {
      readonly host: HostId
    }
    readonly result: {
      readonly host: HostId
      readonly install_revoked: boolean
    }
  }
  /** Post a message to a Slack channel as the cmux bot. */
  readonly "slack.post_as_bot": {
    readonly params: {
      readonly connection: ConnectionId
      readonly channel: string
      readonly text: string
    }
    readonly result: unknown
  }
  /** Fetch the issuer's OpenID discovery document and activate the connection (owners and admins). Needs the secret and every domain verified by this team. */
  readonly "sso.connection.activate": {
    readonly params: {
      readonly connection: SsoConnectionId
    }
    readonly result: SsoConnection
  }
  /** Create an OIDC connection in draft (owners and admins). Then set its client secret and activate it. */
  readonly "sso.connection.create": {
    readonly params: {
      readonly issuer: string
      readonly client_id: string
      readonly domains: ReadonlyArray<EmailDomain>
      readonly scopes?: ReadonlyArray<string>
      readonly jit?: {
        readonly enabled: boolean
        readonly default_role: "member" | "admin"
      }
    }
    readonly result: SsoConnection
  }
  /** Disable a connection (owners and admins): sign-in discovery stops routing to it. */
  readonly "sso.connection.disable": {
    readonly params: {
      readonly connection: SsoConnectionId
    }
    readonly result: SsoConnection
  }
  /** The team's SSO connections, without secrets (owners and admins). */
  readonly "sso.connection.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly team: TeamId
      readonly connections: ReadonlyArray<SsoConnection>
      readonly revision: string
    }
  }
  /** Seal the OIDC client secret (owners and admins). The secret is never returned, logged or recorded in events. */
  readonly "sso.connection.set_secret": {
    readonly params: {
      readonly connection: SsoConnectionId
      readonly client_secret: string
    }
    readonly result: SsoConnection
  }
  /** Create the team VM if it does not exist, resume it if it is paused, and hold it awake with a lease. The same holder and reason renew one lease. When the provider call fails for good, the op answers with that error (the lease stays until it expires). */
  readonly "team_vm.ensure_awake": {
    readonly params: {
      readonly reason: string
      readonly lease_seconds?: number
    }
    readonly result: {
      readonly lease: TeamVmLeaseId
      readonly expires_at: number
      readonly status: TeamVmStatus
      readonly vm: string | null
      readonly epoch: number
    }
  }
  /** Append one seq range (at most 100,000 seqs, 1 MiB) to a team journal stream; returns after the write is durable. A replay of the same range returns the stored acknowledgement. A writer whose reply was lost and whose epoch has since moved gets journal.stale_epoch even though its row is stored. Only the team VM's own install for the current epoch may call it (plans/cmux-next/team-vm-plan.md 3b). */
  readonly "team_vm.journal.append": {
    readonly params: {
      readonly stream: TeamJournalStream
      readonly epoch: number
      readonly first_seq: number
      readonly last_seq: number
      readonly bytes: string
      readonly sha256: string
    }
    readonly result: {
      readonly stream: TeamJournalStream
      readonly first_seq: number
      readonly last_seq: number
      readonly epoch: number
      readonly high_water: number
      readonly replayed: boolean
    }
  }
  /** The last seq a team journal stream holds. Only the team VM's own install for the current epoch may call it (plans/cmux-next/team-vm-plan.md 3b). */
  readonly "team_vm.journal.high_water": {
    readonly params: {
      readonly stream: TeamJournalStream
    }
    readonly result: {
      readonly stream: TeamJournalStream
      readonly high_water: number
      readonly epoch: number
    }
  }
  /** Whole journal entries from a seq on, for restore (up to about 4 MiB per call; `more` asks for the next call). Only the team VM's own install for the current epoch may call it (plans/cmux-next/team-vm-plan.md 3b). */
  readonly "team_vm.journal.read": {
    readonly params: {
      readonly stream: TeamJournalStream
      readonly from_seq: number
    }
    readonly result: {
      readonly entries: ReadonlyArray<{
        readonly first_seq: number
        readonly last_seq: number
        readonly epoch: number
        readonly sha256: string
        readonly bytes: string
      }>
      readonly high_water: number
      readonly more: boolean
    }
  }
  /** Release a wake lease you hold, so the team VM may pause when no other lease is active. */
  readonly "team_vm.lease.release": {
    readonly params: {
      readonly lease: TeamVmLeaseId
    }
    readonly result: {
      readonly lease: TeamVmLeaseId
      readonly released: boolean
    }
  }
  /** The team SSH CA public keys and the current revocation list (KRL), for the team VM's sshd. */
  readonly "team_vm.ssh_ca": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly team: TeamId
      readonly generation: number
      readonly trusted_ca_keys: ReadonlyArray<string>
      readonly krl: string
      readonly krl_version: number
    }
  }
  /** Replace the team SSH CA key (owners and admins, in a person's session). Without `compromised`, certificates from the old key stay valid until they expire (at most 60 minutes). */
  readonly "team_vm.ssh_ca.rotate": {
    readonly params: {
      readonly compromised?: boolean
    }
    readonly result: {
      readonly generation: number
      readonly ca_public_key: string
      readonly previous_trusted_until: number | null
    }
  }
  /** Sign a short-lived SSH user certificate (15 to 60 minutes) for the team VM. The certificate names the caller's Linux user; `agent` certificates run only `cmux team …` commands; a `human` (full shell) certificate needs a person's session and a fresh presence proof. Replaying the same idempotency key returns the same certificate, also after a crash. */
  readonly "team_vm.ssh_cert": {
    readonly params: {
      readonly public_key: string
      readonly validity_minutes?: number
      readonly class?: SshCertClass
      readonly presence?: SshPresenceProof
    }
    readonly result: {
      readonly certificate: string
      readonly serial: number
      readonly key_id: string
      readonly principals: ReadonlyArray<string>
      readonly class: SshCertClass
      readonly valid_after: number
      readonly valid_before: number
      readonly ca_generation: number
      readonly ca_public_key: string
    }
  }
  /** Start a full-shell SSH certificate request: returns a single-use presence challenge for one of your devices. Approve it there (Face ID, Touch ID or passcode), then call team_vm.ssh_cert with class human, the proof and the same request key. */
  readonly "team_vm.ssh_cert.challenge": {
    readonly params: {
      readonly public_key: string
      readonly validity_minutes?: number
      readonly presence_install: InstallId
      readonly request: string
    }
    readonly result: {
      readonly sign: unknown
      readonly message: string
      readonly expires_at: number
    }
  }
  /** Revoke unexpired team VM SSH certificates by serial, user or install; the revocation list (KRL) lists them at once. Members revoke their own certificates; owners and admins revoke anyone's. */
  readonly "team_vm.ssh_cert.revoke": {
    readonly params: {
      readonly serial?: number
      readonly user?: UserId
      readonly install?: InstallId
      readonly reason?: string
    }
    readonly result: {
      readonly revoked: ReadonlyArray<number>
      readonly krl_version: number
    }
  }
  /** Show the team VM: its state, epoch and active wake leases. */
  readonly "team_vm.status": {
    readonly params: Readonly<Record<string, never>>
    readonly result: TeamVmView
  }
  /** Per managed device: the last status report and whether it is compliant (applied the current policy version, no MDM conflicts). Owners and admins; readable by a customer dashboard through an admin's session or install token. */
  readonly "team.device.compliance": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly team: TeamId
      readonly policy_version: number
      readonly devices: ReadonlyArray<{
        readonly device: ManagedDevice
        readonly status: DeviceStatus | null
        readonly compliant: boolean
        readonly reasons: ReadonlyArray<string>
      }>
      readonly revision: string
    }
  }
  /** Make this team the calling install's managing team: with an MDM enrollment token's hash, or without one as the user's explicit acceptance. */
  readonly "team.device.enroll": {
    readonly params: {
      readonly token_hash?: EnrollmentTokenHash
    }
    readonly result: ManagedDevice
  }
  /** The device-scoped policy for the calling install: values only when this team manages it (decision E3). */
  readonly "team.device.policy": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly team: TeamId
      readonly managed: boolean
      readonly team_name: string
      readonly version: number
      readonly defaults: Readonly<Record<string, never>>
      readonly enforced: Readonly<Record<string, never>>
      readonly features: Readonly<Record<string, never>>
      readonly revision: string
    }
  }
  /** Stop managing an install: team admins for any install; the install's user only for an install they accepted (not one enrolled by an MDM token). Agents never. */
  readonly "team.device.release": {
    readonly params: {
      readonly install: InstallId
    }
    readonly result: {
      readonly install: InstallId
    }
  }
  /** Report what this install applied (policy version, MDM key names, conflicts). Send when it changes; the latest report replaces the previous one. */
  readonly "team.device.report_status": {
    readonly params: {
      readonly policy_version: number
      readonly app_version: string
      readonly mdm_keys: ReadonlyArray<string>
      readonly conflicts: ReadonlyArray<string>
    }
    readonly result: DeviceStatus
  }
  /** Read a team's directory: the first 200 members and hosts (U2). Page larger teams with team.members.list and team.hosts.list. */
  readonly "team.directory": {
    readonly params: {
      readonly team?: TeamId
    }
    readonly result: {
      readonly team: TeamId
      readonly members: ReadonlyArray<TeamMember>
      readonly hosts: ReadonlyArray<Host>
      readonly revision: string
    }
  }
  /** Create a device enrollment token (owners and admins). The caller generates the token, sends only its SHA-256, and shows the token once. */
  readonly "team.enrollment_token.create": {
    readonly params: {
      readonly label: string
      readonly token_hash: EnrollmentTokenHash
      readonly allowed_domains?: ReadonlyArray<string>
      readonly expires_at?: number
    }
    readonly result: EnrollmentToken
  }
  /** List enrollment tokens and managed devices (owners and admins). */
  readonly "team.enrollment_token.list": {
    readonly params: Readonly<Record<string, never>>
    readonly result: {
      readonly team: TeamId
      readonly tokens: ReadonlyArray<EnrollmentToken>
      readonly devices: ReadonlyArray<ManagedDevice>
      readonly revision: string
    }
  }
  /** Revoke an enrollment token. Devices already enrolled stay managed. */
  readonly "team.enrollment_token.revoke": {
    readonly params: {
      readonly token: EnrollmentTokenId
    }
    readonly result: EnrollmentToken
  }
  /** Page a team's enrolled hosts by host id (keyset: pass next_cursor as cursor). */
  readonly "team.hosts.list": {
    readonly params: {
      readonly team?: TeamId
      readonly cursor?: string
      readonly limit?: number
    }
    readonly result: {
      readonly team: TeamId
      readonly hosts: ReadonlyArray<Host>
      readonly host_count: number | "Infinity" | "-Infinity" | "NaN"
      readonly next_cursor: string | null
      readonly revision: string
    }
  }
  /** Release the SSO or MDM lock on the team's integration policy (owners and admins; audited). The team policy then applies again. */
  readonly "team.integration.release_lock": {
    readonly params: {
      readonly reason?: string
    }
    readonly result: {
      readonly released: "sso" | "mdm"
    }
  }
  /** Page a team's members by user id (keyset: pass next_cursor as cursor), optionally one role. */
  readonly "team.members.list": {
    readonly params: {
      readonly team?: TeamId
      readonly cursor?: string
      readonly limit?: number
      readonly role?: "owner" | "admin" | "member"
    }
    readonly result: {
      readonly team: TeamId
      readonly members: ReadonlyArray<TeamMember>
      readonly member_count: number | "Infinity" | "-Infinity" | "NaN"
      readonly next_cursor: string | null
      readonly revision: string
    }
  }
  /** Read the team policy (current or a retained past version). Every member may read it; clients apply its device-scoped keys. */
  readonly "team.policy.get": {
    readonly params: {
      readonly version?: number
    }
    readonly result: {
      readonly team: TeamId
      readonly policy: TeamPolicy
      readonly integration_managed_by: "sso" | "mdm" | null
      readonly revision: string
    }
  }
  /** List the last 20 team policy versions, newest first, with actor, reason and changed keys (owners and admins). */
  readonly "team.policy.history": {
    readonly params: {
      readonly limit?: number
    }
    readonly result: {
      readonly team: TeamId
      readonly versions: ReadonlyArray<TeamPolicyVersion>
      readonly revision: string
    }
  }
  /** Apply a retained past version's values as a new version (owners and admins). */
  readonly "team.policy.rollback": {
    readonly params: {
      readonly version: number
      readonly expected_version: number
      readonly reason?: string
    }
    readonly result: TeamPolicy
  }
  /** Set or clear team policy keys as one new version (owners and admins). expected_version is the compare-and-swap; a stale version fails with revision.conflict. */
  readonly "team.policy.update": {
    readonly params: {
      readonly changes: ReadonlyArray<PolicyChange>
      readonly expected_version: number
      readonly reason?: string
    }
    readonly result: TeamPolicy
  }
  /** Rename a group conversation (not a dm or chief thread). */
  readonly "title.set": {
    readonly params: {
      readonly conversation: ConversationId
      readonly title: string
    }
    readonly result: HomeConversationCommit
  }
  /** Attach an owned WireGuard tunnel to an owned private network. */
  readonly "tunnel.attach": {
    readonly params: {
      readonly device_fingerprint: string
      readonly network_id: string
    }
    readonly result: {
      readonly tunnel_id: string
      readonly network_id: string
    }
  }
  /** Detach an owned WireGuard tunnel from an owned private network. */
  readonly "tunnel.detach": {
    readonly params: {
      readonly device_fingerprint: string
      readonly network_id: string
    }
    readonly result: {
      readonly tunnel_id: string
      readonly network_id: string
    }
  }
  /** Rotate an owned tunnel's WireGuard public key without changing its address. */
  readonly "tunnel.rotate-key": {
    readonly params: {
      readonly device_fingerprint: string
      readonly client_public_key: string
    }
    readonly result: {
      readonly tunnel_id: string
      readonly client_public_key: string
    }
  }
  /** Set the team's own monthly hard cap for automations (team admins). The cap in force is the lower of it and the deployment ceiling. */
  readonly "usage.cap.set": {
    readonly params: {
      readonly cap_usd: number | "Infinity" | "-Infinity" | "NaN" | null
    }
    readonly result: {
      readonly owner: TeamId | null
      readonly team_cap_usd: number | "Infinity" | "-Infinity" | "NaN" | null
    }
  }
  /** This month's automation usage of the caller's team, its cost estimate and the hard cap that stops runs. */
  readonly "usage.summary": {
    readonly params: Readonly<Record<string, never>>
    readonly result: UsageSummary
  }
  /** Create or refresh the caller's user record from the Stack session. */
  readonly "user.ensure": {
    readonly params: Readonly<Record<string, never>>
    readonly result: UserProfile
  }
  /** Make an install's presence key unusable at once (device lost); its nonces are dropped. */
  readonly "user.presence_key.revoke": {
    readonly params: {
      readonly install: string
    }
    readonly result: unknown
  }
  /** The level in effect, the user's own level, the lock and the presence keys (public parts and usable_from) for Settings. */
  readonly "user.text_confirm.get": {
    readonly params: Readonly<Record<string, never>>
    readonly result: unknown
  }
  /** Make the text confirmation level safer (applies at once). A riskier level needs lower.challenge and lower. */
  readonly "user.text_confirm.level.set": {
    readonly params: {
      readonly level: ConfirmLevel
    }
    readonly result: {
      readonly level: ConfirmLevel
    }
  }
  /** Lower the level with the signed challenge. Spends the nonce on any attempt; a refused proof commits `lowered: false` with a code. */
  readonly "user.text_confirm.lower": {
    readonly params: {
      readonly level: ConfirmLevel
      readonly nonce: string
      readonly presence_sig: string
      readonly app_attest?: string
    }
    readonly result: unknown
  }
  /** Owner Mac or iPhone install with an active presence key: returns the exact bytes to sign (2 minutes, one live nonce per install). */
  readonly "user.text_confirm.lower.challenge": {
    readonly params: {
      readonly level: ConfirmLevel
    }
    readonly result: unknown
  }
}

export type CloudOpName = keyof CloudOps

/** Routing metadata: mutations go to /v1/ops with an idempotency key, reads to /v1/read. */
export const cloudOpMeta = {
  "automation.create": { class: "mutation", owner: "cloud:SchedulerDO", risk: "mutate-shared" },
  "automation.delete": { class: "mutation", owner: "cloud:SchedulerDO", risk: "destructive" },
  "automation.deploy": { class: "mutation", owner: "cloud:SchedulerDO", risk: "execute" },
  "automation.get": { class: "read", owner: "cloud:SchedulerDO", risk: "read" },
  "automation.list": { class: "read", owner: "cloud:SchedulerDO", risk: "read" },
  "automation.run": { class: "mutation", owner: "cloud:SchedulerDO", risk: "execute" },
  "automation.runs.list": { class: "read", owner: "cloud:SchedulerDO", risk: "read" },
  "automation.settings.get": { class: "read", owner: "cloud:SchedulerDO", risk: "read" },
  "automation.settings.set": { class: "mutation", owner: "cloud:SchedulerDO", risk: "mutate-shared" },
  "automation.update": { class: "mutation", owner: "cloud:SchedulerDO", risk: "mutate-shared" },
  "automation.webhook.get": { class: "read", owner: "cloud:SchedulerDO", risk: "read" },
  "calendar.calendars.list": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "calendar.event.create": { class: "mutation", owner: "cloud:ConnectionDO", risk: "send-external" },
  "calendar.event.respond": { class: "mutation", owner: "cloud:ConnectionDO", risk: "send-external" },
  "calendar.events.list": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "chief.archive": { class: "mutation", owner: "cloud:UserDO", risk: "destructive" },
  "chief.create": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "chief.list": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "chief.update": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "conversation.create": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "conversation.history": { class: "read", owner: "cloud:ConversationDO", risk: "read" },
  "conversation.import": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "conversation.import.commit": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "conversation.settings.set": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "conversation.snapshot": { class: "read", owner: "cloud:ConversationDO", risk: "read" },
  "dm.open": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "domain.claim": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "domain.list": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "domain.release": { class: "mutation", owner: "cloud:TeamDO", risk: "destructive" },
  "domain.verify": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "feed.adopt": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.adopt.cancel": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.answer": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.archive": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.cancel": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.counts": { class: "read", owner: "cloud:FeedDO", risk: "read" },
  "feed.get": { class: "read", owner: "cloud:FeedDO", risk: "read" },
  "feed.kinds": { class: "read", owner: "cloud:FeedDO", risk: "read" },
  "feed.list": { class: "read", owner: "cloud:FeedDO", risk: "read" },
  "feed.post": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.prefs.set": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.read": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.seen": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.snooze": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "feed.unarchive": { class: "mutation", owner: "cloud:FeedDO", risk: "mutate-own" },
  "firewall.create": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "firewall.delete": { class: "mutation", owner: "cloud:UserDO", risk: "destructive" },
  "firewall.get": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "firewall.list": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "github.issue.comment": { class: "mutation", owner: "cloud:ConnectionDO", risk: "send-external" },
  "home.search": { class: "read", owner: "cloud:planetscale", risk: "read" },
  "home.settings.set": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "host.enroll": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "host.remove": { class: "mutation", owner: "cloud:TeamDO", risk: "destructive" },
  "inbox.archive": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "inbox.dm_peer": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "inbox.list": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "inbox.mark_unread": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "inbox.mute": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "inbox.pin": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "install.list": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "install.register": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "install.rename": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "install.revoke": { class: "mutation", owner: "cloud:UserDO", risk: "destructive" },
  "install.sign_out": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "integration.complete": { class: "mutation", owner: "cloud:ConnectionDO", risk: "mutate-shared" },
  "integration.connect": { class: "mutation", owner: "cloud:ConnectionDO", risk: "mutate-shared" },
  "integration.list": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "integration.policy.get": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "integration.policy.set": { class: "mutation", owner: "cloud:ConnectionDO", risk: "mutate-shared" },
  "integration.revoke": { class: "mutation", owner: "cloud:ConnectionDO", risk: "destructive" },
  "invite.accept": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-own" },
  "invite.approve_join": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "invite.create": { class: "mutation", owner: "cloud:ConversationDO", risk: "send-external" },
  "invite.revoke": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "linear.issue.create": { class: "mutation", owner: "cloud:ConnectionDO", risk: "mutate-shared" },
  "linear.teams.list": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "mail.get": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "mail.modify": { class: "mutation", owner: "cloud:ConnectionDO", risk: "mutate-own" },
  "mail.search": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "mail.send": { class: "mutation", owner: "cloud:ConnectionDO", risk: "send-external" },
  "mail.thread.get": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "mail.threads.peek": { class: "read", owner: "cloud:ConnectionDO", risk: "read" },
  "message.edit": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-own" },
  "message.retract": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-own" },
  "message.send": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "mux.ack": { class: "mutation", owner: "cloud:MuxDO", risk: "mutate-own" },
  "mux.configure": { class: "mutation", owner: "cloud:MuxDO", risk: "mutate-own" },
  "network.list": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "participants.add": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "participants.remove": { class: "mutation", owner: "cloud:ConversationDO", risk: "destructive" },
  "push.target.register": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "push.target.remove": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "reaction.add": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "reaction.remove": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-own" },
  "read_cursor.set": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-own" },
  "server.pair.approve": { class: "mutation", owner: "cloud:PairingDO", risk: "mutate-shared" },
  "server.pair.preview": { class: "read", owner: "cloud:PairingDO", risk: "read" },
  "server.revoke": { class: "mutation", owner: "cloud:TeamDO", risk: "destructive" },
  "slack.post_as_bot": { class: "mutation", owner: "cloud:ConnectionDO", risk: "send-external" },
  "sso.connection.activate": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "sso.connection.create": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "sso.connection.disable": { class: "mutation", owner: "cloud:TeamDO", risk: "destructive" },
  "sso.connection.list": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "sso.connection.set_secret": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "team_vm.ensure_awake": { class: "mutation", owner: "cloud:TeamVmDO", risk: "mutate-shared" },
  "team_vm.journal.append": { class: "mutation", owner: "cloud:TeamVmDO", risk: "mutate-own" },
  "team_vm.journal.high_water": { class: "read", owner: "cloud:TeamVmDO", risk: "read" },
  "team_vm.journal.read": { class: "read", owner: "cloud:TeamVmDO", risk: "read" },
  "team_vm.lease.release": { class: "mutation", owner: "cloud:TeamVmDO", risk: "mutate-own" },
  "team_vm.ssh_ca": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team_vm.ssh_ca.rotate": { class: "mutation", owner: "cloud:TeamDO", risk: "destructive" },
  "team_vm.ssh_cert": { class: "mutation", owner: "cloud:TeamDO", risk: "execute" },
  "team_vm.ssh_cert.challenge": { class: "mutation", owner: "cloud:TeamDO", risk: "execute" },
  "team_vm.ssh_cert.revoke": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "team_vm.status": { class: "read", owner: "cloud:TeamVmDO", risk: "read" },
  "team.device.compliance": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.device.enroll": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-own" },
  "team.device.policy": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.device.release": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-own" },
  "team.device.report_status": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-own" },
  "team.directory": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.enrollment_token.create": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "team.enrollment_token.list": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.enrollment_token.revoke": { class: "mutation", owner: "cloud:TeamDO", risk: "destructive" },
  "team.hosts.list": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.integration.release_lock": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "team.members.list": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.policy.get": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.policy.history": { class: "read", owner: "cloud:TeamDO", risk: "read" },
  "team.policy.rollback": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "team.policy.update": { class: "mutation", owner: "cloud:TeamDO", risk: "mutate-shared" },
  "title.set": { class: "mutation", owner: "cloud:ConversationDO", risk: "mutate-shared" },
  "tunnel.attach": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "tunnel.detach": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "tunnel.rotate-key": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "usage.cap.set": { class: "mutation", owner: "cloud:UsageMeterDO", risk: "money" },
  "usage.summary": { class: "read", owner: "cloud:UsageMeterDO", risk: "read" },
  "user.ensure": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "user.presence_key.revoke": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "user.text_confirm.get": { class: "read", owner: "cloud:UserDO", risk: "read" },
  "user.text_confirm.level.set": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "user.text_confirm.lower": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
  "user.text_confirm.lower.challenge": { class: "mutation", owner: "cloud:UserDO", risk: "mutate-own" },
} as const satisfies Record<CloudOpName, { class: "read" | "mutation"; owner: string; risk: string }>

export type CloudMutationName = { [K in CloudOpName]: (typeof cloudOpMeta)[K]["class"] extends "mutation" ? K : never }[CloudOpName]
export type CloudReadName = Exclude<CloudOpName, CloudMutationName>
