/**
 * Generates the GPL TypeScript client types (clients/ts/cloud/src/generated.ts)
 * from the checked-in cloud catalog (backend/catalog/cloud-operations.json).
 * The output holds only types and op metadata, never backend logic, so the
 * macOS app (webviews/) may import it. Interim until the CLI owners' catalog
 * generator emits TypeScript (spec D7).
 *
 *   bun scripts/export-client.ts          write
 *   bun scripts/export-client.ts --check  fail when the checked-in file differs
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { automationCapabilityOps } from "../src/automation-caps.ts"

type T = { kind: string; [k: string]: any }
const catalogPath = fileURLToPath(new URL("../../../catalog/cloud-operations.json", import.meta.url))
const outPath = fileURLToPath(new URL("../../../../clients/ts/cloud/src/generated.ts", import.meta.url))
const catalog = JSON.parse(readFileSync(catalogPath, "utf8")) as {
  types: Record<string, T>
  operations: Record<string, any>
}

const ident = (s: string) => s.replace(/[^A-Za-z0-9]+(.)?/g, (_m, c: string | undefined) => (c ? c.toUpperCase() : "")).replace(/^./, (c) => c.toUpperCase())
const key = (k: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k))

const ts = (t: T, indent = ""): string => {
  switch (t.kind) {
    case "primitive":
      return { string: "string", int64: "number", int32: "number", uint32: "number", uint16: "number", float64: "number", boolean: "boolean", decimal: "string", base64: "string", json: "unknown" }[t.name as string] ?? "unknown"
    case "ref":
      return t.name
    case "array":
      return `ReadonlyArray<${ts(t.items, indent)}>`
    case "map":
      return `Readonly<Record<string, ${ts(t.values, indent)}>>`
    case "enum":
      return (t.values as Array<unknown>).map((v) => JSON.stringify(v)).join(" | ") || "never"
    case "nullable":
      return `${ts(t.inner, indent)} | null`
    case "union":
      return (t.variants as Array<T>).map((v) => ts(v, indent)).join(" | ")
    case "apply":
      return `${t.name}<${(t.arguments as Array<T>).map((a) => ts(a, indent)).join(", ")}>`
    case "parameter":
      return t.name
    case "object": {
      const fields = Object.entries((t.fields ?? {}) as Record<string, { required: boolean; type: T; description?: string }>)
      if (fields.length === 0) return "Readonly<Record<string, never>>"
      const inner = indent + "  "
      return `{\n${fields
        .map(([k, f]) => `${f.description ? `${inner}/** ${f.description.replace(/\*\//g, "* /")} */\n` : ""}${inner}readonly ${key(k)}${f.required ? "" : "?"}: ${ts(f.type, inner)}`)
        .join("\n")}\n${indent}}`
    }
    default:
      return "unknown"
  }
}

const lines: Array<string> = [
  "// GENERATED by backend/packages/protocol/scripts/export-client.ts from backend/catalog/cloud-operations.json.",
  "// Do not edit. Types and op metadata only (GPL-3.0-or-later, like the rest of the repository outside the BSL list).",
  "",
  "export interface MutationResult<T> {",
  "  readonly value: T",
  "  readonly revision: string",
  "  readonly transaction: string",
  "  readonly replayed: boolean",
  "}",
  ""
]
for (const [name, t] of Object.entries(catalog.types).sort(([a], [b]) => a.localeCompare(b))) {
  if (t.description) lines.push(`/** ${String(t.description).replace(/\*\//g, "* /")} */`)
  lines.push(`export type ${name} = ${ts(t)}`, "")
}

const ops = Object.entries(catalog.operations).sort(([a], [b]) => a.localeCompare(b))
lines.push("/** Params and result of every cloud op, keyed by op name. */", "export interface CloudOps {")
for (const [name, op] of ops) {
  const params: T = { kind: "object", fields: Object.fromEntries(Object.entries(op.params.fields).filter(([k]) => k !== "expected_revision")) }
  const result: T = op.class === "mutation" ? op.result.arguments[0] : op.result
  lines.push(`  /** ${String(op.docs).replace(/\*\//g, "* /")} */`)
  lines.push(`  readonly ${JSON.stringify(name)}: {`)
  lines.push(`    readonly params: ${ts(params, "    ")}`)
  lines.push(`    readonly result: ${ts(result, "    ")}`)
  lines.push("  }")
}
lines.push("}", "", "export type CloudOpName = keyof CloudOps", "")
lines.push("/** Routing metadata: mutations go to /v1/ops with an idempotency key, reads to /v1/read. */")
lines.push("export const cloudOpMeta = {")
for (const [name, op] of ops) {
  lines.push(`  ${JSON.stringify(name)}: { class: ${JSON.stringify(op.class)}, owner: ${JSON.stringify(op.owner)}, risk: ${JSON.stringify(op.risk)} },`)
}
lines.push("} as const satisfies Record<CloudOpName, { class: \"read\" | \"mutation\"; owner: string; risk: string }>", "")
lines.push("export type CloudMutationName = { [K in CloudOpName]: (typeof cloudOpMeta)[K][\"class\"] extends \"mutation\" ? K : never }[CloudOpName]")
lines.push("export type CloudReadName = Exclude<CloudOpName, CloudMutationName>", "")

// env.cmux for automation code (automations plan slice 4): the capability ops and their types.
for (const name of automationCapabilityOps) if (!(name in catalog.operations)) throw new Error(`automation capability ${name} is not a cloud op`)
const cmuxText = [
  "// GENERATED by backend/packages/protocol/scripts/export-client.ts from backend/packages/protocol/src/automation-caps.ts",
  "// and backend/catalog/cloud-operations.json. Do not edit.",
  "import type { CloudOps } from \"./generated.ts\"",
  "",
  "/** Cloud ops automation code may call as itself (env.cmux.op and the op step). */",
  `export const automationCapabilityOps = [${automationCapabilityOps.map((n) => JSON.stringify(n)).join(", ")}] as const`,
  "export type AutomationCapabilityOp = (typeof automationCapabilityOps)[number]",
  "",
  "/** `env.cmux` inside automation code. No credential ever reaches the code; the platform calls as the automation. */",
  "export interface Cmux {",
  "  /** Runs one capability op as the automation. A mutation needs options.idempotency_key, unique within the run; a replay or retry with the same key happens once. */",
  "  op<N extends AutomationCapabilityOp>(name: N, params: CloudOps[N][\"params\"], options?: { readonly idempotency_key?: string }): Promise<CloudOps[N][\"result\"]>",
  "  /** One structured log line of this run. */",
  "  log(level: \"debug\" | \"info\" | \"warn\" | \"error\", msg: string, attrs?: Readonly<Record<string, unknown>>): Promise<void>",
  "  /** One metric sample of this run. */",
  "  metric(name: string, value: number, attrs?: Readonly<Record<string, string>>): Promise<void>",
  "}",
  ""
].join("\n")
const cmuxPath = fileURLToPath(new URL("../../../../clients/ts/cloud/src/automation-cmux.ts", import.meta.url))

const text = lines.join("\n")
const outputs: Array<[string, string]> = [
  [outPath, text],
  [cmuxPath, cmuxText]
]
if (process.argv.includes("--check")) {
  for (const [path, want] of outputs) {
    let current = ""
    try {
      current = readFileSync(path, "utf8")
    } catch {}
    if (current !== want) {
      console.error(`client drift: ${path} differs from the catalog; run bun run catalog:client`)
      process.exit(1)
    }
  }
  console.log(`client ok: ${ops.length} ops`)
} else {
  for (const [path, want] of outputs) writeFileSync(path, want)
  console.log(`wrote ${outPath}: ${ops.length} ops, ${Object.keys(catalog.types).length} types; ${cmuxPath}`)
}
