// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.1.0 (SHA-256 799583cb88d70602efe4f5bd10115887380c31edaca71fdec7d2be466bb7673a).

package hellopane

import pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"

// IR the package was generated from.
const (
	IRVersion = "0.1.0"
	IRSHA256  = "799583cb88d70602efe4f5bd10115887380c31edaca71fdec7d2be466bb7673a"
)

// Op names.
const (
	OpCmuxGitDiff              = "cmux.git.diff"
	OpCmuxGitStatus            = "cmux.git.status"
	OpCmuxRouterHello          = "cmux.router.hello"
	OpCmuxRouterInterfacesList = "cmux.router.interfaces.list"
	OpCmuxRouterPagesList      = "cmux.router.pages.list"
	OpCmuxRouterResolve        = "cmux.router.resolve"
	OpCmuxRouterTokenRefresh   = "cmux.router.token.refresh"
	OpComExampleHelloGreetSay  = "com.example.hello.greet.say"
)

// Event stream names.
const (
	EventCmuxGitStatusChanged      = "cmux.git.status.changed"
	EventComExampleHelloGreetTicks = "com.example.hello.greet.ticks"
)

// Op error codes declared in the IR.
const (
	ErrCmuxGitBadRef        = "cmux.git.bad_ref"
	ErrCmuxGitNotARepo      = "cmux.git.not_a_repo"
	ErrCmuxRouterNoProvider = "cmux.router.no_provider"
	ErrCmuxRouterRefused    = "cmux.router.refused"
)

// Shared interface contracts.
const (
	InterfaceCmuxDiffSource1 = "cmux.diff.source/1"
)

// Catalog is the IR this package was generated from, as the runtime enforces
// it: per op the scope, path params, risk metadata and validators.
var Catalog = &pane.Catalog{
	IRVersion: IRVersion,
	IRSHA256:  IRSHA256,
	Ops: []pane.OpInfo{
		{
			Name: "cmux.git.diff", Kind: "read", Scope: "git:read",
			Errors: []string{"cmux.git.not_a_repo", "cmux.git.bad_ref"}, Aliases: nil, Paths: []string{"cwd"},
			MCPExpose: "default", MCPGroup: "git", MCPTool: "cmux_git_diff",
			CLIPath: "git diff", CLIVisible: true, CLIPositional: []string{"base"},
			SecretOutput: false, Risk: "read", Gesture: false, ScopeClass: "standard", ServerOnly: false,
			ValidateParams: ValidateGitDiffParams, ValidateResult: ValidateGitDiff,
		},
		{
			Name: "cmux.git.status", Kind: "read", Scope: "git:read",
			Errors: []string{"cmux.git.not_a_repo"}, Aliases: nil, Paths: []string{"cwd"},
			MCPExpose: "default", MCPGroup: "git", MCPTool: "cmux_git_status",
			CLIPath: "git status", CLIVisible: true, CLIPositional: nil,
			SecretOutput: false, Risk: "read", Gesture: false, ScopeClass: "standard", ServerOnly: false,
			ValidateParams: ValidateGitStatusParams, ValidateResult: ValidateGitStatus,
		},
		{
			Name: "cmux.router.hello", Kind: "mutation", Scope: "router:control",
			Errors: []string{"cmux.router.refused"}, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "cmux_router_hello",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "mutate-shared", Gesture: false, ScopeClass: "sensitive", ServerOnly: false,
			ValidateParams: ValidateProviderHello, ValidateResult: ValidateProviderWelcome,
		},
		{
			Name: "cmux.router.interfaces.list", Kind: "read", Scope: "router:read",
			Errors: nil, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "cmux_router_interfaces_list",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "read", Gesture: false, ScopeClass: "standard", ServerOnly: false,
			ValidateParams: ValidateInterfacesListParams, ValidateResult: ValidateInterfacesListResult,
		},
		{
			Name: "cmux.router.pages.list", Kind: "read", Scope: "router:read",
			Errors: nil, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "cmux_router_pages_list",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "read", Gesture: false, ScopeClass: "standard", ServerOnly: false,
			ValidateParams: ValidatePagesListParams, ValidateResult: ValidatePagesListResult,
		},
		{
			Name: "cmux.router.resolve", Kind: "read", Scope: "router:read",
			Errors: []string{"cmux.router.no_provider"}, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "cmux_router_resolve",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "read", Gesture: false, ScopeClass: "standard", ServerOnly: false,
			ValidateParams: ValidateResolveParams, ValidateResult: ValidateResolveResult,
		},
		{
			Name: "cmux.router.token.refresh", Kind: "mutation", Scope: "router:write",
			Errors: nil, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "cmux_router_token_refresh",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "mutate-own", Gesture: false, ScopeClass: "sensitive", ServerOnly: false,
			ValidateParams: ValidateTokenRefreshParams, ValidateResult: ValidateTokenRefreshResult,
		},
		{
			Name: "com.example.hello.greet.say", Kind: "read", Scope: "hello:read",
			Errors: nil, Aliases: nil, Paths: nil,
			MCPExpose: "never", MCPGroup: "", MCPTool: "com_example_hello_greet_say",
			CLIPath: "", CLIVisible: false, CLIPositional: nil,
			SecretOutput: false, Risk: "read", Gesture: false, ScopeClass: "standard", ServerOnly: false,
			ValidateParams: ValidateHelloParams, ValidateResult: ValidateHelloResult,
		},
	},
	Events: []pane.EventInfo{
		{Name: "cmux.git.status.changed", Scope: "git:read", Validate: ValidateGitStatus},
		{Name: "com.example.hello.greet.ticks", Scope: "hello:read", Validate: ValidateHelloResult},
	},
}

// ProviderNamespaces are the namespaces this package serves.
var ProviderNamespaces = []string{"com.example.hello"}
