// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.1.0 (SHA-256 799583cb88d70602efe4f5bd10115887380c31edaca71fdec7d2be466bb7673a).

package hellopane

import (
	"context"
	"encoding/json"

	pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
)

// App is the app id that owns com.example.hello.
const App = "com.example.hello"

// NewProvider creates a provider for App that owns ProviderNamespaces. Register
// a handler for each namespace, then call Run.
func NewProvider() (*pane.Provider, error) {
	return pane.NewProvider(App, Catalog, ProviderNamespaces...)
}

// ComExampleHelloHandler serves the ops and event streams of namespace com.example.hello.
// Params arrive validated; results and events are validated before they
// are sent. Return *pane.Error with a declared code for expected failures;
// any other error is logged and sent as cmux.protocol.internal.
type ComExampleHelloHandler interface {
	// GreetSay serves com.example.hello.greet.say (read, scope hello:read; errors: none).
	GreetSay(ctx context.Context, call *pane.Call, params HelloParams) (HelloResult, error)
	// SubscribeGreetTicks runs when a peer subscribes to com.example.hello.greet.ticks (scope
	// hello:read), before the ok. Emit on sink for this subscriber only;
	// return an error to refuse. Do not block: start a goroutine that stops
	// when ctx is done. Publish reaches every subscriber.
	SubscribeGreetTicks(ctx context.Context, call *pane.Call, sink *pane.TypedSink[HelloResult]) error
}

// RegisterComExampleHello registers h for every op and event of com.example.hello.
func RegisterComExampleHello(p *pane.Provider, h ComExampleHelloHandler) error {
	if err := p.Register(OpComExampleHelloGreetSay, func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {
		var params HelloParams
		if err := json.Unmarshal(raw, &params); err != nil {
			return nil, err
		}
		result, err := h.GreetSay(ctx, call, params)
		if err != nil {
			return nil, err
		}
		return json.Marshal(result)
	}); err != nil {
		return err
	}
	if err := p.RegisterEvent(EventComExampleHelloGreetTicks, pane.EventHandler{
		OnSubscribe: func(ctx context.Context, call *pane.Call, sink *pane.Sink) error {
			return h.SubscribeGreetTicks(ctx, call, pane.NewTypedSink[HelloResult](sink))
		},
	}); err != nil {
		return err
	}
	return nil
}

// PublishComExampleHelloGreetTicks publishes com.example.hello.greet.ticks to its subscribers.
func PublishComExampleHelloGreetTicks(p *pane.Provider, data HelloResult) error {
	raw, err := json.Marshal(data)
	if err != nil {
		return err
	}
	return p.Publish(EventComExampleHelloGreetTicks, raw) // validated against Catalog
}
