// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.1.0 (SHA-256 799583cb88d70602efe4f5bd10115887380c31edaca71fdec7d2be466bb7673a).

package hellopane

import pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"

// ValidateEndpoint checks a decoded JSON value (pane.DecodeValue)
// against types.Endpoint.
func ValidateEndpoint(v any) error { return validateEndpoint(v, "") }

func validateEndpoint(v any, path string) error {
	{
		o1, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o1, path, "kind"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o1, path, "kind", "path", "url"); err != nil {
			return err
		}
		if x2, ok := o1["kind"]; ok {
			if err := validateEndpointKind(x2, pane.Field(path, "kind")); err != nil {
				return err
			}
		}
		if x3, ok := o1["path"]; ok {
			if x3 != nil {
				if err := pane.CheckString(x3, pane.Field(path, "path")); err != nil {
					return err
				}
			}
		}
		if x4, ok := o1["url"]; ok {
			if x4 != nil {
				if err := pane.CheckString(x4, pane.Field(path, "url")); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// ValidateEndpointKind checks a decoded JSON value (pane.DecodeValue)
// against types.EndpointKind.
func ValidateEndpointKind(v any) error { return validateEndpointKind(v, "") }

func validateEndpointKind(v any, path string) error {
	if err := pane.CheckString(v, path, "ws", "unix"); err != nil {
		return err
	}
	return nil
}

// ValidateGitDiff checks a decoded JSON value (pane.DecodeValue)
// against types.GitDiff.
func ValidateGitDiff(v any) error { return validateGitDiff(v, "") }

func validateGitDiff(v any, path string) error {
	{
		o5, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o5, path, "files"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o5, path, "files"); err != nil {
			return err
		}
		if x6, ok := o5["files"]; ok {
			{
				a7, err := pane.AsArray(x6, pane.Field(path, "files"))
				if err != nil {
					return err
				}
				for i8, x9 := range a7 {
					if err := validateGitDiffFile(x9, pane.Index(pane.Field(path, "files"), i8)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateGitDiffFile checks a decoded JSON value (pane.DecodeValue)
// against types.GitDiffFile.
func ValidateGitDiffFile(v any) error { return validateGitDiffFile(v, "") }

func validateGitDiffFile(v any, path string) error {
	{
		o10, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o10, path, "additions", "deletions", "path"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o10, path, "additions", "deletions", "patch", "path"); err != nil {
			return err
		}
		if x11, ok := o10["additions"]; ok {
			if err := pane.CheckUint(x11, pane.Field(path, "additions"), nil); err != nil {
				return err
			}
		}
		if x12, ok := o10["deletions"]; ok {
			if err := pane.CheckUint(x12, pane.Field(path, "deletions"), nil); err != nil {
				return err
			}
		}
		if x13, ok := o10["patch"]; ok {
			if x13 != nil {
				if err := pane.CheckString(x13, pane.Field(path, "patch")); err != nil {
					return err
				}
			}
		}
		if x14, ok := o10["path"]; ok {
			if err := pane.CheckString(x14, pane.Field(path, "path")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateGitDiffParams checks a decoded JSON value (pane.DecodeValue)
// against types.GitDiffParams.
func ValidateGitDiffParams(v any) error { return validateGitDiffParams(v, "") }

func validateGitDiffParams(v any, path string) error {
	{
		o15, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o15, path, "cwd"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o15, path, "base", "cwd", "include_patch"); err != nil {
			return err
		}
		if x16, ok := o15["base"]; ok {
			if x16 != nil {
				if err := pane.CheckString(x16, pane.Field(path, "base")); err != nil {
					return err
				}
			}
		}
		if x17, ok := o15["cwd"]; ok {
			if err := pane.CheckString(x17, pane.Field(path, "cwd")); err != nil {
				return err
			}
		}
		if x18, ok := o15["include_patch"]; ok {
			if err := pane.CheckBool(x18, pane.Field(path, "include_patch")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateGitFileStatus checks a decoded JSON value (pane.DecodeValue)
// against types.GitFileStatus.
func ValidateGitFileStatus(v any) error { return validateGitFileStatus(v, "") }

func validateGitFileStatus(v any, path string) error {
	{
		o19, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o19, path, "index", "path", "worktree"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o19, path, "index", "path", "worktree"); err != nil {
			return err
		}
		if x20, ok := o19["index"]; ok {
			if err := pane.CheckString(x20, pane.Field(path, "index")); err != nil {
				return err
			}
		}
		if x21, ok := o19["path"]; ok {
			if err := pane.CheckString(x21, pane.Field(path, "path")); err != nil {
				return err
			}
		}
		if x22, ok := o19["worktree"]; ok {
			if err := pane.CheckString(x22, pane.Field(path, "worktree")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateGitStatus checks a decoded JSON value (pane.DecodeValue)
// against types.GitStatus.
func ValidateGitStatus(v any) error { return validateGitStatus(v, "") }

func validateGitStatus(v any, path string) error {
	{
		o23, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o23, path, "branch", "files"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o23, path, "branch", "files"); err != nil {
			return err
		}
		if x24, ok := o23["branch"]; ok {
			if x24 != nil {
				if err := pane.CheckString(x24, pane.Field(path, "branch")); err != nil {
					return err
				}
			}
		}
		if x25, ok := o23["files"]; ok {
			{
				a26, err := pane.AsArray(x25, pane.Field(path, "files"))
				if err != nil {
					return err
				}
				for i27, x28 := range a26 {
					if err := validateGitFileStatus(x28, pane.Index(pane.Field(path, "files"), i27)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateGitStatusParams checks a decoded JSON value (pane.DecodeValue)
// against types.GitStatusParams.
func ValidateGitStatusParams(v any) error { return validateGitStatusParams(v, "") }

func validateGitStatusParams(v any, path string) error {
	{
		o29, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o29, path, "cwd"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o29, path, "cwd"); err != nil {
			return err
		}
		if x30, ok := o29["cwd"]; ok {
			if err := pane.CheckString(x30, pane.Field(path, "cwd")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloEventRef checks a decoded JSON value (pane.DecodeValue)
// against types.HelloEventRef.
func ValidateHelloEventRef(v any) error { return validateHelloEventRef(v, "") }

func validateHelloEventRef(v any, path string) error {
	{
		o31, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o31, path, "name", "scope"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o31, path, "name", "scope"); err != nil {
			return err
		}
		if x32, ok := o31["name"]; ok {
			if err := pane.CheckString(x32, pane.Field(path, "name")); err != nil {
				return err
			}
		}
		if x33, ok := o31["scope"]; ok {
			if err := pane.CheckString(x33, pane.Field(path, "scope")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloIr checks a decoded JSON value (pane.DecodeValue)
// against types.HelloIr.
func ValidateHelloIr(v any) error { return validateHelloIr(v, "") }

func validateHelloIr(v any, path string) error {
	{
		o34, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o34, path, "sha256", "version"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o34, path, "sha256", "version"); err != nil {
			return err
		}
		if x35, ok := o34["sha256"]; ok {
			if err := pane.CheckString(x35, pane.Field(path, "sha256")); err != nil {
				return err
			}
		}
		if x36, ok := o34["version"]; ok {
			if err := pane.CheckString(x36, pane.Field(path, "version")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloOpRef checks a decoded JSON value (pane.DecodeValue)
// against types.HelloOpRef.
func ValidateHelloOpRef(v any) error { return validateHelloOpRef(v, "") }

func validateHelloOpRef(v any, path string) error {
	{
		o37, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o37, path, "kind", "name", "scope"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o37, path, "kind", "name", "scope"); err != nil {
			return err
		}
		if x38, ok := o37["kind"]; ok {
			if err := pane.CheckString(x38, pane.Field(path, "kind")); err != nil {
				return err
			}
		}
		if x39, ok := o37["name"]; ok {
			if err := pane.CheckString(x39, pane.Field(path, "name")); err != nil {
				return err
			}
		}
		if x40, ok := o37["scope"]; ok {
			if err := pane.CheckString(x40, pane.Field(path, "scope")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloParams checks a decoded JSON value (pane.DecodeValue)
// against types.HelloParams.
func ValidateHelloParams(v any) error { return validateHelloParams(v, "") }

func validateHelloParams(v any, path string) error {
	{
		o41, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o41, path, "name"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o41, path, "name"); err != nil {
			return err
		}
		if x42, ok := o41["name"]; ok {
			if err := pane.CheckString(x42, pane.Field(path, "name")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloResult checks a decoded JSON value (pane.DecodeValue)
// against types.HelloResult.
func ValidateHelloResult(v any) error { return validateHelloResult(v, "") }

func validateHelloResult(v any, path string) error {
	{
		o43, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o43, path, "message"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o43, path, "message"); err != nil {
			return err
		}
		if x44, ok := o43["message"]; ok {
			if err := pane.CheckString(x44, pane.Field(path, "message")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateInterfaceListing checks a decoded JSON value (pane.DecodeValue)
// against types.InterfaceListing.
func ValidateInterfaceListing(v any) error { return validateInterfaceListing(v, "") }

func validateInterfaceListing(v any, path string) error {
	{
		o45, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o45, path, "name", "providers", "version"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o45, path, "name", "providers", "version"); err != nil {
			return err
		}
		if x46, ok := o45["name"]; ok {
			if err := pane.CheckString(x46, pane.Field(path, "name")); err != nil {
				return err
			}
		}
		if x47, ok := o45["providers"]; ok {
			{
				a48, err := pane.AsArray(x47, pane.Field(path, "providers"))
				if err != nil {
					return err
				}
				for i49, x50 := range a48 {
					if err := validateProviderInfo(x50, pane.Index(pane.Field(path, "providers"), i49)); err != nil {
						return err
					}
				}
			}
		}
		if x51, ok := o45["version"]; ok {
			if err := pane.CheckUint(x51, pane.Field(path, "version"), pane.U64(4294967295)); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateInterfacesListParams checks a decoded JSON value (pane.DecodeValue)
// against types.InterfacesListParams.
func ValidateInterfacesListParams(v any) error { return validateInterfacesListParams(v, "") }

func validateInterfacesListParams(v any, path string) error {
	{
		o52, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.OnlyFields(o52, path, "name"); err != nil {
			return err
		}
		if x53, ok := o52["name"]; ok {
			if x53 != nil {
				if err := pane.CheckString(x53, pane.Field(path, "name")); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// ValidateInterfacesListResult checks a decoded JSON value (pane.DecodeValue)
// against types.InterfacesListResult.
func ValidateInterfacesListResult(v any) error { return validateInterfacesListResult(v, "") }

func validateInterfacesListResult(v any, path string) error {
	{
		o54, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o54, path, "interfaces"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o54, path, "interfaces"); err != nil {
			return err
		}
		if x55, ok := o54["interfaces"]; ok {
			{
				a56, err := pane.AsArray(x55, pane.Field(path, "interfaces"))
				if err != nil {
					return err
				}
				for i57, x58 := range a56 {
					if err := validateInterfaceListing(x58, pane.Index(pane.Field(path, "interfaces"), i57)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidatePageEngine checks a decoded JSON value (pane.DecodeValue)
// against types.PageEngine.
func ValidatePageEngine(v any) error { return validatePageEngine(v, "") }

func validatePageEngine(v any, path string) error {
	if err := pane.CheckString(v, path, "webkit", "cef", "browser"); err != nil {
		return err
	}
	return nil
}

// ValidatePageManifest checks a decoded JSON value (pane.DecodeValue)
// against types.PageManifest.
func ValidatePageManifest(v any) error { return validatePageManifest(v, "") }

func validatePageManifest(v any, path string) error {
	{
		o59, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o59, path, "entry", "id", "namespace", "provider", "route"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o59, path, "consumes", "engines", "entry", "id", "namespace", "provider", "route", "scopes"); err != nil {
			return err
		}
		if x60, ok := o59["consumes"]; ok {
			{
				a61, err := pane.AsArray(x60, pane.Field(path, "consumes"))
				if err != nil {
					return err
				}
				for i62, x63 := range a61 {
					if err := pane.CheckString(x63, pane.Index(pane.Field(path, "consumes"), i62)); err != nil {
						return err
					}
				}
			}
		}
		if x64, ok := o59["engines"]; ok {
			{
				a65, err := pane.AsArray(x64, pane.Field(path, "engines"))
				if err != nil {
					return err
				}
				for i66, x67 := range a65 {
					if err := validatePageEngine(x67, pane.Index(pane.Field(path, "engines"), i66)); err != nil {
						return err
					}
				}
			}
		}
		if x68, ok := o59["entry"]; ok {
			if err := pane.CheckString(x68, pane.Field(path, "entry")); err != nil {
				return err
			}
		}
		if x69, ok := o59["id"]; ok {
			if err := pane.CheckString(x69, pane.Field(path, "id")); err != nil {
				return err
			}
		}
		if x70, ok := o59["namespace"]; ok {
			if err := pane.CheckString(x70, pane.Field(path, "namespace")); err != nil {
				return err
			}
		}
		if x71, ok := o59["provider"]; ok {
			if err := validatePageProvider(x71, pane.Field(path, "provider")); err != nil {
				return err
			}
		}
		if x72, ok := o59["route"]; ok {
			if err := pane.CheckString(x72, pane.Field(path, "route")); err != nil {
				return err
			}
		}
		if x73, ok := o59["scopes"]; ok {
			{
				a74, err := pane.AsArray(x73, pane.Field(path, "scopes"))
				if err != nil {
					return err
				}
				for i75, x76 := range a74 {
					if err := pane.CheckString(x76, pane.Index(pane.Field(path, "scopes"), i75)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidatePageProvider checks a decoded JSON value (pane.DecodeValue)
// against types.PageProvider.
func ValidatePageProvider(v any) error { return validatePageProvider(v, "") }

func validatePageProvider(v any, path string) error {
	{
		o77, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o77, path, "kind"); err != nil {
			return err
		}
		switch t78 := o77["kind"]; t78 {
		case "daemon-module":
			{
				o79, err := pane.AsObject(v, path)
				if err != nil {
					return err
				}
				if err := pane.RequireFields(o79, path, "kind"); err != nil {
					return err
				}
				if err := pane.OnlyFields(o79, path, "kind"); err != nil {
					return err
				}
				if x80, ok := o79["kind"]; ok {
					if err := pane.CheckString(x80, pane.Field(path, "kind"), "daemon-module"); err != nil {
						return err
					}
				}
			}
		case "process":
			{
				o81, err := pane.AsObject(v, path)
				if err != nil {
					return err
				}
				if err := pane.RequireFields(o81, path, "command", "kind"); err != nil {
					return err
				}
				if err := pane.OnlyFields(o81, path, "args", "command", "kind"); err != nil {
					return err
				}
				if x82, ok := o81["args"]; ok {
					{
						a83, err := pane.AsArray(x82, pane.Field(path, "args"))
						if err != nil {
							return err
						}
						for i84, x85 := range a83 {
							if err := pane.CheckString(x85, pane.Index(pane.Field(path, "args"), i84)); err != nil {
								return err
							}
						}
					}
				}
				if x86, ok := o81["command"]; ok {
					if err := pane.CheckString(x86, pane.Field(path, "command")); err != nil {
						return err
					}
				}
				if x87, ok := o81["kind"]; ok {
					if err := pane.CheckString(x87, pane.Field(path, "kind"), "process"); err != nil {
						return err
					}
				}
			}
		case "external":
			{
				o88, err := pane.AsObject(v, path)
				if err != nil {
					return err
				}
				if err := pane.RequireFields(o88, path, "kind"); err != nil {
					return err
				}
				if err := pane.OnlyFields(o88, path, "kind"); err != nil {
					return err
				}
				if x89, ok := o88["kind"]; ok {
					if err := pane.CheckString(x89, pane.Field(path, "kind"), "external"); err != nil {
						return err
					}
				}
			}
		default:
			return pane.CheckString(t78, pane.Field(path, "kind"), "daemon-module", "process", "external")
		}
	}
	return nil
}

// ValidatePagesListParams checks a decoded JSON value (pane.DecodeValue)
// against types.PagesListParams.
func ValidatePagesListParams(v any) error { return validatePagesListParams(v, "") }

func validatePagesListParams(v any, path string) error {
	{
		o90, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.OnlyFields(o90, path); err != nil {
			return err
		}
	}
	return nil
}

// ValidatePagesListResult checks a decoded JSON value (pane.DecodeValue)
// against types.PagesListResult.
func ValidatePagesListResult(v any) error { return validatePagesListResult(v, "") }

func validatePagesListResult(v any, path string) error {
	{
		o91, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o91, path, "pages"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o91, path, "pages"); err != nil {
			return err
		}
		if x92, ok := o91["pages"]; ok {
			{
				a93, err := pane.AsArray(x92, pane.Field(path, "pages"))
				if err != nil {
					return err
				}
				for i94, x95 := range a93 {
					if err := validatePageManifest(x95, pane.Index(pane.Field(path, "pages"), i94)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateProviderHello checks a decoded JSON value (pane.DecodeValue)
// against types.ProviderHello.
func ValidateProviderHello(v any) error { return validateProviderHello(v, "") }

func validateProviderHello(v any, path string) error {
	{
		o96, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o96, path, "app", "ir", "namespaces", "ops", "proto"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o96, path, "app", "credential", "endpoints", "events", "interfaces", "ir", "namespaces", "ops", "proto"); err != nil {
			return err
		}
		if x97, ok := o96["app"]; ok {
			if err := pane.CheckString(x97, pane.Field(path, "app")); err != nil {
				return err
			}
		}
		if x98, ok := o96["credential"]; ok {
			if x98 != nil {
				if err := pane.CheckString(x98, pane.Field(path, "credential")); err != nil {
					return err
				}
			}
		}
		if x99, ok := o96["endpoints"]; ok {
			{
				a100, err := pane.AsArray(x99, pane.Field(path, "endpoints"))
				if err != nil {
					return err
				}
				for i101, x102 := range a100 {
					if err := validateEndpoint(x102, pane.Index(pane.Field(path, "endpoints"), i101)); err != nil {
						return err
					}
				}
			}
		}
		if x103, ok := o96["events"]; ok {
			{
				a104, err := pane.AsArray(x103, pane.Field(path, "events"))
				if err != nil {
					return err
				}
				for i105, x106 := range a104 {
					if err := validateHelloEventRef(x106, pane.Index(pane.Field(path, "events"), i105)); err != nil {
						return err
					}
				}
			}
		}
		if x107, ok := o96["interfaces"]; ok {
			{
				a108, err := pane.AsArray(x107, pane.Field(path, "interfaces"))
				if err != nil {
					return err
				}
				for i109, x110 := range a108 {
					if err := pane.CheckString(x110, pane.Index(pane.Field(path, "interfaces"), i109)); err != nil {
						return err
					}
				}
			}
		}
		if x111, ok := o96["ir"]; ok {
			if err := validateHelloIr(x111, pane.Field(path, "ir")); err != nil {
				return err
			}
		}
		if x112, ok := o96["namespaces"]; ok {
			{
				a113, err := pane.AsArray(x112, pane.Field(path, "namespaces"))
				if err != nil {
					return err
				}
				for i114, x115 := range a113 {
					if err := pane.CheckString(x115, pane.Index(pane.Field(path, "namespaces"), i114)); err != nil {
						return err
					}
				}
			}
		}
		if x116, ok := o96["ops"]; ok {
			{
				a117, err := pane.AsArray(x116, pane.Field(path, "ops"))
				if err != nil {
					return err
				}
				for i118, x119 := range a117 {
					if err := validateHelloOpRef(x119, pane.Index(pane.Field(path, "ops"), i118)); err != nil {
						return err
					}
				}
			}
		}
		if x120, ok := o96["proto"]; ok {
			if err := pane.CheckString(x120, pane.Field(path, "proto")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateProviderInfo checks a decoded JSON value (pane.DecodeValue)
// against types.ProviderInfo.
func ValidateProviderInfo(v any) error { return validateProviderInfo(v, "") }

func validateProviderInfo(v any, path string) error {
	{
		o121, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o121, path, "app_id", "endpoints", "namespace"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o121, path, "app_id", "endpoints", "namespace"); err != nil {
			return err
		}
		if x122, ok := o121["app_id"]; ok {
			if err := pane.CheckString(x122, pane.Field(path, "app_id")); err != nil {
				return err
			}
		}
		if x123, ok := o121["endpoints"]; ok {
			{
				a124, err := pane.AsArray(x123, pane.Field(path, "endpoints"))
				if err != nil {
					return err
				}
				for i125, x126 := range a124 {
					if err := validateEndpoint(x126, pane.Index(pane.Field(path, "endpoints"), i125)); err != nil {
						return err
					}
				}
			}
		}
		if x127, ok := o121["namespace"]; ok {
			if err := pane.CheckString(x127, pane.Field(path, "namespace")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateProviderWelcome checks a decoded JSON value (pane.DecodeValue)
// against types.ProviderWelcome.
func ValidateProviderWelcome(v any) error { return validateProviderWelcome(v, "") }

func validateProviderWelcome(v any, path string) error {
	{
		o128, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o128, path, "provider", "router_key"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o128, path, "provider", "router_key"); err != nil {
			return err
		}
		if x129, ok := o128["provider"]; ok {
			if err := pane.CheckString(x129, pane.Field(path, "provider")); err != nil {
				return err
			}
		}
		if x130, ok := o128["router_key"]; ok {
			if err := pane.CheckString(x130, pane.Field(path, "router_key")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateResolveParams checks a decoded JSON value (pane.DecodeValue)
// against types.ResolveParams.
func ValidateResolveParams(v any) error { return validateResolveParams(v, "") }

func validateResolveParams(v any, path string) error {
	{
		o131, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o131, path, "namespace"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o131, path, "namespace"); err != nil {
			return err
		}
		if x132, ok := o131["namespace"]; ok {
			if err := pane.CheckString(x132, pane.Field(path, "namespace")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateResolveResult checks a decoded JSON value (pane.DecodeValue)
// against types.ResolveResult.
func ValidateResolveResult(v any) error { return validateResolveResult(v, "") }

func validateResolveResult(v any, path string) error {
	{
		o133, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o133, path, "app_id", "endpoint", "exp", "ir", "namespace", "token"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o133, path, "app_id", "endpoint", "exp", "ir", "namespace", "token"); err != nil {
			return err
		}
		if x134, ok := o133["app_id"]; ok {
			if err := pane.CheckString(x134, pane.Field(path, "app_id")); err != nil {
				return err
			}
		}
		if x135, ok := o133["endpoint"]; ok {
			if err := validateEndpoint(x135, pane.Field(path, "endpoint")); err != nil {
				return err
			}
		}
		if x136, ok := o133["exp"]; ok {
			if x136 != nil {
				if err := pane.CheckUint(x136, pane.Field(path, "exp"), nil); err != nil {
					return err
				}
			}
		}
		if x137, ok := o133["ir"]; ok {
			if err := pane.CheckString(x137, pane.Field(path, "ir")); err != nil {
				return err
			}
		}
		if x138, ok := o133["namespace"]; ok {
			if err := pane.CheckString(x138, pane.Field(path, "namespace")); err != nil {
				return err
			}
		}
		if x139, ok := o133["token"]; ok {
			if x139 != nil {
				if err := pane.CheckString(x139, pane.Field(path, "token")); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// ValidateTokenRefreshParams checks a decoded JSON value (pane.DecodeValue)
// against types.TokenRefreshParams.
func ValidateTokenRefreshParams(v any) error { return validateTokenRefreshParams(v, "") }

func validateTokenRefreshParams(v any, path string) error {
	{
		o140, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o140, path, "token"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o140, path, "token"); err != nil {
			return err
		}
		if x141, ok := o140["token"]; ok {
			if err := pane.CheckString(x141, pane.Field(path, "token")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateTokenRefreshResult checks a decoded JSON value (pane.DecodeValue)
// against types.TokenRefreshResult.
func ValidateTokenRefreshResult(v any) error { return validateTokenRefreshResult(v, "") }

func validateTokenRefreshResult(v any, path string) error {
	{
		o142, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o142, path, "exp", "token"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o142, path, "exp", "token"); err != nil {
			return err
		}
		if x143, ok := o142["exp"]; ok {
			if err := pane.CheckUint(x143, pane.Field(path, "exp"), nil); err != nil {
				return err
			}
		}
		if x144, ok := o142["token"]; ok {
			if err := pane.CheckString(x144, pane.Field(path, "token")); err != nil {
				return err
			}
		}
	}
	return nil
}

// Validators maps each IR type name to its validator (for conformance vectors
// and dynamic checks).
var Validators = map[string]func(any) error{
	"Endpoint":             ValidateEndpoint,
	"EndpointKind":         ValidateEndpointKind,
	"GitDiff":              ValidateGitDiff,
	"GitDiffFile":          ValidateGitDiffFile,
	"GitDiffParams":        ValidateGitDiffParams,
	"GitFileStatus":        ValidateGitFileStatus,
	"GitStatus":            ValidateGitStatus,
	"GitStatusParams":      ValidateGitStatusParams,
	"HelloEventRef":        ValidateHelloEventRef,
	"HelloIr":              ValidateHelloIr,
	"HelloOpRef":           ValidateHelloOpRef,
	"HelloParams":          ValidateHelloParams,
	"HelloResult":          ValidateHelloResult,
	"InterfaceListing":     ValidateInterfaceListing,
	"InterfacesListParams": ValidateInterfacesListParams,
	"InterfacesListResult": ValidateInterfacesListResult,
	"PageEngine":           ValidatePageEngine,
	"PageManifest":         ValidatePageManifest,
	"PageProvider":         ValidatePageProvider,
	"PagesListParams":      ValidatePagesListParams,
	"PagesListResult":      ValidatePagesListResult,
	"ProviderHello":        ValidateProviderHello,
	"ProviderInfo":         ValidateProviderInfo,
	"ProviderWelcome":      ValidateProviderWelcome,
	"ResolveParams":        ValidateResolveParams,
	"ResolveResult":        ValidateResolveResult,
	"TokenRefreshParams":   ValidateTokenRefreshParams,
	"TokenRefreshResult":   ValidateTokenRefreshResult,
}
