// Generates the typed TS client, types and validators from the pane protocol IR. Pure: takes
// the IR, returns file contents. scripts/pane-protocol-codegen.ts writes or checks them.

import { IrError, parseIr, type Ir, type IrOp, type JsonSchema } from "./ir";
import { docComment, refName, renderType, ValidatorBuilder } from "./schema";

export interface GenerateOptions {
  /** Shown in the header; keep it repo-relative so --check output is stable across checkouts. */
  source: string;
}

export type GeneratedFiles = Record<"types.ts" | "validators.ts" | "client.ts" | "index.ts", string>;

function header(ir: Ir, options: GenerateOptions): string {
  return [
    `// @generated by webviews/scripts/pane-protocol-codegen.ts from ${options.source}`,
    `// IR version ${ir.version}. Do not edit; rerun the codegen.`,
    "",
  ].join("\n");
}

function pascal(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function camel(name: string): string {
  const value = pascal(name);
  return value ? value[0].toLowerCase() + value.slice(1) : value;
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

interface SplitName {
  namespace: string;
  family: string;
  member: string;
}

/** Splits `<ns>.<family>.<rest>` using the IR's namespace list (longest match wins). */
function splitName(name: string, namespaces: string[], kind: "op" | "event"): SplitName {
  const ns = namespaces.filter((candidate) => name.startsWith(`${candidate}.`)).sort((a, b) => b.length - a.length)[0];
  if (!ns) throw new IrError(`${kind} ${name} is outside every declared namespace`);
  const rest = name.slice(ns.length + 1).split(".");
  if (rest.some((part) => !/^[a-z][a-z0-9_]*$/.test(part))) {
    throw new IrError(`${kind} ${name}: segments after the namespace must be lower_snake_case`);
  }
  // A verb may nest (`cmux.router.token.refresh`); the client nests the same way.
  if (rest.length < 2) {
    throw new IrError(`${kind} ${name} must be <namespace>.<family>.<${kind === "op" ? "verb" : "event"}>`);
  }
  return { namespace: ns, family: rest[0], member: rest.slice(1).join(".") };
}

/** Uses a referenced type's name, or names an inline schema after its op. */
function typeRef(schema: JsonSchema, fallback: string, ir: Ir, inline: Map<string, JsonSchema>, where: string): string {
  if (typeof schema === "object" && typeof schema.$ref === "string" && Object.keys(schema).length === 1) {
    return refName(schema.$ref, ir.types, where);
  }
  if (fallback in ir.types || inline.has(fallback)) throw new IrError(`${where}: generated name ${fallback} collides`);
  inline.set(fallback, schema);
  return fallback;
}

interface Resolved {
  ir: Ir;
  inline: Map<string, JsonSchema>;
  ops: Array<{
    name: string;
    split: SplitName;
    params: string;
    result: string;
    kind: string;
    scope: string;
    owner: string;
    aliases: string[];
    errors: string[];
    meta: Pick<IrOp, "paths" | "mcp" | "cli" | "secret_output">;
  }>;
  events: Array<{ name: string; split: SplitName; data: string; scope: string }>;
}

function resolve(ir: Ir): Resolved {
  const namespaces = ir.namespaces.map((ns) => ns.name);
  const inline = new Map<string, JsonSchema>();
  const ops = ir.ops.map((op) => {
    const base = pascal(op.name);
    return {
      name: op.name,
      split: splitName(op.name, namespaces, "op"),
      params: typeRef(op.params, `${base}Params`, ir, inline, `op ${op.name} params`),
      result: typeRef(op.result, `${base}Result`, ir, inline, `op ${op.name} result`),
      kind: op.kind,
      scope: op.scope,
      owner: op.owner,
      aliases: op.aliases,
      errors: op.errors,
      meta: { paths: op.paths, mcp: op.mcp, ...(op.cli ? { cli: op.cli } : {}), secret_output: op.secret_output },
    };
  });
  const events = ir.events.map((event) => ({
    name: event.name,
    split: splitName(event.name, namespaces, "event"),
    data: typeRef(event.data, `${pascal(event.name)}Data`, ir, inline, `event ${event.name} data`),
    scope: event.scope,
  }));
  return { ir, inline, ops, events };
}

function allTypes(resolved: Resolved): Array<[string, JsonSchema]> {
  return [...Object.entries(resolved.ir.types), ...resolved.inline.entries()];
}

function generateTypes(resolved: Resolved): string {
  const types = resolved.ir.types;
  const blocks = allTypes(resolved).map(([name, schema]) => {
    const rendered = renderType(schema, types, `types.${name}`);
    const declaration =
      rendered.startsWith("{\n") && !rendered.includes("} &")
        ? `export interface ${name} ${rendered}`
        : `export type ${name} = ${rendered};`;
    return docComment(schema, "") + declaration;
  });
  return `${blocks.join("\n\n")}\n`;
}

/** Validator table rows for every op name and alias. */
function withAliases(resolved: Resolved, pick: (op: Resolved["ops"][number]) => string): Array<[string, string]> {
  return resolved.ops.flatMap((op) => [op.name, ...op.aliases].map((name): [string, string] => [name, pick(op)]));
}

function generateValidators(resolved: Resolved): string {
  const builder = new ValidatorBuilder(resolved.ir.types);
  const functions: string[] = [];
  const publics: string[] = [];
  for (const [name, schema] of allTypes(resolved)) {
    const body = builder.compile(schema, "value", "path", "errs", `types.${name}`, "  ");
    functions.push(
      `function check${name}(value: unknown, path: string, errs: ValidationIssue[]): void {\n${body || "  void value;\n  void path;\n  void errs;\n"}}`,
    );
    publics.push(
      [
        `export function validate${name}(value: unknown): ValidationIssue[] {`,
        `  const errs: ValidationIssue[] = [];`,
        `  check${name}(value, "", errs);`,
        `  return errs;`,
        `}`,
        `export function is${name}(value: unknown): value is T.${name} {`,
        `  return validate${name}(value).length === 0;`,
        `}`,
      ].join("\n"),
    );
  }
  const table = (entries: Array<[string, string]>) =>
    `new Map<string, (value: unknown) => ValidationIssue[]>([\n${entries
      .map(([key, type]) => `  [${JSON.stringify(key)}, validate${type}],`)
      .join("\n")}\n])`;
  const lines = [
    `import type { SessionSchema } from "../session";`,
    `import type { ValidationIssue } from "../errors";`,
    `import type * as T from "./types";`,
    "",
  ];
  if (builder.usesIsObject) {
    lines.push(
      `function isObject(value: unknown): value is Record<string, unknown> {`,
      `  return typeof value === "object" && value !== null && !Array.isArray(value);`,
      `}`,
      "",
    );
  }
  lines.push(...builder.constants, ...(builder.constants.length > 0 ? [""] : []));
  lines.push(functions.join("\n\n"), "", publics.join("\n\n"), "");
  lines.push(
    `const PARAMS = ${table(withAliases(resolved, (op) => op.params))};`,
    `const RESULTS = ${table(withAliases(resolved, (op) => op.result))};`,
    `const EVENTS = ${table(resolved.events.map((event) => [event.name, event.data]))};`,
    "",
    `/** Incoming-value validators for Session; null means the IR has no such op or event. */`,
    `export const schema: SessionSchema = {`,
    `  validateParams: (op, value) => PARAMS.get(op)?.(value) ?? null,`,
    `  validateResult: (op, value) => RESULTS.get(op)?.(value) ?? null,`,
    `  validateEvent: (event, value) => EVENTS.get(event)?.(value) ?? null,`,
    `};`,
    "",
  );
  return lines.join("\n");
}

interface Tree {
  [key: string]: Tree | string;
}

function insert(tree: Tree, path: string[], leaf: string, name: string): void {
  let node = tree;
  for (const key of path.slice(0, -1)) {
    const next = node[key];
    if (typeof next === "string") throw new IrError(`${name}: client member ${key} collides with an op`);
    node = next ?? (node[key] = {});
  }
  const last = path.at(-1)!;
  if (last in node) throw new IrError(`${name}: client member ${path.join(".")} collides`);
  node[last] = leaf;
}

function renderTree(tree: Tree, indent: string): string {
  const inner = `${indent}  `;
  const entries = Object.entries(tree).map(([key, value]) => {
    if (typeof value !== "string") return `${inner}${propertyKey(key)}: ${renderTree(value, inner)},`;
    // Leaves are "<doc comment>\n<arrow function>"; the doc goes above the member.
    const [doc, expr] = value.split("\n");
    return `${inner}${doc}\n${inner}${propertyKey(key)}: ${expr},`;
  });
  return `{\n${entries.join("\n")}\n${indent}}`;
}

function opSummary(op: Resolved["ops"][number], errors: string): string {
  const parts = [`${op.kind}, scope ${op.scope}.`, `Errors: ${errors}.`];
  if (op.meta.cli) parts.push(`CLI: \`${op.meta.cli.path}\`${op.meta.cli.visible ? "" : " (hidden)"}.`);
  parts.push(`MCP: ${op.meta.mcp.expose}${op.meta.mcp.group ? ` (${op.meta.mcp.group})` : ""}.`);
  if (op.meta.paths.length > 0) parts.push(`Paths: ${op.meta.paths.join(", ")}.`);
  if (op.meta.secret_output) parts.push("Secret output: never offered to agents.");
  return parts.join(" ");
}

function generateClient(resolved: Resolved): string {
  const tree: Tree = {};
  const opMap: string[] = [];
  const eventMap: string[] = [];
  for (const op of resolved.ops) {
    const path = [...op.split.namespace.split("."), camel(op.split.family), ...op.split.member.split(".").map(camel)];
    const errors = op.errors.length > 0 ? op.errors.join(", ") : "none declared";
    insert(
      tree,
      path,
      [
        `/** ${opSummary(op, errors)} */`,
        `(params: T.${op.params}, options?: CallOptions): Promise<T.${op.result}> => call(${JSON.stringify(op.name)}, params, options)`,
      ].join("\n"),
      op.name,
    );
    const errorType = op.errors.length > 0 ? op.errors.map((code) => JSON.stringify(code)).join(" | ") : "never";
    opMap.push(
      `  ${JSON.stringify(op.name)}: { params: T.${op.params}; result: T.${op.result}; error: ${errorType} };`,
    );
  }
  for (const event of resolved.events) {
    const path = [...event.split.namespace.split("."), camel(event.split.family), "events", camel(event.split.member)];
    insert(
      tree,
      path,
      [
        `/** scope ${event.scope}. */`,
        `(options: SubscribeOptions<T.${event.data}>): Promise<Subscription> => subscribe(${JSON.stringify(event.name)}, options)`,
      ].join("\n"),
      event.name,
    );
    eventMap.push(`  ${JSON.stringify(event.name)}: T.${event.data};`);
  }
  // Field order is fixed here, not taken from the IR, so the generated bytes do not depend on
  // how emit-ir orders keys.
  const ops = resolved.ops.map((op) => {
    const entry = {
      name: op.name,
      owner: op.owner,
      kind: op.kind,
      scope: op.scope,
      aliases: op.aliases,
      errors: op.errors,
      paths: op.meta.paths,
      mcp:
        op.meta.mcp.group === undefined
          ? { expose: op.meta.mcp.expose }
          : { expose: op.meta.mcp.expose, group: op.meta.mcp.group },
      ...(op.meta.cli
        ? {
            cli: {
              path: op.meta.cli.path,
              visible: op.meta.cli.visible,
              ...(op.meta.cli.positional ? { positional: op.meta.cli.positional } : {}),
            },
          }
        : {}),
      secret_output: op.meta.secret_output,
    };
    return `  ${JSON.stringify(entry)},`;
  });
  const interfaces = resolved.ir.interfaces.map((iface) => `  ${JSON.stringify(iface)},`);
  return [
    `import type { CallOptions, Session, SubscribeOptions, Subscription } from "../session";`,
    `import type * as T from "./types";`,
    "",
    `export const IR_VERSION = ${JSON.stringify(resolved.ir.version)};`,
    "",
    `export interface OpMap {`,
    ...opMap,
    `}`,
    "",
    `export interface EventMap {`,
    ...eventMap,
    `}`,
    "",
    `export type OpName = keyof OpMap;`,
    `export type EventName = keyof EventMap;`,
    "",
    `/** Per-op metadata from the IR, for tools that list ops (CLI, MCP, code mode). */`,
    `export interface OpMeta {`,
    `  readonly name: string;`,
    `  /** "first-party" or "app:<id>". */`,
    `  readonly owner: string;`,
    `  /** read | mutation | stream. */`,
    `  readonly kind: string;`,
    `  readonly scope: string;`,
    `  readonly aliases: readonly string[];`,
    `  readonly errors: readonly string[];`,
    `  /** Top-level params that name filesystem paths; the provider confines them to the token's roots. */`,
    `  readonly paths: readonly string[];`,
    `  /** MCP exposure. The tool name is the op name with "." and "-" as "_". */`,
    `  readonly mcp: { readonly expose: "default" | "opt_in" | "never"; readonly group?: string };`,
    `  /** CLI verb relative to the app; absent when the op has no verb. */`,
    `  readonly cli?: { readonly path: string; readonly visible: boolean; readonly positional?: readonly string[] };`,
    `  /** The result can carry a secret; never offer this op to agents. */`,
    `  readonly secret_output: boolean;`,
    `}`,
    "",
    `export const OPS = [`,
    ...ops,
    `] as const satisfies readonly OpMeta[];`,
    "",
    `export const INTERFACES = [`,
    ...interfaces,
    `] as const;`,
    "",
    `/** Typed client over a Session. Results and events are validated by the Session's schema. */`,
    `export function createClient(session: Session) {`,
    `  const call = <K extends OpName>(op: K, params: OpMap[K]["params"], options?: CallOptions) =>`,
    `    session.call(op, params, options) as Promise<OpMap[K]["result"]>;`,
    `  const subscribe = <K extends EventName>(event: K, options: SubscribeOptions<EventMap[K]>) =>`,
    `    session.subscribe<EventMap[K]>(event, options);`,
    `  return ${renderTree({ ...tree }, "  ").replace(/^\{\n/, "{\n    call,\n    subscribe,\n")};`,
    `}`,
    "",
    `export type PaneClient = ReturnType<typeof createClient>;`,
    "",
  ].join("\n");
}

export function generate(rawIr: unknown, options: GenerateOptions): GeneratedFiles {
  const ir = parseIr(rawIr);
  const resolved = resolve(ir);
  const head = header(ir, options);
  return {
    "types.ts": head + "\n" + generateTypes(resolved),
    "validators.ts": head + "\n" + generateValidators(resolved),
    "client.ts": head + "\n" + generateClient(resolved),
    "index.ts":
      head +
      "\n" +
      [`export * from "./types";`, `export * from "./validators";`, `export * from "./client";`, ""].join("\n"),
  };
}
