// Right-click placements of the catalog actions (plans/cmux-next/actions.md).
// Each row is (menu, group, rank[, style][, in: submenu anchor]). Menus list
// groups in `MenuGroup` order; a rank's hundreds are sections inside the
// group (rank / 100, truncated). An action declared with a `surfacePlan`
// in its descriptor keeps its own placements.

nonisolated extension ActionSurfaceCatalog {
    /// Every placement: windows to tabs here, screens to bookmarks in
    /// `ActionSurfaceCatalog+MenusContent.swift`.
    static let placements: [ActionID: [ContextMenuPlacement]] = layoutPlacements.merging(contentPlacements) { $0 + $1 }

    static let layoutPlacements: [ActionID: [ContextMenuPlacement]] = [
        "newTab": [p(.sidebarBackground, .create, 0)],
        "newBrowserWorkspace": [p(.sidebarBackground, .create, 3)],
        "openFolder": [p(.sidebarBackground, .create, 4)],
        "palette.openFolderInVSCodeInline": [p(.workspaceRow, .create, 100, folder: .new)],
        "reopenPreviousSession": [p(.sidebarBackground, .create, 8, folder: .new)],
        "reopenClosedWorkspace": [p(.sidebarBackground, .create, 7, folder: .new)],
        "moveWorkspaceUp": [p(.workspaceRow, .move, 200, folder: .move)],
        "moveWorkspaceDown": [p(.workspaceRow, .move, 201, folder: .move)],
        "palette.moveWorkspaceToTop": [p(.workspaceRow, .move, 202, folder: .move)],
        "moveWorkspaceToWindow": [p(.workspaceRow, .move, 204, folder: .move)],
        "moveWorkspaceToNewWindow": [p(.workspaceRow, .move, 205, folder: .move)],
        "renameWorkspace": [p(.workspaceRow, .identity, 100)],
        "palette.clearWorkspaceName": [p(.workspaceRow, .identity, 100, folder: .options)],
        "editWorkspaceDescription": [p(.workspaceRow, .identity, 101, folder: .options)],
        "palette.clearWorkspaceDescription": [p(.workspaceRow, .identity, 101, folder: .options)],
        "markWorkspaceDone": [p(.workspaceRow, .identity, 103, folder: .options)],
        "palette.workspaceStatus": [p(.workspaceRow, .identity, 102, folder: .options)],
        "palette.addWorkspaceChecklistItem": [p(.workspaceRow, .identity, 120, folder: .options)],
        "palette.openWorkspaceTodoPane": [p(.workspaceRow, .create, 101, folder: .new)],
        "closeWorkspace": [p(.workspaceRow, .close, 504)],
        "palette.closeOtherWorkspaces": [p(.workspaceRow, .close, 500, folder: .close)],
        "palette.closeWorkspacesBelow": [p(.workspaceRow, .close, 502, folder: .close)],
        "palette.closeWorkspacesAbove": [p(.workspaceRow, .close, 503, folder: .close)],
        "palette.toggleWorkspacePin": [p(.workspaceRow, .identity, 110)],
        "palette.markWorkspaceRead": [p(.workspaceRow, .identity, 111, folder: .options)],
        "palette.markWorkspaceUnread": [p(.workspaceRow, .identity, 112, folder: .options)],
        "palette.workspaceColor": [p(.workspaceRow, .identity, 104, folder: .appearance)],
        "palette.workspaceCustomColor": [p(.workspaceRow, .identity, 105, folder: .appearance)],
        "palette.resetWorkspaceColor": [p(.workspaceRow, .identity, 105, folder: .appearance)],
        "reconnectWorkspace": [p(.workspaceRow, .connection, 401, folder: .options)],
        "disconnectWorkspace": [p(.workspaceRow, .connection, 402, folder: .options)],
        "copyWorkspaceSSHError": [p(.workspaceRow, .inspect, 408, folder: .copy)],
        "clearWorkspaceNotifications": [p(.workspaceRow, .identity, 114, folder: .options)],
        "revealWorkspaceInFinder": [p(.workspaceRow, .inspect, 403, folder: .tools)],
        "palette.copyWorkspaceID": [p(.workspaceRow, .inspect, 405, folder: .copy)],
        "palette.copyWorkspaceIDAndRef": [p(.workspaceRow, .inspect, 407, folder: .copy)],
        "palette.copyWorkspaceLink": [p(.workspaceRow, .inspect, 406, folder: .copy)],
        "workspaceGroup.newWorkspace": [p(.workspaceGroup, .create, 0)],
        "workspaceGroup.rename": [p(.workspaceGroup, .identity, 1)],
        "workspaceGroup.togglePin": [p(.workspaceGroup, .identity, 3)],
        "workspaceGroup.markRead": [p(.workspaceGroup, .identity, 100, folder: .options)],
        "workspaceGroup.markUnread": [p(.workspaceGroup, .identity, 101, folder: .options)],
        "workspaceGroup.clearNotifications": [p(.workspaceGroup, .identity, 102, folder: .options)],
        "workspaceGroup.ungroup": [p(.workspaceGroup, .close, 500, folder: .close)],
        "workspaceGroup.delete": [p(.workspaceGroup, .close, 502, folder: .close)],
        "workspaceGroup.editConfig": [p(.workspaceGroup, .inspect, 400, folder: .tools)],
        "saveLayoutTemplate": [p(.workspaceRow, .organize, 210, folder: .group)],
        "palette.layout.open": [p(.workspaceRow, .create, 102, folder: .new)],
        "palette.openWorkspacePullRequests": [p(.workspaceRow, .inspect, 409, folder: .tools)],
        "workspace.newAbove": [p(.workspaceRow, .create, 0, folder: .new)],
        "workspace.newBelow": [p(.workspaceRow, .create, 1)],
        "workspace.newAtTop": [p(.sidebarBackground, .create, 1, folder: .new)],
        "workspace.newAtBottom": [p(.sidebarBackground, .create, 1, folder: .new)],
        "workspace.newInGroup": [p(.workspaceRow, .create, 2, folder: .new)],
        "workspace.newInNewGroup": [p(.workspaceRow, .create, 3, folder: .new)],
        "workspace.newOnMachine": [p(.sidebarBackground, .create, 2, folder: .new)],
        "workspace.newInSameDirectory": [p(.workspaceRow, .create, 3, folder: .new)],
        "workspace.duplicate": [p(.workspaceRow, .create, 4, folder: .new)],
        "workspace.duplicateTerminalsOnly": [p(.workspaceRow, .create, 5, folder: .new)],
        "workspace.setIcon": [p(.workspaceRow, .identity, 106, folder: .appearance)],
        "workspace.clearIcon": [p(.workspaceRow, .identity, 107, folder: .appearance)],
        "workspace.moveToBottom": [p(.workspaceRow, .move, 203, folder: .move)],
        "workspace.moveToNewGroup": [p(.workspaceRow, .organize, 207, folder: .group)],
        "workspace.closeOthersInGroup": [p(.workspaceRow, .close, 501, folder: .close)],
        "workspace.sortByName": [p(.sidebarBackground, .move, 100, folder: .move)],
        "workspace.sortByLastUsed": [p(.sidebarBackground, .move, 101, folder: .move)],
        "workspace.sortByDirectory": [p(.sidebarBackground, .move, 102, folder: .move)],
        "workspaceGroup.collapseAll": [p(.workspaceGroup, .organize, 5, folder: .group), p(.sidebarBackground, .organize, 103, folder: .group)],
        "workspaceGroup.expandAll": [p(.workspaceGroup, .organize, 6, folder: .group), p(.sidebarBackground, .organize, 104, folder: .group)],
        "workspace.copyPath": [p(.workspaceRow, .inspect, 404, folder: .copy)],
        "workspace.mergeInto": [p(.workspaceRow, .move, 211, folder: .move)],
        "pane.moveToNewWorkspace": [p(.pane, .move, 300, folder: .move)],
        "newWorkspaceGroup": [p(.sidebarBackground, .create, 5)],
        "groupSelectedWorkspaces": [p(.workspaceRow, .organize, 205, folder: .group)],
        "toggleFocusedWorkspaceGroupCollapsed": [p(.workspaceGroup, .organize, 4)],
        "moveWorkspaceToGroup": [p(.workspaceRow, .organize, 206, folder: .group)],
        "removeWorkspaceFromGroup": [p(.workspaceRow, .organize, 208, folder: .group)],
        "workspaceGroup.setColor": [p(.workspaceGroup, .identity, 2, .submenu, folder: .appearance)],
        "workspaceGroup.moveUp": [p(.workspaceGroup, .move, 300, folder: .move)],
        "workspaceGroup.moveDown": [p(.workspaceGroup, .move, 301, folder: .move)],
        "workspaceGroup.moveToWindow": [p(.workspaceGroup, .move, 303, folder: .move)],
        "workspaceGroup.closeWorkspaces": [p(.workspaceGroup, .close, 501, folder: .close)],
        "workspaceGroup.moveToNewWindow": [p(.workspaceGroup, .move, 302, folder: .move)],
        "workspaceGroup.color.grey": [p(.workspaceGroup, .identity, 0, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.blue": [p(.workspaceGroup, .identity, 1, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.red": [p(.workspaceGroup, .identity, 2, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.yellow": [p(.workspaceGroup, .identity, 3, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.green": [p(.workspaceGroup, .identity, 4, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.pink": [p(.workspaceGroup, .identity, 5, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.purple": [p(.workspaceGroup, .identity, 6, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.cyan": [p(.workspaceGroup, .identity, 7, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.orange": [p(.workspaceGroup, .identity, 8, in: "workspaceGroup.setColor")],
        "space.new": [p(.sidebarBackground, .create, 6, folder: .new), p(.profile, .create, 300, folder: .new)],
        "space.newWindow": [p(.profile, .create, 0)],
        "space.newWorkspace": [p(.profile, .create, 1)],
        "space.rename": [p(.profile, .identity, 100)],
        "space.setColor": [p(.profile, .identity, 101, .submenu, folder: .appearance)],
        "space.color.grey": [p(.profile, .identity, 0, in: "space.setColor")],
        "space.color.blue": [p(.profile, .identity, 1, in: "space.setColor")],
        "space.color.red": [p(.profile, .identity, 2, in: "space.setColor")],
        "space.color.yellow": [p(.profile, .identity, 3, in: "space.setColor")],
        "space.color.green": [p(.profile, .identity, 4, in: "space.setColor")],
        "space.color.pink": [p(.profile, .identity, 5, in: "space.setColor")],
        "space.color.purple": [p(.profile, .identity, 6, in: "space.setColor")],
        "space.color.cyan": [p(.profile, .identity, 7, in: "space.setColor")],
        "space.color.orange": [p(.profile, .identity, 8, in: "space.setColor")],
        "space.clearColor": [p(.profile, .identity, 100, in: "space.setColor")],
        "space.setIcon": [p(.profile, .identity, 102, folder: .appearance)],
        "space.clearIcon": [p(.profile, .identity, 103, folder: .appearance)],
        "space.setDefaults": [p(.profile, .identity, 106, folder: .options)],
        "space.delete": [p(.profile, .close, 400)],
        "space.moveLeft": [p(.profile, .move, 200, folder: .move)],
        "space.moveRight": [p(.profile, .move, 201, folder: .move)],
        "workspace.moveToSpace": [p(.workspaceRow, .move, 209, folder: .move)],
        "workspace.duplicateToSpace": [p(.workspaceRow, .move, 210, folder: .move)],
        "workspaceGroup.moveToSpace": [p(.workspaceGroup, .move, 304, folder: .move)],
        "space.setTheme": [p(.profile, .identity, 104, .choices, folder: .appearance)],
        "space.clearTheme": [p(.profile, .identity, 105, folder: .appearance)],
        "workspace.setTheme": [p(.workspaceRow, .identity, 108, .choices, folder: .appearance)],
        "workspace.clearTheme": [p(.workspaceRow, .identity, 109, folder: .appearance)],
        "terminal.setTheme": [p(.tab, .identity, 205, .choices, folder: .options)],
        "terminal.clearTheme": [p(.tab, .identity, 206, folder: .options)],
        "splitRight": [p(.pane, .create, 0), p(.terminalSelection, .create, 100, folder: .split)],
        "newColumn": [p(.pane, .create, 4)],
        "newRow": [p(.pane, .create, 1, folder: .new)],
        "splitDown": [p(.pane, .create, 1), p(.terminalSelection, .create, 101, folder: .split)],
        "newPaneAutoLayout": [p(.pane, .create, 8, folder: .new)],
        "toggleSplitZoom": [p(.pane, .layout, 100), p(.terminalSelection, .layout, 104, folder: .layout)],
        "equalizeSplits": [p(.pane, .layout, 101, folder: .layout)],
        "triggerFlash": [p(.pane, .inspect, 500, folder: .tools)],
        "palette.swapWithSession": [p(.pane, .connection, 200, folder: .connection)],
        "toggleCanvasLayout": [p(.pane, .layout, 102, folder: .layout)],
        "palette.newSimulatorPane": [p(.pane, .create, 100, folder: .new)],
        "newTab.sameKind": [p(.tab, .create, -1)],
        "newSurface": [p(.tab, .create, 0, folder: .new), p(.newTab, .create, 0)],
        "openBrowser.chromium": [p(.tab, .create, 2, folder: .new), p(.newTab, .create, 2)],
        "closeTab": [p(.tab, .close, 604)],
        "closeOtherTabsInPane": [p(.tab, .close, 603, folder: .close)],
        "closeTabsToLeft": [p(.tab, .close, 601, folder: .close)],
        "closeTabsToRight": [p(.tab, .close, 602, folder: .close)],
        "renameTab": [p(.tab, .identity, 200)],
        "palette.clearTabName": [p(.tab, .identity, 201, folder: .options)],
        "moveSurfaceLeft": [p(.tab, .move, 409, folder: .move)],
        "moveSurfaceRight": [p(.tab, .move, 410, folder: .move)],
        "moveSurfaceToPreviousPane": [p(.tab, .move, 411, folder: .move)],
        "moveSurfaceToNextPane": [p(.tab, .move, 412, folder: .move)],
        "moveSurfaceToPaneLeft": [p(.tab, .move, 400, folder: .move)],
        "moveSurfaceToPaneRight": [p(.tab, .move, 401, folder: .move)],
        "moveSurfaceToPaneUp": [p(.tab, .move, 402, folder: .move)],
        "moveSurfaceToPaneDown": [p(.tab, .move, 403, folder: .move)],
        "palette.moveTabToNewWorkspace": [p(.tab, .move, 406, folder: .move)],
        "palette.toggleTabPin": [p(.tab, .identity, 202)],
        "palette.toggleTabUnread": [p(.tab, .identity, 203, folder: .options)],
        "palette.toggleFullWidthTab": [p(.tab, .layout, 408, folder: .options)],
        "duplicateTab": [p(.tab, .create, 3)],
        "reloadTab": [p(.tab, .create, 4, folder: .options)],
        "toggleTabAudioMute": [p(.tab, .identity, 204, folder: .options)],
        "disconnectRemoteTab": [p(.tab, .connection, 2, folder: .options)],
        "palette.copyIdentifiers": [p(.tab, .inspect, 503, folder: .copy)],
        "palette.copyPaneID": [p(.pane, .inspect, 500, folder: .copy), p(.tab, .inspect, 504, folder: .copy)],
        "palette.copyPaneLink": [p(.pane, .inspect, 501, folder: .copy), p(.tab, .inspect, 505, folder: .copy)],
        "palette.copySurfaceID": [p(.tab, .inspect, 501, folder: .copy)],
        "palette.copySurfaceLink": [p(.tab, .inspect, 502, folder: .copy)],
        "tab.showResources": [p(.tab, .inspect, 500, folder: .options)],
        "workspace.showResources": [p(.workspaceRow, .inspect, 400, folder: .tools)],
        "tabGroup.create": [p(.tab, .organize, 300, folder: .group)],
        "tabGroup.addTab": [p(.tab, .organize, 301, folder: .group)],
        "tabGroup.removeTab": [p(.tab, .organize, 302, folder: .group)],
        "tabGroup.rename": [p(.tabGroup, .identity, 1)],
        "tabGroup.setColor": [p(.tabGroup, .identity, 2, .submenu, folder: .appearance)],
        "tabGroup.toggleCollapsed": [p(.tabGroup, .organize, 3)],
        "tabGroup.ungroup": [p(.tabGroup, .close, 300)],
        "tabGroup.close": [p(.tabGroup, .close, 301)],
        "tabGroup.moveToNewSplit": [p(.tabGroup, .move, 202, folder: .move)],
        "tabGroup.moveToNewColumn": [p(.tabGroup, .move, 203, folder: .move)],
        "tabGroup.moveToNewWorkspace": [p(.tabGroup, .move, 204, folder: .move)],
        "tabGroup.moveToWorkspace": [p(.tabGroup, .move, 205, folder: .move)],
        "tabGroup.moveToNewWindow": [p(.tabGroup, .move, 206, folder: .move)],
        "tabGroup.newTab": [p(.tabGroup, .create, 0)],
        "tabGroup.save": [p(.tabGroup, .organize, 100, folder: .group)],
        "tabGroup.unsave": [p(.tabGroup, .organize, 101, folder: .group)],
        "tabGroup.color.grey": [p(.tabGroup, .identity, 0, in: "tabGroup.setColor")],
        "tabGroup.color.blue": [p(.tabGroup, .identity, 1, in: "tabGroup.setColor")],
        "tabGroup.color.red": [p(.tabGroup, .identity, 2, in: "tabGroup.setColor")],
        "tabGroup.color.yellow": [p(.tabGroup, .identity, 3, in: "tabGroup.setColor")],
        "tabGroup.color.green": [p(.tabGroup, .identity, 4, in: "tabGroup.setColor")],
        "tabGroup.color.pink": [p(.tabGroup, .identity, 5, in: "tabGroup.setColor")],
        "tabGroup.color.purple": [p(.tabGroup, .identity, 6, in: "tabGroup.setColor")],
        "tabGroup.color.cyan": [p(.tabGroup, .identity, 7, in: "tabGroup.setColor")],
        "tabGroup.color.orange": [p(.tabGroup, .identity, 8, in: "tabGroup.setColor")],
    ]
}
