// Surface decisions other than placements (plans/cmux-next/actions.md):
// the actions the CLI offers as `cmux <noun> <verb>`, and the reason for
// every action a surface does not offer. `ActionSurfaceParityTests`
// rejects an action missing from both sides of a surface.

nonisolated extension ActionSurfaceCatalog {
    /// Actions with a purpose outside the GUI: creating, closing, renaming,
    /// moving and pinning objects, opening pages, headless settings, agent
    /// and Cloud work (plans/cmux-next/state-ownership.md 5). The `cmux` CLI
    /// offers them by `cliName`; every other action runs by id with
    /// `cmux action run`. A superset of the Rust CLI's `cliActionIDs`
    /// (#16174): screen, screen group, pane, column, tab move, extension,
    /// terminal and headless appearance verbs were added here.
    static let cliNamed: Set<ActionID> = [
        "newWindow", "newIncognitoWindow", "closeWindow", "tab.focus", "quit", "quitKeepSessions", "quitEndSessions",
        "quitEndEverything", "keepMacAwake", "newBrowserWorkspace", "openFolder",
        "palette.openFolderInVSCodeInline", "reopenPreviousSession", "reopenClosedWorkspace", "moveWorkspaceUp",
        "moveWorkspaceDown", "palette.moveWorkspaceToTop", "moveWorkspaceToWindow", "moveWorkspaceToNewWindow",
        "renameWorkspace", "palette.clearWorkspaceName", "editWorkspaceDescription",
        "palette.clearWorkspaceDescription", "markWorkspaceDone", "palette.workspaceStatus",
        "palette.addWorkspaceChecklistItem", "palette.openWorkspaceTodoPane",         "palette.closeOtherWorkspaces", "palette.closeWorkspacesBelow", "palette.closeWorkspacesAbove",
        "palette.toggleWorkspacePin", "palette.markWorkspaceRead", "palette.markWorkspaceUnread",
        "palette.workspaceColor", "palette.resetWorkspaceColor", "reconnectWorkspace", "disconnectWorkspace",
        "clearWorkspaceNotifications", "workspaceGroup.newWorkspace", "workspaceGroup.rename",
        "workspaceGroup.togglePin", "workspaceGroup.markRead", "workspaceGroup.markUnread",
        "workspaceGroup.clearNotifications", "workspaceGroup.ungroup", "workspaceGroup.delete", "saveLayoutTemplate",
        "palette.layout.open", "workspace.newAbove", "workspace.newBelow", "workspace.newAtTop",
        "workspace.newAtBottom", "workspace.newInGroup", "workspace.newInNewGroup", "workspace.newOnMachine",
        "workspace.newInSameDirectory", "workspace.duplicate", "workspace.duplicateTerminalsOnly", "workspace.setIcon",
        "workspace.clearIcon", "workspace.moveToBottom", "workspace.moveToNewGroup", "workspace.closeOthersInGroup",
        "workspace.sortByName", "workspace.sortByLastUsed", "workspace.sortByDirectory", "workspaceGroup.collapseAll",
        "workspaceGroup.expandAll", "workspace.mergeInto", "pane.moveToNewWorkspace", "newWorkspaceGroup",
        "moveWorkspaceToGroup", "removeWorkspaceFromGroup", "workspaceGroup.setColor", "workspaceGroup.collapse",
        "workspaceGroup.expand", "workspaceGroup.moveUp", "workspaceGroup.moveDown", "workspaceGroup.moveToWindow",
        "workspaceGroup.closeWorkspaces", "workspaceGroup.moveToNewWindow",
        "space.newWindow", "space.newWorkspace", "space.rename", "space.setColor", "space.clearColor",
        "space.setIcon", "space.clearIcon", "space.setDefaults", "space.delete", "space.moveLeft",
        "space.moveRight", "space.move", "space.switch", "workspace.moveToSpace", "workspace.duplicateToSpace",
        "workspaceGroup.moveToSpace", "space.setTheme", "space.clearTheme",
        "space.newWindow", "space.newWorkspace", "space.rename", "space.setColor",
        "space.clearColor", "space.setIcon", "space.clearIcon", "space.setDefaults", "space.delete",
        "space.moveLeft", "space.moveRight", "space.move", "space.switch", "workspace.moveToSpace",
        "workspace.duplicateToSpace", "workspaceGroup.moveToSpace", "space.setTheme", "space.clearTheme",
        "workspace.setTheme", "workspace.clearTheme", "terminal.setTheme", "terminal.clearTheme",
        "splitRight", "newColumn", "newRow", "splitDown", "newPaneAutoLayout", "equalizeSplits", "triggerFlash",
        "palette.swapWithSession", "toggleCanvasLayout", "canvasTidy", "palette.newSimulatorPane", "file.open",
        "newTab.sameKind", "newTab.page", "newTab.submit", "newSurface", "openBrowser", "openBrowser.webkit",
        "openBrowser.chromium", "closeOtherTabsInPane", "closeTabsToLeft", "closeTabsToRight",
        "renameTab", "palette.clearTabName",
        "moveSurfaceLeft", "moveSurfaceRight", "moveSurfaceToPreviousPane", "moveSurfaceToNextPane",
        "moveSurfaceToPaneLeft", "moveSurfaceToPaneRight", "moveSurfaceToPaneUp", "moveSurfaceToPaneDown",
        "palette.moveTabToNewWorkspace", "palette.toggleTabPin", "palette.toggleTabUnread", "duplicateTab",
        "reloadTab", "reopenClosedBrowserPanel", "tabGroup.create",
        "tabGroup.addTab", "tabGroup.removeTab", "tabGroup.rename", "tabGroup.setColor", "tabGroup.collapse",
        "tabGroup.expand", "tabGroup.ungroup", "tabGroup.close", "tabGroup.moveToNewSplit", "tabGroup.moveToNewColumn",
        "tabGroup.moveToNewWorkspace", "tabGroup.moveToWorkspace", "tabGroup.moveToNewWindow", "tabGroup.newTab",
        "tabGroup.save", "tabGroup.unsave", "tabGroup.deleteSaved", "tabGroup.reopenSaved",         "screen.newWith", "screen.duplicate", "screen.closeOthers", "screen.closeToRight",
        "screen.closeToLeft", "screen.reopenClosed", "screen.rename", "screen.clearName", "screen.setColor",
        "screen.clearColor", "screen.setIcon", "screen.clearIcon", "screen.togglePin", "screen.moveLeft",
        "screen.moveRight", "screen.moveToWorkspace", "screen.moveToNewWorkspace", "screen.moveToNewWindow",
        "screenGroup.create", "screenGroup.addScreen", "screenGroup.removeScreen", "screenGroup.newScreen",
        "screenGroup.rename", "screenGroup.setColor", "screenGroup.collapse", "screenGroup.expand",
        "screenGroup.ungroup", "screenGroup.close", "screenGroup.moveLeft", "screenGroup.moveRight",
        "screenGroup.moveToWorkspace", "screenGroup.moveToNewWorkspace", "screenGroup.moveToNewWindow",
        "screenGroup.save", "screenGroup.unsave", "screenGroup.reopenSaved", "screenGroup.deleteSaved",
        "terminal.keep", "clearScreenKeepScrollback", "resetTerminal", "reconnectPane", "resumeCommandSet",
        "resumeCommandClear", "palette.terminalOpenDirectory", "browserReload",
        "browserHardReload", "browser.openInChromium", "browser.openInWebKit", "splitBrowserRight", "splitBrowserDown",
        "palette.browserOpenDefault", "palette.browserClearHistory", 
        "browserScreenshotPage", "browserTheme", 
        "browser.pageInfo.deleteSiteData", "browser.pageInfo.setPermission", "browser.pageInfo.resetPermissions",
        "browser.extensions.loadUnpacked", "browser.extension.run", "browser.extension.pin", "browser.extension.unpin",
        "browser.extension.enable", "browser.extension.disable", "browser.extension.move", "browser.extension.reload",
        "browser.extension.remove", "browser.extension.command", "browserProfile.new", "browserProfile.rename",
        "browserProfile.setColor", "browserProfile.clearColor", "browserProfile.setIcon", "browserProfile.clearIcon",
        "browserProfile.delete", "browserProfile.newTab", "browserProfile.newWindow", "browserProfile.newWorkspace",
        "browserProfile.openLink", "browserProfile.setWorkspaceDefault", "browserProfile.clearWorkspaceDefault",
        "browserProfile.setSpaceDefault", "browserProfile.clearSpaceDefault", "browserProfile.moveTab",
        "browserProfile.duplicateTab", "palette.toggleMatchTerminalBackground", "palette.enableMinimalMode",
        "palette.disableMinimalMode", "markAllNotificationsRead", "clearAllNotifications",
        "notifications.toggleWorkspaceMute", "notifications.toggleBanners", "notifications.dismissal.keystroke",
        "notifications.dismissal.focus", "notifications.dismissal.click", "notifications.dismissal.explicit",
        "notifications.dismissal.timeout", "notifications.dismissal.never", "palette.newAgentChat", "palette.quickAgentChat",
        "palette.launchClaudeTeams", "palette.launchCodexTeams", "palette.forkAgentConversationRight",
        "palette.forkAgentConversationLeft", "palette.forkAgentConversationTop", "palette.forkAgentConversationBottom",
        "palette.forkAgentConversationNewTab", "palette.forkAgentConversationNewWorkspace", "computerUseStop",
        "newCloudWorkspace", "newCloudMachine", "palette.cloud.fork", "palette.cloud.snapshot",
        "palette.cloud.restore", "palette.cloud.promoteTemplate", "palette.cloud.status", "palette.cloud.ports",
        "palette.cloud.handoff", "cloudSSH", "cloudExec", "cloudFilesList", "cloudFileRead", "cloudFileWrite",
        "cloudFileMkdir", "cloudFileRemove", "cloudFileStat", "cloudPrepareSCP",
        "cloudTunnelAttach", "cloudTunnelDetach", "cloudTunnelRotateKey", "cloudNetworkList",
        "cloudFirewallList", "cloudFirewallGet", "cloudFirewallCreate", "cloudFirewallDelete", "cloudNewTerminal", "cloudRenameMachine", "cloudKillMachine", "cloudResizeMachine",
        "cloudDiagnostics", "cloudPauseMachine", "cloudResumeMachine", "palette.cloud.deleteSnapshot", "palette.auth.signIn", "palette.auth.signOut", "accounts.show", "accounts.refresh",
        "accounts.reauthenticate", "accounts.connect", "accounts.remove", "remote.connect", "remote.newWorkspace",
        "remote.openTerminalHere", "remote.reconnect", "remote.disconnect", "remote.install", "remote.forget",
        "reloadConfiguration", "palette.makeDefaultBrowser", "palette.makeDefaultTerminal", "palette.toggleSetting",
        "palette.shortcutKeymap", "palette.installCLI", "palette.uninstallCLI", "palette.restartSocketListener",
        "palette.checkForUpdates", "palette.applyUpdateIfAvailable", "palette.switchAppChannel", "palette.importClassicSessions",
        "appearance.density.compact", "appearance.density.comfortable", "appearance.animationSpeed.fast",
        "appearance.animationSpeed.normal", "appearance.animationSpeed.off", "browser.defaultEngine.chromium",
        "browser.defaultEngine.webkit", "appearance.paneBorder.toggle", "appearance.panePadding.toggle",
        "appearance.paneCorners.toggle", "layout.centerFocusedColumn.never", "layout.centerFocusedColumn.always",
        "layout.centerFocusedColumn.onOverflow", "focusRing.toggle", "focusRing.style.ring", "focusRing.style.glow",
        "focusRing.singlePane.toggle", "appearance.paneBorderWidth.toggle", "appearance.paneBorderColor.reset",
        "appearance.titlebar.minimal", "appearance.titlebar.standard", "browser.hibernation.off",
        "browser.hibernation.moderate", "browser.hibernation.aggressive", "hibernateTab", "wakeTab",
        "tab.moveToNewSplit", "tab.moveToNewColumn", "tab.moveToNewStickyColumn", "tab.moveToWorkspace", "tab.moveToNewWindow", "tabGroup.moveLeft",
        "tabGroup.moveRight", "splitLeft", "splitUp", "swapPaneLeft", "swapPaneRight", "swapPaneUp", "swapPaneDown",
        "renamePane", "column.moveLeft", "column.moveRight", "column.center", "column.widthOneThird",
        "column.widthHalf", "column.widthTwoThirds", "column.widthFull", "column.dock", "column.dockLeft",
        "column.dockRight", "column.dockTop", "column.dockBottom", "column.float", "column.undock", "layout.toggleStripScrollbar", "terminal.clear",
        "terminal.sendText", "history.show", "agentActivity.open", "history.resumeAgentSession", "history.reopen", "history.open", "history.clear",
        "layout.undo", "bookmark.addPage", "bookmark.addAllTabs", "bookmark.add", "bookmark.newFolder",
        "bookmark.open", "bookmark.openInNewTab", "bookmark.openInBackgroundTab", "bookmark.openAll", "bookmark.edit",
        "bookmark.move", "bookmark.remove", "bookmark.import", "bookmark.export",
    ]

    /// Why the CLI has no verb for an action (`cmux action run <id>` still runs it).
    /// Why the palette does not list an action (beyond palette-internal
    /// navigation, which the descriptor derives from `requires`).
    static let paletteExemption: [ActionID: SurfaceExemption] = byReason(paletteExemptionsByReason)
    static let paletteExemptionsByReason: [SurfaceExemption: [ActionID]] = [
        .duplicateOfDefault: [
            "openBrowser.chromium",
        ],
        // A row of the titlebar Back / Forward list: the click on the row is the gesture.
        .focusMove: [
            "history.goTo",
        ],
    ]

    static let cliExemption: [ActionID: SurfaceExemption] = byReason(cliExemptionsByReason)
    static let cliExemptionsByReason: [SurfaceExemption: [ActionID]] = [
        .ownerVerb: ownerVerbActions,
        .unimplemented: [
            "palette.openDirectoryDiffViewer",
            "openDiffViewer",
            "palette.disableBrowser",
            "palette.enableBrowser",
            "disconnectRemoteTab",
            "toggleTabAudioMute",
            "palette.openCloudPane",
            "palette.openVaultPane",
            "palette.openFindPane",
            "palette.openFilesPane",
        ],
        .guiOnly: [
            "openSettings", "minimizeWindow", "toggleFullScreen", "globalSearch", "commandPalette", "appearance.customize",
            "palette.openTaskManager", "palette.sleepyMode", "about", "palette.workspaceCustomColor",
            "revealWorkspaceInFinder", "workspaceGroup.editConfig", "manageLayouts",
            "palette.openWorkspacePullRequests", "palette.findWork", "toggleSplitZoom", "canvasOverview",
            "palette.toggleFullWidthTab", "tab.showResources", "workspace.showResources",
            "toggleBrowserDeveloperTools", "showBrowserJavaScriptConsole", "inspectBrowserElement",
            "toggleBrowserFocusMode", "toggleBrowserDesignMode", "toggleReactGrab", "palette.browserToggleOmnibar",
            "importFromBrowser", "password.importCSV", "openLinkInDefaultBrowser", "filePreviewOpenWith", "filePreviewOpenExternally",
            "filePreviewRevealInFinder", "palette.vscodeServeWebStop", "palette.vscodeServeWebRestart",
            "browser.pageInfo", "browser.pageInfo.connection", "browser.pageInfo.certificate",
            "browser.pageInfo.cookies", "browser.pageInfo.manageSiteData", "browser.pageInfo.siteSettings",
            "browser.pageInfo.aboutThisPage", "browser.extensions.menu", "browser.extensions.manage",
            "browser.extensions.webStore", "browser.extension.options", "browserProfile.manageExtensions",
            "toggleSidebar", "toggleRightSidebar", "switchRightSidebarToFiles", "switchRightSidebarToFind",
            "switchRightSidebarToSessions", "switchRightSidebarToFeed", "switchRightSidebarToDock",
            "switchRightSidebarToMachines", "showNotifications", "feed.show", "palette.openTerminalChatView",
            "palette.computerUse.setup", "palette.computerUse.accessibility", "palette.computerUse.screenRecording",
            "palette.cloud.tools", "cloudOpenMachine", "openTeamPicker", "palette.mobileConnect",
            "palette.openCmuxSettingsFile", "palette.openGhosttySettings", "palette.searchShortcuts",
            "palette.pro.upgrade", "palette.welcomeChecklist", "sendFeedback", "help.featureFlags",
            "help.documentation", "recentlyFocused", "recentlyClosed", "history.commands", "browserShowHistory",
            "history.search", "bookmark.toggleBar", "bookmark.manager", "browserLinkHints", "browserLinkHintsNewSplit",
        ],
        .liveInput: [
            "palette.toggleDictation", "agentPane.searchChats",
            "taskManager.killProcess", "toggleChecklistItemComplete", "groupSelectedWorkspaces", "canvasAlignLeft",
            "canvasAlignRight", "canvasAlignTop", "canvasAlignBottom", "canvasEqualizeWidths", "canvasEqualizeHeights",
            "canvasDistributeHorizontally", "canvasDistributeVertically", "simulatorHome", "simulatorRotateLeft",
            "simulatorRotateRight", "simulatorToggleAppearance", "simulatorToggleSoftwareKeyboard",
            "toggleTerminalCopyMode", "palette.terminalToggleTextBoxInput", "cycleTextBoxSubmitAction",
            "attachTextBoxFile", "sendCtrlFToTerminal", "pasteLastScreenshot", "find", "findInDirectory", "findNext",
            "findPrevious", "hideFind", "useSelectionForFind", "terminal.scrollToSelection", "terminalCopy", "terminalPaste",
            "openLinkInNewTab",
            "browserScreenshotSection", "saveFilePreview", "toggleFileEditorWordWrap", "diffViewerNextLine",
            "diffViewerPreviousLine", "diffViewerHalfPageDown", "diffViewerHalfPageUp", "diffViewerNextHunk",
            "diffViewerPreviousHunk", "diffViewerGoToBottom", "diffViewerGoToTop", "diffViewerSearch",
            "diffViewerNextFile", "diffViewerPreviousFile", "fileExplorerOpenSelection",
            "fileExplorerOpenSelectionFinderAlias", "fileExplorerOpenInCmux", "fileExplorerReveal",
            "fileExplorerCopyPath", "fileExplorerCopyRelativePath", "fileExplorerOpenWith", "vaultOpenSession",
            "vaultResumeInNewWorkspace", "vaultCopyResumeCommand", "vaultOpenPullRequest", "checklistEditItem",
            "checklistMarkInProgress", "checklistCompleteItem", "checklistRemoveItem", "checklistOpenAsPane",
            "checklistAttachImages", "toggleUnread", "notificationCopy", "notificationToggleRead",
            "notificationDismiss", "terminal.selectAll",
        ],
        .familyMember: [
            "cycleWorkspaceStatus", "toggleFocusedWorkspaceGroupCollapsed", "workspaceGroup.color.grey",
            "workspaceGroup.color.blue", "workspaceGroup.color.red", "workspaceGroup.color.yellow",
            "workspaceGroup.color.green", "workspaceGroup.color.pink", "workspaceGroup.color.purple",
            "workspaceGroup.color.cyan", "workspaceGroup.color.orange", "space.color.grey", "space.color.blue",
            "space.color.red", "space.color.yellow", "space.color.green", "space.color.pink", "space.color.purple",
            "space.color.cyan", "space.color.orange", "tabGroup.toggleCollapsed", "tabGroup.color.grey",
            "tabGroup.color.blue", "tabGroup.color.red", "tabGroup.color.yellow", "tabGroup.color.green",
            "tabGroup.color.pink", "tabGroup.color.purple", "tabGroup.color.cyan", "tabGroup.color.orange",
            "screen.color.grey", "screen.color.blue", "screen.color.red", "screen.color.yellow", "screen.color.green",
            "screen.color.pink", "screen.color.purple", "screen.color.cyan", "screen.color.orange",
            "screenGroup.toggleCollapsed", "screenGroup.color.grey", "screenGroup.color.blue", "screenGroup.color.red",
            "screenGroup.color.yellow", "screenGroup.color.green", "screenGroup.color.pink",
            "screenGroup.color.purple", "screenGroup.color.cyan", "screenGroup.color.orange", "resumeCommandEdit",
            "palette.attemptUpdate",
        ],
        .focusMove: [
            "history.goTo",
            "home.show",
            "showHideAllWindows", "goToWorkspace", "showMainWindow", "nextSidebarTab", "prevSidebarTab",
            "nextSidebarTabInGroup", "prevSidebarTabInGroup", "nextWorkspaceGroup", "prevWorkspaceGroup",
            "selectWorkspaceByNumber", "workspace.selectFirst",
            "workspace.selectLast", "workspace.selectLastUsed", "space.next", "space.previous", "space.selectByNumber",
            "focusLeft", "focusRight", "focusUp", "focusDown", "focusPreviousPane", "focusNextPane",
            "canvasRevealFocusedPane", "nextSurface", "prevSurface", "selectSurfaceByNumber",
            "screen.next", "screen.previous", "screen.select", "screen.selectLast", "focusTextBoxInput",
            "focusBrowserAddressBar", "focusLocation", "focusRightSidebar", "vaultFocusSession", "jumpToUnread",
            "markOldestUnreadAndJumpNext", "notificationOpen", "computerUseFocus", "computerUseFocusCallingTerminal",
            "column.focusLeft", "column.focusRight", "focusHistoryBack", "focusHistoryForward", "focusHistoryLast",
        ],
        .stepAdjust: [
            "resizePaneLeft", "resizePaneRight", "resizePaneUp", "resizePaneDown", "increaseWorkspaceTerminalFontSize",
            "decreaseWorkspaceTerminalFontSize", "resetWorkspaceTerminalFontSize", "canvasZoomIn", "canvasZoomOut",
            "canvasZoomReset", "browserZoomIn", "browserZoomOut", "browserZoomReset", "markdownZoomIn",
            "markdownZoomOut", "markdownZoomReset", "appearance.interfaceSize.increase",
            "appearance.interfaceSize.decrease", "appearance.interfaceSize.reset", "column.cycleWidth",
            "column.cycleWidthBack", "terminal.increaseFontSize", "terminal.decreaseFontSize",
            "terminal.resetFontSize", "terminal.scrollPageUp", "terminal.scrollPageDown", "terminal.scrollToTop",
            "terminal.scrollToBottom",
        ],
        .clipboard: [
            "copyWorkspaceSSHError", "palette.copyWorkspaceID", "palette.copyWorkspaceIDAndRef",
            "palette.copyWorkspaceLink", "workspace.copyPath", "palette.copyIdentifiers", "palette.copyPaneID",
            "palette.copyPaneLink", "palette.copySurfaceID", "palette.copySurfaceLink", "cloudCopyLink",
            "cloudCopyPort", "cloudCopyMachineID",
        ],
        .paletteInternal: [
            "commandPaletteNext", "commandPalettePrevious",
        ],
        .devOnly: [
            "openDebugSettings", "palette.onboardingGallery",
        ],
    ]

    /// CLI verbs `cmux mcp serve` leaves out (plans/cmux-next/mcp.md).
    static let mcpExemption: [ActionID: SurfaceExemption] = byReason(mcpExemptionsByReason)
    static let mcpExemptionsByReason: [SurfaceExemption: [ActionID]] = [
        .systemChange: [
            "notifications.dismissal.keystroke",
            "notifications.dismissal.focus",
            "notifications.dismissal.click",
            "notifications.dismissal.explicit",
            "notifications.dismissal.timeout",
            "notifications.dismissal.never",
            "appearance.density.compact",
            "appearance.density.comfortable",
            "appearance.animationSpeed.fast",
            "appearance.animationSpeed.normal",
            "appearance.animationSpeed.off",
            "browser.defaultEngine.chromium",
            "browser.defaultEngine.webkit",
            "appearance.paneBorder.toggle",
            "appearance.panePadding.toggle",
            "appearance.paneCorners.toggle",
            "layout.centerFocusedColumn.never",
            "layout.centerFocusedColumn.always",
            "layout.centerFocusedColumn.onOverflow",
            "focusRing.toggle",
            "focusRing.style.ring",
            "focusRing.style.glow",
            "focusRing.singlePane.toggle",
            "appearance.paneBorderWidth.toggle",
            "appearance.paneBorderColor.reset",
            "appearance.titlebar.minimal",
            "appearance.titlebar.standard",
            "browser.hibernation.off",
            "browser.hibernation.moderate",
            "browser.hibernation.aggressive",
            "notifications.toggleBanners",
            "palette.enableMinimalMode",
            "palette.disableMinimalMode",
            "palette.toggleMatchTerminalBackground",
            "layout.toggleStripScrollbar",
            "keepMacAwake",
            "palette.shortcutKeymap",
            "palette.makeDefaultBrowser", "palette.makeDefaultTerminal", "palette.toggleSetting", "palette.installCLI",
            "palette.uninstallCLI", "palette.restartSocketListener", "palette.applyUpdateIfAvailable",
            "palette.switchAppChannel",
        ],
        .credentials: [
            "palette.auth.signIn", "palette.auth.signOut", "accounts.reauthenticate", "accounts.connect",
            "accounts.remove",
        ],
        .endsApp: [
            "quit", "quitKeepSessions", "quitEndSessions", "quitEndEverything",
        ],
    ]
}
