// Code generated by cmux-tui SDK codegen. DO NOT EDIT.
// Mux protocol 12; IR SHA-256 0edc0a3c7e51c1f0843d49e78b98ef01dea251fb14beeda82935fcf345a138a1.

package raw

const (
	SDKSchemaVersion   = 2
	MuxProtocolVersion = 12
	SDKIRSHA256        = "0edc0a3c7e51c1f0843d49e78b98ef01dea251fb14beeda82935fcf345a138a1"
)

type Authority string

const (
	AuthorityControl           Authority = "control"
	AuthorityFrontend          Authority = "frontend"
	AuthorityLocalAdmin        Authority = "local-admin"
	AuthorityProviderAuthority Authority = "provider-authority"
)

type CommandMetadata struct {
	Name              string
	GoMethod          string
	Authority         Authority
	Since             uint32
	Capability        string
	Stream            string
	FieldSince        map[string]uint32
	FieldCapabilities map[string]string
}

type EventMetadata struct {
	Name       string
	Since      uint32
	Capability string
	Streams    []string
	Emission   string
}

type Profile string

const (
	ProfileControl           Profile = "control"
	ProfileFrontend          Profile = "frontend"
	ProfileLocalAdmin        Profile = "local-admin"
	ProfileProviderAuthority Profile = "provider-authority"
)

type ProfileMetadata struct {
	Name              Profile
	Description       string
	Inherits          []Profile
	Transport         string
	RequiresAuthority bool
}

var profileMetadata = map[Profile]ProfileMetadata{
	ProfileControl:           {Name: ProfileControl, Description: "Base authenticated session-control commands available to ordinary SDK clients.", Inherits: []Profile{}, Transport: "", RequiresAuthority: false},
	ProfileFrontend:          {Name: ProfileFrontend, Description: "Rendering, input, presentation, subscribe, and attach commands.", Inherits: []Profile{ProfileControl}, Transport: "", RequiresAuthority: false},
	ProfileLocalAdmin:        {Name: ProfileLocalAdmin, Description: "Trusted local administration commands.", Inherits: []Profile{ProfileControl}, Transport: "Unix-classified transport, including direct Unix and the current stdio relay", RequiresAuthority: false},
	ProfileProviderAuthority: {Name: ProfileProviderAuthority, Description: "Provider-owned workspace mutation commands.", Inherits: []Profile{ProfileControl}, Transport: "", RequiresAuthority: true},
}

var commandMetadata = map[string]CommandMetadata{
	"ack-tab-notifications":              {Name: "ack-tab-notifications", GoMethod: "AckTabNotifications", Authority: AuthorityControl, Since: 12, Capability: "notification-ack-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"add-screens-to-screen-group":        {Name: "add-screens-to-screen-group", GoMethod: "AddScreensToScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"add-tabs-to-tab-group":              {Name: "add-tabs-to-tab-group", GoMethod: "AddTabsToTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"apply-layout":                       {Name: "apply-layout", GoMethod: "ApplyLayout", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"attach-surface":                     {Name: "attach-surface", GoMethod: "AttachSurface", Authority: AuthorityFrontend, Since: 5, Capability: "", Stream: "attach", FieldSince: map[string]uint32{"mode": 7}, FieldCapabilities: map[string]string{"cols": "attach-initial-size", "expected_generation": "attach-identity-v1", "expected_terminal_id": "attach-identity-v1", "rows": "attach-initial-size", "snapshot": "terminal-snapshot-v1", "snapshot_version": "terminal-snapshot-v1", "viewer_backlog_bytes": "terminal-snapshot-v1"}},
	"browser-activate":                   {Name: "browser-activate", GoMethod: "BrowserActivate", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-back":                       {Name: "browser-back", GoMethod: "BrowserBack", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-forward":                    {Name: "browser-forward", GoMethod: "BrowserForward", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-frame-presented":            {Name: "browser-frame-presented", GoMethod: "BrowserFramePresented", Authority: AuthorityFrontend, Since: 10, Capability: "browser-pointer-frame-guard-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-insert-text":                {Name: "browser-insert-text", GoMethod: "BrowserInsertText", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-key":                        {Name: "browser-key", GoMethod: "BrowserKey", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-key-press":                  {Name: "browser-key-press", GoMethod: "BrowserKeyPress", Authority: AuthorityFrontend, Since: 10, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-mouse":                      {Name: "browser-mouse", GoMethod: "BrowserMouse", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-mouse-guarded":              {Name: "browser-mouse-guarded", GoMethod: "BrowserMouseGuarded", Authority: AuthorityFrontend, Since: 10, Capability: "browser-pointer-frame-guard-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-navigate":                   {Name: "browser-navigate", GoMethod: "BrowserNavigate", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-reload":                     {Name: "browser-reload", GoMethod: "BrowserReload", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-wheel":                      {Name: "browser-wheel", GoMethod: "BrowserWheel", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-wheel-guarded":              {Name: "browser-wheel-guarded", GoMethod: "BrowserWheelGuarded", Authority: AuthorityFrontend, Since: 10, Capability: "browser-pointer-frame-guard-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"clear-history":                      {Name: "clear-history", GoMethod: "ClearHistory", Authority: AuthorityControl, Since: 9, Capability: "clear-history-v1", Stream: "", FieldSince: map[string]uint32{"fallback_key": 9}, FieldCapabilities: map[string]string{"fallback_key": "clear-history-key-v1"}},
	"clear-window-title":                 {Name: "clear-window-title", GoMethod: "ClearWindowTitle", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"client-focus":                       {Name: "client-focus", GoMethod: "ClientFocus", Authority: AuthorityControl, Since: 12, Capability: "client-focus-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-pane":                         {Name: "close-pane", GoMethod: "ClosePane", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"end_terminals": 12}, FieldCapabilities: map[string]string{"end_terminals": "batch-close-v1"}},
	"close-provider-managed-workspace":   {Name: "close-provider-managed-workspace", GoMethod: "CloseProviderManagedWorkspace", Authority: AuthorityProviderAuthority, Since: 9, Capability: "provider-managed-workspace-authority-v2", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-screen":                       {Name: "close-screen", GoMethod: "CloseScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"end_terminals": 12}, FieldCapabilities: map[string]string{"end_terminals": "batch-close-v1"}},
	"close-screen-group":                 {Name: "close-screen-group", GoMethod: "CloseScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-surface":                      {Name: "close-surface", GoMethod: "CloseSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-tab-group":                    {Name: "close-tab-group", GoMethod: "CloseTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: map[string]uint32{"end_terminals": 12}, FieldCapabilities: map[string]string{"end_terminals": "batch-close-v1"}},
	"close-tabs":                         {Name: "close-tabs", GoMethod: "CloseTabs", Authority: AuthorityControl, Since: 12, Capability: "batch-close-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-terminal":                     {Name: "close-terminal", GoMethod: "CloseTerminal", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-workspace":                    {Name: "close-workspace", GoMethod: "CloseWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"end_terminals": 12, "expected_generation": 7, "expected_revision": 7, "key": 7, "mutation_id": 7, "origin": 7}, FieldCapabilities: map[string]string{"end_terminals": "batch-close-v1", "key": "workspace-registry-v1"}},
	"conversation-agent-token":           {Name: "conversation-agent-token", GoMethod: "ConversationAgentToken", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-bind":                  {Name: "conversation-bind", GoMethod: "ConversationBind", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-create":                {Name: "conversation-create", GoMethod: "ConversationCreate", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-history":               {Name: "conversation-history", GoMethod: "ConversationHistory", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-list":                  {Name: "conversation-list", GoMethod: "ConversationList", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-op":                    {Name: "conversation-op", GoMethod: "ConversationOp", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-search":                {Name: "conversation-search", GoMethod: "ConversationSearch", Authority: AuthorityLocalAdmin, Since: 12, Capability: "conversation-search-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-snapshot":              {Name: "conversation-snapshot", GoMethod: "ConversationSnapshot", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"conversation-typing":                {Name: "conversation-typing", GoMethod: "ConversationTyping", Authority: AuthorityLocalAdmin, Since: 12, Capability: "local-conversations-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"copy":                               {Name: "copy", GoMethod: "Copy", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-bookmark":                    {Name: "create-bookmark", GoMethod: "CreateBookmark", Authority: AuthorityControl, Since: 12, Capability: "bookmarks-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-browser-profile":             {Name: "create-browser-profile", GoMethod: "CreateBrowserProfile", Authority: AuthorityControl, Since: 12, Capability: "browser-profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-personal-group":              {Name: "create-personal-group", GoMethod: "CreatePersonalGroup", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-profile":                     {Name: "create-profile", GoMethod: "CreateProfile", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-screen-group":                {Name: "create-screen-group", GoMethod: "CreateScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-surface-with-receipt":        {Name: "create-surface-with-receipt", GoMethod: "CreateSurfaceWithReceipt", Authority: AuthorityControl, Since: 10, Capability: "creation-receipts-v1", Stream: "", FieldSince: nil, FieldCapabilities: map[string]string{"idempotency_key": "creation-attempt-keys-v1"}},
	"create-tab-group":                   {Name: "create-tab-group", GoMethod: "CreateTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-terminal":                    {Name: "create-terminal", GoMethod: "CreateTerminal", Authority: AuthorityControl, Since: 7, Capability: "workspace-registry-v1", Stream: "", FieldSince: map[string]uint32{"env": 12, "keep": 12, "shell_args": 12, "terminal_id": 9}, FieldCapabilities: map[string]string{"env": "terminal-env-v1", "keep": "terminal-reap-v1", "shell_args": "terminal-shell-args-v1"}},
	"create-workspace":                   {Name: "create-workspace", GoMethod: "CreateWorkspace", Authority: AuthorityControl, Since: 7, Capability: "workspace-registry-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-workspace-group":             {Name: "create-workspace-group", GoMethod: "CreateWorkspaceGroup", Authority: AuthorityControl, Since: 12, Capability: "workspace-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-bookmark":                    {Name: "delete-bookmark", GoMethod: "DeleteBookmark", Authority: AuthorityControl, Since: 12, Capability: "bookmarks-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-browser-profile":             {Name: "delete-browser-profile", GoMethod: "DeleteBrowserProfile", Authority: AuthorityControl, Since: 12, Capability: "browser-profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-personal-group":              {Name: "delete-personal-group", GoMethod: "DeletePersonalGroup", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-profile":                     {Name: "delete-profile", GoMethod: "DeleteProfile", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-saved-screen-group":          {Name: "delete-saved-screen-group", GoMethod: "DeleteSavedScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-saved-tab-group":             {Name: "delete-saved-tab-group", GoMethod: "DeleteSavedTabGroup", Authority: AuthorityControl, Since: 12, Capability: "saved-tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"delete-workspace-group":             {Name: "delete-workspace-group", GoMethod: "DeleteWorkspaceGroup", Authority: AuthorityControl, Since: 12, Capability: "workspace-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"detach-attached-view":               {Name: "detach-attached-view", GoMethod: "DetachAttachedView", Authority: AuthorityFrontend, Since: 10, Capability: "view-attachment-detach-v1", Stream: "", FieldSince: map[string]uint32{"view": 12}, FieldCapabilities: map[string]string{"view": "shared-sizing-v1"}},
	"detach-client":                      {Name: "detach-client", GoMethod: "DetachClient", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: map[string]uint32{"by": 12, "surface": 12}, FieldCapabilities: map[string]string{"by": "shared-sizing-v1", "surface": "shared-sizing-v1"}},
	"export-layout":                      {Name: "export-layout", GoMethod: "ExportLayout", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"focus-direction":                    {Name: "focus-direction", GoMethod: "FocusDirection", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"focus-pane":                         {Name: "focus-pane", GoMethod: "FocusPane", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"forget-session":                     {Name: "forget-session", GoMethod: "ForgetSession", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-browser-provider":               {Name: "get-browser-provider", GoMethod: "GetBrowserProvider", Authority: AuthorityLocalAdmin, Since: 10, Capability: "browser-provider-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-cell-pixels":                    {Name: "get-cell-pixels", GoMethod: "GetCellPixels", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-frontend-browser-history":       {Name: "get-frontend-browser-history", GoMethod: "GetFrontendBrowserHistory", Authority: AuthorityControl, Since: 12, Capability: "frontend-browser-history-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-frontend-projection":            {Name: "get-frontend-projection", GoMethod: "GetFrontendProjection", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-size-state":                     {Name: "get-size-state", GoMethod: "GetSizeState", Authority: AuthorityControl, Since: 12, Capability: "shared-sizing-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"identify":                           {Name: "identify", GoMethod: "Identify", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"ids":                                {Name: "ids", GoMethod: "IDs", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"import-bookmarks":                   {Name: "import-bookmarks", GoMethod: "ImportBookmarks", Authority: AuthorityControl, Since: 12, Capability: "bookmarks-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"import-session-organization":        {Name: "import-session-organization", GoMethod: "ImportSessionOrganization", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"journal-frontend-event":             {Name: "journal-frontend-event", GoMethod: "JournalFrontendEvent", Authority: AuthorityControl, Since: 10, Capability: "frontend-journal-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-agents":                        {Name: "list-agents", GoMethod: "ListAgents", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-bookmarks":                     {Name: "list-bookmarks", GoMethod: "ListBookmarks", Authority: AuthorityControl, Since: 12, Capability: "bookmarks-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-clients":                       {Name: "list-clients", GoMethod: "ListClients", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-notifications":                 {Name: "list-notifications", GoMethod: "ListNotifications", Authority: AuthorityControl, Since: 12, Capability: "notification-ack-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-personal":                      {Name: "list-personal", GoMethod: "ListPersonal", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-saved-screen-groups":           {Name: "list-saved-screen-groups", GoMethod: "ListSavedScreenGroups", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-saved-tab-groups":              {Name: "list-saved-tab-groups", GoMethod: "ListSavedTabGroups", Authority: AuthorityControl, Since: 12, Capability: "saved-tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-tab-groups":                    {Name: "list-tab-groups", GoMethod: "ListTabGroups", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-terminals":                     {Name: "list-terminals", GoMethod: "ListTerminals", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-workspace-groups":              {Name: "list-workspace-groups", GoMethod: "ListWorkspaceGroups", Authority: AuthorityControl, Since: 12, Capability: "workspace-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-workspaces":                    {Name: "list-workspaces", GoMethod: "ListWorkspaces", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"machine-listening-tcp":              {Name: "machine-listening-tcp", GoMethod: "MachineListeningTcp", Authority: AuthorityControl, Since: 12, Capability: "machine-listening-tcp-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"machine-usage":                      {Name: "machine-usage", GoMethod: "MachineUsage", Authority: AuthorityControl, Since: 12, Capability: "machine-usage-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"mark-workspaces-provider-managed":   {Name: "mark-workspaces-provider-managed", GoMethod: "MarkWorkspacesProviderManaged", Authority: AuthorityProviderAuthority, Since: 9, Capability: "provider-managed-workspace-authority-v2", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"mint-terminal-renderer":             {Name: "mint-terminal-renderer", GoMethod: "MintTerminalRenderer", Authority: AuthorityFrontend, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"mint-terminal-renderer-by-terminal": {Name: "mint-terminal-renderer-by-terminal", GoMethod: "MintTerminalRendererByTerminal", Authority: AuthorityFrontend, Since: 11, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-bookmark":                      {Name: "move-bookmark", GoMethod: "MoveBookmark", Authority: AuthorityControl, Since: 12, Capability: "bookmarks-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-browser-profile":               {Name: "move-browser-profile", GoMethod: "MoveBrowserProfile", Authority: AuthorityControl, Since: 12, Capability: "browser-profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-personal-group":                {Name: "move-personal-group", GoMethod: "MovePersonalGroup", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-profile":                       {Name: "move-profile", GoMethod: "MoveProfile", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-screen":                        {Name: "move-screen", GoMethod: "MoveScreen", Authority: AuthorityControl, Since: 12, Capability: "screen-metadata-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-screen-group":                  {Name: "move-screen-group", GoMethod: "MoveScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-tab":                           {Name: "move-tab", GoMethod: "MoveTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"transaction": 12}, FieldCapabilities: map[string]string{"transaction": "tab-drag-v1"}},
	"move-tab-group":                     {Name: "move-tab-group", GoMethod: "MoveTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-tab-group-to-column":           {Name: "move-tab-group-to-column", GoMethod: "MoveTabGroupToColumn", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-tab-group-to-new-workspace":    {Name: "move-tab-group-to-new-workspace", GoMethod: "MoveTabGroupToNewWorkspace", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-tab-group-to-split":            {Name: "move-tab-group-to-split", GoMethod: "MoveTabGroupToSplit", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-tab-to-column":                 {Name: "move-tab-to-column", GoMethod: "MoveTabToColumn", Authority: AuthorityControl, Since: 12, Capability: "tab-drag-v1", Stream: "", FieldSince: map[string]uint32{"respawn": 12, "sticky": 12}, FieldCapabilities: map[string]string{"respawn": "tab-column-respawn-v1", "sticky": "edge-docks-v1"}},
	"move-tab-to-new-workspace":          {Name: "move-tab-to-new-workspace", GoMethod: "MoveTabToNewWorkspace", Authority: AuthorityControl, Since: 12, Capability: "tab-drag-v1", Stream: "", FieldSince: nil, FieldCapabilities: map[string]string{"name": "tab-workspace-name-v1"}},
	"move-tab-to-split":                  {Name: "move-tab-to-split", GoMethod: "MoveTabToSplit", Authority: AuthorityControl, Since: 12, Capability: "tab-drag-v1", Stream: "", FieldSince: map[string]uint32{"respawn": 12}, FieldCapabilities: map[string]string{"respawn": "tab-split-respawn-v1"}},
	"move-tab-to-workspace":              {Name: "move-tab-to-workspace", GoMethod: "MoveTabToWorkspace", Authority: AuthorityControl, Since: 12, Capability: "tab-workspace-move-v1", Stream: "", FieldSince: map[string]uint32{"transaction": 12}, FieldCapabilities: map[string]string{"transaction": "tab-drag-v1"}},
	"move-terminal":                      {Name: "move-terminal", GoMethod: "MoveTerminal", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-workspace":                     {Name: "move-workspace", GoMethod: "MoveWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"expected_generation": 7, "expected_revision": 7, "key": 7, "mutation_id": 7, "origin": 7}, FieldCapabilities: map[string]string{"key": "workspace-registry-v1"}},
	"move-workspace-group":               {Name: "move-workspace-group", GoMethod: "MoveWorkspaceGroup", Authority: AuthorityControl, Since: 12, Capability: "workspace-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-workspace-to-group":            {Name: "move-workspace-to-group", GoMethod: "MoveWorkspaceToGroup", Authority: AuthorityControl, Since: 12, Capability: "workspace-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-browser-tab":                    {Name: "new-browser-tab", GoMethod: "NewBrowserTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-conversation-tab":               {Name: "new-conversation-tab", GoMethod: "NewConversationTab", Authority: AuthorityControl, Since: 12, Capability: "conversation-tabs-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-frontend-browser-tab":           {Name: "new-frontend-browser-tab", GoMethod: "NewFrontendBrowserTab", Authority: AuthorityControl, Since: 12, Capability: "frontend-browser-tabs-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-pane":                           {Name: "new-pane", GoMethod: "NewPane", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: map[string]uint32{"cwd": 12, "env": 12, "keep": 12, "shell_args": 12, "terminal_id": 12}, FieldCapabilities: map[string]string{"cwd": "terminal-placement-env-v1", "env": "terminal-placement-env-v1", "keep": "terminal-reap-v1", "shell_args": "terminal-shell-args-v1", "terminal_id": "terminal-placement-env-v1"}},
	"new-pane-right":                     {Name: "new-pane-right", GoMethod: "NewPaneRight", Authority: AuthorityControl, Since: 9, Capability: "viewport-splits-v1", Stream: "", FieldSince: map[string]uint32{"cwd": 12, "env": 12, "keep": 12, "shell_args": 12, "terminal_id": 12}, FieldCapabilities: map[string]string{"cwd": "terminal-placement-env-v1", "env": "terminal-placement-env-v1", "keep": "terminal-reap-v1", "shell_args": "terminal-shell-args-v1", "terminal_id": "terminal-placement-env-v1"}},
	"new-row":                            {Name: "new-row", GoMethod: "NewRow", Authority: AuthorityControl, Since: 12, Capability: "rows-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-screen":                         {Name: "new-screen", GoMethod: "NewScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-tab":                            {Name: "new-tab", GoMethod: "NewTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"env": 12, "keep": 12, "shell_args": 12, "terminal_id": 12}, FieldCapabilities: map[string]string{"env": "terminal-env-v1", "keep": "terminal-reap-v1", "shell_args": "terminal-shell-args-v1", "terminal_id": "terminal-placement-env-v1"}},
	"new-workspace":                      {Name: "new-workspace", GoMethod: "NewWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"note-size-activity":                 {Name: "note-size-activity", GoMethod: "NoteSizeActivity", Authority: AuthorityControl, Since: 12, Capability: "shared-sizing-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"notify":                             {Name: "notify", GoMethod: "Notify", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: map[string]uint32{"source": 12}, FieldCapabilities: map[string]string{"source": "notification-source-v1"}},
	"pairing-response":                   {Name: "pairing-response", GoMethod: "PairingResponse", Authority: AuthorityLocalAdmin, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"pane-neighbor":                      {Name: "pane-neighbor", GoMethod: "PaneNeighbor", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"paste-image":                        {Name: "paste-image", GoMethod: "PasteImage", Authority: AuthorityControl, Since: 12, Capability: "terminal-image-paste-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"pin-workspace":                      {Name: "pin-workspace", GoMethod: "PinWorkspace", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"ping":                               {Name: "ping", GoMethod: "Ping", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"process-info":                       {Name: "process-info", GoMethod: "ProcessInfo", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"put-frontend-projection":            {Name: "put-frontend-projection", GoMethod: "PutFrontendProjection", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"put-session":                        {Name: "put-session", GoMethod: "PutSession", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"read-screen":                        {Name: "read-screen", GoMethod: "ReadScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"read-scrollback":                    {Name: "read-scrollback", GoMethod: "ReadScrollback", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"reattach-view":                      {Name: "reattach-view", GoMethod: "ReattachView", Authority: AuthorityControl, Since: 12, Capability: "sizing-view-detach-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"register-browser-provider":          {Name: "register-browser-provider", GoMethod: "RegisterBrowserProvider", Authority: AuthorityLocalAdmin, Since: 10, Capability: "browser-provider-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"release-attached-view-size":         {Name: "release-attached-view-size", GoMethod: "ReleaseAttachedViewSize", Authority: AuthorityFrontend, Since: 10, Capability: "view-attachment-lease-v1", Stream: "", FieldSince: map[string]uint32{"view": 12}, FieldCapabilities: map[string]string{"view": "shared-sizing-v1"}},
	"release-surface-size":               {Name: "release-surface-size", GoMethod: "ReleaseSurfaceSize", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"reload-config":                      {Name: "reload-config", GoMethod: "ReloadConfig", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"remove-screens-from-screen-group":   {Name: "remove-screens-from-screen-group", GoMethod: "RemoveScreensFromScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"remove-tabs-from-tab-group":         {Name: "remove-tabs-from-tab-group", GoMethod: "RemoveTabsFromTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-pane":                        {Name: "rename-pane", GoMethod: "RenamePane", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-provider-managed-workspace":  {Name: "rename-provider-managed-workspace", GoMethod: "RenameProviderManagedWorkspace", Authority: AuthorityProviderAuthority, Since: 9, Capability: "provider-managed-workspace-authority-v2", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-screen":                      {Name: "rename-screen", GoMethod: "RenameScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-surface":                     {Name: "rename-surface", GoMethod: "RenameSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-workspace":                   {Name: "rename-workspace", GoMethod: "RenameWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"expected_generation": 7, "expected_revision": 7, "key": 7, "mutation_id": 7, "origin": 7}, FieldCapabilities: map[string]string{"key": "workspace-registry-v1"}},
	"reopen-saved-screen-group":          {Name: "reopen-saved-screen-group", GoMethod: "ReopenSavedScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"reopen-saved-tab-group":             {Name: "reopen-saved-tab-group", GoMethod: "ReopenSavedTabGroup", Authority: AuthorityControl, Since: 12, Capability: "saved-tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"report-agent":                       {Name: "report-agent", GoMethod: "ReportAgent", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"report-focus":                       {Name: "report-focus", GoMethod: "ReportFocus", Authority: AuthorityControl, Since: 12, Capability: "client-focus-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"resize-attached-view":               {Name: "resize-attached-view", GoMethod: "ResizeAttachedView", Authority: AuthorityFrontend, Since: 10, Capability: "view-attachment-lease-v1", Stream: "", FieldSince: map[string]uint32{"identity": 12, "view": 12}, FieldCapabilities: map[string]string{"identity": "shared-sizing-v1", "view": "shared-sizing-v1"}},
	"resize-surface":                     {Name: "resize-surface", GoMethod: "ResizeSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"resolve-terminal":                   {Name: "resolve-terminal", GoMethod: "ResolveTerminal", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"run":                                {Name: "run", GoMethod: "Run", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: map[string]uint32{"key": 9}, FieldCapabilities: nil},
	"save-screen-group":                  {Name: "save-screen-group", GoMethod: "SaveScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"save-tab-group":                     {Name: "save-tab-group", GoMethod: "SaveTabGroup", Authority: AuthorityControl, Since: 12, Capability: "saved-tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"scroll-surface":                     {Name: "scroll-surface", GoMethod: "ScrollSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"select-screen":                      {Name: "select-screen", GoMethod: "SelectScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"select-tab":                         {Name: "select-tab", GoMethod: "SelectTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"select-workspace":                   {Name: "select-workspace", GoMethod: "SelectWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"send":                               {Name: "send", GoMethod: "Send", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"paste": 7}, FieldCapabilities: nil},
	"send-key":                           {Name: "send-key", GoMethod: "SendKey", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"server-stats":                       {Name: "server-stats", GoMethod: "ServerStats", Authority: AuthorityLocalAdmin, Since: 12, Capability: "server-stats-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-cell-pixels":                    {Name: "set-cell-pixels", GoMethod: "SetCellPixels", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-client-info":                    {Name: "set-client-info", GoMethod: "SetClientInfo", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: map[string]uint32{"device_id": 12, "device_kind": 12, "device_name": 12, "display_name": 12, "user_id": 12}, FieldCapabilities: map[string]string{"device_id": "shared-sizing-v1", "device_kind": "shared-sizing-v1", "device_name": "shared-sizing-v1", "display_name": "shared-sizing-v1", "user_id": "shared-sizing-v1"}},
	"set-client-sizing":                  {Name: "set-client-sizing", GoMethod: "SetClientSizing", Authority: AuthorityControl, Since: 10, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-column-sticky":                  {Name: "set-column-sticky", GoMethod: "SetColumnSticky", Authority: AuthorityControl, Since: 12, Capability: "sticky-columns-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-default-colors":                 {Name: "set-default-colors", GoMethod: "SetDefaultColors", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"complete": 9, "cursor": 9, "cursor_blink": 9, "cursor_style": 9, "palette": 9, "selection_bg": 9, "selection_fg": 9}, FieldCapabilities: nil},
	"set-frontend-browser-history":       {Name: "set-frontend-browser-history", GoMethod: "SetFrontendBrowserHistory", Authority: AuthorityControl, Since: 12, Capability: "frontend-browser-history-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-personal-terminal":              {Name: "set-personal-terminal", GoMethod: "SetPersonalTerminal", Authority: AuthorityControl, Since: 12, Capability: "personal-terminals-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-personal-workspace":             {Name: "set-personal-workspace", GoMethod: "SetPersonalWorkspace", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-profile-follows":                {Name: "set-profile-follows", GoMethod: "SetProfileFollows", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-ratio":                          {Name: "set-ratio", GoMethod: "SetRatio", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-row-heights":                    {Name: "set-row-heights", GoMethod: "SetRowHeights", Authority: AuthorityControl, Since: 12, Capability: "rows-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-screen-metadata":                {Name: "set-screen-metadata", GoMethod: "SetScreenMetadata", Authority: AuthorityControl, Since: 12, Capability: "screen-metadata-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-screen-pinned":                  {Name: "set-screen-pinned", GoMethod: "SetScreenPinned", Authority: AuthorityControl, Since: 12, Capability: "screen-metadata-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-size-counts":                    {Name: "set-size-counts", GoMethod: "SetSizeCounts", Authority: AuthorityControl, Since: 12, Capability: "shared-sizing-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-size-policy":                    {Name: "set-size-policy", GoMethod: "SetSizePolicy", Authority: AuthorityControl, Since: 12, Capability: "shared-sizing-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-split-ratio":                    {Name: "set-split-ratio", GoMethod: "SetSplitRatio", Authority: AuthorityControl, Since: 8, Capability: "", Stream: "", FieldSince: map[string]uint32{"transaction": 9}, FieldCapabilities: map[string]string{"transaction": "layout-undo-v1"}},
	"set-tab-pinned":                     {Name: "set-tab-pinned", GoMethod: "SetTabPinned", Authority: AuthorityControl, Since: 12, Capability: "tab-metadata-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-terminal-command-history":       {Name: "set-terminal-command-history", GoMethod: "SetTerminalCommandHistory", Authority: AuthorityLocalAdmin, Since: 12, Capability: "terminal-command-journal-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-terminal-idle-policy":           {Name: "set-terminal-idle-policy", GoMethod: "SetTerminalIdlePolicy", Authority: AuthorityControl, Since: 12, Capability: "terminal-idle-close-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-terminal-keep":                  {Name: "set-terminal-keep", GoMethod: "SetTerminalKeep", Authority: AuthorityControl, Since: 12, Capability: "terminal-reap-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-viewport-pane-width":            {Name: "set-viewport-pane-width", GoMethod: "SetViewportPaneWidth", Authority: AuthorityControl, Since: 9, Capability: "viewport-column-resize-v1", Stream: "", FieldSince: map[string]uint32{"transaction": 9}, FieldCapabilities: map[string]string{"transaction": "layout-undo-v1"}},
	"set-window-title":                   {Name: "set-window-title", GoMethod: "SetWindowTitle", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-workspace-metadata":             {Name: "set-workspace-metadata", GoMethod: "SetWorkspaceMetadata", Authority: AuthorityControl, Since: 12, Capability: "workspace-metadata-v1", Stream: "", FieldSince: map[string]uint32{"marked_unread": 12, "pinned": 12}, FieldCapabilities: map[string]string{"marked_unread": "notification-mark-unread-v1", "pinned": "workspace-pin-v1"}},
	"shutdown-daemon":                    {Name: "shutdown-daemon", GoMethod: "ShutdownDaemon", Authority: AuthorityLocalAdmin, Since: 9, Capability: "", Stream: "", FieldSince: map[string]uint32{"end_terminals": 12, "force": 10, "keep_layout": 12}, FieldCapabilities: map[string]string{"end_terminals": "terminal-reap-v1", "force": "daemon-handoff-force-v1", "keep_layout": "end-terminals-keep-layout-v1"}},
	"sidebar-plugin":                     {Name: "sidebar-plugin", GoMethod: "SidebarPlugin", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"snapshot-request":                   {Name: "snapshot-request", GoMethod: "SnapshotRequest", Authority: AuthorityFrontend, Since: 12, Capability: "terminal-snapshot-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"split":                              {Name: "split", GoMethod: "Split", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"cwd": 12, "env": 12, "keep": 12, "shell_args": 12, "terminal_id": 12}, FieldCapabilities: map[string]string{"cwd": "terminal-env-v1", "env": "terminal-env-v1", "keep": "terminal-reap-v1", "shell_args": "terminal-shell-args-v1", "terminal_id": "terminal-placement-env-v1"}},
	"subscribe":                          {Name: "subscribe", GoMethod: "Subscribe", Authority: AuthorityFrontend, Since: 5, Capability: "", Stream: "subscribe", FieldSince: map[string]uint32{"surface": 9, "tree_events": 7}, FieldCapabilities: map[string]string{"surface": "surface-subscribe-filter"}},
	"swap-pane":                          {Name: "swap-pane", GoMethod: "SwapPane", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"terminal-events":                    {Name: "terminal-events", GoMethod: "TerminalEvents", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"terminal-history":                   {Name: "terminal-history", GoMethod: "TerminalHistory", Authority: AuthorityControl, Since: 12, Capability: "terminal-snapshot-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"terminal-read-range":                {Name: "terminal-read-range", GoMethod: "TerminalReadRange", Authority: AuthorityControl, Since: 12, Capability: "terminal-snapshot-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"terminal-resources":                 {Name: "terminal-resources", GoMethod: "TerminalResources", Authority: AuthorityControl, Since: 12, Capability: "terminal-resources-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"undo-layout":                        {Name: "undo-layout", GoMethod: "UndoLayout", Authority: AuthorityControl, Since: 9, Capability: "layout-undo-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"ungroup-screen-group":               {Name: "ungroup-screen-group", GoMethod: "UngroupScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"ungroup-tab-group":                  {Name: "ungroup-tab-group", GoMethod: "UngroupTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"unpin-workspace":                    {Name: "unpin-workspace", GoMethod: "UnpinWorkspace", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"unregister-browser-provider":        {Name: "unregister-browser-provider", GoMethod: "UnregisterBrowserProvider", Authority: AuthorityLocalAdmin, Since: 10, Capability: "browser-provider-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"unsave-screen-group":                {Name: "unsave-screen-group", GoMethod: "UnsaveScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"unsave-tab-group":                   {Name: "unsave-tab-group", GoMethod: "UnsaveTabGroup", Authority: AuthorityControl, Since: 12, Capability: "saved-tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-bookmark":                    {Name: "update-bookmark", GoMethod: "UpdateBookmark", Authority: AuthorityControl, Since: 12, Capability: "bookmarks-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-browser-profile":             {Name: "update-browser-profile", GoMethod: "UpdateBrowserProfile", Authority: AuthorityControl, Since: 12, Capability: "browser-profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-frontend-browser-tab":        {Name: "update-frontend-browser-tab", GoMethod: "UpdateFrontendBrowserTab", Authority: AuthorityControl, Since: 12, Capability: "frontend-browser-tabs-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-personal-group":              {Name: "update-personal-group", GoMethod: "UpdatePersonalGroup", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-profile":                     {Name: "update-profile", GoMethod: "UpdateProfile", Authority: AuthorityControl, Since: 12, Capability: "profiles-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-screen-group":                {Name: "update-screen-group", GoMethod: "UpdateScreenGroup", Authority: AuthorityControl, Since: 12, Capability: "screen-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-tab-group":                   {Name: "update-tab-group", GoMethod: "UpdateTabGroup", Authority: AuthorityControl, Since: 12, Capability: "tab-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"update-workspace-group":             {Name: "update-workspace-group", GoMethod: "UpdateWorkspaceGroup", Authority: AuthorityControl, Since: 12, Capability: "workspace-groups-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"url-open":                           {Name: "url-open", GoMethod: "URLOpen", Authority: AuthorityLocalAdmin, Since: 12, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"url-open-claim":                     {Name: "url-open-claim", GoMethod: "URLOpenClaim", Authority: AuthorityFrontend, Since: 12, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"url-open-result":                    {Name: "url-open-result", GoMethod: "URLOpenResult", Authority: AuthorityFrontend, Since: 12, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"url-open-subscribe":                 {Name: "url-open-subscribe", GoMethod: "URLOpenSubscribe", Authority: AuthorityFrontend, Since: 12, Capability: "", Stream: "subscribe", FieldSince: nil, FieldCapabilities: nil},
	"vt-state":                           {Name: "vt-state", GoMethod: "VTState", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"wait-for":                           {Name: "wait-for", GoMethod: "WaitFor", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"zoom-pane":                          {Name: "zoom-pane", GoMethod: "ZoomPane", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
}

var eventMetadata = map[string]EventMetadata{
	"agent-changed":               {Name: "agent-changed", Since: 11, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"bell":                        {Name: "bell", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"bookmarks-changed":           {Name: "bookmarks-changed", Since: 12, Capability: "bookmarks-v1", Streams: []string{"subscribe"}, Emission: "emitted"},
	"browser-state":               {Name: "browser-state", Since: 6, Capability: "", Streams: []string{"attach-browser"}, Emission: "emitted"},
	"client-attached":             {Name: "client-attached", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"client-changed":              {Name: "client-changed", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"client-detached":             {Name: "client-detached", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"client-list-invalidated":     {Name: "client-list-invalidated", Since: 9, Capability: "", Streams: []string{"subscribe"}, Emission: "serialized-never-emitted"},
	"colors-changed":              {Name: "colors-changed", Since: 6, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"config-reload-requested":     {Name: "config-reload-requested", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"conversation-changed":        {Name: "conversation-changed", Since: 12, Capability: "local-conversations-v1", Streams: []string{"subscribe"}, Emission: "emitted"},
	"conversation-typing":         {Name: "conversation-typing", Since: 12, Capability: "local-conversations-v1", Streams: []string{"subscribe"}, Emission: "emitted"},
	"daemon-shutdown":             {Name: "daemon-shutdown", Since: 12, Capability: "", Streams: []string{"control"}, Emission: "emitted"},
	"detached":                    {Name: "detached", Since: 5, Capability: "", Streams: []string{"attach-byte", "attach-render", "attach-browser"}, Emission: "emitted"},
	"empty":                       {Name: "empty", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"frame":                       {Name: "frame", Since: 6, Capability: "", Streams: []string{"attach-browser"}, Emission: "emitted"},
	"frontend-projection-changed": {Name: "frontend-projection-changed", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"graphics-status":             {Name: "graphics-status", Since: 10, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"layout-changed":              {Name: "layout-changed", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"machine-usage-changed":       {Name: "machine-usage-changed", Since: 12, Capability: "machine-usage-v1", Streams: []string{"subscribe"}, Emission: "emitted"},
	"notification":                {Name: "notification", Since: 6, Capability: "", Streams: []string{"subscribe", "attach-byte", "attach-browser"}, Emission: "emitted"},
	"output":                      {Name: "output", Since: 5, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"overflow":                    {Name: "overflow", Since: 7, Capability: "", Streams: []string{"subscribe", "attach-byte", "attach-render", "attach-browser"}, Emission: "emitted"},
	"pairing-requested":           {Name: "pairing-requested", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"pairing-resolved":            {Name: "pairing-resolved", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"pane-added":                  {Name: "pane-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"pane-closed":                 {Name: "pane-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"personal-changed":            {Name: "personal-changed", Since: 12, Capability: "profiles-v1", Streams: []string{"subscribe"}, Emission: "emitted"},
	"render-delta":                {Name: "render-delta", Since: 7, Capability: "", Streams: []string{"attach-render"}, Emission: "emitted"},
	"render-state":                {Name: "render-state", Since: 7, Capability: "", Streams: []string{"attach-render"}, Emission: "emitted"},
	"resized":                     {Name: "resized", Since: 6, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"screen-added":                {Name: "screen-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"screen-changed":              {Name: "screen-changed", Since: 12, Capability: "screen-metadata-v1", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"screen-closed":               {Name: "screen-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"screen-renamed":              {Name: "screen-renamed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"scroll-changed":              {Name: "scroll-changed", Since: 6, Capability: "", Streams: []string{"subscribe", "attach-byte", "attach-render", "attach-browser"}, Emission: "emitted"},
	"size-state":                  {Name: "size-state", Since: 12, Capability: "shared-sizing-v1", Streams: []string{"subscribe", "attach-byte", "attach-render"}, Emission: "emitted"},
	"status":                      {Name: "status", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-exited":              {Name: "surface-exited", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-output":              {Name: "surface-output", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-resize-failed":       {Name: "surface-resize-failed", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-resized":             {Name: "surface-resized", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"tab-added":                   {Name: "tab-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"tab-changed":                 {Name: "tab-changed", Since: 12, Capability: "tab-metadata-v1", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"tab-closed":                  {Name: "tab-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"tab-renamed":                 {Name: "tab-renamed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"terminal-reaped":             {Name: "terminal-reaped", Since: 12, Capability: "terminal-reap-v1", Streams: []string{"subscribe"}, Emission: "emitted"},
	"terminal-registry-changed":   {Name: "terminal-registry-changed", Since: 9, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"title-changed":               {Name: "title-changed", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"tree-changed":                {Name: "tree-changed", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"url-open":                    {Name: "url-open", Since: 12, Capability: "", Streams: []string{"control"}, Emission: "emitted"},
	"vt-state":                    {Name: "vt-state", Since: 5, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"window-title-requested":      {Name: "window-title-requested", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"workspace-added":             {Name: "workspace-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-changed":           {Name: "workspace-changed", Since: 12, Capability: "workspace-metadata-v1", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-closed":            {Name: "workspace-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-moved":             {Name: "workspace-moved", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-renamed":           {Name: "workspace-renamed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
}

func CommandInfo(name string) (CommandMetadata, bool) {
	metadata, ok := commandMetadata[name]
	if ok {
		metadata = cloneCommandMetadata(metadata)
	}
	return metadata, ok
}

func cloneCommandMetadata(metadata CommandMetadata) CommandMetadata {
	if metadata.FieldSince != nil {
		values := metadata.FieldSince
		metadata.FieldSince = make(map[string]uint32, len(metadata.FieldSince))
		for name, since := range values {
			metadata.FieldSince[name] = since
		}
	}
	if metadata.FieldCapabilities != nil {
		values := metadata.FieldCapabilities
		metadata.FieldCapabilities = make(map[string]string, len(metadata.FieldCapabilities))
		for name, capability := range values {
			metadata.FieldCapabilities[name] = capability
		}
	}
	return metadata
}

func EventInfo(name string) (EventMetadata, bool) {
	metadata, ok := eventMetadata[name]
	if ok {
		metadata.Streams = append([]string(nil), metadata.Streams...)
	}
	return metadata, ok
}

func ProfileInfo(name Profile) (ProfileMetadata, bool) {
	metadata, ok := profileMetadata[name]
	if ok {
		metadata.Inherits = append([]Profile(nil), metadata.Inherits...)
	}
	return metadata, ok
}

func AllCommandMetadata() []CommandMetadata {
	result := make([]CommandMetadata, 0, 213)
	result = append(result, cloneCommandMetadata(commandMetadata["ack-tab-notifications"]))
	result = append(result, cloneCommandMetadata(commandMetadata["add-screens-to-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["add-tabs-to-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["apply-layout"]))
	result = append(result, cloneCommandMetadata(commandMetadata["attach-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-activate"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-back"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-forward"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-frame-presented"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-insert-text"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-key"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-key-press"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-mouse"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-mouse-guarded"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-navigate"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-reload"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-wheel"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-wheel-guarded"]))
	result = append(result, cloneCommandMetadata(commandMetadata["clear-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["clear-window-title"]))
	result = append(result, cloneCommandMetadata(commandMetadata["client-focus"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-provider-managed-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-tabs"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-agent-token"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-bind"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-create"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-list"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-op"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-search"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-snapshot"]))
	result = append(result, cloneCommandMetadata(commandMetadata["conversation-typing"]))
	result = append(result, cloneCommandMetadata(commandMetadata["copy"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-bookmark"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-browser-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-personal-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-surface-with-receipt"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-workspace-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-bookmark"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-browser-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-personal-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-saved-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-saved-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["delete-workspace-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["detach-attached-view"]))
	result = append(result, cloneCommandMetadata(commandMetadata["detach-client"]))
	result = append(result, cloneCommandMetadata(commandMetadata["export-layout"]))
	result = append(result, cloneCommandMetadata(commandMetadata["focus-direction"]))
	result = append(result, cloneCommandMetadata(commandMetadata["focus-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["forget-session"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-browser-provider"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-cell-pixels"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-frontend-browser-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-frontend-projection"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-size-state"]))
	result = append(result, cloneCommandMetadata(commandMetadata["identify"]))
	result = append(result, cloneCommandMetadata(commandMetadata["ids"]))
	result = append(result, cloneCommandMetadata(commandMetadata["import-bookmarks"]))
	result = append(result, cloneCommandMetadata(commandMetadata["import-session-organization"]))
	result = append(result, cloneCommandMetadata(commandMetadata["journal-frontend-event"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-agents"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-bookmarks"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-clients"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-notifications"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-personal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-saved-screen-groups"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-saved-tab-groups"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-tab-groups"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-terminals"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-workspace-groups"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-workspaces"]))
	result = append(result, cloneCommandMetadata(commandMetadata["machine-listening-tcp"]))
	result = append(result, cloneCommandMetadata(commandMetadata["machine-usage"]))
	result = append(result, cloneCommandMetadata(commandMetadata["mark-workspaces-provider-managed"]))
	result = append(result, cloneCommandMetadata(commandMetadata["mint-terminal-renderer"]))
	result = append(result, cloneCommandMetadata(commandMetadata["mint-terminal-renderer-by-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-bookmark"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-browser-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-personal-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-group-to-column"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-group-to-new-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-group-to-split"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-to-column"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-to-new-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-to-split"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab-to-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-workspace-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-workspace-to-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-browser-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-conversation-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-frontend-browser-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-pane-right"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-row"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["note-size-activity"]))
	result = append(result, cloneCommandMetadata(commandMetadata["notify"]))
	result = append(result, cloneCommandMetadata(commandMetadata["pairing-response"]))
	result = append(result, cloneCommandMetadata(commandMetadata["pane-neighbor"]))
	result = append(result, cloneCommandMetadata(commandMetadata["paste-image"]))
	result = append(result, cloneCommandMetadata(commandMetadata["pin-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["ping"]))
	result = append(result, cloneCommandMetadata(commandMetadata["process-info"]))
	result = append(result, cloneCommandMetadata(commandMetadata["put-frontend-projection"]))
	result = append(result, cloneCommandMetadata(commandMetadata["put-session"]))
	result = append(result, cloneCommandMetadata(commandMetadata["read-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["read-scrollback"]))
	result = append(result, cloneCommandMetadata(commandMetadata["reattach-view"]))
	result = append(result, cloneCommandMetadata(commandMetadata["register-browser-provider"]))
	result = append(result, cloneCommandMetadata(commandMetadata["release-attached-view-size"]))
	result = append(result, cloneCommandMetadata(commandMetadata["release-surface-size"]))
	result = append(result, cloneCommandMetadata(commandMetadata["reload-config"]))
	result = append(result, cloneCommandMetadata(commandMetadata["remove-screens-from-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["remove-tabs-from-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-provider-managed-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["reopen-saved-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["reopen-saved-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["report-agent"]))
	result = append(result, cloneCommandMetadata(commandMetadata["report-focus"]))
	result = append(result, cloneCommandMetadata(commandMetadata["resize-attached-view"]))
	result = append(result, cloneCommandMetadata(commandMetadata["resize-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["resolve-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["run"]))
	result = append(result, cloneCommandMetadata(commandMetadata["save-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["save-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["scroll-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["select-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["select-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["select-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["send"]))
	result = append(result, cloneCommandMetadata(commandMetadata["send-key"]))
	result = append(result, cloneCommandMetadata(commandMetadata["server-stats"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-cell-pixels"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-client-info"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-client-sizing"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-column-sticky"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-default-colors"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-frontend-browser-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-personal-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-personal-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-profile-follows"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-ratio"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-row-heights"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-screen-metadata"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-screen-pinned"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-size-counts"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-size-policy"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-split-ratio"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-tab-pinned"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-terminal-command-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-terminal-idle-policy"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-terminal-keep"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-viewport-pane-width"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-window-title"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-workspace-metadata"]))
	result = append(result, cloneCommandMetadata(commandMetadata["shutdown-daemon"]))
	result = append(result, cloneCommandMetadata(commandMetadata["sidebar-plugin"]))
	result = append(result, cloneCommandMetadata(commandMetadata["snapshot-request"]))
	result = append(result, cloneCommandMetadata(commandMetadata["split"]))
	result = append(result, cloneCommandMetadata(commandMetadata["subscribe"]))
	result = append(result, cloneCommandMetadata(commandMetadata["swap-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["terminal-events"]))
	result = append(result, cloneCommandMetadata(commandMetadata["terminal-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["terminal-read-range"]))
	result = append(result, cloneCommandMetadata(commandMetadata["terminal-resources"]))
	result = append(result, cloneCommandMetadata(commandMetadata["undo-layout"]))
	result = append(result, cloneCommandMetadata(commandMetadata["ungroup-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["ungroup-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["unpin-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["unregister-browser-provider"]))
	result = append(result, cloneCommandMetadata(commandMetadata["unsave-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["unsave-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-bookmark"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-browser-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-frontend-browser-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-personal-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-profile"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-screen-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-tab-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["update-workspace-group"]))
	result = append(result, cloneCommandMetadata(commandMetadata["url-open"]))
	result = append(result, cloneCommandMetadata(commandMetadata["url-open-claim"]))
	result = append(result, cloneCommandMetadata(commandMetadata["url-open-result"]))
	result = append(result, cloneCommandMetadata(commandMetadata["url-open-subscribe"]))
	result = append(result, cloneCommandMetadata(commandMetadata["vt-state"]))
	result = append(result, cloneCommandMetadata(commandMetadata["wait-for"]))
	result = append(result, cloneCommandMetadata(commandMetadata["zoom-pane"]))
	return result
}

func AllEventMetadata() []EventMetadata {
	result := make([]EventMetadata, 0, 58)
	var metadata EventMetadata
	metadata = eventMetadata["agent-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["bell"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["bookmarks-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["browser-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-attached"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-detached"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-list-invalidated"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["colors-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["config-reload-requested"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["conversation-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["conversation-typing"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["daemon-shutdown"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["detached"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["empty"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["frame"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["frontend-projection-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["graphics-status"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["layout-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["machine-usage-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["notification"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["output"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["overflow"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pairing-requested"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pairing-resolved"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pane-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pane-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["personal-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["render-delta"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["render-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["resized"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-renamed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["scroll-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["size-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["status"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-exited"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-output"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-resize-failed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-resized"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-renamed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["terminal-reaped"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["terminal-registry-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["title-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tree-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["url-open"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["vt-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["window-title-requested"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-moved"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-renamed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	return result
}
